{
  "hash": "6d3a4fd22b349b32ad77030183b0e847",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 10\"\nauthor: \"Miguel Fudolig\"\nengine: knitr\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 10- [Back to home](https://madfudolig.quarto.pub/eab770slides/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n  pdf: \n    number-sections: true\n---\n\n# Conditional Logistic Regression\n\n## Outline\n\n- Paired Observations and Crossover Design Studies\n- General Conditional Logistic Regression\n- Exact Conditional Logistic Regression\n\n## Conditional Logistic Regression\n\nWhen data is highly stratified and each strata contain small numbers of subjects, logistic regression may not be appropriate. Maximum likelihood estimates need a large sample size relative to the parameter number.\n\n::: callout-note\nHighly stratified data such as paired observations, matched case control studies in epidemiology come from a cluster sampling design. Conditional Logistic Regression accounts for stratification by basing the maximum likelihood estimation on a conditional likelihood.\n:::\n\n## Conditional Logistic Regression\n\nConsider a highly stratified cohort study where there are $q$ centers randomly selected. At each center, one randomly selected patient is placed on treatment and another randomly selected patient is assigned to a placebo. \n\n::: callout-note\nThe response variable is y_{hi}=1 if there is improvement, 0 otherwise. With two patients per center, this could lead to biased estimates of the effect size.\n:::\n  \n## Likelihood\n\nThe likelihood for $y_{hi}$ can be written as:\n\n$$\nP(y_{hi} = \\pi_{hi} = \\frac{\\exp[\\alpha_h + \\beta x_{hi} + \\sum_g \\gamma'_g z_{hig}]}{1+ \\exp[\\alpha_h + \\beta x_{hi} + \\sum_g \\gamma'_g z_{hig}]})\n$$\n\n::: callout-note\n$\\alpha_h$ is an intercept for the $h^{th}$ center (strata), $\\beta$ is the treatment parameter, and $\\gamma'$ is the parameter of covariates $z$. Note that there are a lot of parameters, which may lead to biased estimates with only two patients per center.\n:::\n\n::: callout-note\n## Nuisance parameters\n\nWe can fit a model based on probabilities conditioned on the center effects. After conditioning, the center dependent intercept $\\alpha_h$ would not be important. This is why $\\alpha_h$ is referred to as a _nuisance parameter_.\n:::\n\n## Why conditional?\n\nWe condition the result to a specific \"sufficient statistic\" or event.\n\n::: callout-note\nIn the example, the events considered could be concordant (both showed no effect or both improved) or discordant (only one improved per clinic) outcomes.\n:::\n\nIn the case of the cohort study, we can condition on the case that exactly one of the participants in each clinic will show improvement.\n\n::: callout-note\nThe improvement could be observed in the test participants ($y_{h1}=1$, $y_{h2}=0$) or the placebo participants ($y_{h1}=0$, $y_{h2}=1$). Either way, $y_{h1}+y_{h2}=1$.\n:::\n\n\n## Condiitonal Probability\n\nThe conditional probability that the test participant improved conditioning on the discordant outcome that exactly one of the participants in each clinic will show improvement is:\n\n$$\nP((y_{h1},y_{h2}) = (1,0) | y_{h1}+y_{h2}=1) = \\frac{P(y_{h1}=1)P(y_{h2}=0)}{P(y_{h1}=1)P(y_{h2}=0) + P(y_{h1}=0)P(y_{h2}=1)}\n$$\n\n::: callout-note\nPerforming the mathematical calculations, we will end up with a likelihood independent of $\\alpha_h$, which means we effectively removed center-only terms in our model.\n:::\n\n## Conditional vs. Unconditional Logistic Regression\n\nThe conditional likelihood has the same form as that of the unconditional likelihood, but the intercept term is now $\\beta$, which is related to the treatment effect.\n\n\n::: callout-note\nThe nuisance parameters $\\alpha_h$ do not affect the likelihood. The conditional likelihood applies to paired data can be written as a simple case of the Cox proportional hazards model, which is used in the analysis of survival times.\n:::\n\n## Conditional Logistic Regression: `SAS`\n\n- The `STRATA` statement allows us to add the stratification variables when there is a small sample size per strata. \n\n\n::: callout-note\nYou should establish which variables are stratification variables and which ones are covariates.\n:::\n\n## Conditional Logistic Regression: `R`\n\nThe `clogit()` function in the `survival` package in `R` can be used to perform conditional logistic regression by applying the Cox proportional hazards model.\n\n::: callout-important\nThe `strata()` function is used to indicate which variable is the stratification variable. Forward selection can be implemented using the `stepAIC` function in `MASS`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(MASS)\nfull_model <- clogit(response~treatment + covariate + strata(stratificationvariable),data=sample_data,model=TRUE)\nbase_model <- clogit(response~treatment + covariate + strata(stratificationvariable),data=sample_data,model=TRUE)\nselected_model <- stepAIC(base_model,list(upper=full_model),direction=\"forward\")\n```\n:::\n\n\nThe Type 3 Tests of Fixed Effects can be implemented using the `Anova()` function in the `car` package.\n:::\n\n## Example\n\nThe data listed below includes data from a study about the effect of a new treatment on a skin condition. The data were collected from 79 clinics. In each clinic, one patient received the treatment, and another received a placebo. Demographic variables such as age, sex, and initial grade for the skin condition (1-4, mild to severe) was collected. The response variable was whether the skin condition improved.\n\n::: {.panel-tabset}\n### SAS Data Set\n\n```{.r}\ndata trial;\ninput center treatment $ sex $ age improve initial @@;\ndatalines;\n1 t f 27 0 1 1 p f 32 0 2 41 t f 13 1 2 41 p m 22 0 3\n2 t f 41 1 3 2 p f 47 0 1 42 t m 31 1 1 42 p f 21 1 3\n3 t m 19 1 4 3 p m 31 0 4 43 t f 19 1 3 43 p m 35 1 3\n4 t m 55 1 1 4 p m 24 1 3 44 t m 31 1 3 44 p f 37 0 2\n5 t f 51 1 4 5 p f 44 0 2 45 t f 44 0 1 45 p f 41 1 1\n6 t m 23 0 1 6 p f 44 1 3 46 t m 41 1 2 46 p m 41 0 1\n7 t m 31 1 2 7 p f 39 0 2 47 t m 41 1 2 47 p f 21 0 4\n8 t m 22 0 1 8 p m 54 1 4 48 t f 51 1 2 48 p m 22 1 1\n9 t m 37 1 3 9 p m 63 0 2 49 t f 62 1 3 49 p f 32 0 3\n10 t m 33 0 3 10 p f 43 0 3 50 t m 21 0 1 50 p m 34 0 1\n11 t f 32 1 1 11 p m 33 0 3 51 t m 55 1 3 51 p f 35 1 2\n12 t m 47 1 4 12 p m 24 0 4 52 t f 61 0 1 52 p m 19 0 1\n13 t m 55 1 3 13 p f 38 1 1 53 t m 43 1 2 53 p m 31 0 2\n14 t f 33 0 1 14 p f 28 1 2 54 t f 44 1 1 54 p f 41 1 1\n15 t f 48 1 1 15 p f 42 0 1 55 t m 67 1 2 55 p m 41 0 1\n16 t m 55 1 3 16 p m 52 0 1 56 t m 41 0 2 56 p m 21 1 4\n17 t m 30 0 4 17 p m 48 1 4 57 t f 51 1 3 57 p m 51 0 2\n18 t f 31 1 2 18 p m 27 1 3 58 t m 62 1 3 58 p m 54 1 3\n19 t m 66 1 3 19 p f 54 0 1 59 t m 22 0 1 59 p f 22 0 1\n20 t f 45 0 2 20 p f 66 1 2 60 t m 42 1 2 60 p f 29 1 2\n21 t m 19 1 4 21 p f 20 1 4 61 t f 51 1 1 61 p f 31 0 1\n22 t m 34 1 4 22 p f 31 0 1 62 t m 27 0 2 62 p m 32 1 2\n23 t f 46 0 1 23 p m 30 1 2 63 t m 31 1 1 63 p f 21 0 1\n24 t m 48 1 3 24 p f 62 0 4 64 t m 35 0 3 64 p m 33 1 3\n25 t m 50 1 4 25 p m 45 1 4 65 t m 67 1 2 65 p m 19 0 1\n26 t m 57 1 3 26 p f 43 0 3 66 t m 41 0 2 66 p m 62 1 4\n27 t f 13 0 2 27 p m 22 1 3 67 t f 31 1 2 67 p m 45 1 3\n28 t m 31 1 1 28 p f 21 0 1 68 t m 34 1 1 68 p f 54 0 1\n29 t m 35 1 3 29 p m 35 1 3 69 t f 21 0 1 69 p m 34 1 4\n30 t f 36 1 3 30 p f 37 0 3 70 t m 64 1 3 70 p m 51 0 1\n31 t f 45 0 1 31 p f 41 1 1 71 t f 61 1 3 71 p m 34 1 3\n32 t m 13 1 2 32 p m 42 0 1 72 t m 33 0 1 72 p f 43 0 1\n33 t m 14 0 4 33 p f 22 1 2 73 t f 36 0 2 73 p m 37 0 3\n34 t f 15 1 2 34 p m 24 0 1 74 t m 21 1 1 74 p m 55 0 1\n35 t f 19 1 3 35 p f 31 0 1 75 t f 47 0 2 75 p f 42 1 3\n36 t m 20 0 2 36 p m 32 1 3 76 t f 51 1 4 76 p m 44 0 2\n37 t m 23 1 3 37 p f 35 0 1 77 t f 23 1 1 77 p m 41 1 3\n38 t f 23 0 1 38 p m 21 1 1 78 t m 31 0 2 78 p f 23 1 4\n39 t m 24 1 4 39 p m 30 1 3 79 t m 22 0 1 79 p m 19 1 4\n40 t m 57 1 3 40 p f 43 1 3\n;\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.2.1     v readr     2.2.0\nv forcats   1.0.1     v stringr   1.6.0\nv ggplot2   4.0.3     v tibble    3.3.1\nv lubridate 1.9.5     v tidyr     1.3.2\nv purrr     1.2.2     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ntrial <- read.csv(\"trial.csv\")\n\ntrial <- trial |> \n  mutate(Center = as.factor(Center),\n         Initial=as.factor(Initial))\nglimpse(trial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 158\nColumns: 6\n$ Center      <fct> 1, 1, 41, 41, 2, 2, 42, 42, 3, 3, 43, 43, 4, 4, 44, 44, 5,~\n$ Treatment   <chr> \"t\", \"p\", \"t\", \"p\", \"t\", \"p\", \"t\", \"p\", \"t\", \"p\", \"t\", \"p\"~\n$ Sex         <chr> \"f\", \"f\", \"f\", \"m\", \"f\", \"f\", \"m\", \"f\", \"m\", \"m\", \"f\", \"m\"~\n$ Age         <int> 27, 32, 13, 22, 41, 47, 31, 21, 19, 31, 19, 35, 55, 24, 31~\n$ Improvement <int> 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1~\n$ Initial     <fct> 1, 2, 2, 3, 3, 1, 1, 3, 4, 4, 3, 3, 1, 3, 3, 2, 4, 2, 1, 1~\n```\n\n\n:::\n:::\n\n\n\n### SAS Code\n\n#### Without Covariates\n```{.r}\nproc logistic data=trial;\nclass treatment(ref=\"p\") /param=ref;\nstrata center; # <1>\nmodel improve(event=\"1\")= treatment;\nrun;\n```\n\n1. The strata argument lets SAS know that conditional logistic regression should be performed.\n\n#### With Covariates\n```{.r}\nproc logistic data=trial;\nclass sex (ref=\"f\") treatment(ref=\"p\") initial(ref=\"1\") /param=ref;\nstrata center;\nmodel improve(event=\"1\") = treatment initial sex age/\nselection=forward include=1 details;\nrun;\n```\n\n### R Code\n\nwithout covariates,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nmod_cond <- clogit(Improvement~Treatment + strata(Center), data=trial,model=TRUE)\nsummary(mod_cond)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 158L), Improvement) ~ Treatment + \n    strata(Center), data = trial, model = TRUE, method = \"exact\")\n\n  n= 158, number of events= 90 \n\n             coef exp(coef) se(coef)     z Pr(>|z|)  \nTreatmentt 0.5306    1.7000   0.2818 1.883   0.0597 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n           exp(coef) exp(-coef) lower .95 upper .95\nTreatmentt       1.7     0.5882    0.9785     2.953\n\nConcordance= 0.63  (se = 0.093 )\nLikelihood ratio test= 3.67  on 1 df,   p=0.06\nWald test            = 3.55  on 1 df,   p=0.06\nScore (logrank) test = 3.63  on 1 df,   p=0.06\n```\n\n\n:::\n:::\n\nWith covariates,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_cov <- clogit(Improvement~Treatment + Initial + Age + strata(Center), data=trial,model=TRUE)\nlibrary(MASS)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_step <- stepAIC(mod_cond,list(upper=mod_cov),direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=73.19\nSurv(rep(1, 158L), Improvement) ~ Treatment + strata(Center)\n\n          Df    AIC\n+ Initial  3 57.227\n+ Age      1 73.093\n<none>       73.188\n\nStep:  AIC=57.23\nSurv(rep(1, 158L), Improvement) ~ Treatment + strata(Center) + \n    Initial\n\n       Df    AIC\n<none>    57.227\n+ Age   1 57.952\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_step\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 158L), Improvement) ~ Treatment + \n    strata(Center) + Initial, data = trial, model = TRUE, method = \"exact\")\n\n              coef exp(coef) se(coef)     z       p\nTreatmentt  0.6243    1.8670   0.3646 1.712 0.08682\nInitial2    2.2230    9.2355   1.0772 2.064 0.03905\nInitial3    3.6658   39.0882   1.2530 2.926 0.00344\nInitial4    3.2769   26.4925   1.2254 2.674 0.00749\n\nLikelihood ratio test=25.63  on 4 df, p=3.752e-05\nn= 158, number of events= 90 \n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(mod_step)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in Anova.coxph(mod_step): LR tests not supported for models with clusters or strata\n Wald tests substituted\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nskipping term strata(Center)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: Surv(rep(1, 158L), Improvement)\n          Df   Chisq Pr(>Chisq)  \nTreatment  1  2.9324    0.08682 .\nInitial    3 10.5689    0.01430 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nAfter adding the covariates, only the initial skin condition rating was added to the model. There is a significant effect of initial skin condition ($\\chi^2$ = 10.57, p=0.0143), and a marginal effect of treatment ($\\chi^2 $= 2.93, p=0.09). The odds of improvement in the treatment group is 1.87 (0.914, 3.82) times that of the placebo group. The odds of improvement for severe initial skin condition is 26.5 (2.4, 292) times that of mild initial skin condition.\n\nNote that the answers will be different if you treated the initial skin condition as a continuous variable.\n:::\n\n## Exercise\n\nThe dataset CORRECT includes data from a study that asked pairs of individuals to interpret a visual infographic regarding health disparities arising from the COVID-19 pandemic. Each participant was asked about their occupations. The response variable was whether they correctly interpreted the infographic (1) or not (0). Implement a conditional logistic regression analysis to determine whether occupation affects the accuracy of interpretation of visual infographics.\n\n::: panel-tabset\n### SAS Data Set\n\n```{.r}\ndata correct;\nformat occupation $10.;\ninput pair Occupation $ Correct;\ndatalines;\n1 STEM 0\n1 Other 0\n2 Other 0\n2 Healthcare 1\n3 Healthcare 0\n3 Other 0\n4 Other 0\n4 STEM 0\n5 Healthcare 0\n5 Healthcare 0\n6 Healthcare 0\n6 STEM 0\n7 STEM 0\n7 Healthcare 1\n8 STEM 0\n8 Healthcare 1\n9 Healthcare 0\n9 Healthcare 1\n10 Other 0\n10 STEM 0\n11 Healthcare 1\n11 STEM 1\n12 Other 0\n12 Healthcare 0\n13 Healthcare 0\n13 Healthcare 1\n14 STEM 0\n14 STEM 0\n15 Healthcare 0\n15 Healthcare 1\n16 Other 0\n16 STEM 0\n17 Other 0\n17 STEM 0\n18 STEM 0\n18 Healthcare 0\n19 Healthcare 1\n19 Other 1\n20 Other 0\n20 Healthcare 0\n21 Other 0\n21 Other 0\n22 Other 1\n22 Healthcare 1\n23 Healthcare 0\n23 Healthcare 1\n24 Other 0\n24 Healthcare 0\n25 Healthcare 1\n25 STEM 0\n26 STEM 0\n26 Healthcare 1\n27 Other 1\n27 Healthcare 1\n28 Other 1\n28 Healthcare 0\n29 Healthcare 0\n29 STEM 0\n30 Other 0\n30 Other 0\n31 Other 1\n31 Healthcare 0\n32 Healthcare 0\n32 Other 1\n33 STEM 0\n33 Other 0\n34 Other 0\n34 STEM 1\n35 Healthcare 0\n35 Healthcare 0\n36 Healthcare 0\n36 Healthcare 1\n37 Other 0\n37 Healthcare 0\n38 Healthcare 0\n38 Other 1\n39 Healthcare 0\n39 Other 0\n40 Other 0\n40 Other 1\n41 Healthcare 1\n41 Healthcare 0\n42 Other 0\n42 Other 0\n43 Other 1\n43 STEM 0\n44 Other 1\n44 Healthcare 0\n45 STEM 0\n45 STEM 0\n46 Healthcare 0\n46 Healthcare 0\n47 Healthcare 0\n47 Other 1\n48 Healthcare 0\n48 Healthcare 0\n49 Other 0\n49 STEM 1\n50 Healthcare 0\n50 Healthcare 0\n;\n\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrect <- read.csv(\"correct.csv\")\n\ncorrect <- correct |> \n  mutate(Pair = as.factor(Pair))\nglimpse(correct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 3\n$ Pair       <fct> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 1~\n$ Occupation <chr> \"STEM\", \"Other\", \"Other\", \"Healthcare\", \"Healthcare\", \"Othe~\n$ Correct    <int> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,~\n```\n\n\n:::\n:::\n\n\n:::\n\n## Exercise\n\nThe dataset CORRECT includes data from a study that asked pairs of individuals to interpret a visual infographic regarding health disparities arising from the COVID-19 pandemic. Each participant was asked about their occupations. The response variable was whether they correctly interpreted the infographic (1) or not (0). Implement a conditional logistic regression analysis to determine whether occupation affects the accuracy of interpretation of visual infographics.\n\n::: {.panel-tabset}\n### SAS Code\n\n```{.r}\nproc logistic data=correct;\nstrata pair;\nclass occupation(ref=\"Other\")/param=ref;\nmodel correct(event=\"1\")=occupation/details;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- clogit(Correct~Occupation + strata(Pair),data=correct,model=TRUE)\nmod1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nclogit(Correct ~ Occupation + strata(Pair), data = correct, model = TRUE)\n\n                   coef exp(coef) se(coef)      z     p\nOccupationOther  0.6702    1.9546   0.7278  0.921 0.357\nOccupationSTEM  -0.6531    0.5204   0.8844 -0.738 0.460\n\nLikelihood ratio test=2.22  on 2 df, p=0.3293\nn= 100, number of events= 29 \n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(mod1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in Anova.coxph(mod1): LR tests not supported for models with clusters or strata\n Wald tests substituted\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nskipping term strata(Pair)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: Surv(rep(1, 100L), Correct)\n           Df  Chisq Pr(>Chisq)\nOccupation  2 1.9604     0.3752\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThere was no significant effect of occupation on the accuracy of interpretation of visual infographics ($\\chi^2_2=1.96,p=0.38$).\n:::\n\n## Crossover Designs\n\n- When an individual or group of individuals undergo different treatments at each pre-determined period.\n  - Patients act as their own controls.\n- Common types of crossover design studies:\n  - Two-period design (AB/BA)\n  - Three-period design\t(ABC/CBA/ACB…)\n\n- Important effects to account for in crossover designs are the carryover effect and the period effect.\n  - An extra variable can be introduced to indicate which effect is carried over at any given period.\n  - If the preceding treatment is a placebo, it is safe to assume the absence of a carryover effect.\n\n## Example\n\nPatients were stratified according to two age groups and then assigned to one of three treatment sequences. Responses were measured as favorable (F) or unfavorable (U); thus, FF indicates a favorable response in both Period 1 and Period 2. The data is included in the SAS file as CROSS2 and `crossover.csv`.\n\n::: {.panel-tabset}\n### Contingency Table\n\n![](img/crossover_C10.png)\n\n### `SAS` Data Set\n\n```{.r}\ndata cross1 (drop=count);\ninput age $ sequence $ time1 $ time2 $ count;\ndo i=1 to count;\noutput;\nend;\ndatalines;\nolder AB F F 12\nolder AB F U 12\nolder AB U F 6\nolder AB U U 20\nolder BP F F 8\nolder BP F U 5\nolder BP U F 6\nolder BP U U 31\nolder PA F F 5\nolder PA F U 3\nolder PA U F 22\nolder PA U U 20\nyounger BA F F 19\nyounger BA F U 3\nyounger BA U F 25\nyounger BA U U 3\nyounger AP F F 25\nyounger AP F U 6\nyounger AP U F 6\nyounger AP U U 13\nyounger PB F F 13\nyounger PB F U 5\nyounger PB U F 21\nyounger PB U U 11\n;\n\ndata cross2; set cross1;\nsubject=_n_;\nperiod=1;\ndrug = substr(sequence, 1, 1);\ncarry='none';\nresponse =time1;\noutput;\nperiod=2;\ndrug = substr(sequence, 2, 1);\ncarry = substr(sequence, 1, 1);\nif carry='P' then carry='none';\nresponse =time2;\noutput;\nrun;\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ncrossover <-read.csv(\"crossover.csv\", stringsAsFactors = TRUE)\ncrossover <- crossover |> \n  mutate(Subject= as.factor(Subject),\n         period = as.factor(period),\n         response = ifelse(response==\"F\",1,0)) \nglimpse(crossover)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 600\nColumns: 6\n$ age      <fct> older, older, older, older, older, older, older, older, older~\n$ Subject  <fct> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10,~\n$ period   <fct> 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1~\n$ drug     <fct> A, B, A, B, A, B, A, B, A, B, A, B, A, B, A, B, A, B, A, B, A~\n$ carry    <fct> none, A, none, A, none, A, none, A, none, A, none, A, none, A~\n$ response <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n```\n\n\n:::\n:::\n\n\n\n### SAS Code\n\n```{.r}\nproc logistic data=cross2;\nclass drug period age carry / param=ref;\nstrata subject;\nmodel response = period drug period*age carry; # <1>\nA_B: test drugA=drugB;\noddsratio drug;\nrun;\n\n```\n\n1. Carryover effect is accounted for with `carry`.\n\nSince there is no significant carryover effect, we can remove it from the model.\n\n```{.r}\nproc logistic data=cross2;\nclass drug period age carry / param=ref;\nstrata subject;\nmodel response = period drug period*age;\nA_B: test drugA=drugB;\noddsratio drug;\nrun;\n\n```\n\n### R Code\n\n::: callout-important\nBecause age dictates the sequence of treatments, age by itself is confounded by the other variables in the model. What we can test for is the interaction between period and age-- do the age groups behave differently across age.\n\nHowever, because of the nesting, there are some coefficients that are non-estimable as shown below.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\n\nmod_c <- clogit(response~period+drug +period:age+ carry + strata(Subject), \n                data=crossover,\n                model=TRUE)\nsummary(mod_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 600L), response) ~ period + drug + \n    period:age + carry + strata(Subject), data = crossover, model = TRUE, \n    method = \"exact\")\n\n  n= 600, number of events= 284 \n\n                      coef exp(coef) se(coef)      z Pr(>|z|)  \nperiod2             0.7457    2.1080   0.7678  0.971   0.3314  \ndrugB              -1.2486    0.2869   0.6523 -1.914   0.0556 .\ndrugP              -1.2467    0.2875   0.6807 -1.832   0.0670 .\ncarryB             -0.3750    0.6873   1.1517 -0.326   0.7447  \ncarrynone           0.1903    1.2096   1.1125  0.171   0.8642  \nperiod1:ageyounger -0.6912    0.5010   0.4654 -1.485   0.1375  \nperiod2:ageyounger      NA        NA   0.0000     NA       NA  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                   exp(coef) exp(-coef) lower .95 upper .95\nperiod2               2.1080     0.4744   0.46805     9.494\ndrugB                 0.2869     3.4854   0.07990     1.030\ndrugP                 0.2875     3.4788   0.07572     1.091\ncarryB                0.6873     1.4550   0.07191     6.568\ncarrynone             1.2096     0.8267   0.13668    10.705\nperiod1:ageyounger    0.5010     1.9962   0.20119     1.247\nperiod2:ageyounger        NA         NA        NA        NA\n\nConcordance= 0.767  (se = 0.055 )\nLikelihood ratio test= 48.78  on 6 df,   p=8e-09\nWald test            = 32.85  on 6 df,   p=1e-05\nScore (logrank) test = 43.66  on 6 df,   p=9e-08\n```\n\n\n:::\n:::\n\n\nBecause of this, we cannot use `Anova()` in `car`. We will have to do the joint test manually using `anova()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_main <- clogit(response~period+drug + carry + strata(Subject), \n                data=crossover,\n                model=TRUE)\n\nmod_nocarry <- clogit(response~period + drug + period:age+ strata(Subject), \n                data=crossover,\n                model=TRUE)\nsummary(mod_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 600L), response) ~ period + drug + \n    period:age + carry + strata(Subject), data = crossover, model = TRUE, \n    method = \"exact\")\n\n  n= 600, number of events= 284 \n\n                      coef exp(coef) se(coef)      z Pr(>|z|)  \nperiod2             0.7457    2.1080   0.7678  0.971   0.3314  \ndrugB              -1.2486    0.2869   0.6523 -1.914   0.0556 .\ndrugP              -1.2467    0.2875   0.6807 -1.832   0.0670 .\ncarryB             -0.3750    0.6873   1.1517 -0.326   0.7447  \ncarrynone           0.1903    1.2096   1.1125  0.171   0.8642  \nperiod1:ageyounger -0.6912    0.5010   0.4654 -1.485   0.1375  \nperiod2:ageyounger      NA        NA   0.0000     NA       NA  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                   exp(coef) exp(-coef) lower .95 upper .95\nperiod2               2.1080     0.4744   0.46805     9.494\ndrugB                 0.2869     3.4854   0.07990     1.030\ndrugP                 0.2875     3.4788   0.07572     1.091\ncarryB                0.6873     1.4550   0.07191     6.568\ncarrynone             1.2096     0.8267   0.13668    10.705\nperiod1:ageyounger    0.5010     1.9962   0.20119     1.247\nperiod2:ageyounger        NA         NA        NA        NA\n\nConcordance= 0.767  (se = 0.055 )\nLikelihood ratio test= 48.78  on 6 df,   p=8e-09\nWald test            = 32.85  on 6 df,   p=1e-05\nScore (logrank) test = 43.66  on 6 df,   p=9e-08\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod_main,mod_c) # period:age effect\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(rep(1, 600L), response)\n Model 1: ~ period + drug + carry + strata(Subject)\n Model 2: ~ period + drug + period:age + carry + strata(Subject)\n  loglik  Chisq Df Pr(>|Chi|)\n1 -59.89                     \n2 -58.79 2.2005  1      0.138\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod_nocarry,mod_c) # carryover effect\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(rep(1, 600L), response)\n Model 1: ~ period + drug + period:age + strata(Subject)\n Model 2: ~ period + drug + period:age + carry + strata(Subject)\n   loglik  Chisq Df Pr(>|Chi|)\n1 -58.913                     \n2 -58.790 0.2465  2      0.884\n```\n\n\n:::\n:::\n\n\nBecause there is no evidence of a carryover effect, we can interpret the results of the model without the carryover effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_nocarry)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 600L), response) ~ period + drug + \n    period:age + strata(Subject), data = crossover, model = TRUE, \n    method = \"exact\")\n\n  n= 600, number of events= 284 \n\n                      coef exp(coef) se(coef)      z Pr(>|z|)    \nperiod2             0.4803    1.6166   0.3219  1.492  0.13565    \ndrugB              -1.0800    0.3396   0.3268 -3.305  0.00095 ***\ndrugP              -1.3462    0.2602   0.3289 -4.093 4.26e-05 ***\nperiod1:ageyounger -0.7102    0.4916   0.4576 -1.552  0.12066    \nperiod2:ageyounger      NA        NA   0.0000     NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                   exp(coef) exp(-coef) lower .95 upper .95\nperiod2               1.6166     0.6186    0.8602    3.0382\ndrugB                 0.3396     2.9448    0.1790    0.6443\ndrugP                 0.2602     3.8429    0.1366    0.4958\nperiod1:ageyounger    0.4916     2.0343    0.2005    1.2052\nperiod2:ageyounger        NA         NA        NA        NA\n\nConcordance= 0.767  (se = 0.055 )\nLikelihood ratio test= 48.53  on 4 df,   p=7e-10\nWald test            = 32.34  on 4 df,   p=2e-06\nScore (logrank) test = 43.14  on 4 df,   p=1e-08\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThere is no significant carryover effect. At a significance level of 0.05, there is no significant interaction effect. There is a significant drug effect ($\\chi^2$ = 18.7, p=0.001). The odds of a favorable response with drug A is 3.84 (2.02, 7.32) times that for the placebo and 2.95 (1.55, 5.59) times that for drug B.\n:::\n\n## Three-Period Crossover Studies\n\n- The approach is similar to the two-period crossover studies\n  - Period effect\n  - Crossover effect – Need to restrict which levels you assume a carryover effect for.\n- The response profiles would be different:   \n  - The total values of {$y_{hi}$={0,1,2,3}} can be {0,1,2,3}. Only {1,2} is informative, but adds complexity to the likelihood.\n- PROC LOGISTIC can handle three-period crossover studies with the same syntax.\n\n## Matching in Case-Control Studies\n\n- Case-control studies pair a person known to have the event of interest (case) with a person who doesn’t have the event (control)\n  - Research question: Is the exposure/risk factor associated with the event?\n\n## Conditional Logistic Regression: Matching\n- The conditional likelihood for the matched pairs data is the unconditional likelihood for a logistic regression model where the response is always equal to 1, the covariate values are equal to the differences between the values for the case and the control, and there is no intercept.\n  - The pairs/groups are used as the strata in the analysis.\n\n## Example\n\n- The data set ENDO is subset of the data from the Los Angeles Study of the Endometrial Cancer Data in Breslow and Day (1980). Outcome=1 corresponds to cases of endometrial cancer. Two prognostic factors are included\n  - Gall: gallbladder disease\n  - Hyper: hypertension\n- Use conditional logistic regression to determine the association between gallbladder disease and endometrial cancer after controlling for hypertension.\n\n::: {.panel-tabset}\n### SAS Data Set\n\n```{.r}\ndata endo;\n   do ID=1 to 63;\n      do Outcome = 1 to 0 by -1;\n         input Gall Hyper @@;\n         output;\n      end;\n   end;\n   datalines;\n0 0  0 0    0 0  0 0    0 1  0 1    0 0  1 0    1 0  0 1\n0 1  0 0    1 0  0 0    1 1  0 1    0 0  0 0    0 0  0 0\n1 0  0 0    0 0  0 1    1 0  0 1    1 0  1 0    1 0  0 1\n0 1  0 0    0 0  1 1    0 0  1 1    0 0  0 1    0 1  0 0\n0 0  1 1    0 1  0 1    0 1  0 0    0 0  0 0    0 0  0 0\n0 0  0 1    1 0  0 1    0 0  0 1    1 0  0 0    0 1  0 0\n0 1  0 0    0 1  0 0    0 1  0 0    0 0  0 0    1 1  1 1\n0 0  0 1    0 1  0 0    0 1  0 1    0 1  0 1    0 1  0 0\n0 0  0 0    0 1  1 0    0 0  0 1    0 0  0 0    1 0  0 0\n0 0  0 0    1 1  0 0    0 1  0 0    0 0  0 0    0 1  0 1\n0 0  0 0    0 1  0 1    0 1  0 0    0 1  0 0    1 0  0 0\n0 0  0 0    1 1  1 0    0 0  0 0    0 0  0 0    1 1  0 0\n1 0  1 0    0 1  0 0    1 0  0 0\n;\n\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nendo <- read.csv(\"endo.csv\")\nendo <- endo |> \n  mutate(ID = as.factor(ID))\nglimpse(endo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 126\nColumns: 4\n$ ID      <fct> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, ~\n$ Outcome <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,~\n$ Gall    <int> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,~\n$ Hyper   <int> 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,~\n```\n\n\n:::\n:::\n\n\n### SAS Code\n\n```{.r}\nproc logistic data=endo;\n   strata ID;\n   model outcome(event='1')=Gall hyper Gall*hyper/selection=forward include=2 details;\nrun;\n```\n\n### R Code\n\nFirst, let's explore the interaction model to see if there is evidence of an interaction between the two comorbidities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_c <- clogit(Outcome~Gall + Hyper + Gall:Hyper + strata(ID), \n                data=endo,\n                model=TRUE)\nsummary(mod_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 126L), Outcome) ~ Gall + Hyper + \n    Gall:Hyper + strata(ID), data = endo, model = TRUE, method = \"exact\")\n\n  n= 126, number of events= 63 \n\n              coef exp(coef) se(coef)      z Pr(>|z|)  \nGall        1.5168    4.5577   0.6990  2.170    0.030 *\nHyper       0.6270    1.8721   0.4353  1.440    0.150  \nGall:Hyper -1.5483    0.2126   1.1246 -1.377    0.169  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n           exp(coef) exp(-coef) lower .95 upper .95\nGall          4.5577     0.2194   1.15818    17.935\nHyper         1.8721     0.5342   0.79760     4.394\nGall:Hyper    0.2126     4.7035   0.02346     1.927\n\nConcordance= 0.603  (se = 0.068 )\nLikelihood ratio test= 6.5  on 3 df,   p=0.09\nWald test            = 5.56  on 3 df,   p=0.1\nScore (logrank) test = 6.17  on 3 df,   p=0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(car)\nAnova(mod_c)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in Anova.coxph(mod_c): LR tests not supported for models with clusters or strata\n Wald tests substituted\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nskipping term strata(ID)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: Surv(rep(1, 126L), Outcome)\n           Df  Chisq Pr(>Chisq)  \nGall        1 2.8137    0.09346 .\nHyper       1 0.7775    0.37792  \nGall:Hyper  1 1.8955    0.16858  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nBecause the interaction, we can take it out of the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_main <- clogit(Outcome~Gall + Hyper  + strata(ID), \n                data=endo,\n                model=TRUE)\n\nsummary(mod_main)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(rep(1, 126L), Outcome) ~ Gall + Hyper + \n    strata(ID), data = endo, model = TRUE, method = \"exact\")\n\n  n= 126, number of events= 63 \n\n        coef exp(coef) se(coef)     z Pr(>|z|)  \nGall  0.9704    2.6390   0.5307 1.828   0.0675 .\nHyper 0.3481    1.4163   0.3770 0.923   0.3558  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n      exp(coef) exp(-coef) lower .95 upper .95\nGall      2.639     0.3789    0.9326     7.468\nHyper     1.416     0.7061    0.6765     2.965\n\nConcordance= 0.635  (se = 0.066 )\nLikelihood ratio test= 4.55  on 2 df,   p=0.1\nWald test            = 4.01  on 2 df,   p=0.1\nScore (logrank) test = 4.36  on 2 df,   p=0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(mod_main)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in Anova.coxph(mod_main): LR tests not supported for models with clusters or strata\n Wald tests substituted\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nskipping term strata(ID)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: Surv(rep(1, 126L), Outcome)\n      Df  Chisq Pr(>Chisq)  \nGall   1 3.3432    0.06748 .\nHyper  1 0.8526    0.35583  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThere is marginal association between history of gallbladder disease ($\\chi^2$ = 3.34, p=0.07) and endometrial cancer, but there is no evidence of an association between hypertension and endometrial cancer ($\\chi^2$ = 0.85, p=0.36). The odds of developing endometrial cancer is 164% higher for those with gallbladder disease (OR: 2.64, 95% CI: 0.93, 7.5) \n:::\n\n  \n## Exact Conditional Logistic Regression\n\n- Exact tests can be used if there is not enough data, or the data are too sparse.\n  - EXACT statement in SAS can estimate effects and perform joint tests for repeated measures.\n  - If exact methods are used, selection options cannot be used concurrently.\n\n\n## Example: Exact Conditional Logistic Regression\n\nThe data set CARDIO includes data from a cardiovascular study of eight animals who received various drug treatments. Researchers then arrested coronary flow, which led to the development of regional ischemia, and they recorded whether an adverse cardiovascular event occurred during an eight-minute interval. The heart was re-perfused for 50 minutes to allow the heart to return to normal, and then another treatment was tested. Thus, there are up to five repeated measurements on eight animals. The treatments are: (1) Control (C), (2) Test Drug with counteracting agent (DA), (3) Low dose test drug (D1), (4) High dose test drug (D2).\n\nThe treatment S indicates the placement of intracoronary artery catheter, which is dropped in the final data set.\n\n:::{.panel-tabset}\n### SAS Data Set\n```{.r}\ndata cardio;\ninput animal treatment $ response $ @@;\nif treatment='S' then delete;\nelse if treatment='C' then ordtreat=1;\nelse if treatment='DA' then ordtreat=2;\nelse if treatment='D1' then ordtreat=3;\nelse if treatment='D2' then ordtreat=4;\ndatalines;\n1 S no 1 C no 1 C no 1 D2 yes 1 D1 yes\n2 S no 2 D2 yes 2 C no 2 D1 yes\n3 S no 3 C yes 3 D1 yes 3 DA no 3 C no\n4 S no 4 C no 4 D1 yes 4 DA no 4 C no\n5 S yes 5 C no 5 DA no 5 D1 no 5 C no\n6 S no 6 C no 6 D1 yes 6 DA no 6 C no\n7 S no 7 C no 7 D1 yes 7 DA no 7 C no\n8 S yes 8 C yes 8 D1 yes\n;\n\ndata cardio;\nset cardio;\ndrop treatment;\nrun;\n```\n\n### SAS Code\n\n```{.r}\nproc logistic data=cardio descending exactonly;\nstrata animal;\nmodel response = ordtreat;\nexact ordtreat / estimate=both;\nrun;\n```\n\n### Answer\n\nWe treat the treatments as an ordinal variable with equal separation. Based on the exact analysis, there is a significant effect of treatment (p=0.0017). The odds of an adverse event becomes seven times higher with each unit change in treatment level.\n:::",
    "supporting": [
      "Chapter10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}