{
  "hash": "7d612035eb130461f94077c57ead274f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 4\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: solarized\n    scrollable: true\n    footer: \"Chapter 4- [Back to home](https://madfudolig.quarto.pub/eab770slides/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n  pdf: \n    number-sections: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n# \\$ 2 \\times r\\$ and $s \\times 2$ tables\n\n## Outline\n\n-   $2 \\times r$ table\n-   Sets of $2 \\times r$ tables\n-   $s \\times 2$ table\n-   Sets of $s \\times 2$ tables\n    -   Relationships between Sets of Tables\n    -   Exact Analysis of Association ($s \\times 2$) tables)\n\n# what if there are more than two outcomes?\n\n## Multiple Categorical Outcomes\n\n-   Likert Scale (Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree)\n-   Part of a whole (None, Some, All)\n-   We would need more than two columns in our contingency table to account for these other outcomes.\n    -   Variables can be forced to be “binary”, but some important information can be lost.\n-   If there are $r$ outcome levels and $2$ levels of the exploratory variable, we use a $2 \\times r$ contingency table.\n    -   Focus on outcomes being ordinally scaled.\n\n## $2\\times r$ table\n\n::: columns\n::: {.column style=\"width:40%; font-size: 75%\"}\nLet $A_j$ be the $j^{th}$ outcome level.\n\n-   Since $A_J$ is ordinal, then $A_1 < A_2 < A_3 <... A_r$.\n    -   The $\\leq$ can replace $<$ as long as at least one is a strict inequality\n\nTo account for ordinality, we assign a set of scores $\\mathbf{a}$ reflecting the relationship between response levels.\n\n$$\n\\mathbf{a} = \\{a_1, a_2, a_3,... a_r\\} : a_1 < a_2 < ...< a_r\n$$\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/2xr_C4.png)\n:::\n:::\n\n## Row Mean Scores\n\nWe can define a group mean for $X_1$, denoted by $\\bar{f}_1$.\n\n$$\n\\bar{f}_1 = \\sum_{j=1}^r \\frac{a_j n_{1j}}{n_{1+}}\n$$\n\nThe random variable $\\bar{f}_1$ approximately has a normal distribution when the central limit theorem is imposed.\n\n-   High row sum\n\nWe refer to these scores as **Row Mean Scores**\n\n## 2 \\times r table: Null hypothesis\n\nNull hypothesis $H_0$: There is no association between the row (X) and column (A) variables.\n\nUnder the null hypothesis:\n\n-   The expected value of the mean can be calculated as:\n\n$$\n\\mu_a =  \\sum_{j=1}^r \\frac{a_j n_{+j}}{n}\n$$\n\n## Mean Score Statistic\n\nWe can define a mean score statistic, $Q_S$, given by\n\n$$\nQ_S = \\frac{(\\bar{f}_1 - \\mu_1)^2}{V}\n$$\n\n::: callout-note\n-   $V$ is the variance of $\\bar{f}_1$ under the null hypothesis.\n-   $Q_S$ follows a chi-square distribution with one degree of freedom.\n:::\n\n## Mean Score Statistic\n\n-   Targets alternative hypothesis of mean shifts to the hypothesis of no association\n    -   Uses fewer degrees of freedom compared to Pearson chi-square\n\n::: callout-note\nPearson chi-square requires $(r-1)$ degrees of freedom compared to 1 degree of freedom for $Q_S$\n:::\n\n-   The mean score statistic can also be used to determine the tendency of one group having better scores compared to the other.\n-   The $Q_S$ sample size condition is less stringent:\n\n::: callout-note\nChoose one or more cutpoints \\$ j = (2,3,...(r-1))\\$, add the first through $j^{th}$ columns together and add the $(j-1)^{th}$ through $r^{th}$ columns together. If both of these sums are 5 or greater for at least one cutpoint in each row, then the sample size is adequate.\n:::\n\n## $2 \\times r$ analysis: SAS {.smaller}\n\n-   Data should be encoded in increasing order of the outcome variable.\n-   The `FREQ` procedure will give us the mean score statistic:\n    -   **ORDER=DATA should be included in the code with the `PROC FREQ` statement. (See sample code)**\n-   Can be obtained using the `cmh` option or `chisq` option in the `tables` statement\n    -   $Q_S$: Mantel-Haesnzel Chi-square statistic in the SAS output\n    -   `CMH`: “*Row Mean Scores Differ*” statistic.\n      - The CMH values would now display different values unlike the $2 \\times 2$ tables.\n\n## Example {.smaller}\n\nThe data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.\n\n- Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group?\n\n![](img/arthritis_C4.png)\n\n## Example\n\nThe data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.\n\n- Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group?\n\n::: {.panel-tabset}\n\n### SAS Code\n\n```{.r}\ndata arth;\ninput treat $ response $ count @@;\ndatalines;\nactive none 13 active some 7 active marked 21\nplacebo none 29 placebo some 7 placebo marked 7\n;\nproc freq data=arth order=data;\nweight count;\ntables treat*response / cmh chisq nocol nopct;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcdExtra)\ndat  <- expand.grid(Treat=c(\"Active\",\"Placebo\"),\n                    Response = c(\"None\",\"Some\",\"Marked\")\n                  ) |> \nmutate(count = c(13,29,7,7,21,7))\n\nxtabs(count ~  Treat+Response  ,data=dat) -> dat_cc\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Response\nTreat     None Some Marked\n  Active    13    7     21\n  Placebo   29    7      7\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        types=\"ALL\",\n        overall=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treat by Response \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 12.900  2 0.00158084\nrmeans  Row mean scores differ 12.859  1 0.00033586\ncmeans  Col mean scores differ 12.900  2 0.00158084\ncor        Nonzero correlation 12.859  1 0.00033586\n```\n\n\n:::\n:::\n\n### Answer\n\n$Q_S$ = 12.86, p=0.0003. We have strong evidence to conclude that the active treatment displayed higher improvement compared to the placebo group.\n\n- The active group has a higher proportion of marked + some improvement, which enables us to formulate the following conclusion.\n\n:::\n\n## Exercise\n\nA survey was administered to students at a US-based university who are habitual smokers to determine the likelihood of using a mobile app to help them quit smoking. Is there sufficient evidence to conclude that heavy smokers are less likely to use a mobile app compared to light smokers?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       Response\nSmokers Very Unlikely Unlikely Likely Very Likely\n  Heavy            36       75     56          17\n  Light            38       59     64          23\n```\n\n\n:::\n:::\n\n\n## Exercise\n\nA survey was administered to students at a US-based university who are habitual smokers to determine the likelihood of using a mobile app to help them quit smoking. Is there sufficient evidence to conclude that heavy smokers are less likely to use a mobile app compared to light smokers?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Chapter4_files/figure-pdf/unnamed-chunk-4-1.pdf)\n:::\n:::\n\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata smoke;\ninput treat $ response $ count @@;\ndatalines;\nheavy vu 36 heavy u 75 heavy l 56 heavy vl 17\nlight vu 38 light u 59 light l 64 light vl 23\n;\n\nproc freq data=smoke order=data;\nweight count;\ntables treat*response / cmh chisq nocol nopct;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcdExtra)\nCMHtest(dat_cc,\n        types=\"rmeans\",\n        overall=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Smokers by Response \n\n                AltHypothesis  Chisq Df    Prob\nrmeans Row mean scores differ 1.0394  1 0.30795\n```\n\n\n:::\n:::\n\n\n### Answer\n\n$Q_S$ = 1.04, p=0.31. There is insufficient evidence that heavy smokers are less likely to use a mobile app compared to light smokers.\n:::\n\n\n# Sets of $2\\times r$ tables\n\n## Sets of $2\\times r$ tables\n\n- We extend the Mantel-Haenszel strategy to $2\\times r$ tables for ordinal responses\n- Compute mean scores for the responses\n  - Calculate mean score differences across tables\n  - Similar approach to the difference in proportions ($Q_S$)\n- Assume hypergeometric distributions for the contingency tables in the different strata.\n  - Also assume that the across-strata sample sizes are sufficiently large for each group (row sums)\n\n## Extended Mean Score Statistic\n\n- $Q_{SMH}$ is the extended Mantel-Haenszel mean score statistic.\n  - Also known as the ANOVA statistic\n  - Function of the weighted average of the differences in mean scores of the two treatments for all strata.\n- $Q_{SMH}$ is good for detecting consistent patterns of differences across strata.\n- Sample size requirements involve collapsing each stratum table into a 2x2 table by choosing cutpoints (Just like that in $Q_S$), then apply the Mantel-Fleiss criterion.\n\n## Different Types of Scores\n\n\n::: {.panel-tabset}\n### Integer Scores\n- (0,1,2,...)\n- Response levels are ordered categories that correspond to discrete counts.\n- Produce same results regardless of starting number.\n- Default in SAS.\n\n### Rank \n\n- Rank scores based on the row totals.\n- In stratified analysis, rank scores are not robust when there are large strata.\n\n$$\nR_i^1 = \\sum_{k<i} n_{k+} + \\frac{n_{i+}+1}{2}\n$$\n### Ridit\n- Ridit scores are standardized rank scores based on the sample size\n\n$$\nR_i^3 = 1/(n+1) \\left[\\sum_{k<i} n_{k+} + \\frac{n_{i+}+1}{2}\\right]\n$$\n\n### Standardized Midranks\n- Also known as modified ridit scores.\n- Constrained to lie between 0 and 1.\n- Requires no scaling of response levels.\n- Used when there is no argument for equal spaces between ordinal levels\n\n$$\nR_i^3 = 1/(n+1) \\left[\\sum_{k<i} n_{k+} + \\frac{n_{i+}+1}{2}\\right]\n$$\n\n### Logrank Scores\n- Useful when the distribution is L-shaped.\n- Need to apply the logarithmic transformation of the rank scores before applying to the `tables` statement.\n:::\n\n\n## Different Types of Scores\n\n::: callout-note\nWhen there is no strata, the rank, ridit, and modridit scores correspond to the Wilcoxon rank-sum test. \n:::\n\n::: callout-note\nIn stratified analyses, the _modridit scores_ are preferred out of these rank-based scores because it produces an extension of the Wilcoxon rank-sum test.\n:::\n\n## Measures of Association in Sets of $ 2 \\times r$ tables\n\n:::{.panel-tabset}\n### Somers' D\n- Measure of association for ordinally scaled data.\n- For ordinal scores with two groups, let $G1$ be the score of group 1 and $G2$ be the score of group 2\n\n$$\nD = \\frac{P(G1 > G2) - P(G1 < G2)}{P(G1>G2)+P(G1<G2) + P(G1=G2)}\n$$\n\n::: callout-note\nSAS will provide two values of the Somers'D: $D(R|C)$ and $D(C|R)$\n\n- $D(R|C)$ treats the _column_ as the independent variable.\n- $D(C|R)$ treats the _row_ as the independent variable\n\n:::\n\n### Mann-Whitney rank measure of association\n\n- Assesses association between a dichotomous predictor variable and an ordinal outcome.\n- Can be calculated from Somers'D\n\n$$\ng_h = (D+1)/2\n$$\nwhere the standard error of $g_h$ is $v_h = v_D/2$.\n:::\n\n## Extension of the Mann-Whitney Rank Measure\n\n- When there are $q$ strata, we can calculate a test statistic $Q_H$ such that\n\n$$\nQ_H = \\sum_{h=1}^q (g_h-\\tilde{g})^2/v_h  \n$$\n$$\n\\tilde{g} = \\frac{\\sum_{h=1}^q g_h\\left(n_{h1}n_{h2}/(n_{h1}+n_{h2})\\right)}{\\sum_{h=1}^q \\left(n_{h1}n_{h2}/(n_{h1}+n_{h2})\\right)}\n$$\n\n- This is an extension of the van Elteren's rank sum test.\n\n## Scores: SAS\n\n- The default score used in SAS are integer/table scores\n- Scoring method can be specified using the SCORES option in SAS\n  - TABLE: integer\n  - RIDIT: midranks\n  - MODRIDIT: standardized midranks\n  - RANK: rank scores.\n- Use the Cochran-Mantel-Haenszel table (CMH) in testing the hypothesis\n  - Difference in mean scores: “Row means differ”\n\n```{.r}\nproc freq;\ntables A*B/scores=MODRIDIT;\nrun;\n\n```\n\n\n## Somers' D: SAS\n\n- `measures` includes the Somers' D estimate with the standard errors (`ASE` column).\n- The Mann-Whitney rank-sum statistic can be calculated using PROC IML.\n- The `cl` option calculates confidence intervals for Somers' D\n\n```{.r}\nproc freq;\ntables A*B/scores=MODRIDIT measures cl;\nrun;\n```\n\n## Mann-Whitney: SAS (optional)\n\n```{.r}\nproc freq ;\nweight count;\ntables S*A*B/ measures scores=modridit;\noutput out=somerout smdcr; # <1>\nods output CrosstabFreqs=myFreqs; # <2>\nrun;\ndata ns;\nset myFreqs; where _type_=\"110\";\nrun;\n\nproc iml;\nuse somerout var{_SMDCR_ E_SMDCR};\nread all into combined;\nuse ns var{Frequency};\nread all into total;\nprint total;\nWH=(total[1,]#total[2,]) / (total[1,]+total[2,]) //\n(total[3,]#total[4,]) / (total[3,]+total[4,]);\nprint wh;\nGH=(combined[,1]+1)/2;\nSEGH=(combined[,2])/2;\nprint wh GH SEGH;\nQH= (GH[1] - GH[2])**2 / SSQ(SEGH);\npvalue=1-probchi(QH,1);\nprint GH SEGH QH pvalue;\ngtilde1=sum(GH # WH);\ngtilde2=sum(WH);\ngtilde=gtilde1/gtilde2;\ngtildevar=(sum(WH##2 # SEGH##2)) /((sum(WH))**2);\nsegtilde=sqrt(gtildevar);\nqgtilde=(gtilde-.5)**2/gtildevar;\nprint gtilde gtildevar qgtilde;\nquit;\n```\n\n1. Outputs somers'D(C|R) and error\n2. crosstabs outputs the contigency table\n\n## Example\n\n::: columns\n::: {.column style=\"width:50%; font-size: 75%\"}\nThe data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.\n\n- Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group after controlling for gender?\n- Compare the results using table scores and modridit scores.\n:::\n\n::: {.column style=\"width:50%\"}\n![](img/arth2_C4.png)\n:::\n:::\n\n\n## Example\n\n\n::: columns\n::: {.column style=\"width:50%; font-size: 75%\"}\n\n- Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group after controlling for gender?\n- Compare the results using table scores and modridit scores.\n:::\n\n::: {.column style=\"width:50%\"}\n![](img/arth2_C4.png)\n:::\n:::\n\n:::{.panel-tabset}\n### SAS Code\n```{.r}\ndata arth;\ninput gender $ treat $ response $ count @@;\ndatalines;\nfemale active none 6 female active some 5 female active marked 16\nfemale placebo none 19 female placebo some 7 female placebo marked 6\nmale active none 7 male active some 2 male active marked 5\nmale placebo none 10 male placebo some 0 male placebo marked 1\n;\n\nproc freq data=arth order=data;\nweight count;\ntables gender*treat*response / cmh nocol nopct; # <1>\ntables gender*treat*response / cmh nocol nopct scores=modridit; # <2>\nrun;\n```\n\n1. Table Scores\n2. Modridit scores (Standardized Midranks)\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Improvement=c(\"None\",\"Some\",\"Marked\"),\n            Treatment = c(\"Active\",\"Placebo\"),\n            gender=c(\"Female\",\"Male\")\n            ) |> \nmutate(count = c(6,5,16,19,7,6,7,2,5,10,0,1))\nxtabs(count ~  Treatment + Improvement + gender  ,data=dat) -> dat_cc\ndat_cc\nCMHtest(dat_cc,\n        types=\"ALL\",\n        cscores = 1:ncol(dat_cc), # <1>\n        overall=T, strata=\"gender\")\n\nCMHtest(dat_cc,\n        types=\"ALL\",\n        overall=T,\n        cscores=\"midrank\", # <2>\n        strata=\"gender\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , gender = Female\n\n         Improvement\nTreatment None Some Marked\n  Active     6    5     16\n  Placebo   19    7      6\n\n, , gender = Male\n\n         Improvement\nTreatment None Some Marked\n  Active     7    2      5\n  Placebo   10    0      1\n\n$`gender:Female`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum gender:Female \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 11.105  2 0.00387828\nrmeans  Row mean scores differ 10.935  1 0.00094361\ncmeans  Col mean scores differ 11.105  2 0.00387828\ncor        Nonzero correlation 10.935  1 0.00094361\n\n\n$`gender:Male`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum gender:Male \n\n                 AltHypothesis  Chisq Df     Prob\ngeneral    General association 4.7105  2 0.094871\nrmeans  Row mean scores differ 3.7128  1 0.053997\ncmeans  Col mean scores differ 4.7105  2 0.094871\ncor        Nonzero correlation 3.7128  1 0.053997\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 14.632  2 0.00066473\nrmeans  Row mean scores differ 14.632  1 0.00013068\ncmeans  Col mean scores differ 14.632  2 0.00066473\ncor        Nonzero correlation 14.632  1 0.00013068\n\n\n$`gender:Female`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum gender:Female \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 11.105  2 0.00387828\nrmeans  Row mean scores differ 10.879  1 0.00097249\ncmeans  Col mean scores differ 11.105  2 0.00387828\ncor        Nonzero correlation 10.879  1 0.00097249\n\n\n$`gender:Male`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum gender:Male \n\n                 AltHypothesis  Chisq Df     Prob\ngeneral    General association 4.7105  2 0.094871\nrmeans  Row mean scores differ 4.1469  1 0.041712\ncmeans  Col mean scores differ 4.7105  2 0.094871\ncor        Nonzero correlation 4.1469  1 0.041712\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 14.632  2 0.00066473\nrmeans  Row mean scores differ 15.004  1 0.00010728\ncmeans  Col mean scores differ 14.632  2 0.00066473\ncor        Nonzero correlation 15.004  1 0.00010728\n```\n\n\n:::\n:::\n\n\n1. table scores\n2. standardized midrank scores\n\n### Answer\n\n$Q_{SMH} = 14.6$, p<0.001. There is sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group.\n\nWhen using the modridit scores, $Q_{SMH}=15.00, p<0.001$. Same conclusion with a slight deviation between statistics.\n\n:::\n\n## Exercise \n\nThe following data is obtained from the 2003 Programme for International Student Assessment (PISA) study. \n\n- Use the appropriate analysis to determine whether the attitude toward school is different between students in the US and Korea after controlling for gender.\n- Calculate the relevant Somers’ D values for each gender.\n\n:::{.panel-tabset}\n\n### Contingency Table\n![](img/pisa_C4.png)\n\n### SAS Data\n\n```{.r}\ndata school;\ninput gender $ location $ response $ count @@;\ndatalines;\nfemale US sd 1253 female US d 1227 female US a 125 female US sa 38\nfemale korea sd 578 female korea d 1415 female korea a 199 female korea sa 26\nmale US sd 922 male US d 1369 male US a 249 male US sa 102\nmale korea sd 897 male korea d 1942 male korea a 281 male korea sa 58\n;\n```\n\n:::\n\n## Exercise \n\nThe following data is obtained from the 2003 Programme for International Student Assessment (PISA) study. \n\n- Use the appropriate analysis to determine whether the attitude toward school is different between students in the US and Korea after controlling for gender.\n- Calculate the relevant Somers’ D values for each gender.\n\n:::{.panel-tabset}\n\n### SAS Code\n\n```{.r}\nproc freq data=school order=data;\nweight count;\ntables gender*location*response/all nocol nopct measures cl;\ntables gender*location*response/all nocol nopct measures scores=modridit cl;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Rating=c(\"StD\",\"D\",\"A\",\"StA\"),\n            gender=c(\"Female\",\"Male\"), \n            country = c(\"US\",\"Korea\")) |> \nmutate(count = c(1253,1227,125,38,922,1369,249,102,578,1415,199,26,897,1942,281,58))\n\nxtabs(count ~  country +Rating + gender  ,data=dat) -> dat_cc\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , gender = Female\n\n       Rating\ncountry  StD    D    A  StA\n  US    1253 1227  125   38\n  Korea  578 1415  199   26\n\n, , gender = Male\n\n       Rating\ncountry  StD    D    A  StA\n  US     922 1369  249  102\n  Korea  897 1942  281   58\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        types=\"ALL\",\n        cscores = 1:ncol(dat_cc), \n        overall=T, strata=\"gender\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`gender:Female`\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tin stratum gender:Female \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 246.04  3 4.6999e-53\nrmeans  Row mean scores differ 182.24  1 1.5754e-41\ncmeans  Col mean scores differ 246.04  3 4.6999e-53\ncor        Nonzero correlation 182.24  1 1.5754e-41\n\n\n$`gender:Male`\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tin stratum gender:Male \n\n                 AltHypothesis   Chisq Df       Prob\ngeneral    General association 64.7130  3 5.7775e-14\nrmeans  Row mean scores differ  1.2096  1 2.7140e-01\ncmeans  Col mean scores differ 64.7130  3 5.7775e-14\ncor        Nonzero correlation  1.2096  1 2.7140e-01\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 246.36  3 4.0051e-53\nrmeans  Row mean scores differ 91.317  1  1.224e-21\ncmeans  Col mean scores differ 246.36  3 4.0051e-53\ncor        Nonzero correlation 91.317  1  1.224e-21\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        types=\"ALL\",\n        overall=T,\n        cscores=\"midrank\",\n        strata=\"gender\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`gender:Female`\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tin stratum gender:Female \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 246.04  3 4.6999e-53\nrmeans  Row mean scores differ 223.84  1 1.3178e-50\ncmeans  Col mean scores differ 246.04  3 4.6999e-53\ncor        Nonzero correlation 223.84  1 1.3178e-50\n\n\n$`gender:Male`\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tin stratum gender:Male \n\n                 AltHypothesis   Chisq Df       Prob\ngeneral    General association 64.7130  3 5.7775e-14\nrmeans  Row mean scores differ  8.4411  1 3.6683e-03\ncmeans  Col mean scores differ 64.7130  3 5.7775e-14\ncor        Nonzero correlation  8.4411  1 3.6683e-03\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for country by Rating \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 246.36  3 4.0051e-53\nrmeans  Row mean scores differ 149.89  1 1.8367e-34\ncmeans  Col mean scores differ 246.36  3 4.0051e-53\ncor        Nonzero correlation 149.89  1 1.8367e-34\n```\n\n\n:::\n:::\n\n\n### Answer\n\nUsing MODRIDIT scores, we get $Q_{SMH} = 149.88, p<0.001$. Using TABLE scores, we get $Q_{SMH} = 91.3, p<0.001$. There is sufficient evidence that  there is a difference in the attitude toward school between the students from US and Korea.\n\n- I would use the modridit scores because the spacing between ratings is non-uniform.\n- You can use multiple scores and see whether the resulting inference is the same.\n\n- The Somers' D (C|R) for females is 0.22 (0.19,0.25)\n- The Somer's D (C|R) for males is 0.04 (0.01,0.07)\n\n:::\n\n# $s \\times 2$ table\n\n## $s \\times 2$ table\n\n- Used when there are multiple groups defined by an ordinal variable with a dichotomous outcome. \n- Example: Degree of gambling experience, degree of smoking experience, Educational Attainment\n\n## $s \\times 2$ table\n\n::: columns\n::: {.column style=\"width:40%; font-size: 75%\"}\nAssume $X$ is an ordinal variable. \n\n\nTo account for ordinality, we assign a set of scores $\\mathbf{c}$ reflecting the relationship between response levels.\n\n$$\n\\mathbf{c} = \\{c_1, c_2, c_3,... c_s\\} : c_1 < c_2 < ...< c_s\n$$\n\nIn $2 \\times r$ tables, $\\mathbf{a} = (a_1,a_2)$ is effectively (0,1)\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/sx2_C4.png)\n:::\n:::\n\n## $s \\times 2$ table\n\nThe expected frequency can be expressed as \n\n$$\n\\bar{f} = \\sum_{i=1}^s\\sum_{j=1}^2 \\frac{c_ia_jn_{ij}}{n}\n$$\n\n\n## $s \\times 2$ table\n\nThe null hypothesis $H_0$: There is no association between the two variables. To test this hypothesis, we can use a randomization statistic $Q_{CS}$ such that\n\n$$\nQ_{CS} = \\frac{(\\bar{f}-\\mu_c\\mu_a)^2}{v_cv_a/(n-1)} = (n-1)r_{ac}^2\n$$\n\n::: callout-note\n- $\\mu_c$ is the expected value of the row scores\n- $\\mu_a$ is the expected value of the column scores.\n- $v_c$ is the variance of the row scores\n- $v_a$ is variance of the column scores\n:::\n\n::: callout-note\n$Q_{CS}$ is also referred to the correlation statistic. $Q_{CS}$ follows a chi-square distribution with one degree of freedom.\n:::\n\n::: callout-note\n$Q_{CS}$ is related to the Pearson correlation coefficient $r_{ac}$\n:::\n\n\n## Cochran-Armitage test\n\nA similar statistic to the correlation statistic is the $z^2$ statistic used in the Cochran-Armitage test.\n\n- The Cochran-Armitage trend test tests for trends in binomial proportions across levels of an ordinal covariate.\n\n$$\nz^2 = Q_{CS} \\left[\\frac{n}{n-1}\\right]\n$$\n\n## $s \\times 2$ analysis: SAS\n\n- The correlation statistic can be found in the SAS Output as the Mantel-Haenszel chi-square statistic from the `chisq` option.\n- SAS can also perform the Cochran-Armitage trend test by including the `trend` option in the `tables` statement.\n- The Pearson correlation coefficient and the Somers’ D(C|R) are of particular interest in the `measures` output since both metrics account for ordinality.\n\n```{.r}\nproc freq;\nweight count;\ntables a*b/trend chisq measures;\nrun;\n```\n\n## Example\n\nA random sample of 200 married men, all retired, were classified according to education and number of children. The data is shown in the table.\n\n- Is there sufficient evidence of association between the father’s educational attainment and the number of children?\n- Using the Cochran-Armitage trend test to determine if there is an increasing trend in number of children with increasing educational attainment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(education=c(\"secondary\",\"college\",\"graduate\"), Kids = c(\"At most 3\",\"More than 3\")) |> \nmutate(count=c(51,61,29,32,17,10))\n\nxtabs(count ~  education+Kids  ,data=dat) -> dat_cc\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Kids\neducation   At most 3 More than 3\n  secondary        51          32\n  college          61          17\n  graduate         29          10\n```\n\n\n:::\n:::\n\n\n\n## Example\n\nA random sample of 200 married men, all retired, were classified according to education and number of children. The data is shown in the table.\n\n- Is there sufficient evidence of association between the father’s educational attainment and the number of children?\n- Using the Cochran-Armitage trend test to determine if there is an increasing trend in number of children with increasing educational attainment.\n\n:::{.panel-tabset}\n\n### SAS Code\n\n```{.r}\ndata educ;\ninput education $ kids3 $ count @@;\ndatalines;\nsecondary leq 51 secondary g 32\ncollege leq 61 college g 17\ngraduate leq 29 graduate g 10\n;\nrun;\n\nproc freq data= educ order=data;\nweight count;\ntables education*kids3/chisq measures trend cl; # <1>\nrun;\n```\n\n1. `chisq` gives $Q_{CS}$, `measure`s provides Somers and pearson, `trend` gives cochran-armitage, `cl` calculates confidence intervals.\n\n### Answer\n\n$Q_{CS} = 3.47, p =0.06$. There is weak evidence of association between the father's educational attainment and number of offspring.\n\nThe one-sided Cochran-Armitage test yielded a p-value = 0.03, which is sufficient evidence to support a decreasing trend in number of children with increasing educational attainment.\n\n:::\n\n# Sets of $s \\times 2$ tables\n\n## Sets of $s \\times 2$ tables\n\n- Just like 2xr tables, there is also a statistic for the association of two ordinal variables for a combined set of strata called the extended Mantel-Haenszel correlation statistic ($Q_{CSMH}$).\n  - $Q_{CSMH}$ approximately follows a chi-square distribution with df=1 when the combined strata sample sizes is greater than or equal to 40 (sufficiently large).\n\n## Example\n\nThe table contains two contingency tables of risk perception (minimal, moderate, and substantial) and adolescent tobacco usage by father’s usage. \n\n- Comment on whether there is an association between risk perception and adolescent usage when the father does not use tobacco.\n- Is there a discernible trend in the proportions of adolescent usage over the levels of risk perception after controlling for father’s tobacco usage?\n\n![](img/tobaccoset_C4.png)\n\n## Example\n\nThe table contains two contingency tables of risk perception (minimal, moderate, and substantial) and adolescent tobacco usage by father’s usage. \n\n- Comment on whether there is an association between risk perception and adolescent usage when the father does not use tobacco.\n- Is there a discernible trend in the proportions of adolescent usage over the levels of risk perception after controlling for father’s tobacco usage?\n\n:::{.panel-tabset}\n### Contingency table\n![](img/tobaccoset_C4.png)\n\n### SAS Code\n\n```{.r}\ndata tobacco;\nlength risk $11. ;\ninput f_usage $ risk $ usage $ count @@;\ndatalines;\nno minimal no 59 no minimal yes 25\nno moderate no 169 no moderate yes 29\nno substantial no 196 no substantial yes 9\nyes minimal no 11 yes minimal yes 8\nyes moderate no 33 yes moderate yes 11\nyes substantial no 22 yes substantial yes 2\n;\nproc freq;\nweight count;\ntables f_usage*risk*usage /cmh chisq measures trend;\ntables f_usage*risk*usage /cmh scores=modridit;\nrun;\n```\n\n### Answer\n\nWhen the father is not a tobacco user, $Q_{CS}=34.3, p<0.001$, which means there is sufficient evidence of an association between risk perception and participant tobacco use.\n\n$Q_{CSMH}=39.3$ using modified ridit scores ($Q_{CSMH}=40.7$ for table scores), resulting to a p-value p<0.001. There is sufficient evidence of an association between risk perception and participant tobacco use.\n\n:::\n\n# $s \\times 2$: Exact Analysis\n\n## Exact Analysis\n\n- For small sample sizes, $Q_{CS}$ does not satisfy the asymptotic requirements.\n- We use exact tests to calculate the correct Mantel-Haenszel statistics.\n- We manually calculate the Wilcoxon rank and logrank scores for each row.\n  - Wilcoxon vs logrank: Logrank is better when there are more counts in the lower end of the row ordinal variable.\n  \n## Exact Analysis: SAS\n\n- The `exact` statement is used to perform an exact test on the correlation statistic. \n  - `exact mhchi` would perform the statement on the Mantel-Haenszel statistic.\n  - `scorout` outputs the scores used in the exact analysis\n\n```{.r}\nproc freq;\ntables a*b /scorout;\nexact mhchi;\nrun;\n```\n\n## Example\n\nThe table shows data from a study of mice who were exposed to a bacterial challenge and treated with the drugs carbenicillin or cefotaxmine (Bowdre, et al. 1983). Surviving mice were assessed at intervals of 6 to 24 hours. Is there evidence that there is a difference in performance between the two drugs?\n\n:::{.panel-tabset}\n\n### Contingency Table\n![](img/mice_C4.png)\n\n### SAS Data\n\n```{.r}\ndata mice;\ninput LogRank Treatment $ count @@;\ndatalines;\n0.909 Ca 1 0.909 Ce 1\n0.709 Ca 3 0.709 Ce 1\n0.334 Ca 5 0.334 Ce 1\n0.234 Ca 1 0.234 Ce 0\n-0.099 Ca 1 -0.099 Ce 2\n-0.433 Ca 0 -0.433 Ce 2\n-0.933 Ca 1 -0.933 Ce 1\n-1.433 Ca 0 -1.433 Ce 1\n-2.433 Ca 0 -2.433 Ce 1\n;\n```\n\n:::\n\n\n## Example\n\nThe table shows data from a study of mice who were exposed to a bacterial challenge and treated with the drugs carbenicillin or cefotaxmine (Bowdre, et al. 1983). Surviving mice were assessed at intervals of 6 to 24 hours. Is there evidence that there is a difference in performance between the two drugs?\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata mice;\ninput LogRank Treatment $ count @@;\ndatalines;\n0.909 Ca 1 0.909 Ce 1\n0.709 Ca 3 0.709 Ce 1\n0.334 Ca 5 0.334 Ce 1\n0.234 Ca 1 0.234 Ce 0\n-0.099 Ca 1 -0.099 Ce 2\n-0.433 Ca 0 -0.433 Ce 2\n-0.933 Ca 1 -0.933 Ce 1\n-1.433 Ca 0 -1.433 Ce 1\n-2.433 Ca 0 -2.433 Ce 1\n;\n\nproc freq order=data;\nweight count;\ntables LogRank*Treatment / norow nocol nopct scorout chisq; # <1>\ntables LogRank*Treatment / noprint scores=rank scorout chisq; # <2>\nexact mhchi;\nrun;\n```\n\n1. Using Logranks\n2. using ranks. Note that logranks preserves the order of the original data set.\n\n\n### Answer\n\nThe exact logrank analysis showed that $Q_{CS}=4.06, p=0.04$, which means we have sufficient evidence of an association/difference between the treatment and specimen survival.\n\nHowever, the exact *rank* analysis showed that $Q_{CS}=3.51, p=0.06$, which means we have weak evidence of an association/difference between the treatment and specimen survival.\n\nI would favor the logrank analysis better because it encapsulates the data better and accounts for the higher representation of the lower end of the ordinal variable.\n:::",
    "supporting": [
      "Chapter4_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}