project:
  type: website

website:
  title: "EAB770: Applied Statistical Methods for Categorical Data"
  navbar: 
    logo: "UNLV-186.jpg"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: Chapter1.qmd
        text: Chapter 1
      - href: Chapter2.qmd
        text: "Chapter 2: 2x2 tables"
      - href: Chapter3.qmd
        text: "Chapter 3: Sets of 2x2 tables"
      - href: Chapter4.qmd
        text: "Chapter 4: 2xr and sx2 tables"
      - href: Chapter5.qmd
        text: "Chapter 5: sxr tables"
      - href: Chapter6.qmd
        text: "Chapter 6: Sets of sxr tables"
      - href: Chapter7.qmd
        text: "Chapter 8: Logistic Regression"

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    



