{
  "hash": "0978d74db772a985a154a44e58be88b1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 3\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 3- [Back to home](https://miguelfudolig.github.io/EAB770-Slides-Website/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n    echo: true\n  pdf: \n    number-sections: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n# Chapter 3: Sets of $2\\times2$ tables\n\n## Outline\n\n- Cochran-Mantel-Haenszel test\n- Measures of Association\n  - Common Odds ratio\n  - Breslow-Day test\n  - Zelen's Test\n\n# Cochran-Mantel-Haenszel Statistic \n\n## Sets of $2 \\times 2$ tables\n\n::: columns\n::: {.column style=\"width:40%; font-size: 85%\"}\n- Consider a multi-location RCT\n  - Different locations will have different contingency tables\n  - We want to consolidate **all** data and account for the location effect in testing for the association between the treatment and outcome.\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/resp_C3.png)\n\n:::\n:::\n\n## Stratified Analysis\n\nStratified analysis examines the association between two variables while adjusting for the effect of other covariates.\n\n::: callout-note\nThe variable that define the strata may be an explanatory variable, location, or classification variable. Each contingency table corresponds to one level of the explanatory variables (stratum). The contingency tables at each level of the stratification variable are called **partial tables**.\n:::\n\n## Conditional Associations\n\nAssociations in partial tables are called conditional associations because it is conditional on a particular level of the stratification variable.\n\n::: callout-note\nWe can use the methods from the previous chapters to test for conditional associations at each level of the stratification variable. Odds ratios can be calculated for each partial table.\n:::\n\n## Marginal Associations\n\nMarginal associations are associations in marginal tables.\n\n::: callout-note\n### Marginal Table\nA marginal table contains the summed frequencies of the partial tables across the stratification variable. Suppose the frequency in the cell $(i,j)$ in the $k^{th}$ partial table is $n_{ijk}$. The marginal table will have the following value for the cell $(i,j)$:\n\n$$\nn_{ij} = \\sum_{k=1}^K n_{ijk}\n$$\n:::\n\n::: callout-tip\nConditional associations examine two-way associations at each strata, but marginal associations examine the overall two-way associations by averaging over all strata. Interpreting marginal association in the presence of differing conditional associations is **NOT** recommended.\n:::\n\n## Independence\n\n::: callout-note\n### Marginal Independence\n\nMarginal independence implies that the there is no association in the marginal table. When there is marginal independence, the marginal odds ratio ($OR_{XY}$ or $\\theta_{XY}$) is equal to 1. In general, for any $s \\times r$ table, marginal independence implies that all odds ratios that can be formed using any two levels of the variables will be equal to 1.\n:::\n\n::: callout-note\n### Conditional Independence\n\nConditional independence implies that there is no association between the variables X and Y in any of the partial tables that are conditional on the stratification variable levels. Conditional independence implies that the conditional odds ratios ($OR_{XY|Z}$ or $\\theta_{XY|Z}$) in all the partial tables are equal to 1.\n\nConditional dependence implies that there is an association in at least one of the partial tables. Conditional independence does not imply marginal independnece and vice versa.\n:::\n\n:::callout-tip\nIn the symbolic convention, $X$ and $Y$ are the variables being tested for association, $Z$ is the stratification variable/covariate.\n:::\n\n\n## Homogeneous Association\n\nWhen the conditional associations between $X$ and $Y$ are the same across all partial tables in each strata of $Z$, we have **homogeneous association** between X and Y. For $K$ strata,\n\n$$\n\\theta_{XY|Z_1} = \\theta_{XY|Z_2} = ...= \\theta_{XY|Z_K}\n$$\n\nBy definition, the following equalities should also hold:\n\n$$\n\\theta_{XZ|Y_1} = \\theta_{XZ|Y_2} = ...= \\theta_{XZ|Y_K}\n$$\n\n$$\n\\theta_{YZ|X_1} = \\theta_{YZ|X_2} = ...= \\theta_{YZ|X_K}\n$$\n\n## Notes\n\n::: callout-tip\n### Simpson's Paradox\n\nSimpson's paradox corresponds to the scenario where the marginal association is completely different from the conditional association.\n:::\n\n\nAlthough conditional independence implies homogeneous association (because $\\theta_{XY|Z} = 1$ for all strata), homogeneous association does not necessarily imply conditional independence. For homogeneous association to hold, the odds ratios have to be equal but are not required to be equal to 1.\n\n\n# Inferential Statistics\n\n## Mantel-Haenszel Test\n\nRecall the Mantel-Haenszel Chi-Square statistic\n\n$$\nQ = (n_{11}-m_{11})^2/v_{11}\n$$\nwhere $m_{11}$ is the expected value of the $n_{11}$ and $v_{11}$ is the variance of $n_{11}$ based on the hypergeometric distribution assumption.\n\n::: callout-note\nIf there are $q$ $2\\times 2$ tables, each table will have a value for $Q$.\n:::\n\n## Cochran-Mantel-Haenszel Test\n\nThe Cochran-Mantel-Haenszel test assesses the presence of conditional association of X and Y after adjusting for the strata Z. If $n_{j11}$ is the $n_{11}$ value of the $j^{th}$ contingency table, the Cochran-Mantel-Haenszel statistic, $Q_{MH}$ can be written as:\n\n$$\nQ_{MH} =    \\frac{\\left[\\sum_{j=1}^q n_{j11} - \\sum_{j=1}^q m_{j11}\\right]^2}{\\sum_{j=1}^q v_{j11}}\n$$\n\n::: callout-note\n$Q_{MH}$ is often called an **average partial association statistic**.\n:::\n\n## Cochran-Mantel-Haenszel Test: Hypotheses\n\nThe Cochran-Mantel-Haenszel test tests the following hypotheses:\n\n- $H_0$: Given the stratification variable, there is conditional independence such that all conditional odds ratios are equal to 1.\n- $H_a$: At least one conditional odds ratio is not equal to 1.\n\n\n\n## Mantel-Haenszel Statistic\n\nThe statistic $Q_{MH}$ relies on detecting patterns of the differences of proportions in each table. \n\n::: callout-note\nThe statistic $Q_{MH}$ approximately follows a chi-square distribution with one degree of freedom if the **combined** random sample sizes are large. This means that individual cell counts and isolated table sample sizes may be small.\n\nThe **Mantel-Fleiss criterion** can be used to check if the chi-square assumption holds. The Mantel-Fleiss criterion should be greater than 5.\n:::\n\n::: callout-warning\nThere is no function in `R` that can calculate the Mantel-Fleiss criterion, but `SAS` will provide the estimate of the Mantel-Fleiss criterion. The Mantel-Fliess criterion can be calculated using the following formula for a total of $K$ strata:\n\n$$\nMF= min\\left\\{\\sum_{h=1}^K [m_{h11} - max(0,n_{h1+}-n_{h+2})], \\sum_{h=1}^K [min(n_{h+1},n_{h1+}) - m_{h11}]\\right\\}\n$$\n:::\n\n## Cochran-Mantel-Haenszel Test: `SAS`\n\n- The `cmh` option in the `tables` statement produces the Mantel-Haenszel statistic values. There will be three Mantel-Haenszel values included in the output.\n\n- Nonzero Correlation\n- Row Mean Scores Differ\n- General Association\n\n::: callout-note\nFor $2 \\times 2$ tables, the scores and degrees of freedom do not differ for these three MH-statistics. These measures will be distinguished for larger contingency tables.\n:::\n\n::: callout-note\nThe `mf` option in the `tables` statement produces the Mantel-Fleiss criterion. Recall that the Mantel-Fleiss criterion (MF) should be greater than 5 for the chi-square distributional assumption to be valid.\n:::\n\n## Cochran-Mantel-Haenszel Test: `R`\n\nJust like the previous chapter, we can use the `mantelhaen.test()` function in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- xtabs(count~row_var+column_var+strata_var, data=dat)\n# OR\n\ncontingency_table <- xtabs(~ row_var+column_var+strata_var, data=dat) # for non-aggregated data\n\n\nmantelhaen.test(contingency_table, correct = FALSE) #no correction gives the same result as SAS and CMHtest\n```\n:::\n\n\nTo explore conditional associations, we can use the `CMHtest()` function in the `vcdExtra` package in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(contingency_table,\n        strata=strata_var,\n        overall=T)\n```\n:::\n\n\n## Example\n\nThe table shows the results of a study about how general daily stress affects one’s opinion on a proposed new health policy. Participants were sampled from urban and rural areas.\n\n::: panel-tabset\n\n### Question\n\n- Is there enough evidence that there is an association between the opinion and stress levels of residents after controlling for residential area? Use 𝛼=0.05 as the significance level.\n\n\n![](img/health_C3.png)\n\n### SAS Code\n\n```{.r code-line-numbers=\"11,12\"}\ndata stress;\ninput region $ stress $ outcome $ count @@;\ndatalines;\nurban low f 48 urban low u 12\nurban high f 96 urban high u 94\nrural low f 55 rural low u 135\nrural high f 7 rural high u 53\n;\nproc freq order=data data=stress;\nweight count;\ntables region*stress*outcome / all chisq cmh (mf) nocol nopct; # <1>\nrun;\n```\n\n1. `CMH` includes the Mantel-Haenszel statistics. `MF` gives the Mantel-Fleiss condition;\n\n### R Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcdExtra)\ndat  <- expand.grid(Outcome = c(\"Favorable\",\"Unfavorable\"),\n                    Residence=c(\"Urban\",\"Rural\"),\n                    Stress = c(\"Low\",\"High\")\n                  ) \ndat$count <- c(48,12,55,135,96,94,7,53)\n\ndat_cc <- xtabs(count ~  Stress + Outcome + Residence  ,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Residence = Urban\n\n      Outcome\nStress Favorable Unfavorable\n  Low         48          12\n  High        96          94\n\n, , Residence = Rural\n\n      Outcome\nStress Favorable Unfavorable\n  Low         55         135\n  High         7          53\n```\n\n\n:::\n\n```{.r .cell-code}\nmantelhaen.test(dat_cc,correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMantel-Haenszel chi-squared test without continuity correction\n\ndata:  dat_cc\nMantel-Haenszel X-squared = 23.05, df = 1, p-value = 1.578e-06\nalternative hypothesis: true common odds ratio is not equal to 1\n95 percent confidence interval:\n 2.066744 6.069367\nsample estimates:\ncommon odds ratio \n         3.541726 \n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        strata=\"Residence\",\n        overall=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Residence:Urban`\nCochran-Mantel-Haenszel Statistics for Stress by Outcome \n\tin stratum Residence:Urban \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 16.155  1 5.8367e-05\nrmeans  Row mean scores differ 16.155  1 5.8367e-05\ncmeans  Col mean scores differ 16.155  1 5.8367e-05\ngeneral    General association 16.155  1 5.8367e-05\n\n\n$`Residence:Rural`\nCochran-Mantel-Haenszel Statistics for Stress by Outcome \n\tin stratum Residence:Rural \n\n                 AltHypothesis  Chisq Df      Prob\ncor        Nonzero correlation 7.2724  1 0.0070022\nrmeans  Row mean scores differ 7.2724  1 0.0070022\ncmeans  Col mean scores differ 7.2724  1 0.0070022\ngeneral    General association 7.2724  1 0.0070022\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for Stress by Outcome \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis Chisq Df       Prob\ncor        Nonzero correlation 23.05  1 1.5783e-06\nrmeans  Row mean scores differ 23.05  1 1.5783e-06\ncmeans  Col mean scores differ 23.05  1 1.5783e-06\ngeneral    General association 23.05  1 1.5783e-06\n```\n\n\n:::\n:::\n\n\nCalculating the Mantel-Fleiss manually:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmantel_fleiss <- function(cc,k){\n  sum_expected =0\n  sum_max = 0\n  sum_min =0\n  for (h in 1:k){\n    nh1p = rowSums(cc[,,h])[1]\n    nhp2 = colSums(cc[,,h])[2]\n    nhp1 = colSums(cc[,,h])[1]\n    m11 = nh1p*nhp1/sum(cc[,,h])\n    sum_expected = sum_expected + m11\n    sum_max = sum_max + max(0,nh1p-nhp2)\n    sum_min = sum_min + min(nhp1,nh1p)\n    \n  }\n  min(sum_expected-sum_max,sum_min-sum_expected)\n}\n\nmantel_fleiss(dat_cc,k=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40.32\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n$Q_{MH}= 23.05$, $df=1$, $p < 0.0001$. There is strong evidence that there is some conditional association between stress level and opinion. Examining each residence level, we see that there is strong evidence of conditional association between stress level and opinion at both rural and urban residences.\n:::\n\n\n\n## Example\n\n::: columns\n::: {.column style=\"width:40%; font-size: 85%\"}\nThe table shows the results of an RCT for a test treatment designed for respiratory infections. Is there a significant association between the treatment and the outcome after controlling for the center?\n\n- Is the Mantel-Fleiss criterion satisfied?\n\n\n\n:::\n\n::: {.column style=\"width:60%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Center = 1\n\n         Improvement\nTreatment Yes No\n  Test     29 16\n  Placebo  14 31\n\n, , Center = 2\n\n         Improvement\nTreatment Yes No\n  Test     37  8\n  Placebo  24 21\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n\n\n\n## Exercise\n\n\nThe table shows the results of an RCT for a test treatment designed for respiratory infections. Is there a significant association between the treatment and the outcome after controlling for the center?\n\n::: {.panel-tabset}\n### Data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Center = 1\n\n         Improvement\nTreatment Yes No\n  Test     29 16\n  Placebo  14 31\n\n, , Center = 2\n\n         Improvement\nTreatment Yes No\n  Test     37  8\n  Placebo  24 21\n```\n\n\n:::\n:::\n\n\n### SAS Code\n\n```{.r}\n\ndata resp;\nlength treatment $7.;\ninput treatment $ improvement $ center $ count;\ndatalines;\nTest Yes 1 29\nPlacebo Yes 1 14\nTest No 1 16\nPlacebo No 1 31\nTest Yes 2 37\nPlacebo Yes 2 24\nTest No 2 8\nPlacebo No 2 21\n;\n\n\nproc freq data=resp order=data;\nweight count;\ntables center*treatment*improvement / cmh (MF) nocol norow nopct;\nrun;\n\n```\n\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat  <- expand.grid(Improvement = c(\"Yes\",\"No\"),\n                    Center=c(1,2),\n                    Treatment = c(\"Test\",\"Placebo\")\n                  )  \ndat$count = c(29,16,37,8,14,31,24,21)\n\ndat_cc <- xtabs(count ~  Treatment+Improvement + Center, data=dat) \ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Center = 1\n\n         Improvement\nTreatment Yes No\n  Test     29 16\n  Placebo  14 31\n\n, , Center = 2\n\n         Improvement\nTreatment Yes No\n  Test     37  8\n  Placebo  24 21\n```\n\n\n:::\n\n```{.r .cell-code}\nmantelhaen.test(dat_cc,\n                correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMantel-Haenszel chi-squared test without continuity correction\n\ndata:  dat_cc\nMantel-Haenszel X-squared = 18.411, df = 1, p-value = 1.781e-05\nalternative hypothesis: true common odds ratio is not equal to 1\n95 percent confidence interval:\n 2.105716 7.708353\nsample estimates:\ncommon odds ratio \n         4.028846 \n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        strata=\"Center\",\n        types=\"ALL\",\n        overall=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Center:1`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum Center:1 \n\n                 AltHypothesis  Chisq Df      Prob\ngeneral    General association 9.9085  1 0.0016452\nrmeans  Row mean scores differ 9.9085  1 0.0016452\ncmeans  Col mean scores differ 9.9085  1 0.0016452\ncor        Nonzero correlation 9.9085  1 0.0016452\n\n\n$`Center:2`\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tin stratum Center:2 \n\n                 AltHypothesis  Chisq Df      Prob\ngeneral    General association 8.5025  1 0.0035465\nrmeans  Row mean scores differ 8.5025  1 0.0035465\ncmeans  Col mean scores differ 8.5025  1 0.0035465\ncor        Nonzero correlation 8.5025  1 0.0035465\n\n\n$ALL\nCochran-Mantel-Haenszel Statistics for Treatment by Improvement \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df       Prob\ngeneral    General association 18.411  1 1.7807e-05\nrmeans  Row mean scores differ 18.411  1 1.7807e-05\ncmeans  Col mean scores differ 18.411  1 1.7807e-05\ncor        Nonzero correlation 18.411  1 1.7807e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nmantel_fleiss(dat_cc,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n- The Mantel-Fleiss criterion was determined to be 36, which means the chi-square assumption holds.\n\n- $Q_{MH}=18.4$, $p < 0.0001$, there is strong evidence of a conditional association between the treatment and improvement.\n\n:::\n\n## Homogeneity of Odds Ratios\n\nThe Breslow-Day test or the Zelen's test can be used to test if the homogeneous association is satisfied.\n\n::: {.panel-tabset}\n### Breslow-Day test\n\nThe null hypothesis associated with the Breslow-Day test is that there is homogeneous association between $X$ and $Y$. \n\n::: callout-note\nWhen the null hypothesis is rejected, there is an implied three-way association between the variables. This implies that conditional associations should be investigated at each strata.\n:::\n\n$$\nQ_{BD}  = \\sum_{h=1}^{q} \\sum_{i=1}^{2} \\sum_{j=1}^{2} \\frac{(n_{hij}-m_{hij})^2}{m_{hij}}\n$$\n\nwhich approximately follows a chi-square distribution with $(n-1)$ degrees of freedom.\n\n### Zelen's Test\n\nZelen's test is similar to the Breslow-Day test, but uses exact methods. \n\n::: callout-note\nSimilar to the Fisher's Exact Test, the Zelen's test entails calculating the probability of all possible sets of tables. The resulting p-value is the sum of all table probabilities that are lower than the probability of the observed table. This test is not available in `R`.\n:::\n\n\n# Measures of Association\n\n## Common Odds Ratio\n\nWhen there is homogeneous association, we can compute a **common odds ratio** to summarize the conditional associations that exist in the partial tables.\n\n- The Mantel-Haenszel estimator $\\hat{\\psi}_{MH}$ can approximate the common odds ratio such that\n\n$$\n\\hat{\\psi}_{MH} = \\frac{\\sum_{j=1}^q n_{j11}n_{j22}/n_j}{\\sum_{j=1}^q n_{j12}n_{j21}/n_j}\n$$\n\n::: callout-note\nWe can calculate confidence intervals (asymptotic and exact) for common odds ratios!\n:::\n\n## Common Odds Ratio: Confidence Intervals\n\nThere are two confidence intervals for the common odds ratios provided by SAS: The Mantel-Haenszel and Logit confidence limits.\n\n:::{.panel-tabset}\n### Mantel-Haenszel\n\n- based on an estimate of the variance of $\\log \\psi_{MH}$\n- Not sensitive to small sample sizes\n\n### Logit\n\n- based on weighted regression estimates\n- reasonable but requires adequate sample sizes, i.e. $n_{hij} \\geq 5$\n\n\n:::\n\n\n## Common Odds Ratios: SAS\n\n- The common odds ratios are calculated with the `cmh` option\n  - Only includes asymptotic (MH and logit) CI limits.\n  - Including the `measures` options yields plots of common odds ratios and stratum-level odds ratios.\n- The Breslow-Day test is also included in the `cmh` option\n- The `comor` and `eqor` options in the `exact` statement yield the exact common odds ratio and the Zelen's test results, respectively.\n\nSample SAS code:\n\n```{.r code-line-numbers=\"2,3\"}\nproc freq;\ntables a*b*c/cmh measures;\nexact comor eqor;\nrun;\n```\n\n## Common Odds Ratios: `R`\n\nThe `mantelhaen.test()` provides an estimate of the common odds ratio. This function provides the Mantel-Haenszel confidence interval provided in `SAS`.\n\n\n\n## Example\n\n\n\nThe table shows  the data from a study on coronary artery disease. Investigators were interested in whether electrocardiogram (ECG) measurement was associated with disease status. Gender was thought to be associated with disease status, so investigators post-stratified the data into male and female groups. In addition, there was interest in examining the odds ratios.\n\n::: panel-tabset\n\n### Data\n![](img/coronary_C3.png)\n\n\n### SAS Code\n```{.r}\ndata ca;\ninput sex $ ECG $ disease $ count;\ndatalines;\nfemale <0.1 yes 4\nfemale <0.1 no 11\nfemale >=0.1 yes 8\nfemale >=0.1 no 10\nmale <0.1 yes 9\nmale <0.1 no 9\nmale >=0.1 yes 21\nmale >=0.1 no 6\n;\nproc freq data=ca ;\nweight count;\ntables sex*disease / nocol nopct chisq measures; # <1>\ntables sex*ECG*disease / nocol nopct cmh measures; # <2>\nrun;\n```\n\n1. Testing for marginal association between sex and disease status\n2. Using sex as a stratification variable/strata. `measures` includes common odds ratio plots.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat  <- expand.grid(Sex = c(\"Female\",\"Male\"),\n                    ECG=c(\"Less\",\"Greater\"),\n                    Disease = c(\"No\",\"Yes\")\n                  )  \ndat$count = c(11,9,10,6,4,9,8,21)\n\ndat_cc <- xtabs(count ~  Disease+Sex, data=dat) \ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Sex\nDisease Female Male\n    No      21   15\n    Yes     12   30\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc, correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Disease by Sex \n\n                 AltHypothesis  Chisq Df     Prob\ncor        Nonzero correlation 6.9444  1 0.008408\nrmeans  Row mean scores differ 6.9444  1 0.008408\ncmeans  Col mean scores differ 6.9444  1 0.008408\ngeneral    General association 6.9444  1 0.008408\n```\n\n\n:::\n:::\n\n\n\nAccounting for partial tables,\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(count ~  ECG+Disease+Sex, data=dat) \ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Sex = Female\n\n         Disease\nECG       No Yes\n  Less    11   4\n  Greater 10   8\n\n, , Sex = Male\n\n         Disease\nECG       No Yes\n  Less     9   9\n  Greater  6  21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbreslow_day_test(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBreslow-Day Test on Homogeneity of Odds Ratios \n\nData:          dat_cc \nOR variables:  ECG, Disease \nStrata:        Sex \nCommon OR:     2.847 \n\nX-squared = 0.2155, df = 1, p-value = 0.6425\n```\n\n\n:::\n\n```{.r .cell-code}\nmantelhaen.test(dat_cc, correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMantel-Haenszel chi-squared test without continuity correction\n\ndata:  dat_cc\nMantel-Haenszel X-squared = 4.5026, df = 1, p-value = 0.03384\nalternative hypothesis: true common odds ratio is not equal to 1\n95 percent confidence interval:\n 1.076514 7.527901\nsample estimates:\ncommon odds ratio \n         2.846734 \n```\n\n\n:::\n:::\n\n\n\n\n### Answer \n\n- Sex was determined to be marginally associated with disease status ($\\chi^2=6.9, p=0.0084$).\n- Controlling for sex, there is strong evidence that the ECG measurements is conditionally associated with disease status ($\\chi^2=4.5, p=0.03$).\n- The Breslow-Day test yielded a non-significant p-value (p=0.64), hence we can use the common odds ratios\n- The MH odds ratio was estimated to be 2.86 (95% CI: 1.1,7.5). We can interpret this value as: The odds of having the disease is 2.86 times that for patients with a high ECG segment depression compared to those with a low ECG segment depression.\n:::\n\n\n## Exercise \n\n::: columns\n::: {.column style=\"width:50%; font-size: 85%\"}\nTable 3.8 shows the data from research done by a small company in initiating exercise programs (office/home) in their two locations in a nearby suburbs. After a year, participants and non-participants underwent a cardiovascular stress test to assess their fitness, and their result was recorded as good or not good depending on age-adjusted criteria. The exercise counselor was interested in whether type of program was associated with good test results.\n\n- Calculate the common odds ratio $\\psi_{MH}$ and the **exact** 95% confidence intervals.\n- Use Zelen’s test to test if the odds ratio is uniform in both locations.\n\n:::\n\n::: {.column style=\"width:50%\"}\n![](img/cardio_C3.png)\n:::\n:::\n\n## Exercise\n\nTable 3.8 shows the data from research done by a small company in initiating exercise programs (office/home) in their two locations in a nearby suburbs. After a year, participants and non-participants underwent a cardiovascular stress test to assess their fitness, and their result was recorded as good or not good depending on age-adjusted criteria. The exercise counselor was interested in whether type of program was associated with good test results.\n\n- Calculate the common odds ratio $\\psi_{MH}$ and the **exact** 95% confidence intervals.\n- Use Zelen’s test to test if the odds ratio is uniform in both locations\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata exercise;\ninput location $ program $ outcome $ count @@;\ndatalines;\ndowntown office good 12 downtown office not 5\ndowntown home good 3 downtown home not 5\nsatellite office good 6 satellite office not 1\nsatellite home good 1 satellite home not 3\n;\n\nproc freq order=data;\nweight count;\ntables location*program*outcome /cmh(mf); # <1>\nexact comor eqor; # <2>\nrun;\n```\n\n1. `MF` should be enclosed in parentheses\n2. `eqor`: Zelen's test, `comor`: exact confidence interval for the common odds ratio.\n\n### Answer\n\n- Mantel-Fleiss criterion is not satisfied (MF=4.65), so be careful with using the asymptotic chi-square test for $Q_{MH}$.\n  - This motivates using exact methods in calculating effect sizes.\n- Common odds ratio was estimated to be 5.84 (**EXACT** 95% CI: 1.05, 33.3). There is sufficient evidence at the 0.05 significance level that the program type is associated with the quality of cardiovascular test results.\n  - The Zelen's test yielded $p=1$, which means there is no evidence against homogeneity.\n\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}