{
  "hash": "22b493553248fc8dae675e3a23a22ed8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 Problem Set 1 Key\"\nauthor: \"Miguel Fudolig\"\nformat: \n  html: \n    engine: knitr\n    embed-resources: true\n  pdf:\n    number-sections: true\n---\n\n\n# Problem 1 \n\nA batch of 250 pills is tested by randomly sampling 10 pills for quality control. If all 10 pills pass, the batch is approved for distribution. Suppose there are 25 pills that were not acceptable in this batch, what is the probability that the batch passes? Identify the appropriate distribution to calculate these probabilities.\n\n::: callout-note\n### Solution\n\nThe most appropriate distribution to calculate these probabilities is the *hypergeometric distribution*. We are interested in P(X=0) when there are $N=250$ pills, $m=25$ unacceptable pills, and a sample of $k=10$ pills.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 250\nm <- 25\nk <- 10\n\ndhyper(x=0,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3415857\n```\n\n\n:::\n:::\n\n\n:::\n\n# Problem 2\n\nAseffa et al. (1998) examined the prevalence of HIV among women visiting health care clinics in northwest Ethiopia. Along with testing individuals for HIV, additional information was collected on each woman such as condom use.\n\n![](img/PS1_1.png)\n\n## 2a\n\nCalculate the following 95% confidence intervals for the difference in probabilities of being HIV positive based on condom use. (Corrected Wald, Agresti-Caffo, Miettinen-Nurminen).\n\n::: callout-note\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'DescTools' was built under R version 4.6.1\n```\n\n\n:::\n\n```{.r .cell-code}\nBinomDiffCI(x1=135,n1=569,\n            x2=15,n2=24,\n            method=c('waldcc','ac','mn'))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              est     lwr.ci     upr.ci\nwaldcc -0.3877417 -0.6062683 -0.1692150\nac     -0.3877417 -0.5674447 -0.1869673\nmn     -0.3877417 -0.5556362 -0.1863982\n```\n\n\n:::\n:::\n\n:::\n\n## 2b\n\nAt a significance level of 0.05, do we have any evidence of association between condom use and HIV prevalence?\n\n::: callout-note\n### Solution\n\nThere are two possible ways to answer this question: using the confidence intervals in (2a) or using the Mantel-Haenszel test of association.\n\nBecause the confidence intervals in (2a) did not include 0, we have strong evidence of an association between condom use and HIV prevalence.\n\nThe Mantel-Haenszel tests can be performed as shown:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Condom=c(\"Never\",\"Ever\"),\n                   HIV = c(\"+\",\"-\"))\n\ndat$Count <- c(135,15,434,9)\n\ndat_cc <- xtabs(Count~Condom+HIV, data=dat)\n\nlibrary(vcdExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'vcdExtra' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: vcd\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'vcd' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: gnm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'gnm' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 methods overwritten by 'vcdExtra':\n  method      from\n  pairs.table vcd \n  print.Kappa vcd \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'vcdExtra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:vcd':\n\n    pairs_diagonal_mosaic, woolf_test\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Condom by HIV \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 18.291  1 1.8961e-05\nrmeans  Row mean scores differ 18.291  1 1.8961e-05\ncmeans  Col mean scores differ 18.291  1 1.8961e-05\ngeneral    General association 18.291  1 1.8961e-05\n```\n\n\n:::\n:::\n\n\nThe MH test yielded $\\chi^2_1 = 18.3,p<0.0001$. At the 0.05 significance level, we reject the null hypothesis. We have sufficient evidence to support the claim that there is an association between condom use and HIV prevalence.\n:::\n\n## 2c\n\n\nEstimate the odds ratio and its corresponding 95% confidence interval. Interpret the odds ratio in the context of the problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epitools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'epitools' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'epitools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:vcdExtra':\n\n    expand.table\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:vcd':\n\n    oddsratio\n```\n\n\n:::\n\n```{.r .cell-code}\noddsratio(dat_cc,rev=\"columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n       HIV\nCondom    -   + Total\n  Never 434 135   569\n  Ever    9  15    24\n  Total 443 150   593\n\n$measure\n       odds ratio with 95% C.I.\nCondom  estimate    lower    upper\n  Never 1.000000       NA       NA\n  Ever  5.302773 2.288386 13.02109\n\n$p.value\n       two-sided\nCondom    midp.exact fisher.exact   chi.square\n  Never           NA           NA           NA\n  Ever  0.0001059792 9.067182e-05 1.865601e-05\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"median-unbiased estimate & mid-p exact CI\"\n```\n\n\n:::\n:::\n\n\nThose who reported condom use were estimated to have odds of having HIV that is 5.30 (95% CI: 2.29-13.02) times that of those who did not report condom use.\n\n# Problem 3\n\n\nCalculate the sensitivity and the specificity of the test and their 95% confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Test = c(\"Positive\",\"Negative\"),\n                   Disorder = c(\"Positive\",\"Negative\"))\n\ndat$Count <- c(123,34,27,189)\n\ndat_cc <- xtabs(Count~Test+Disorder,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Disorder\nTest       Positive Negative\n  Positive      123       27\n  Negative       34      189\n```\n\n\n:::\n:::\n\n::: callout-note\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epiR)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'survival'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:epitools':\n\n    ratetable\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPackage epiR 2.0.94 is loaded\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nType help(epi.about) for summary information\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nType browseVignettes(package = 'epiR') to learn how to use epiR for applied epidemiological analyses\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n```{.r .cell-code}\nepi.tests(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Outcome +    Outcome -      Total\nTest +          123           27        150\nTest -           34          189        223\nTotal           157          216        373\n\nPoint estimates and 95% CIs:\n--------------------------------------------------------------\nApparent prevalence *                  0.40 (0.35, 0.45)\nTrue prevalence *                      0.42 (0.37, 0.47)\nSensitivity *                          0.78 (0.71, 0.85)\nSpecificity *                          0.88 (0.82, 0.92)\nPositive predictive value *            0.82 (0.75, 0.88)\nNegative predictive value *            0.85 (0.79, 0.89)\nPositive likelihood ratio              6.27 (4.36, 9.00)\nNegative likelihood ratio              0.25 (0.18, 0.33)\nFalse T+ proportion for true D- *      0.12 (0.08, 0.18)\nFalse T- proportion for true D+ *      0.22 (0.15, 0.29)\nFalse T+ proportion for T+ *           0.18 (0.12, 0.25)\nFalse T- proportion for T- *           0.15 (0.11, 0.21)\nCorrectly classified proportion *      0.84 (0.79, 0.87)\n--------------------------------------------------------------\n* Exact CIs\n```\n\n\n:::\n:::\n\nSensitivity: 0.78 (0.71-0.85)\n\nSpecificity: 0.88 (0.82-0.92)\n\n:::\n\n# Problem 4\n\nIn a study by Shaked et al. (2003), researchers studied 26 children with blunt pancreatic injuries. These injuries occurred from a direct blow to the abdomen, bicycle handlebars, fall from height, or car accident. Nineteen of the patients were classified as having minor injuries, and seven were classified as having major injuries. Pseudocyst formation was suspected when signs of clinical deterioration developed, such as increased abdominal pain, epigastric fullness, fever, and increased pancreatic enzyme levels. In the major injury group, six of the seven children developed pseudocysts while in the minor injury group, three of the 19 children developed pseudocysts.\n\n\n## 4a\n\nConstruct the relevant 2x2 table for this problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Injury=c(\"Major\",\"Minor\"),\n                   Pseudocyst =c(\"Positive\",\"Negative\"))\n\ndat$Count <- c(6,3,1,16)\ndat_cc <- xtabs(Count~Injury+Pseudocyst,data=dat)\n\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Pseudocyst\nInjury  Positive Negative\n  Major        6        1\n  Minor        3       16\n```\n\n\n:::\n:::\n\n\n## 4b \n\nWould it be advisable to use the asymptotic confidence interval when reporting the odds ratio for this problem? Why or why not? If it is not advisable, what confidence interval should we use?\n\n::: callout-note\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(dat_cc)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(dat_cc): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  dat_cc\nX-squared = 8.1773, df = 1, p-value = 0.004242\n```\n\n\n:::\n:::\n\n\nBecause the chi-squared approximation may be incorrect due to low expected values, it would be better to report the exact confidence intervals.\n\n\n:::\n\n## 4c\n\nIs there sufficient evidence to allow us to conclude that there is an association between pseudocyst development and degree of injuries? Use a significance level of 0.10.\n\n::: callout-note\n### Solution\n\nIt is recommended to use the Fisher's Exact test because of the low expected counts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dat_cc\np-value = 0.002226\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n    2.162745 1539.843484\nsample estimates:\nodds ratio \n  26.16028 \n```\n\n\n:::\n:::\n\nThe resulting p-value is 0.002. We reject the null hypothesis at 0.05 level of significance. There is sufficient evidence to conclude that there is an association between pseudocyst development and degree of injuries.\n:::\n\n# Problem 5\n\nThe table below shows data obtained from the 2006 administration of the General Social Survey (GSS).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Work = c(\"Full\",\"Part\"),\n                   SelfEmployment = c(\"No\",\"Yes\"),\n                   Gender= c(\"Males\",\"Females\"))\n\ndat$Count <- c(1051,108,199,38,978,238,87,60) \n\ndat_cc <- xtabs(Count~Work+SelfEmployment+Gender,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Gender = Males\n\n      SelfEmployment\nWork     No  Yes\n  Full 1051  199\n  Part  108   38\n\n, , Gender = Females\n\n      SelfEmployment\nWork     No  Yes\n  Full  978   87\n  Part  238   60\n```\n\n\n:::\n:::\n\n\n## 5a\n\nAt $\\alpha=0.05$, is there evidence of marginal association between work schedule (full-time/part-time) and self-employment?\n\n::: callout-note\n### Solution \n\nMarginal association means we are summing over gender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_marginal <- xtabs(Count~Work+SelfEmployment,data=dat)\nCMHtest(dat_marginal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Work by SelfEmployment \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 29.355  1 6.0276e-08\nrmeans  Row mean scores differ 29.355  1 6.0276e-08\ncmeans  Col mean scores differ 29.355  1 6.0276e-08\ngeneral    General association 29.355  1 6.0276e-08\n```\n\n\n:::\n:::\n\n\nAt 0.05 level of significance, we reject the null hypothesis ($\\chi^2_1=29.4,p<0.0001). We have sufficient evidence of marginal association between work and self-employment.\n:::\n\n## 5b\n\nAt $\\alpha=0.05$, is there evidence of conditional association between work schedule (full-time/part-time) and self-employment after controlling for gender?\n\n::: callout-note\n### Solution \n\nConditional association means we have association between work schedule and self-employment at any strata (Gender).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc,overall=T)$ALL\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Work by SelfEmployment \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df      Prob\ncor        Nonzero correlation 41.289  1 1.313e-10\nrmeans  Row mean scores differ 41.289  1 1.313e-10\ncmeans  Col mean scores differ 41.289  1 1.313e-10\ngeneral    General association 41.289  1 1.313e-10\n```\n\n\n:::\n:::\n\n\nAt 0.05 level of significance, we reject the null hypothesis ($\\chi^2_1=41.29,p<0.0001). We have sufficient evidence of conditional association between work and self-employment after controlling for gender.\n:::\n\n## 5c\n\nDoes the assumption of the homogeneity of the odds ratios hold?\n\n::: callout-note\n### Solution\n\nWe perform the Breslow-Day test to confirm homogeneity of the odds ratios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbreslow_day_test(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBreslow-Day Test on Homogeneity of Odds Ratios \n\nData:          dat_cc \nOR variables:  Work, SelfEmployment \nStrata:        Gender \nCommon OR:     2.343 \n\nX-squared = 2.3832, df = 1, p-value = 0.1226\n```\n\n\n:::\n:::\n\n\nThe resulting test statistic is $\\chi^2_1=2.38,p=0.12$. At 0.05 level of significance, we fail to reject the null hypothesis. We have no evidence against the homogeneity of odds ratios. Hence, we can interpret the common odds ratio.\n:::\n\n## 5d.\n\nBased on your answer in part (5c), report the relevant odds ratios and the asymptotic 95% confidence intervals.\n\n::: callout-note\n### Solution \n\nWe can interpret the common odds ratio reported by the `mantelhaen.test()` function. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmantelhaen.test(dat_cc,correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMantel-Haenszel chi-squared test without continuity correction\n\ndata:  dat_cc\nMantel-Haenszel X-squared = 41.289, df = 1, p-value = 1.313e-10\nalternative hypothesis: true common odds ratio is not equal to 1\n95 percent confidence interval:\n 1.797651 3.053437\nsample estimates:\ncommon odds ratio \n         2.342864 \n```\n\n\n:::\n:::\n\n\nThe common odds ratio estimate suggests that the odds of not being self-employed for those who work full time is 2.34 (1.80-3.05) times that of those who work part-time.\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}