{
  "hash": "141d4052125461fd594f8c89ef4b5c55",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 8\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 8 - [Back to home](https://madfudolig.quarto.pub/eab770slides/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n    echo: true\n  pdf: \n    number-sections: true\n    echo: true\n    toc: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n# Chapter 8: Logistic Regression: Dichotomous Response\n\n## Outline\n\n-   Dichotomous Explanatory Variables\n-   Qualitative Explanatory Variables\n-   Continuous and Ordinal Explanatory Variables\n-   Diagnostics\n-   Likelihood methods\n\n\n## Review: Mantel-Haenszel Tests\n\nMantel-Haenszel statistics investigate association between two variables with adjustment for a stratification variable.\n    -   General association\n    -   Location shifts for means\n    -   Linear/increasing trends \n    \n::: callout-note\nMantel-Haenszel Tests do not involve statistical models, and therefore can’t be used for estimation for effect sizes or prediction. Furthermore, these tests cannot accommodate for continuous variables as predictors.\n:::\n\n## Logistic Regression\n\nStatistical modeling method that enables us to make inferences, estimate/predict outcome variables, and describe the relationship between a categorical response variable and multiple explanatory variables. Possible applications include epidemiology, medical research, agronomy, and social science research.\n\n::: callout-note\nContinuous explanatory variables can be included in the analysis, unlike in Mantel-Haenszel tests. Responses can be dichotomous or polytomous (more than two levels).\n:::\n\n# Dichotomous Response\n\n## Logistic Regression: Model\n\nLogistic regression enables us to write a model for the probability of success for each group.\n\nLet $\\theta_{mi}$ be the probability of success of the $i^{th}$ group in\nthe $m^{th}$ strata.The logistic model can be used to describe the\nvariation among {$\\theta_{mi}$}\n\n$$\n\\theta_{mi} = \\frac{1}{1+\\exp[-\\eta_{mi}]}\n$$\n\n## Logistic Regression: Model\n\nWhere\n\n$$\n\\eta_{mi} = \\alpha + \\sum_{k=1}^t \\beta_kx_{mik}\n$$ \n\nand $t$ is the number of explanatory variables.\n\n::: callout-note\n$\\eta_{mi}$ is referred to as the linear predictor of the model.\n:::\n\n## Logistic Regression: Model\n\nUsing algebra, we can invert the equation to the following form:\n\n$$\n\\eta_{mi} = \\alpha + \\sum_{k=1}^t \\beta_kx_{mik} = \\log\\left[\\frac{\\theta_{mi}}{1-\\theta_{mi}}\\right]\n$$\n\n::: callout-note\n$\\log\\left[\\frac{\\theta_{mi}}{1-\\theta_{mi}}\\right]$ is referred to as\nthe **logit** transformation of $\\theta_{mi}$, which is the logarithm of\nthe odds.\n\nOther functions that can serve as a link function include the probit model and the complementary log-log model.\n:::\n\n## Odds and Odds Ratios\n\nThe odds of success for an individual in the $m^{th}$ strata and\n$i^{th}$ group can be calculated as\n\n$$\n\\theta_{mi}/(1-\\theta_{mi}) = e^{\\eta_{mi}}\n$$\n\nThe odds ratio between the $i^{th}$ and $j^{th}$ group in the $m^{th}$\nstrata can easily be calculated.\n\n$$\nOR = \\frac{odds_{mj}}{odds_{mi}} = e^{\\eta_{mj}}/e^{\\eta_{mi}} = e^{\\eta_{mj}-\\eta_{mi}}\n$$\n\n## Advantages\n\n-   The logit transformation enables us to monitor the change in log\n    odds.\n-   Easy to calculate odds ratio.\n-   The linear predictor can take on values from $(-\\infty,\\infty)$, but\n    the values of $\\theta_{mi}$ will be constrained in \\[0,1\\].\n\n::: callout-tip\nIf you used linear regression to model a proportion, it assumes that the\nresponse variable can be negative or above 1.\n:::\n\n## Fit Statistics\n\n-   The model performance can be measured using the **deviance** and\n    **goodness-of-fit** statistics.\n\n::: callout-note\nBoth use chi-square statistics to assess model fit.\n:::\n\n## Chi-square statistics\n\n::: callout-note\nLikelihood ratio chi-square measures the difference between two models\nby using the ratio of the two likelihoods as a chi-square statistic.\n:::\n\n::: callout-note\nPearson chi-square goodness of fit uses observed and expected values to\ntest for a goodness of fit.\n:::\n\n## Chi-square statistics\n\n-   If the chi-square statistic divided by the degrees of freedom is\n    higher than one, then the data has some variation that is\n    unaccounted for in the model.\n    -   This is called overdispersion\n-   The high ratio between the chi-square statistic and degrees of\n    freedom can also mean that the data does not follow a binomial\n    distribution well.\n    -   Heterogeneity\n-   Both cases are accounted for using generalized linear mixed\n    models/generalized estimating equations.\n\n## Chi-square statistics: Sample Size\n\nSample size guidelines for the chi-square assumption for these fit\nstatistics include:\n\n-   Each group should have at least ten subjects.\n-   80% of the predicted counts should be at least 5.\n-   No 0 counts, remaining 20% of the counts should be above 2.\n-   Failure to satisfy these assumptions means exact tests should be\n    used.\n\n## Chi-square statistics: Hypothesis Test\n\nThe null hypothesis for both deviance and goodness-of-fit tests is that\nthe departures of the observed data from the predicted values based on\nthe model are random.\n\n::: callout-note\nFailure to reject the null hypothesis means we have no evidence against good agreement between observed and predicted values based on the model.\n:::\n\n## Fit Statistics\n\nThe Akaike Infomation Criterion (AIC) and the Bayesian Information Criterion (BIC)/Schwarz Criterion (SC) can also be used to assess model fit. Lower values of these criteria indicate better model fit.\n\n::: callout-note\nAIC predicts estimation error based on the provided model. BIC also\npredicts estimation error but uses a different penalization scheme for\nerrors.\n\nThe AIC (or BIC) for the full model (intercept + covariates) should be lower than the AIC (or BIC) of the intercept-only model if the covariates are associated with the response.\n\n:::\n\n\n## The Main Effect Model\n\nRecall that the linear predictor can be written as:\n\n$$\n\\eta_i = \\beta_0 + \\beta_1x_{i1} + \\beta_2x_{i2} + ...\n$$ \n\n::: callout-note \n$\\beta_0$ is the intercept of the linear model \n:::\n\n::: callout-note\n$\\beta_k$ are the coefficients of the explanatory variables. These\ncoefficients will tell us the effect of predictor $x_{ik}$.\n:::\n\n## The Main Effect Model\n\nThe current form of the linear predictor assumes the explanatory variables are in quantitative form. When the explanatory variables are categorical, we need to create dichotomous dummy variables to denote each level of the variables.\n    \n::: callout-note    \nThe case $x_{ik}=0$ is called the reference level of the variables. When all $x_{ik}=0$ the linear predictor collapses to        the intercept $\\beta_0$.\n:::\n\n::: callout-note\nFor dummy dichotomous variables, odds ratios can be calculated as an\neffect size of association.\n:::\n\n## The Main Effect Model\n\n::: callout-note\nThe main effect model follows a regression framework, which means we can\nuse ANOVA to test for effect significance.\n:::\n\n## `SAS`: The LOGISTIC Procedure\n\nThe LOGISTIC procedure can perform logistic regression in SAS.\n\n-   Can take both categorical and continuous explanatory variable\n-   Syntax is slightly different from the FREQ procedure.\n\n## `SAS`: The LOGISTIC Procedure\n\nThe LOGISTIC procedure provides estimates for $\\beta$ as in regression\nanalysis.\n\n### Sample Syntax\n\n``` r\nproc logistic data=data;\nfreq count; # <1>\nmodel y(event='Yes') = x1 x2 /scale=none aggregate; # <2>\nrun;\n```\n\n1.  `freq` functions similar to `weight` in the `FREQ` procedure. When\n    the data consists of an observation for each row, this statement is\n    not needed.\n2.  `model` specifies the model for the response `y` using the\n    explanatory variables `x1` and `x2`. `event` tells SAS what the\n    \"success\" response level is. The `scale` option produces\n    goodness-of-fit statistics. The `aggregate` option requests that SAS\n    treat each unique combination of the explanatory variable values as\n    a distinct group in computing the goodness-of-fit statistics.\n\n\n## `R`: `glm()`\n\nThe `glm()` function in `R` can fit a logistic regression model in the generalized linear model framework.\n\n::: callout-note\nBecause there are other distributions that work with `glm()`, we need to specify that we are dealing with a binomial distribution using the `family=\"binomial\"` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(dependent~independent+covariates,\n    data=dataset,\n    family=\"binomial\")\n\nsummary(mod_glm)\n```\n:::\n\n\n:::\n\n## `R`: Odds Ratios\n\nWe can use `emmeans()` and `contrast()` from the `emmeans` package to estimate the probabilities and odds ratios based on the model provided by the `glm()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\nemm <- emmeans(mod_glm,~independent, type=\"response\",infer=T)\nemm\ncontrast(emm,method=\"pairwise\",type=\"response\",infer=T)\n```\n:::\n\n\n\n\n## Example\n\nThe data shows people who visited a clinic and required a\ncatheterization. The response is the presence of coronary artery\ndisease. The explanatory variables are ECG segment depression and sex.\nUse logistic regression methods to obtain odds ratio estimates and\ncreate a logistic regression model to estimate the probability of\ndeveloping CA disease based on sex and ECG segment depression.\n\n![](img/coronary_C3.png){height=\"200px\"}\n\n### Data Set\n\n``` r\ndata coronary;\ninput sex ecg ca count @@;\ndatalines;\n0 0 0 11 0 0 1 4\n0 1 0 10 0 1 1 8\n1 0 0 9 1 0 1 9\n1 1 0 6 1 1 1 21\n;\n```\nor refer to `ECG.csv` uploaded on Canvas. Sex=0 refers to female, while ECG=0 refers to\nlower segment depression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.2.1     v readr     2.2.0\nv forcats   1.0.1     v stringr   1.6.0\nv ggplot2   4.0.3     v tibble    3.3.1\nv lubridate 1.9.5     v tidyr     1.3.2\nv purrr     1.2.2     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\necg <- read.csv(\"ECG.csv\", stringsAsFactors = T)\nglimpse(ecg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 78\nColumns: 4\n$ ID      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,~\n$ Sex     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,~\n$ ECG     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,~\n$ Disease <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No~\n```\n\n\n:::\n:::\n\n\n\n## Example\n\nThe data shows people who visited a clinic and required a\ncatheterization. The response is the presence of coronary artery\ndisease. The explanatory variables are ECG segment depression and sex.\nUse logistic regression methods to obtain odds ratio estimates and\ncreate a logistic regression model to estimate the probability of\ndeveloping CA disease based on sex and ECG segment depression.\n\n::: panel-tabset\n### SAS Code\n\n``` r\nproc logistic data=coronary ;\nfreq count;\nmodel ca(event='1')=sex ecg / scale=none aggregate;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_glm <- glm(Disease~Sex+ECG,\n               data=ecg,\n               family=\"binomial\")\n\n# intercept only model \nmod1 <- glm(Disease~1,\n            data=ecg,\n            family=\"binomial\")\n\n# comparing intercept only  model to intercept + variables model\n\nanova(mod1,mod_glm,test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Disease ~ 1\nModel 2: Disease ~ Sex + ECG\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)   \n1        77     107.67                        \n2        75      95.90  2   11.769 0.002782 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Disease ~ 1, family = \"binomial\", data = ecg)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept)   0.1542     0.2271   0.679    0.497\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 107.67  on 77  degrees of freedom\nResidual deviance: 107.67  on 77  degrees of freedom\nAIC: 109.67\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Disease ~ Sex + ECG, family = \"binomial\", data = ecg)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -1.1747     0.4854  -2.420   0.0155 *\nSex           1.2770     0.4980   2.564   0.0103 *\nECG           1.0545     0.4980   2.118   0.0342 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 107.67  on 77  degrees of freedom\nResidual deviance:  95.90  on 75  degrees of freedom\nAIC: 101.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculating probabilities and odds ratios.\n\nemm <- emmeans(mod_glm,~Sex,type=\"response\")\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Sex  prob     SE  df asymp.LCL asymp.UCL\n   0 0.344 0.0853 Inf     0.200     0.523\n   1 0.652 0.0740 Inf     0.497     0.781\n\nResults are averaged over the levels of: ECG \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method=\"pairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n Sex0 / Sex1      0.279 0.139 Inf     0.105      0.74    1  -2.564  0.0103\n\nResults are averaged over the levels of: ECG \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method=\"revpairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value\n Sex1 / Sex0       3.59 1.79 Inf      1.35      9.52    1   2.564  0.0103\n\nResults are averaged over the levels of: ECG \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_ecg <- emmeans(mod_glm,~ECG,type=\"response\")\nemm_ecg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ECG  prob     SE  df asymp.LCL asymp.UCL\n   0 0.369 0.0880 Inf     0.218     0.551\n   1 0.627 0.0764 Inf     0.470     0.761\n\nResults are averaged over the levels of: Sex \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_ecg,method=\"pairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n ECG0 / ECG1      0.348 0.173 Inf     0.131     0.924    1  -2.118  0.0342\n\nResults are averaged over the levels of: Sex \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_ecg,method=\"revpairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value\n ECG1 / ECG0       2.87 1.43 Inf      1.08      7.62    1   2.118  0.0342\n\nResults are averaged over the levels of: Sex \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n### Answer\n\nFrom `SAS` output: Both chi-square tests had p-values above 0.05, which meant there was no\nevidence that the errors were not random.\n\nThe AIC values for the full model are lower than the intercept-only\nmodel, which meant model performance increased after including our\ncovariates.\n\nAssuming the probability of developing CA is given by $\\theta_CA$, the\nlogistic model was estimated to be:\n\n$$\nlogit~[\\hat{\\theta}_{CA}] = -1.17 + 1.28*SEX + 1.05*ECG\n$$\n\nThere is a significant effect of sex ($\\beta = 1.28$, p=0.01) and\nsegment depression ($\\beta = 1.05$, p=0.03) on the probability of\ndeveloping CA disease. In terms of odds ratios, the odds that males\ndevelop CA is 3.58 (95% CI: 1.35,9.52) times that of females. Additionally, the odds of\ndeveloping CA with higher segment depression is 2.87 (95% CI: 1.08, 7.62) times that of\npatients with lower segment depression in their ECG.\n:::\n\n## Exercise\n\nA simple random sample of individuals from different age groups were\nasked about their caffeine and exercise habits.\n\n::: panel-tabset\n\n### Data\n\n|             |              |              |             |\n|-------------|--------------|--------------|-------------|\n| Age Group   | Caffeine     | Yes Exercise | No Exercise |\n| Young Adult | Yes Caffeine | 121          | 158         |\n| Young Adult | No Caffeine  | 36           | 97          |\n| Older Adult | Yes Caffeine | 44           | 132         |\n| Older Adult | No Caffeine  | 15           | 130         |\n\nIt is also uploaded as line-level data as `exercise_caffeine.csv` on Canvas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexercise <- read.csv(\"exercise_caffeine.csv\")\nglimpse(exercise)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 733\nColumns: 3\n$ AgeGrp   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ Caffeine <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ Exercise <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n```\n\n\n:::\n:::\n\n\n### Questions \n\n-   Use logistic regression to estimate the logistic model for the data.\n    Use Young Adult and No caffeine as the reference levels.\n-   Is there a significant age group effect on exercise habits?\n-   Is there a significant effect of caffeine intake on exercise habits?\n-   Calculate and interpret the appropriate odds ratios for age group\n    and caffeine intake.\n-   Does the model fit the data well?\n\n:::\n\n## Exercise\n\nA simple random sample of individuals from different age groups were\nasked about their caffeine and exercise habits.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata caf;\ninput agegrp  caffeine  exercise  count;\ndatalines;\n0 1 1 121\n0 1 0 158\n0 0 1 36\n0 0 0 97\n1 1 1 44\n1 1 0 132\n1 0 1 15\n1 0 0 130\n;\n\nproc logistic;\nfreq count;\nmodel exercise(event='1')=agegrp caffeine / scale=none aggregate;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexercise <- read.csv(\"exercise_caffeine.csv\")\nglimpse(exercise)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 733\nColumns: 3\n$ AgeGrp   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ Caffeine <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ Exercise <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(Exercise~AgeGrp+Caffeine,\n               data=exercise,\n               family=\"binomial\")\n\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ AgeGrp + Caffeine, family = \"binomial\", \n    data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.0759     0.1711  -6.288 3.22e-10 ***\nAgeGrp       -0.9308     0.1789  -5.203 1.96e-07 ***\nCaffeine      0.8409     0.1866   4.507 6.58e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 832.30  on 730  degrees of freedom\nAIC: 838.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm <- emmeans(mod_glm,~Caffeine,type=\"response\",infer=T)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Caffeine  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n        0 0.176 0.0231 Inf     0.136     0.226  0.5  -9.696 <0.0001\n        1 0.332 0.0233 Inf     0.288     0.379  0.5  -6.676 <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method='revpairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n Caffeine1 / Caffeine0       2.32 0.433 Inf      1.61      3.34    1   4.507\n p.value\n <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_age <- emmeans(mod_glm,~AgeGrp,type=\"response\",infer=T)\nemm_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n AgeGrp  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n      0 0.342 0.0252 Inf     0.294     0.393  0.5  -5.861 <0.0001\n      1 0.170 0.0211 Inf     0.132     0.215  0.5 -10.607 <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_age,method='pairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n AgeGrp0 / AgeGrp1       2.54 0.454 Inf      1.79       3.6    1   5.203\n p.value\n <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nmod1 <- glm(Exercise~1,\n               data=exercise,\n               family=\"binomial\")\nanova(mod1,mod_glm,test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Exercise ~ 1\nModel 2: Exercise ~ AgeGrp + Caffeine\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1       732     888.82                          \n2       730     832.30  2   56.515 5.345e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ 1, family = \"binomial\", data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.87276    0.08102  -10.77   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 888.82  on 732  degrees of freedom\nAIC: 890.82\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ AgeGrp + Caffeine, family = \"binomial\", \n    data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.0759     0.1711  -6.288 3.22e-10 ***\nAgeGrp       -0.9308     0.1789  -5.203 1.96e-07 ***\nCaffeine      0.8409     0.1866   4.507 6.58e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 832.30  on 730  degrees of freedom\nAIC: 838.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nSuppose the probability of exercise is given by $\\theta$,The estimated logistic regression model is: $logit (\\theta) = -1.08 -0.93*AGEGRP + 0.84*CAFFEINE$. The AIC for the full model is lower than that of the intercept only model, indicating better model fit.\n\nThere is a significant effect of age in the likelihood of exercising. The odds of an older participant reporting regular exercise is 0.39 (95% CI: 0.28, 0.56; p<0.001) times that of younger participants.\n\nThere is a significant effect of caffeine intake on exercise. The odds of a participant reporting regular exercise when they consume caffeine is 2.3 (95% CI: 1.6,3.3; p<0.001) times that of those who do not consume caffeine.\n\n`SAS`: The deviance (p=0.39) and goodness-of-fit chi-square tests (p=0.40) showed no evidence against the randomness of errors, which indicates good model fit. The AIC and SC values also decreased after including covariates, also supporting good fit.\n\n:::\n\n\n\n## `SAS`: `CLASS` statement\n\n- The `class` statement can create dummy variable coding automatically through the LOGISTIC procedure.\n  - The REF option allows us to set the reference level for each variable.\n  \n  \n```{.r code-line-numbers=2}\nproc logistic;\nclass cat;\nmodel y = x cat/scale=none aggregate;\nrun;\n```\n\n## `SAS`: Model parameterizations\n\n::: callout-note\n**Effect parameterization** produces deviation from the _grand mean_. The reference level corresponds to $X=-1$.\n\n- In `R`, this is established using `contr.sum()`\n- In `SAS`, this is the default parameterization in the `LOGISTIC` procedure.\n:::\n\n::: callout-note\n**Reference cell parameterization** produces measurements based on reference level. The reference level corresponds to $X=0$.\n\n- In `R`, this is established using `contr.treatment()` or `contr.SAS()`. This is the default in `R`.\n- In `SAS`, this can be specified in the class statement as `param=ref` in the `LOGISTIC` procedure.\n\n\n:::\n\n## Example\n\nThe data is based on a study on prison sentencing for persons convicted of a burglary or larceny. The researchers wanted to test whether the type of crime (nonresidential or other) and prior arrests (some or none) affect whether the offender was sent to prison.\n\n::: panel-tabset\n\n### Data\n\n![](img/sentencing_C8.png){height=\"200px\"}\n\n### Questions\n\n-   Perform a logistic regression analysis to estimate the appropriate logistic model for the data. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.\n  -   Using effect parameterization\n  -   Using reference cell parameterization\n\n:::\n\n## Example\n\nRecall the age x caffeine x exercise habits exercise. Use the class statement to perform logistic regression using effect and reference cell parameterization. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.\n\n\n## Example\nRecall the age x caffeine x exercise habits exercise. Use the class statement to perform logistic regression using effect and reference cell parameterization. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.\n\n:::{.panel-tabset}\n\n### SAS Code\n```{.r}\ntitle \"effect\";\nproc logistic data=caf;\nfreq count;\nclass agegrp (REF='0') caffeine (REF='0');\nmodel exercise(event='1')=agegrp caffeine / scale=none aggregate;\nrun;\n\ntitle \"ref cell\";\nproc logistic data=caf;\nfreq count;\nclass agegrp (REF='0') caffeine (REF='0')/param=ref;\nmodel exercise(event='1')=agegrp caffeine / scale=none aggregate;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nexercise <- read.csv(\"exercise_caffeine.csv\")\nglimpse(exercise)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 733\nColumns: 3\n$ AgeGrp   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~\n$ Caffeine <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n$ Exercise <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~\n```\n\n\n:::\n:::\n\n\nReference Cell parameterization\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts=c(\"contr.treatment\",\"contr.poly\"))\n\n\nmod_glm <- glm(Exercise~AgeGrp+Caffeine,\n               data=exercise,\n               family=\"binomial\")\n\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ AgeGrp + Caffeine, family = \"binomial\", \n    data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.0759     0.1711  -6.288 3.22e-10 ***\nAgeGrp       -0.9308     0.1789  -5.203 1.96e-07 ***\nCaffeine      0.8409     0.1866   4.507 6.58e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 832.30  on 730  degrees of freedom\nAIC: 838.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm <- emmeans(mod_glm,~Caffeine,type=\"response\",infer=T)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Caffeine  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n        0 0.176 0.0231 Inf     0.136     0.226  0.5  -9.696 <0.0001\n        1 0.332 0.0233 Inf     0.288     0.379  0.5  -6.676 <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method='revpairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n Caffeine1 / Caffeine0       2.32 0.433 Inf      1.61      3.34    1   4.507\n p.value\n <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_age <- emmeans(mod_glm,~AgeGrp,type=\"response\",infer=T)\nemm_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n AgeGrp  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n      0 0.342 0.0252 Inf     0.294     0.393  0.5  -5.861 <0.0001\n      1 0.170 0.0211 Inf     0.132     0.215  0.5 -10.607 <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_age,method='pairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n AgeGrp0 / AgeGrp1       2.54 0.454 Inf      1.79       3.6    1   5.203\n p.value\n <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nmod1 <- glm(Exercise~1,\n               data=exercise,\n               family=\"binomial\")\nanova(mod1,mod_glm,test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Exercise ~ 1\nModel 2: Exercise ~ AgeGrp + Caffeine\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1       732     888.82                          \n2       730     832.30  2   56.515 5.345e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ 1, family = \"binomial\", data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.87276    0.08102  -10.77   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 888.82  on 732  degrees of freedom\nAIC: 890.82\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n::: callout-warning\nEffect parameterization can only be implemented in `R` if the predictors are inputted as factors.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts=c(\"contr.sum\",\"contr.poly\"))\n\nexercise <- exercise |> \n  mutate(AgeGrp=as.factor(AgeGrp),\n         Caffeine = as.factor(Caffeine))\n\nmod_glm <- glm(Exercise~AgeGrp+Caffeine,\n               data=exercise,\n               family=\"binomial\")\n\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ AgeGrp + Caffeine, family = \"binomial\", \n    data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.12090    0.09714 -11.539  < 2e-16 ***\nAgeGrp1      0.46541    0.08944   5.203 1.96e-07 ***\nCaffeine1   -0.42046    0.09330  -4.507 6.58e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 832.30  on 730  degrees of freedom\nAIC: 838.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm <- emmeans(mod_glm,~Caffeine,type=\"response\",infer=T)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Caffeine  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n 0        0.176 0.0231 Inf     0.136     0.226  0.5  -9.696 <0.0001\n 1        0.332 0.0233 Inf     0.288     0.379  0.5  -6.676 <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method='revpairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n Caffeine1 / Caffeine0       2.32 0.433 Inf      1.61      3.34    1   4.507\n p.value\n <0.0001\n\nResults are averaged over the levels of: AgeGrp \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_age <- emmeans(mod_glm,~AgeGrp,type=\"response\",infer=T)\nemm_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n AgeGrp  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n 0      0.342 0.0252 Inf     0.294     0.393  0.5  -5.861 <0.0001\n 1      0.170 0.0211 Inf     0.132     0.215  0.5 -10.607 <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_age,method='pairwise', type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n AgeGrp0 / AgeGrp1       2.54 0.454 Inf      1.79       3.6    1   5.203\n p.value\n <0.0001\n\nResults are averaged over the levels of: Caffeine \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nmod1 <- glm(Exercise~1,\n               data=exercise,\n               family=\"binomial\")\nanova(mod1,mod_glm,test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Exercise ~ 1\nModel 2: Exercise ~ AgeGrp + Caffeine\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1       732     888.82                          \n2       730     832.30  2   56.515 5.345e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Exercise ~ 1, family = \"binomial\", data = exercise)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.87276    0.08102  -10.77   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 888.82  on 732  degrees of freedom\nResidual deviance: 888.82  on 732  degrees of freedom\nAIC: 890.82\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nEffect parameterization: $logit (\\theta_{ij}) = -1.12 - 0.47 * AGEGRP +0.42* CAFFEINE$\n\nReference Cell parameterization: $logit (\\theta_{ij}) = -1.08- 0.93 * AGEGRP +0.84* CAFFEINE$\n\nThere is strong evidence of an effect of age (p<0.001). The odds of older adults reporting regular exercise is 0.39 (95% CI: 0.28, 0.56) times that of younger adults.\n\nThere is strong evidence of an association with caffeine consumption (p<0.001). The odds of reporting regular exercise for participants who consumed caffeine is 2.32 times that of those who do not consume caffeine.\n:::\n\n\n\n## Example\n\nThe data is based on a study on prison sentencing for persons convicted of a burglary or larceny. The researchers wanted to test whether the type of crime (nonresidential or other) and prior arrests (some or none) affect whether the offender was sent to prison.\n\n-   Perform a logistic regression analysis to estimate the appropriate logistic model for the data. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.\n  -   Using effect parameterization\n  -   Using reference cell parameterization\n  \n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata sentence;\ninput type $ prior $ sentence $ count @@;\ndatalines;\nnrb some y 42 nrb some n 109\nnrb none y 17 nrb none n 75\nother some y 33 other some n 175\nother none y 53 other none n 359\n;\n\nproc logistic data=sentence order=data;\ntitle \"effect\";\nclass type(ref=\"nrb\") prior(ref=\"none\") / ; # <1>\nfreq count;\nmodel sentence(event='y') = type prior / scale=none aggregate;\nrun;\n\n\nproc logistic data=sentence order=data;\ntitle \"reference\";\nclass type(ref=\"nrb\") prior(ref=\"none\") / param=ref; # <2>\nfreq count;\nmodel sentence(event='y') = type prior / scale=none aggregate;\nrun;\n\n\n\n```\n\n1. Default: effect parameterization\n2. Reference cell parameterization used after `param=ref` is specified.\n\n### R Code\n\nWe can also use `glm()` for aggregated counts, but we don't need to create a contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(type = c(\"nonresidential\",\"other\"),\n                   prior = c(\"none\",\"some\"))\ndat$prison <- c(17,53,42,33)\ndat$noprison <- c(75,359,109,175)\n\ndat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            type prior prison noprison\n1 nonresidential  none     17       75\n2          other  none     53      359\n3 nonresidential  some     42      109\n4          other  some     33      175\n```\n\n\n:::\n:::\n\n\n**Reference Cell Parameterization**\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts=c(\"contr.treatment\",\"contr.poly\"))\nmod_glm <- glm(cbind(prison,noprison)~type + prior,data=dat,family=\"binomial\")\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(prison, noprison) ~ type + prior, family = \"binomial\", \n    data = dat)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.3603     0.1962  -6.933 4.13e-12 ***\ntypeother    -0.5920     0.1968  -3.008  0.00263 ** \npriorsome     0.3469     0.1906   1.820  0.06875 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 16.59755  on 3  degrees of freedom\nResidual deviance:  0.50763  on 1  degrees of freedom\nAIC: 27.079\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm <- emmeans(mod_glm,~type,type=\"response\",infer=T)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type            prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n nonresidential 0.234 0.0274 Inf     0.184     0.292  0.5  -7.747 <0.0001\n other          0.144 0.0146 Inf     0.118     0.175  0.5 -15.051 <0.0001\n\nResults are averaged over the levels of: prior \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method=\"revpairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast               odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n other / nonresidential      0.553 0.109 Inf     0.376     0.814    1  -3.008\n p.value\n  0.0026\n\nResults are averaged over the levels of: prior \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_prior <- emmeans(mod_glm,~prior,type=\"response\",infer=T)\nemm_prior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n prior  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n none  0.160 0.0186 Inf     0.127     0.200  0.5 -11.971 <0.0001\n some  0.213 0.0219 Inf     0.173     0.259  0.5 -10.012 <0.0001\n\nResults are averaged over the levels of: type \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_prior,method=\"revpairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value\n some / none       1.41 0.27 Inf     0.974      2.06    1   1.820  0.0687\n\nResults are averaged over the levels of: type \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n::: callout-tip\nTry replacing \"contr.treatment\" with \"contr.SAS\". Which parts of the output change? Which parts do not change?\n:::\n\n**Effect parameterization**\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts=c(\"contr.sum\",\"contr.poly\"))\nmod_glm <- glm(cbind(prison,noprison)~type + prior,data=dat,family=\"binomial\")\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(prison, noprison) ~ type + prior, family = \"binomial\", \n    data = dat)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.48282    0.09507 -15.596  < 2e-16 ***\ntype1        0.29598    0.09838   3.008  0.00263 ** \nprior1      -0.17347    0.09531  -1.820  0.06875 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 16.59755  on 3  degrees of freedom\nResidual deviance:  0.50763  on 1  degrees of freedom\nAIC: 27.079\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n\n```{.r .cell-code}\nemm <- emmeans(mod_glm,~type,type=\"response\",infer=T)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type            prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n nonresidential 0.234 0.0274 Inf     0.184     0.292  0.5  -7.747 <0.0001\n other          0.144 0.0146 Inf     0.118     0.175  0.5 -15.051 <0.0001\n\nResults are averaged over the levels of: prior \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm,method=\"pairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast               odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio\n nonresidential / other       1.81 0.356 Inf      1.23      2.66    1   3.008\n p.value\n  0.0026\n\nResults are averaged over the levels of: prior \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_prior <- emmeans(mod_glm,~prior,type=\"response\",infer=T)\nemm_prior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n prior  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n none  0.160 0.0186 Inf     0.127     0.200  0.5 -11.971 <0.0001\n some  0.213 0.0219 Inf     0.173     0.259  0.5 -10.012 <0.0001\n\nResults are averaged over the levels of: type \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_prior,method=\"pairwise\",type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n none / some      0.707 0.135 Inf     0.486      1.03    1  -1.820  0.0687\n\nResults are averaged over the levels of: type \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nEffect parameterization: $logit (\\theta_{ij}) = -1.48 - 0.30 * TYPE +0.17* PRIOR$\n\nReference Cell parameterization: $logit (\\theta_{ij}) = -1.36- 0.59 * TYPE +0.35* PRIOR$\n\nThe odds of sending an offender to prison after committing other crimes is 0.55 times (95% CI: 0.38, 0.81) that when committing non-residential crimes. There is strong evidence against the null hypothesis of no difference.\n\nThe odds of sending an offender with some prior arrests are 1.42 times (95% CI: 0.974, 2.06) times more likely to be sent to prison than those who have no prior arrests. There is moderate evidence against the null hypothesis of no difference.\n\n:::\n\n\n\n## Saturated models\n\n- Saturated models often include an interaction term $A*B$, which tests the difference of the effect of B in the different levels of $A$.\n\n::: {.callout-note title=\"Simple Effects\"}\nThe effect of $B$ conditional on the level of $A$ is referred to as _simple effects_.\n:::\n\n## Interaction Models\n\nThe interaction model in the logistic regression framework can be written as:\n\n$$\nlogit(\\theta) = \\alpha + \\beta_1 x_1  + \\beta_2 x_2 + \\beta_{12}x_1x_2\n$$\n\n::: callout-tip\nInteraction terms should be tested first ($x_1x_2$). If the interaction is not significant, it can be dropped from the model, leaving you with a main effects model.\n:::\n\n## Interaction models\n\n::: panel-tabset\n\n### Interaction tests\n- Interaction tests are Wald chi-square tests with $(a-1)(b-1)$ degrees of freedom, where $a$ is the number of levels of A and $b$ is the number of levels of B.\n- The degrees of freedom is also equal to the number of coefficients that should be allotted to the interactions.\n  - Interactions can be visually recognized using interaction plots.\n  \n### Figure \n\n![](img/interaction_C8.png)\n\n:::\n\n## Non-Dichotomous Explanatory Variables\n\n- What if the explanatory variables have more than two levels?\n  - Nominal\n  - Ordinal\n  - Continuous\n\n## Non-Dichotomous Explanatory Variables\n\nIf an explanatory variable has $n$ levels, $(n-1)$ dichotomous dummy variables are needed to be produced to include the explanatory variable in the regression model.\n\n::: callout-note\nIn interaction models, this leads to more interaction terms.\n:::\n\nFor a variable with $(a-1)$ levels\n$$\nlogit(\\theta) = \\alpha + \\beta_1x_{a1} + \\beta_2x_{a2} + ... + \\beta_{(a-1)}x_{a,a-1}\n$$\n\nThe matrix form of the predictor variables is called the **Design Matrix**.\n\n## Non-Dichotomous Explanatory Variables\n\nFor a model with two variables/factors: one with $(a-1)$ levels and the other with $(b-1)$ levels, the interaction model can be written as:\n\n$$\nlogit(\\theta) = \\alpha + \\beta_{a1}x_{a1} + \\beta_{a2}x_{a2} + ... + \\beta_{a,(a-1)}x_{a,a-1} +  \\beta_{b1}x_{b1} + \\beta_{b2}x_{b2} + ... + \\beta_{b(b-1)}x_{b,b-1} + Interaction\n$$\n\n$$\nInteraction = \\beta_{a1b1}x_{a1}x_{b1} + \\beta_{a1b2}x_{a1}x_{b2} + \\beta_{a2b1}x_{a2}x_{b1} +... + \\beta_{a,a-1;b,b-1}x_{a,a-1}x_{b,b-1}\n$$\n\n## Nominal Explanatory Variables\n\nSince there is no order in the levels of explanatory variables, we might be interested in the difference between specific levels\n\n- Example: How did the difference in placebo and test treatments compare between Hospital 1 and Hospital 2?\n- Example: How did the placebo and test treatments compare in Hospital 2?\n\n## Contrasts\n\n- Contrasts are used in performing a formal test for estimable effects\n- The null hypotheses for these tests are usually the hypothesis of no effect\n  - “There is no main effect of Variable/ Factor A”\n  - “There is no interaction”\n  - “The estimated treatment mean of the first level of Factor A and first level of Factor B is zero”\n\n## Contrasts: Estimable Effects\n\nSuppose we refer to $logit(\\theta_{ij})$ as $\\eta_{ij}$.\n\n::: {.callout-note title=\"Estimable Effects\"}\nEstimable effects are effects that can be expressed as the sum or difference of linear predictors $\\eta_{ij}$.\n:::\n\nExample: How did the difference in placebo and test treatments compare between Hospital 1 and Hospital 2?\n\n- The null hypothesis can be expressed as $\\eta_{t1}-\\eta_{p1} -(\\eta_{t2}-\\eta_{p2}) = 0$. This effect is estimable!\n- The expression can be expressed in terms of $\\beta_i$ by substituting the linear predictor expressions.\n\n## Contrasts: Joint Tests\n\nSuppose we have an explanatory variable/factor $A$ with three levels, which requires **two** different dummy variables. The regression model can be expressed as:\n\n$$\nlogit (\\theta) = \\eta = \\alpha + \\beta_1 X_{a1} + \\beta_2 X_{a2}\n$$\n\nTo test for a main effect of $A$, we need to test the following null hypotheses simultaneously: $\\beta_1=0$ and $\\beta_2=0$. These could be done using **joint tests**.\n\n- The joint tests use Wald statistics similar to an ANOVA.\n\n## Contrasts: SAS\n\nWe use the `contrast` statement in the `LOGISTIC` procedure to test these contrasts.\n\n:::callout-note\nIn SAS, we focus on the coefficients of each term defined in the linear predictor. Each linear predictor is broken down into the effect and interaction terms and simplified. The resulting **coefficients** would then make it to the contrast statement.\n:::\n\n## Contrasts: `R`\n\nThe `contrast()` function in the `emmeans` package enables us to perform contrasts. There are preset contrasts like \"pairwise\" and \"revpairwise\" that do not need to specify coefficients. Complex contrasts and joint tests need to have the coefficient inputted in the function.\n\n## Example: `SAS`\n\nSuppose we are interested in modeling the mortality rate of cardiothoracic surgery across 4 hospitals. The resulting logistic regression model would be:\n\n\n$$\n\\eta = \\alpha + \\beta_1X_{h1} + \\beta_1X_{h2} + \\beta_3X_{h3}\n$$\n\nSuppose we want to test for a difference in mortality between hospital 1 and hospital 4.\n\n:::{.panel-tabset}\n### Reference Cell\nThe effect due to Hospital 1 corresponds to the case $(X_{h1},X_{h2},X_{h3} = 1,0,0)$ yields a regression model given by: $\\alpha + \\beta_1$.\nHospital 4 corresponds to the case $(X_{h1},X_{h2},X_{h3} = 0,0,0)$, which yields a regression model given by: $\\alpha$.\n\nThen the difference between Hospital 1 and Hospital 4 can be calculated as \n$$\\alpha +\\beta_1 - \\alpha = \\beta_1 $$. T\nhe corresponding null hypothesis of no difference can the be written as\n$$ 1* \\beta_1 + 0*\\beta_2 + 0*\\beta_3 = 0$$\n\nIn SAS, we can code this as:\n\n```{.r}\ncontrast A 1 0 0 ;\n```\n\n### Effect\nThe effect due to Hospital 1 corresponds to the case $(X_{h1},X_{h2},X_{h3} = 1,0,0)$ yields a regression model given by: $\\alpha + \\beta_1$.\nHospital 4 corresponds to the case $(X_{h1},X_{h2},X_{h3} = -1,-1,-1)$, which yields a regression model given by: $\\alpha -\\beta_1 - \\beta_2 - \\beta_3$.\n\nThen the difference between Hospital 1 and Hospital 4 can be calculated as \n$$\\alpha +\\beta_1 - [\\alpha -\\beta_1 - \\beta_2 - \\beta_3] = 2\\beta_1 +\\beta_2 + \\beta_3$$. \n\nThe corresponding null hypothesis of no difference can the be written as:\n\n$$\n2\\beta_1 +1* \\beta_2 + 1*\\beta_3 = 0\n$$\n\nIn SAS, we can code this as:\n\n```{.r}\ncontrast A 2 1 1 ;\n```\n\nIn `R`, we can code this as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast_list <- list(contrast1=c(2,1,1))\ncontrast(emm,method=contrast_list,type=\"response\")\n```\n:::\n\n\n:::\n\n## Example: `R`\n\nSuppose we are interested in modeling the mortality rate of cardiothoracic surgery across 4 hospitals. The resulting logistic regression model would be:\n\n\n$$\n\\eta = \\alpha + \\beta_1X_{h1} + \\beta_1X_{h2} + \\beta_3X_{h3}\n$$\n\nThe `contrast()` function uses the coefficients of the **marginal means** to perform the contrast. Suppose we want to test for a difference in mortality between hospital 1 and hospital 4. This means we are testing the hypothesis $H_0: \\mu_1-\\mu_4=0$, which can be interpreted as:\n\n$$\n\\mu_1 + 0*\\mu_2 + 0*\\mu_3 -\\mu_4 =0\n$$\n\nwhich yields the coefficients (1,0,0,-1). In `R`, we can code this as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm <- emmeans(mod_glm,~hospital,type=\"response\")\n\ncontrast_list <- list(contrast1=c(1,0,0,-1))\ncontrast(emm,method=contrast_list,type=\"response\")\n```\n:::\n\n\n## Exercise: `SAS`\n\nConsider a Factor A with three levels $(A_1,A_2,A_3)$, with $A_3$ as the reference level. Provide the corresponding null hypotheses and formulate the contrast statements for both reference cell and effect parameterization.\n\n  - There is no difference between the first and third levels of A.\n  - The mean effect of $A_1$ and $A_2$ is equal to the effect of $A_3$.\n\n## Exercise: `SAS`\n\nConsider a Factor A with three levels $(A_1,A_2,A_3)$, with $A_3$ as the reference level. Provide the corresponding null hypotheses and formulate the SAS contrast statements for both reference cell and effect parameterization.\n\n  - There is no effect difference between the first and third levels of A.\n  - The mean effect of $A_1$ and $A_2$ is equal to the effect of $A_3$.\n\nThe logit model can be expressed as:\n\n$$\n\\eta = \\alpha + \\beta_1 X_1 + \\beta_2 X_2\n$$\n\n\n:::{.panel-tabset}\n### Item 1\n\nReference Cell: \nEffect $A_1 = \\alpha + \\beta_1$\nEffect $A_3 = \\alpha$\n\nNo effect difference between the first and third levels: $A_1-A_3 = 0 \\to \\beta_1=0$. Therefore, the contrast coefficients are $(\\beta_1,\\beta_2) = (1,0)$.\n\n```{.r}\ncontrast A 1 0;\n```\n\n\nEffect parameterization:\nEffect $A_1 = \\alpha + \\beta_1$\nEffect $A_3 = \\alpha-\\beta_1 - \\beta_2$\n\nNo effect difference between the first and third levels: $A_1-A_3 = 0 \\to 2\\beta_1 +\\beta_2=0$. Therefore, the contrast coefficients are $(\\beta_1,\\beta_2) = (2,1)$.\n\n```{.r}\ncontrast A 2 1;\n```\n\n### Item 2\n\nReference Cell: \nEffect $A_1 = \\alpha + \\beta_1$\nEffect $A_2 = \\alpha + \\beta_2$\nEffect $A_3 = \\alpha$\n\nNo effect difference between the first and third levels: $(A_1+A_2)/2-A_3 = 0 \\to 1/2(\\beta_1+\\beta_2)=0$. Therefore, the contrast coefficients are $(\\beta_1,\\beta_2) = (0.5,0.5)$.\n\n```{.r}\ncontrast A 0.5 0.5;\n```\n\nEffect parameterization:\nEffect $A_1 = \\alpha + \\beta_1$\nEffect $A_2 = \\alpha + \\beta_2$\nEffect $A_3 = \\alpha-\\beta_1 - \\beta_2$\n\nNo effect difference between the first and third levels: $(A_1+A_2)/2-A_3 = 0 \\to 3/2(\\beta_1+\\beta_2)=0$. Therefore, the contrast coefficients are $(\\beta_1,\\beta_2) = (1.5,1.5)$.\n\n```{.r}\ncontrast A 1.5 1.5;\n```\n:::\n\n\n## Exercise: `R`\n\nConsider a Factor A with three levels $(A_1,A_2,A_3)$, with $A_3$ as the reference level. Provide the corresponding null hypotheses and formulate the contrast statements.\n\n::: panel-tabset\n### Questions\n\n  - There is no difference between the first and third levels of A.\n  - The mean effect of $A_1$ and $A_2$ is equal to the effect of $A_3$.\n\n### Answer\n- `contrast1`:  There is no difference between the first and third levels of A. $(\\mu_1-\\mu_3) = 0$\n- `contrast2`:The mean effect of $A_1$ and $A_2$ is equal to the effect of $A_3$. $\\frac{\\mu_1+\\mu_2}{2}-\\mu_3=0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast_list <- list(contrast1 = c(1,0,-1),\n                      contrast2 = c(1/2,1/2,-1))\ncontrast(emm,method=contrast_list)\n```\n:::\n\n\n:::  \n\n## Example\n\nConsider a Factor A with three levels $(A_1,A_2,A_3)$ and Factor B with two levels $(B_1,B_2)$, with $A_3$ and $B_2$ as the reference level. Suppose $\\theta$ is a probability of observing success for a dichotomous response variable $y$.\n\n  - Please write the saturated/interaction logistic model for $\\theta$  \n\nProvide the corresponding null hypothesis and formulate the contrast statements for both reference cell and effect parameterizations.\n\n  - \"There is no interaction between A and B\".\n\n\n\n## Example: `SAS`\n\nConsider a Factor A with three levels $(A_1,A_2,A_3)$ and Factor B with two levels $(B_1,B_2)$, with $A_3$ and $B_2$ as the reference level. Suppose $\\theta$ is a probability of observing success for a dichotomous response variable $y$.\n\n  - Write the saturated/interaction logistic model for $\\theta$  \n\n$$\n\\eta = \\alpha + \\beta_{A1}x_{A1} + \\beta_{A2}x_{A2} +\\\\\n\\beta_{B1}x_{B1}+ \\beta_{A1B1}x_{A1}x_{B1} + \\beta_{A2B1}x_{A2}x_{B1}\n$$\n\nProvide the corresponding null hypotheses and formulate the SAS contrast statements for both reference cell and effect parameterizations.\n\n  - \"There is no interaction between A and B\".\n    - The joint tests of the following hypotheses should be tested: $\\beta_{A1B1} = 0$ and $\\beta_{A2B1}=0$, which corresponds to the following coefficients for A*B: (1,0) and (0,1).\n    \n```{.r}\ncontrast A*B 1 0,\n              0 1;\n```\n\n## Example: `R`\n\n\n\n## Implementing Qualitative Explanatory Variables in SAS\n\n- Use the `class` statement in `LOGISTIC` procedure to identify qualitative variables.\n- Interaction between Factors A and B are included in the model as $A*B$\n  - To include the saturated model of Factors A and B, you can write (response variable)=`A|B`.\n  - You can add more than two factors in these statements.\n  - Three-way interaction: `A*B*C`\n  - Saturated model for a three-factor model: `A|B|C`\n- If you wish to only include up to two-way interactions in a three-factor model: `A|B|C@2`\n- You can introduce contrasts in the `contrast` statement.\n- `effectplot` can be used to create interaction plots.\n- `oddsratio` calculates odds ratios and graphs of confidence limits for odds ratios.\n\n## Implementing Qualitative Explanatory Variables in `R`.\n\nIt would be ideal to change all character variables into factors using the `mutate()` function in the `dplyr`/`tidyverse` package in `R` before using it in the `glm()` function in `R`.\n\n::: callout-note\nInteractions are written as `A:B`. This can be extended to higher order interactions: `A:B:C`.\n\nWriting `A*B` means we are including the following terms: `A + B + A:B`.\n:::\n\n::: callout-note\nMarginal and conditional means can still be calculated using the `emmeans()` package. To create an interaction plot, we just use the `plot()` function.\n\nContrasts can be used to calculate odds ratios and confidence limits.\n:::\n\n::: callout-note\nType III tests of fixed effects should be used to test for interactions. This can be done by using the `Anova()` function in `R`.\n:::\n\n## Example\n\nThe data set is from a cross-sectional prevalence study conducted to investigate textile worker complaints about respiratory symptoms experienced while working in the mills. Investigators were interested in whether occupational environment was related to prevalence of respiratory ailments associated with the disease byssinosis.\n\n- Use logistic regression to model the probability of complaining based on workplace condition, years of employment, and smoking history. Include only up to two-way interaction effects.\n- Is there evidence of any two-way interactions at a significance level of 0.10?\n- Generate an interaction plot for these cases.\n- Generate the main effects using contrast statements.\n\n:::{.panel-tabset}\n### Table\n\n![](img/byss_C8.png)\n\n### SAS Data Set\n```{.r}\ndata byss;\ninput work $ years $ smoke $ status $ count @@;\ndatalines ;\ndusty <10 yes yes 30 dusty <10 yes no 203\ndusty <10 no yes 7 dusty <10 no no 119\ndusty >=10 yes yes 57 dusty >=10 yes no 161\ndusty >=10 no yes 11 dusty >=10 no no 81\nnot <10 yes yes 14 not <10 yes no 1340\nnot <10 no yes 12 not <10 no no 1004\nnot >=10 yes yes 24 not >=10 yes no 1360\nnot >=10 no yes 10 not >=10 no no 986\n;\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Smoking = c(\"No\",\"Yes\"),\n                   Years = c(\"Less10\",\"Greater10\"),\n                   Work= c(\"Not Dusty\",\"Dusty\"))\n\ndat$yes <- c(12,14,10,24,7,30,11,57)\ndat$no <- c(1004,1340,986,1360,119,203,81,161)\ndat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Smoking     Years      Work yes   no\n1      No    Less10 Not Dusty  12 1004\n2     Yes    Less10 Not Dusty  14 1340\n3      No Greater10 Not Dusty  10  986\n4     Yes Greater10 Not Dusty  24 1360\n5      No    Less10     Dusty   7  119\n6     Yes    Less10     Dusty  30  203\n7      No Greater10     Dusty  11   81\n8     Yes Greater10     Dusty  57  161\n```\n\n\n:::\n:::\n\n\n\n:::\n\n##  Example\n\nThe data set is from a cross-sectional prevalence study conducted to investigate textile worker complaints about respiratory symptoms experienced while working in the mills. Investigators were interested in whether occupational environment was related to prevalence of respiratory ailments associated with the disease byssinosis.\n\n:::{.panel-tabset}\n\n### Questions\n\n- Use logistic regression to model the probability of complaining based on workplace condition, years of employment, and smoking history. Include only up to two-way interaction effects.\n- Is there evidence of any two-way interactions at a significance level of 0.10?\n- Generate an interaction plot for these cases.\n- Generate the main effects using contrast statements.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts=c(\"contr.treatment\",\"contr.poly\"))\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'car' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'carData' was built under R version 4.6.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_glm <- glm(cbind(yes,no)~Work*Years + Work*Smoking + Years*Smoking,\n               data=dat,family=\"binomial\")\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(yes, no) ~ Work * Years + Work * Smoking + \n    Years * Smoking, family = \"binomial\", data = dat)\n\nCoefficients:\n                          Estimate Std. Error z value Pr(>|z|)    \n(Intercept)               -4.52127    0.27984 -16.157  < 2e-16 ***\nWorkDusty                  1.83929    0.37561   4.897 9.74e-07 ***\nYearsGreater10             0.03291    0.35754   0.092   0.9267    \nSmokingYes                 0.03433    0.34262   0.100   0.9202    \nWorkDusty:YearsGreater10   0.53710    0.35213   1.525   0.1272    \nWorkDusty:SmokingYes       0.69408    0.38654   1.796   0.0726 .  \nYearsGreater10:SmokingYes  0.37047    0.38834   0.954   0.3401    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 285.91881  on 7  degrees of freedom\nResidual deviance:   0.69434  on 1  degrees of freedom\nAIC: 51.212\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(mod_glm,test.statistic = \"Wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: cbind(yes, no)\n              Df    Chisq Pr(>Chisq)    \nWork           1 235.9077  < 2.2e-16 ***\nYears          1  12.9074  0.0003273 ***\nSmoking        1   8.9631  0.0027549 ** \nWork:Years     1   2.3264  0.1271922    \nWork:Smoking   1   3.2242  0.0725566 .  \nYears:Smoking  1   0.9101  0.3400949    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n- Main Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm_work <- emmeans(mod_glm,~Work,type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_work\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Work        prob      SE  df asymp.LCL asymp.UCL null z.ratio p.value\n Not Dusty 0.0122 0.00163 Inf   0.00937    0.0158  0.5 -32.395 <0.0001\n Dusty     0.1256 0.01520 Inf   0.09866    0.1587  0.5 -13.979 <0.0001\n\nResults are averaged over the levels of: Years, Smoking \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\n# main effect\ncontrast_list <- list(main.effect = c(-1,1))\ncontrast(emm_work,method=contrast_list,infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value\n main.effect       11.6 2.26 Inf      7.96        17    1  12.646 <0.0001\n\nResults are averaged over the levels of: Years, Smoking \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_years <- emmeans(mod_glm,~Years,type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_years\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Years      prob      SE  df asymp.LCL asymp.UCL null z.ratio p.value\n Less10    0.032 0.00440 Inf    0.0244    0.0418  0.5 -23.974 <0.0001\n Greater10 0.051 0.00627 Inf    0.0400    0.0648  0.5 -22.549 <0.0001\n\nResults are averaged over the levels of: Work, Smoking \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\n# main effect\ncontrast_list <- list(main.effect = c(-1,1))\ncontrast(emm_years,method=contrast_list,infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n main.effect       1.63 0.311 Inf      1.12      2.37    1   2.549  0.0108\n\nResults are averaged over the levels of: Work, Smoking \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n\n```{.r .cell-code}\nemm_smoking <- emmeans(mod_glm,~Smoking,type=\"response\",infer=T)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_smoking\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Smoking   prob      SE  df asymp.LCL asymp.UCL null z.ratio p.value\n No      0.0307 0.00488 Inf    0.0225    0.0419  0.5 -21.086 <0.0001\n Yes     0.0529 0.00523 Inf    0.0436    0.0642  0.5 -27.633 <0.0001\n\nResults are averaged over the levels of: Work, Years \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\n# main effect\ncontrast_list <- list(main.effect = c(-1,1))\ncontrast(emm_smoking,method=contrast_list,infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n main.effect       1.76 0.342 Inf       1.2      2.58    1   2.918  0.0035\n\nResults are averaged over the levels of: Work, Years \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n- Interaction\n\nThe `Anova()` function already has the Wald test. Let's see if we can re-create one of the interactions using the `contrast()` and `test()` functions. Note that the interaction null hypothesis can be interpreted as \n\n$$\nH_0: \\mu_{Dusty,No}-\\mu_{NDusty,No} - (\\mu_{Dusty,Yes}-\\mu_{NDusty,Yes}) = 0\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm_interaction <- emmeans(mod_glm,~Work*Smoking,type=\"response\")\nemm_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Work      Smoking   prob      SE  df asymp.LCL asymp.UCL\n Not Dusty No      0.0109 0.00232 Inf   0.00721    0.0166\n Dusty     No      0.0834 0.01890 Inf   0.05307    0.1287\n Not Dusty Yes     0.0136 0.00223 Inf   0.00984    0.0187\n Dusty     Yes     0.1849 0.01880 Inf   0.15080    0.2247\n\nResults are averaged over the levels of: Years \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(emm_interaction)\n```\n\n::: {.cell-output-display}\n![](Chapter8_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ncontrast_list <- list(interaction = c(-1,1,1,-1))\ncontrast(emm_interaction,method=contrast_list,infer=T,type=\"response\") |> test(joint=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n df1 df2 F.ratio Chisq p.value\n   1 Inf   3.224 3.224  0.0726\n```\n\n\n:::\n:::\n\n\n\n\n### SAS Code\n\n```{.r}\nproc logistic data=byss;\nfreq count;\nclass work years(ref=first) smoke(ref=first) /param=ref;\nmodel status(event=last) = work|years|smoke@2 /scale=none aggregate;\neffectplot interaction (x=work) / at(smoke=all years=all) link noobs;\noddsratios work;\ncontrast 'work' work 1;\ncontrast 'years' years 1;\ncontrast 'smoke' smoke 1;\nrun;\n```\n\n\n### Answer\n\nWe have evidence of an interaction between work conditions and smoking status ($Work*Smoke$) ($\\chi^2_1$=3.22,p = 0.07) at the 0.10 level of significance, which means we need to be careful in interpreting the main effect of work conditions and smoking status.\n\nWe can interpret the main effect of the years of employment. Those who work more than 10 years have odds of complaining about byssinosis disease that are 1.6 times that of those who worked less than 10 years.\n:::\n\n## Exercise\n\nThe following data come from a study on urinary tract infections. Investigators applied three treatments to patients who had either a complicated or uncomplicated diagnosis of urinary tract infection. Since complicated cases of urinary tract infections are difficult to cure, investigators were interested in whether the pattern of treatment differences is the same across diagnoses.\n\n- Are we interested in main effects or interaction?\n- Is there a significant interaction effect?\n- Calculate the odds ratio between the diagnoses of UTI for different treatments.\n- Generate plots for the interaction and odds ratios.\n\n\n\n::: {.panel-tabset}\n### Table\n\n![](img/uti_C8.png)\n\n### SAS Data Set\n\n```{.r}\ndata uti;\ninput diagnosis : $13. treatment $ response $ count @@;\ndatalines;\ncomplicated A cured 78 complicated A not 28\ncomplicated B cured 101 complicated B not 11\ncomplicated C cured 68 complicated C not 46\nuncomplicated A cured 40 uncomplicated A not 5\nuncomplicated B cured 54 uncomplicated B not 5\nuncomplicated C cured 34 uncomplicated C not 6\n;\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuti <- expand.grid(Treatment=c(\"A\",\"B\",\"C\"),\n            Diagnosis=c(\"Complicated\",\"Uncomplicated\"))\n\nuti$yes=c(78,101,68,40,54,34)\nuti$no = c(28,11,46,5,5,6)\n\nuti\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment     Diagnosis yes no\n1         A   Complicated  78 28\n2         B   Complicated 101 11\n3         C   Complicated  68 46\n4         A Uncomplicated  40  5\n5         B Uncomplicated  54  5\n6         C Uncomplicated  34  6\n```\n\n\n:::\n:::\n\n\n:::\n\n## Exercise\n\nThe following data come from a study on urinary tract infections. Investigators applied three treatments to patients who had either a complicated or uncomplicated diagnosis of urinary tract infection. Since complicated cases of urinary tract infections are difficult to cure, investigators were interested in whether the pattern of treatment differences is the same across diagnoses.\n\n- Are we interested in main effects or interaction?\n- Is there a significant interaction effect?\n- Calculate the odds ratio between the diagnoses of UTI for different treatments.\n- Generate plots for the interaction and odds ratios.\n\n\n\n::: {.panel-tabset}\n### SAS Code\n\n```{.r}\ndata uti;\ninput diagnosis : $13. treatment $ response $ count @@;\ndatalines;\ncomplicated A cured 78 complicated A not 28\ncomplicated B cured 101 complicated B not 11\ncomplicated C cured 68 complicated C not 46\nuncomplicated A cured 40 uncomplicated A not 5\nuncomplicated B cured 54 uncomplicated B not 5\nuncomplicated C cured 34 uncomplicated C not 6\n;\n\nproc logistic data=uti order=data;\nfreq count;\nclass diagnosis treatment /param=ref;\nmodel response(event='cured') = diagnosis|treatment /scale=none aggregate;\neffectplot interaction (x=treatment) / at(treatment=all) link noobs;\noddsratios diagnosis;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(cbind(yes,no)~Diagnosis*Treatment,\n               data=uti,\n               family=\"binomial\")\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(yes, no) ~ Diagnosis * Treatment, family = \"binomial\", \n    data = uti)\n\nCoefficients:\n                                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                         1.0245     0.2203   4.650 3.31e-06 ***\nDiagnosisUncomplicated              1.0549     0.5230   2.017  0.04369 *  \nTreatmentB                          1.1927     0.3865   3.086  0.00203 ** \nTreatmentC                         -0.6336     0.2915  -2.174  0.02973 *  \nDiagnosisUncomplicated:TreatmentB  -0.8926     0.7700  -1.159  0.24634    \nDiagnosisUncomplicated:TreatmentC   0.2888     0.7114   0.406  0.68476    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 4.4473e+01  on 5  degrees of freedom\nResidual deviance: 1.1990e-14  on 0  degrees of freedom\nAIC: 36.423\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: cbind(yes, no)\n                    LR Chisq Df Pr(>Chisq)    \nDiagnosis            11.7183  1  0.0006189 ***\nTreatment            28.1137  2  7.856e-07 ***\nDiagnosis:Treatment   2.5147  2  0.2844080    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nTo calculate the conditional odds ratios, we can manually add contrast statements:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm_interaction <- emmeans(mod_glm,~Diagnosis*Treatment,type=\"response\",infer=T)\nemm_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Diagnosis     Treatment  prob     SE  df asymp.LCL asymp.UCL null z.ratio\n Complicated   A         0.736 0.0428 Inf     0.644     0.811  0.5   4.650\n Uncomplicated A         0.889 0.0468 Inf     0.759     0.953  0.5   4.384\n Complicated   B         0.902 0.0281 Inf     0.831     0.945  0.5   6.983\n Uncomplicated B         0.915 0.0363 Inf     0.812     0.964  0.5   5.090\n Complicated   C         0.596 0.0459 Inf     0.504     0.682  0.5   2.047\n Uncomplicated C         0.850 0.0565 Inf     0.704     0.931  0.5   3.917\n p.value\n <0.0001\n <0.0001\n <0.0001\n <0.0001\n  0.0406\n <0.0001\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast_list <- list(OR.at.A = c(1,-1,0,0,0,0),\n                      OR.at.B=c(0,0,1,-1,0,0),\n                      OR.at.C = c(0,0,0,0,1,-1))\n\ncontrast(emm_interaction,method=contrast_list,infer=T,type=\"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n OR.at.A       0.348 0.182 Inf     0.125     0.971    1  -2.017  0.0437\n OR.at.B       0.850 0.480 Inf     0.281     2.573    1  -0.287  0.7739\n OR.at.C       0.261 0.126 Inf     0.101     0.671    1  -2.787  0.0053\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nWe are more interested in the interaction effect.\n\nThere is no significant interaction effect between diagnosis and treatment ($\\chi^2_2$=0.28, p=0.28).\n\n![Odds Ratios](img/odds_C8.png)\n:::\n\n## Continuous and Ordinal Explanatory Variables\n\nSometimes, continuous explanatory variables are unique in the data set. The sample size requirements for the goodness-of-fit tests will not be satisfied.\n  - Income\n  - Age\n  - Years in University\n\n::: callout-note\nThere should be at least 5 observations for the rarer outcome per parameter in the full model. If there are 50 observations of the rarer outcome, then the maximum number of parameters supported is 10.\n:::\n\n:::callout-note\nIn `SAS`, continuous variables should **NOT** be included in the class statement.\n:::\n\n## `SAS` Model Selection: Logistic Regression \n\n- We can use the residual score statistic $Q_{RS}$ to determine up to what extent does the residuals from the model are linearly associated with other potential explanatory variables.\n  - DF: difference in number of parameters between models\n  \n\n- The `SELECTION=FORWARD` option should be included in the `MODEL` statement. The `LOGISTIC` procedure will then start from an intercept model and build it up to the most parsimonious model.\n  - The `INCLUDE` option tells SAS how many of the variables listed should always be included in the model.\n\n## `SAS Model Selection: Logistic Regression\n\n- SAS also provides the Hosmer and Lemeshow Goodness-of-Fit test that tests the adequacy for these data by including the `lackfit` option.\n  - Null hypothesis: The model is adequate, i.e., the residuals are explained by the model.\n- The UNITS option specifies at what increment of the continuous variable will SAS calculate the odds ratios.\n\n## `R` Model Selection\n\nThe function `step()` can perform forward selection, i.e. adding more predictors and interaction terms to the model until we reach the full model, in `R`. The model selection will be based on the Akaike Information Criteria (AIC), by default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_model <- glm(dependent~independent1,data=sampledata,family=\"binomial\")\nfull_model <- glm(dependent~independent1+independent2 + covariates,data=sampledata,family=\"binomial\")\n\nstep(base_model,full_model, direction=\"forward\")\nanova(base_model,full_model)\n```\n:::\n\n\n## `R`: Hosmer and Lemeshow test\n\nThe Hosmer and Lemeshow goodness-of-fit test tests the adequacy of the model for the provided data. \n\n::: callout-note\nThe null hypothesis of the Hosmer and Lemeshow test is that the model is adequate, i.e. the residuals are explained by the current model.\n:::\n\nThe Hosmer and Lemeshow test can be performed using the `performance_hosmer()` function in the `performance` package in `R`.\n\n\n## Example\n\nThe data set CORONARY is from the same study on coronary artery disease as previously analyzed; in addition, the continuous variable AGE is an explanatory variable. The variable ECG is now treated as an ordinal variable, with values 0, 1, and 2. ECG is coded 0 if the ST segment depression is less than 0.1, 1 if it equals 0.1 or higher but less than 0.2, and 2 if the ST segment depression is greater than or equal to 0.2. The variable AGE is age in years.\n\n  - What is the resulting logistic model?\n  - Calculate the odds ratio for patients that differ in age by 10 years.\n\n### SAS Data Set\n\n```{.r}\n\ndata coronary;\ninput sex ecg age ca @@ ;\ndatalines;\n0 0 28 0 1 0 42 1 0 1 46 0 1 1 45 0\n0 0 34 0 1 0 44 1 0 1 48 1 1 1 45 1\n0 0 38 0 1 0 45 0 0 1 49 0 1 1 45 1\n0 0 41 1 1 0 46 0 0 1 49 0 1 1 46 1\n0 0 44 0 1 0 48 0 0 1 52 0 1 1 48 1\n0 0 45 1 1 0 50 0 0 1 53 1 1 1 57 1\n0 0 46 0 1 0 52 1 0 1 54 1 1 1 57 1\n0 0 47 0 1 0 52 1 0 1 55 0 1 1 59 1\n0 0 50 0 1 0 54 0 0 1 57 1 1 1 60 1\n0 0 51 0 1 0 55 0 0 2 46 1 1 1 63 1\n0 0 51 0 1 0 59 1 0 2 48 0 1 2 35 0\n0 0 53 0 1 0 59 1 0 2 57 1 1 2 37 1\n0 0 55 1 1 1 32 0 0 2 60 1 1 2 43 1\n0 0 59 0 1 1 37 0 1 0 30 0 1 2 47 1\n0 0 60 1 1 1 38 1 1 0 34 0 1 2 48 1\n0 1 32 1 1 1 38 1 1 0 36 1 1 2 49 0\n0 1 33 0 1 1 42 1 1 0 38 1 1 2 58 1\n0 1 35 0 1 1 43 0 1 0 39 0 1 2 59 1\n0 1 39 0 1 1 43 1 1 0 42 0 1 2 60 1\n0 1 40 0 1 1 44 1\n;\n```\n\n### R Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\necg <- read.csv(\"ECG_withage.csv\")\nglimpse(ecg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 78\nColumns: 4\n$ Sex <int> 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ~\n$ ECG <int> 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, ~\n$ Age <int> 28, 42, 46, 45, 34, 44, 48, 45, 38, 45, 49, 45, 41, 46, 49, 46, 44~\n$ CA  <int> 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, ~\n```\n\n\n:::\n:::\n\n\n\n\n## Example\n\nThe data set CORONARY is from the same study on coronary artery disease as previously analyzed; in addition, the continuous variable AGE is an explanatory variable. The variable ECG is now treated as an ordinal variable, with values 0, 1, and 2. ECG is coded 0 if the ST segment depression is less than 0.1, 1 if it equals 0.1 or higher but less than 0.2, and 2 if the ST segment depression is greater than or equal to 0.2. The variable AGE is age in years.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc logistic descending;\nmodel ca=sex ecg age ecg*ecg age*age\nsex*ecg sex*age ecg*age /selection=forward include=3 details lackfit; # <1>\nunits age=10; # <2>\nrun;\n```\n\n1. `include=3` indicates we are including the first three variables in the model. In this case, it's sex, ecg, and age.\n2. Looks at the odds ratio due to a 10-point difference in age.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(CA~Sex+ECG+Age,data=ecg,family=\"binomial\")\nmod_full <- glm(CA~Sex+ECG+Age + ECG:ECG + Age:Age + Sex:ECG + Sex:Age + ECG:Age,data=ecg,family=\"binomial\")\nstep(mod_glm,mod_full,direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=94.81\nCA ~ Sex + ECG + Age\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = CA ~ Sex + ECG + Age, family = \"binomial\", data = ecg)\n\nCoefficients:\n(Intercept)          Sex          ECG          Age  \n   -5.64176      1.35643      0.87320      0.09285  \n\nDegrees of Freedom: 77 Total (i.e. Null);  74 Residual\nNull Deviance:\t    107.9 \nResidual Deviance: 86.81 \tAIC: 94.81\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod_glm,mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: CA ~ Sex + ECG + Age\nModel 2: CA ~ Sex + ECG + Age + ECG:ECG + Age:Age + Sex:ECG + Sex:Age + \n    ECG:Age\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1        74     86.811                     \n2        71     85.522  3   1.2891   0.7317\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = CA ~ Sex + ECG + Age, family = \"binomial\", data = ecg)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept) -5.64176    1.80614  -3.124  0.00179 **\nSex          1.35643    0.54645   2.482  0.01306 * \nECG          0.87320    0.38433   2.272  0.02309 * \nAge          0.09285    0.03509   2.646  0.00815 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 107.926  on 77  degrees of freedom\nResidual deviance:  86.811  on 74  degrees of freedom\nAIC: 94.811\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(performance)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'performance' was built under R version 4.6.1\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance_hosmer(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Hosmer-Lemeshow Goodness-of-Fit Test\n\n  Chi-squared: 4.421\n           df: 8    \n      p-value: 0.817\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSummary: model seems to fit well.\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemm_sex <- emmeans(mod_glm,~Age,type=\"response\",at=list(Age=c(50,60)),infer=T)\nemm_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Age  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value\n  50 0.581 0.0695 Inf     0.442     0.709  0.5   1.150  0.2503\n  60 0.778 0.0913 Inf     0.555     0.908  0.5   2.374  0.0176\n\nResults are averaged over the levels of: Sex \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \nTests are performed on the logit scale \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(emm_sex,method=\"revpairwise\",infer=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast      odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value\n Age60 / Age50       2.53 0.888 Inf      1.27      5.03    1   2.646  0.0081\n\nResults are averaged over the levels of: Sex \nConfidence level used: 0.95 \nIntervals are back-transformed from the log odds ratio scale \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThe logistic model is as follows:\n\n$$\nlogit(\\hat{\\theta}) = -5.64 + 1.35*Sex + 0.873*ECG +0.09*Age\n$$\nThe odds of developing a coronary artery disease in patients older than 10 years increases by 2.53 (95% CI: 1.27-5.03) times.\n:::\n\n## Exercise\n\nChapter8-Corn.csv includes the data of 82 plants from a randomized controlled trial that tests the effect of a new formulation of pesticide as well as the effect of using cover crops in planting corn. The farmers are also interested if the yield (measured in kg) is associated to the plant discoloration. \n\n- Use the forward selection approach to determine if an interaction term between cover crop and pesticide needs to be included in the model.\n- What is the resulting logistic model?\n- Calculate the odds ratio for corn plants that have a yield difference of 2 kg.\n\n## Exercise\n\nChapter8-Corn.csv includes the data of 82 plants from a randomized controlled trial that tests the effect of a new formulation of pesticide as well as the effect of using cover crops in planting corn. The farmers are also interested if the yield (measured in kg) is associated to the plant discoloration. \n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc logistic data=corn;\nclass pesticide (ref=\"No\") covercrop (ref=\"No\");\nmodel Discolored(event=\"Yes\") = pesticide covercrop yield pesticide*covercrop/selection=forward include=3 details lackfit;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorn <- read.csv(\"Chapter8-Corn.csv\",stringsAsFactors = TRUE)\nglimpse(corn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 82\nColumns: 4\n$ Pesticide  <fct> Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes,~\n$ CoverCrop  <fct> Yes , Yes , Yes , Yes , Yes , Yes , Yes , Yes , Yes , Yes ,~\n$ Yield      <dbl> 2.3, 2.5, 2.0, 1.2, 2.5, 2.5, 1.0, 2.3, 1.9, 2.2, 1.2, 1.5,~\n$ Discolored <fct> Yes, No, Yes, No, No, No, No, No, No, Yes, Yes, Yes, No, No~\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(Discolored~Pesticide + CoverCrop + Yield, data=corn, family=\"binomial\")\nmod_interaction <- glm(Discolored~Pesticide + CoverCrop + Yield + Pesticide:CoverCrop, data=corn, family=\"binomial\") \n\nstep(mod_glm,mod_interaction,direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=94.51\nDiscolored ~ Pesticide + CoverCrop + Yield\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = Discolored ~ Pesticide + CoverCrop + Yield, family = \"binomial\", \n    data = corn)\n\nCoefficients:\n  (Intercept)   PesticideYes  CoverCropYes           Yield  \n       0.7951         1.3635        -2.2028        -0.2744  \n\nDegrees of Freedom: 81 Total (i.e. Null);  78 Residual\nNull Deviance:\t    113.5 \nResidual Deviance: 86.51 \tAIC: 94.51\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod_glm,mod_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: Discolored ~ Pesticide + CoverCrop + Yield\nModel 2: Discolored ~ Pesticide + CoverCrop + Yield + Pesticide:CoverCrop\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1        78     86.509                     \n2        77     86.432  1 0.077057   0.7813\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance_hosmer(mod_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Hosmer-Lemeshow Goodness-of-Fit Test\n\n  Chi-squared: 6.544\n           df: 8    \n      p-value: 0.587\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSummary: model seems to fit well.\n```\n\n\n:::\n:::\n\n\n\n\n### Answer\n\nThere was no evidence to indicate that a pesticide*covercrop interaction needed to be included ($Q_{RS} = 0.08, p=0.78$). The Hosmer-Lemeshow goodness-of-fit test also provides no evidence against model adequacy ($\\chi^2 = 6.9, p=0.55$). \n\nThe resulting logistic model is:\n\n$$\nlogit(\\theta) = 0.38 - 0.68*Pesticide - 1.10 * CoverCrop - 0.27*Yield\n$$\nThe odds of discoloration decreases by 0.42 (1-0.58) times when the yield increases by 2 kg.\n:::\n\n# Model Diagnostics\n\n## Diagnostics\n\n- We are interested in how a model fits our data and the lack of fit.\n\n  - Lack of fit: Should we still consider other variables to include in the model?\n\n- Model fit: Pearson chi-square and deviance chi-square tests (`SAS`)\n- Lack of fit: Pearson *residuals* and deviance *residuals*\n\n\n::: {.callout-note}\n- Pearson residuals look at the difference between the observed and expected occurrences in a group. A value of 2 is usually indicative of a lack of fit.\n- Deviance residuals are the components that make up the deviance statistic\n- Likelihood residuals: weighted average of standardized Pearson and Deviance residuals\n:::\n\n## Diagnostics\n\n- These residuals can be viewed in graphical form.\n\n:::callout-tip\nIn SAS, we can view the residual plots by specifying `PLOTS=INFLUENCE` in the `PROC LOGISTIC` statement. `stdres` specifies plots for standardized residuals\n\n```{.r}\nproc logistic plots(label)=influence(unpack stdres);\n```\n:::\n\n::: callout-tip\nIn `R`, we can use the `check_model` function in the `performance` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(mod_glm,\n            check=c(\"pp_check\", \"binned_residuals\",\"vif\",\"outliers\"))\n```\n:::\n\n\n:::\n## Example\n\nConsider a modified version of the UTI data set. Generate the standardized residual plot, likelihood residual plot, and the Pearson chi-square residual plot.\n\n```{.r}\ndata uti2;\ninput diagnosis : $13. treatment $ response trials;\ndatalines;\ncomplicated A 78 106\ncomplicated B 101 112\ncomplicated C 68 114\nuncomplicated A 40 45\nuncomplicated B 54 59\nuncomplicated C 34 40\n;\n```\n\n::: callout-note\nIn `R`, the previous `uti` data set can still be used.\n:::\n\n## Example\n\nConsider a modified version of the UTI data set. Generate the standardized residual plot, likelihood residual plot, and the Pearson chi-square residual plot.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r }\nproc logistic data=uti2 \nplots(label)=influence(unpack stdres); #<1>\nclass diagnosis treatment / param=ref;\nmodel response/trials = diagnosis treatment; # <2>\nrun;\n```\n\n1. `plots=influence` yield all residual plots. `stdres` generates the standardized residual plot.\n2. The model can also be expressed in terms of # of success/sample size;\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_glm <- glm(cbind(yes,no)~Treatment+Diagnosis, \n               data=uti,\n               family=\"binomial\")\nlibrary(performance)\ncheck_model(mod_glm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'lme4':\n  method           from\n  na.action.merMod car \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Chapter8_files/figure-pdf/unnamed-chunk-31-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n### Answer\n\nThe plots indicate good fit and lack of multicollinearity.\n:::\n\n## Alternative Estimation Methods\n\n- We have been using maximum likelihood (ML) estimation to estimate values of $\\beta$, which leads to odds ratio estimates.\n  - What if there are no successes or failures in your data? (Complete separation)\n  - What if there is a small number of successes in the data?\n  - What if the sample size is small?\n- These conditions might yield non-converging solutions\n  - Infinite odds ratios\n  - Nonsensical odds ratio estimates\n\n## Complete Separation\n\n![Complete Separation: One level includes all successes or all failures.](img/complete_C8.png)\n\n::: callout-note\nIf nearly all the observations have a probability of 1 of being allocated to the correct response\ngroup, then the data configuration may be one of **quasi-complete separation**.\n:::\n\n## Dealing with non-convergence\n\n- Exact tests\n  - Non-convergence due to small cell counts\n  - Quasi-complete separation\n\n::: callout-tip\nThe `EXACT` statement calculates the exact p-values for each variable/factor. Adding a `joint` option performs joint tests for the variables included. We use the results of the joint _probability_ tests as its results are analogous to the Fisher's exact test.\n:::\n\n::: callout-warning\nThe output of the exact statement typically yields a one-sided p-value for median unbiased estimates and one-sided confidence intervals. To get a two-sided 95% confidence interval, we can use a one-sided 97.5% confidence interval by specifying `alpha = 0.025`.\n:::\n\n- Firth’s penalized likelihood\n  - Complete separation/quasi-complete separation when there are continuous explanatory variables \n  - Applies a penalty in the likelihood function.\n\n\n::: callout-tip\nAdding the `FIRTH` option to the model statement tells SAS to use the Firth penalized likelihood.\n`CLPARM=PL` uses the likelihood profile consistent with the Firth penalized likelihood method.\n:::\n\n## Example\n\nConsider the following data set:\n\n  - Does this display complete separation, quasi-complete separation, or neither?\n  - Calculate exact p-values for the effect of treatments A and B as well as the joint tests.\n  - Calculate exact estimates for the odds ratio.\n\n```{.r}\ndata preclinical;\ninput treatA $ treatB $ response $ count @@;\ndatalines;\nno no yes 0 no no no 0\nyes no yes 8 yes no no 0\nno yes yes 0 no yes no 2\nyes yes yes 21 yes yes no 6\n;\n```\n\n## Example\n\nConsider the following data set:\n\n  - Does this display complete separation, quasi-complete separation, or neither?\n  - Calculate exact p-values for the effect of treatments A and B as well as the joint tests.\n  - Calculate exact estimates for the odds ratio.\n\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc logistic data=preclinical;\nfreq count;\nclass treatA (ref=\"no\") treatB (ref=\"no\") /param=ref ;\nmodel response (event=\"yes\") = treatA treatB ;\nexact treatA treatB /joint estimate=both alpha=0.025;\nrun;\n```\n\n### Answer\n\nThe data shows quasi-complete separation. \n\nThe odds of a successful response is for those who received Treatment A is 7.06 (CI: 0.52, $\\infty$) times that of those who did not receive Treatment A. The exact p-value is 0.07.\n\nThe odds of a successful response is for those who received Treatment B is 0.35 (CI: 0, 2.85) times that of those who did not receive Treatment B.The exact p-value is 0.18.\n:::\n\n\n## Example: Complete Separation\n\nConsider the following data set:\n\n  - Does this display complete separation, quasi-complete separation, or neither?\n  - Calculate exact p-values for the effect of treatments A and B as well as the joint tests.\n  - Calculate estimates for the odds ratio from the Firth penalized likelihood approach.\n\n```{.r}\ndata complete;\ninput gender region count response @@;\ndatalines;\n0 0 0 1 0 0 5 0\n0 1 1 1 0 1 0 0\n1 0 0 1 1 0 175 0\n1 1 53 1 1 1 0 0\n;\n```\n\n\n## Example: Complete Separation\n\nConsider the following data set:\n\n  - Does this display complete separation, quasi-complete separation, or neither?\n  - Calculate exact p-values for the effect of treatments A and B as well as the joint tests.\n  - Calculate estimates for the odds ratio from the Firth penalized likelihood approach.\n\n::: {.panel-tabset}\n\n### SAS Code\n```{.r}\nproc logistic data=complete;\nfreq count;\nmodel response = gender region / firth clparm=pl;\nexact gender region/estimate=both;\nrun;\n```\n\n### Answer\n\nBased on the exact tests, there appears to be no effect of gender (p=0.5). However, there is an effect of region.\n\nThere is complete separation in region. We can use the penalized likelihood approach to calculate odds ratio estimates. The estimated odds ratio between region=1 and region = 0 is 10.5 (95% CI: 7.55, 16.26).\n\n:::\n\n# The `GENMOD` procedure\n\n## The `GENMOD` procedure\n\n- The `GENMOD` procedure uses generalized estimating equations in performing logistic regression when the responses are correlated.\n  - Similar syntax as the `LOGISTIC` procedure.\n\n- Reference levels are included in the estimates, but are automatically zeroed out by the `GENMOD` procedure.\n  - You can set the reference levels by applying the `ref` option to each variable in the class statement.\n\n### Sample Code\n\n```{.r}\nproc genmod;\nfreq count;\nclass A B;\nmodel response = A B A*B/link=logit dist=binomial type3 aggregate; # <1>\nestimate '[NAME OF CONTRAST]' A 1 -1/exp cl; # <2>\nrun;\n```\n\n1. We need to specify the link function and the distribution as `GENMOD` can be used to model other distributions like Poisson. `type3` invokes the Type III tests of fixed effects, which looks at partial testing of each effect.\n2. `GENMOD` does not output odds ratio by default. Hence, we use the `estimate` statement. The `estimate` statement follows the `contrast` statement, but since it calculates effect sizes, fractions cannot be eliminated by multiplying a factor unlike contrast statements.\n\n\n## Example\n\nConsider the UTI example. Perform a logistic regression analysis using PROC GENMOD.\n\n## Example \n\nConsider the UTI example. Perform a logistic regression analysis using PROC GENMOD.\n\n### SAS Code\n\n```{.r}\nproc genmod data=uti;\nfreq count;\nclass diagnosis treatment;\nmodel response = diagnosis treatment /link=logit dist=binomial type3 aggregate;\ncontrast 'treatment' treatment 1 0 -1 ,\n\t\t\t\t\t treatment 0 1 -1; # <1>\ncontrast 'A-B' treatment 1 -1 0;\ncontrast 'A-C' treatment 1 0 -1;\nestimate 'odds ratio of diagnosis' diagnosis 1 -1/exp;\nrun;\n```\n\n1. This contrast should yield the same values as that of the Type 3 test for treatment.\n\n## Exercise\n\nConsider the Byssinosis example. Perform a logistic regression analysis by applying an interaction model that includes up to two-way interactions in PROC GENMOD.\n\n- Test for the main effect of workplace condition using contrasts. Compare the chi-square and p-values obtained through the Type 3 tests.\n- Test for the interaction of years of employment and smoking for dusty workplace conditions.\n- Calculate the odds ratio of developing byssinosis between the two work conditions.\n\n### SAS Data Set\n```{.r}\ndata byss;\ninput work $ years $ smoke $ status $ count @@;\ndatalines ;\ndusty <10 yes yes 30 dusty <10 yes no 203\ndusty <10 no yes 7 dusty <10 no no 119\ndusty >=10 yes yes 57 dusty >=10 yes no 161\ndusty >=10 no yes 11 dusty >=10 no no 81\nnot <10 yes yes 14 not <10 yes no 1340\nnot <10 no yes 12 not <10 no no 1004\nnot >=10 yes yes 24 not >=10 yes no 1360\nnot >=10 no yes 10 not >=10 no no 986\n;\n```\n\n## Exercise\n\nConsider the Byssinosis example. Perform a logistic regression analysis by applying an interaction model that includes up to two-way interactions in PROC GENMOD.\n\n:::{.panel-tabset}\n### SAS Code\n```{.r}\nproc genmod data=byss;\nfreq count;\nclass work years smoke;\nmodel status(event='yes') = work years smoke work*years work*smoke years*smoke /link=logit dist=binomial type3 aggregate;\ncontrast 'work' work 1 -1; * same as the Type 3 Tests;\ncontrast 'interaction' work*years 1 -1 -1 1;\nestimate 'OR for work' work 1 -1/e exp;\nrun; \n```\n\n### Answer\n\nThe workplace effect has a $\\chi^2$ = 114.10, p<.0001. There is sufficient evidence of a workplace main effect.\n\nThe interaction term between years of work and smoking yielded a $\\chi^2= 0.91$, p=0.34. There is insufficient evidence of a workplace main effect.\n\nThe estimated odds of developing byssinosis for dusty work places is 11.6 (95% CI: 7.96, 17.03) times that of non-dusty places \n\n\n:::\n\n",
    "supporting": [
      "Chapter8_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}