<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Miguel Fudolig">
  <title>EAB770: Applied Statistical Methods for Categorical Data – EAB 770 - Chapter 8</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-146a52615c86749306b5caa224a9b489.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">EAB 770 - Chapter 8</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Miguel Fudolig 
</div>
</div>
</div>

</section>
<section>
<section id="chapter-8-logistic-regression-dichotomous-response" class="title-slide slide level1 center">
<h1>Chapter 8: Logistic Regression: Dichotomous Response</h1>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<ul>
<li>Dichotomous Explanatory Variables</li>
<li>Qualitative Explanatory Variables</li>
<li>Continuous and Ordinal Explanatory Variables</li>
<li>Diagnostics</li>
<li>Likelihood methods</li>
</ul>
</section>
<section id="review-mantel-haenszel-tests" class="slide level2">
<h2>Review: Mantel-Haenszel Tests</h2>
<p>Mantel-Haenszel statistics investigate association between two variables with adjustment for a stratification variable. - General association - Location shifts for means - Linear/increasing trends</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Mantel-Haenszel Tests do not involve statistical models, and therefore can’t be used for estimation for effect sizes or prediction. Furthermore, these tests cannot accommodate for continuous variables as predictors.</p>
</div>
</div>
</div>
</section>
<section id="logistic-regression" class="slide level2">
<h2>Logistic Regression</h2>
<p>Statistical modeling method that enables us to make inferences, estimate/predict outcome variables, and describe the relationship between a categorical response variable and multiple explanatory variables. Possible applications include epidemiology, medical research, agronomy, and social science research.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Continuous explanatory variables can be included in the analysis, unlike in Mantel-Haenszel tests. Responses can be dichotomous or polytomous (more than two levels).</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="dichotomous-response" class="title-slide slide level1 center">
<h1>Dichotomous Response</h1>

</section>
<section id="logistic-regression-model" class="slide level2">
<h2>Logistic Regression: Model</h2>
<p>Logistic regression enables us to write a model for the probability of success for each group.</p>
<p>Let <span class="math inline">\(\theta_{mi}\)</span> be the probability of success of the <span class="math inline">\(i^{th}\)</span> group in the <span class="math inline">\(m^{th}\)</span> strata.The logistic model can be used to describe the variation among {<span class="math inline">\(\theta_{mi}\)</span>}</p>
<p><span class="math display">\[
\theta_{mi} = \frac{1}{1+\exp[-\eta_{mi}]}
\]</span></p>
</section>
<section id="logistic-regression-model-1" class="slide level2">
<h2>Logistic Regression: Model</h2>
<p>Where</p>
<p><span class="math display">\[
\eta_{mi} = \alpha + \sum_{k=1}^t \beta_kx_{mik}
\]</span></p>
<p>and <span class="math inline">\(t\)</span> is the number of explanatory variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\eta_{mi}\)</span> is referred to as the linear predictor of the model.</p>
</div>
</div>
</div>
</section>
<section id="logistic-regression-model-2" class="slide level2">
<h2>Logistic Regression: Model</h2>
<p>Using algebra, we can invert the equation to the following form:</p>
<p><span class="math display">\[
\eta_{mi} = \alpha + \sum_{k=1}^t \beta_kx_{mik} = \log\left[\frac{\theta_{mi}}{1-\theta_{mi}}\right]
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\log\left[\frac{\theta_{mi}}{1-\theta_{mi}}\right]\)</span> is referred to as the <strong>logit</strong> transformation of <span class="math inline">\(\theta_{mi}\)</span>, which is the logarithm of the odds.</p>
<p>Other functions that can serve as a link function include the probit model and the complementary log-log model.</p>
</div>
</div>
</div>
</section>
<section id="odds-and-odds-ratios" class="slide level2">
<h2>Odds and Odds Ratios</h2>
<p>The odds of success for an individual in the <span class="math inline">\(m^{th}\)</span> strata and <span class="math inline">\(i^{th}\)</span> group can be calculated as</p>
<p><span class="math display">\[
\theta_{mi}/(1-\theta_{mi}) = e^{\eta_{mi}}
\]</span></p>
<p>The odds ratio between the <span class="math inline">\(i^{th}\)</span> and <span class="math inline">\(j^{th}\)</span> group in the <span class="math inline">\(m^{th}\)</span> strata can easily be calculated.</p>
<p><span class="math display">\[
OR = \frac{odds_{mj}}{odds_{mi}} = e^{\eta_{mj}}/e^{\eta_{mi}} = e^{\eta_{mj}-\eta_{mi}}
\]</span></p>
</section>
<section id="advantages" class="slide level2">
<h2>Advantages</h2>
<ul>
<li>The logit transformation enables us to monitor the change in log odds.</li>
<li>Easy to calculate odds ratio.</li>
<li>The linear predictor can take on values from <span class="math inline">\((-\infty,\infty)\)</span>, but the values of <span class="math inline">\(\theta_{mi}\)</span> will be constrained in [0,1].</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>If you used linear regression to model a proportion, it assumes that the response variable can be negative or above 1.</p>
</div>
</div>
</div>
</section>
<section id="fit-statistics" class="slide level2">
<h2>Fit Statistics</h2>
<ul>
<li>The model performance can be measured using the <strong>deviance</strong> and <strong>goodness-of-fit</strong> statistics.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Both use chi-square statistics to assess model fit.</p>
</div>
</div>
</div>
</section>
<section id="chi-square-statistics" class="slide level2">
<h2>Chi-square statistics</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Likelihood ratio chi-square measures the difference between two models by using the ratio of the two likelihoods as a chi-square statistic.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Pearson chi-square goodness of fit uses observed and expected values to test for a goodness of fit.</p>
</div>
</div>
</div>
</section>
<section id="chi-square-statistics-1" class="slide level2">
<h2>Chi-square statistics</h2>
<ul>
<li>If the chi-square statistic divided by the degrees of freedom is higher than one, then the data has some variation that is unaccounted for in the model.
<ul>
<li>This is called overdispersion</li>
</ul></li>
<li>The high ratio between the chi-square statistic and degrees of freedom can also mean that the data does not follow a binomial distribution well.
<ul>
<li>Heterogeneity</li>
</ul></li>
<li>Both cases are accounted for using generalized linear mixed models/generalized estimating equations.</li>
</ul>
</section>
<section id="chi-square-statistics-sample-size" class="slide level2">
<h2>Chi-square statistics: Sample Size</h2>
<p>Sample size guidelines for the chi-square assumption for these fit statistics include:</p>
<ul>
<li>Each group should have at least ten subjects.</li>
<li>80% of the predicted counts should be at least 5.</li>
<li>No 0 counts, remaining 20% of the counts should be above 2.</li>
<li>Failure to satisfy these assumptions means exact tests should be used.</li>
</ul>
</section>
<section id="chi-square-statistics-hypothesis-test" class="slide level2">
<h2>Chi-square statistics: Hypothesis Test</h2>
<p>The null hypothesis for both deviance and goodness-of-fit tests is that the departures of the observed data from the predicted values based on the model are random.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Failure to reject the null hypothesis means we have no evidence against good agreement between observed and predicted values based on the model.</p>
</div>
</div>
</div>
</section>
<section id="fit-statistics-1" class="slide level2">
<h2>Fit Statistics</h2>
<p>The Akaike Infomation Criterion (AIC) and the Bayesian Information Criterion (BIC)/Schwarz Criterion (SC) can also be used to assess model fit. Lower values of these criteria indicate better model fit.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>AIC predicts estimation error based on the provided model. BIC also predicts estimation error but uses a different penalization scheme for errors.</p>
<p>The AIC (or BIC) for the full model (intercept + covariates) should be lower than the AIC (or BIC) of the intercept-only model if the covariates are associated with the response.</p>
</div>
</div>
</div>
</section>
<section id="the-main-effect-model" class="slide level2">
<h2>The Main Effect Model</h2>
<p>Recall that the linear predictor can be written as:</p>
<p><span class="math display">\[
\eta_i = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + ...
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\beta_0\)</span> is the intercept of the linear model</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\beta_k\)</span> are the coefficients of the explanatory variables. These coefficients will tell us the effect of predictor <span class="math inline">\(x_{ik}\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="the-main-effect-model-1" class="slide level2">
<h2>The Main Effect Model</h2>
<p>The current form of the linear predictor assumes the explanatory variables are in quantitative form. When the explanatory variables are categorical, we need to create dichotomous dummy variables to denote each level of the variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The case <span class="math inline">\(x_{ik}=0\)</span> is called the reference level of the variables. When all <span class="math inline">\(x_{ik}=0\)</span> the linear predictor collapses to the intercept <span class="math inline">\(\beta_0\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>For dummy dichotomous variables, odds ratios can be calculated as an effect size of association.</p>
</div>
</div>
</div>
</section>
<section id="the-main-effect-model-2" class="slide level2">
<h2>The Main Effect Model</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The main effect model follows a regression framework, which means we can use ANOVA to test for effect significance.</p>
</div>
</div>
</div>
</section>
<section id="sas-the-logistic-procedure" class="slide level2">
<h2><code>SAS</code>: The LOGISTIC Procedure</h2>
<p>The LOGISTIC procedure can perform logistic regression in SAS.</p>
<ul>
<li>Can take both categorical and continuous explanatory variable</li>
<li>Syntax is slightly different from the FREQ procedure.</li>
</ul>
</section>
<section id="sas-the-logistic-procedure-1" class="slide level2">
<h2><code>SAS</code>: The LOGISTIC Procedure</h2>
<p>The LOGISTIC procedure provides estimates for <span class="math inline">\(\beta\)</span> as in regression analysis.</p>
<h3 id="sample-syntax">Sample Syntax</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-1"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1"></a>proc logistic data<span class="ot">=</span>data;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-1-2" class="code-annotation-target"><a href="#annotated-cell-1-2"></a>freq count;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-1-3" class="code-annotation-target"><a href="#annotated-cell-1-3"></a>model <span class="fu">y</span>(<span class="at">event=</span><span class="st">'Yes'</span>) <span class="ot">=</span> x1 x2 <span class="sc">/</span>scale<span class="ot">=</span>none aggregate;</span>
<span id="annotated-cell-1-4"><a href="#annotated-cell-1-4"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="2" data-code-annotation="1"><code>freq</code> functions similar to <code>weight</code> in the <code>FREQ</code> procedure. When the data consists of an observation for each row, this statement is not needed.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="3" data-code-annotation="2"><code>model</code> specifies the model for the response <code>y</code> using the explanatory variables <code>x1</code> and <code>x2</code>. <code>event</code> tells SAS what the “success” response level is. The <code>scale</code> option produces goodness-of-fit statistics. The <code>aggregate</code> option requests that SAS treat each unique combination of the explanatory variable values as a distinct group in computing the goodness-of-fit statistics.</span>
</dd>
</dl>
</section>
<section id="r-glm" class="slide level2">
<h2><code>R</code>: <code>glm()</code></h2>
<p>The <code>glm()</code> function in <code>R</code> can fit a logistic regression model in the generalized linear model framework.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Because there are other distributions that work with <code>glm()</code>, we need to specify that we are dealing with a binomial distribution using the <code>family="binomial"</code> argument.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(dependent<span class="sc">~</span>independent<span class="sc">+</span>covariates,</span>
<span id="cb1-2"><a></a>    <span class="at">data=</span>dataset,</span>
<span id="cb1-3"><a></a>    <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb1-4"><a></a></span>
<span id="cb1-5"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="r-odds-ratios" class="slide level2">
<h2><code>R</code>: Odds Ratios</h2>
<p>We can use <code>emmeans()</code> and <code>contrast()</code> from the <code>emmeans</code> package to estimate the probabilities and odds ratios based on the model provided by the <code>glm()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb2-2"><a></a></span>
<span id="cb2-3"><a></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>independent, <span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb2-4"><a></a>emm</span>
<span id="cb2-5"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>The data shows people who visited a clinic and required a catheterization. The response is the presence of coronary artery disease. The explanatory variables are ECG segment depression and sex. Use logistic regression methods to obtain odds ratio estimates and create a logistic regression model to estimate the probability of developing CA disease based on sex and ECG segment depression.</p>
<p><img data-src="img/coronary_C3.png" height="200"></p>
<h3 id="data-set">Data Set</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>data coronary;</span>
<span id="cb3-2"><a></a>input sex ecg ca count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb3-3"><a></a>datalines;</span>
<span id="cb3-4"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">11</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">4</span></span>
<span id="cb3-5"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">10</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">8</span></span>
<span id="cb3-6"><a></a><span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">9</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">9</span></span>
<span id="cb3-7"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">6</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">21</span></span>
<span id="cb3-8"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>or refer to <code>ECG.csv</code> uploaded on Canvas. Sex=0 refers to female, while ECG=0 refers to lower segment depression.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a></a>ecg <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ECG.csv"</span>, <span class="at">stringsAsFactors =</span> T)</span>
<span id="cb4-3"><a></a><span class="fu">glimpse</span>(ecg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 78
Columns: 4
$ ID      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ Sex     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,…
$ ECG     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,…
$ Disease &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, No…</code></pre>
</div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The data shows people who visited a clinic and required a catheterization. The response is the presence of coronary artery disease. The explanatory variables are ECG segment depression and sex. Use logistic regression methods to obtain odds ratio estimates and create a logistic regression model to estimate the probability of developing CA disease based on sex and ECG segment depression.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">SAS Code</a></li><li><a href="#tabset-1-2">R Code</a></li><li><a href="#tabset-1-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>proc logistic data<span class="ot">=</span>coronary ;</span>
<span id="cb6-2"><a></a>freq count;</span>
<span id="cb6-3"><a></a>model <span class="fu">ca</span>(<span class="at">event=</span><span class="st">'1'</span>)<span class="ot">=</span>sex ecg <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb6-4"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb7-2"><a></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Disease<span class="sc">~</span>Sex<span class="sc">+</span>ECG,</span>
<span id="cb7-3"><a></a>               <span class="at">data=</span>ecg,</span>
<span id="cb7-4"><a></a>               <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb7-5"><a></a></span>
<span id="cb7-6"><a></a><span class="co"># intercept only model </span></span>
<span id="cb7-7"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Disease<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb7-8"><a></a>            <span class="at">data=</span>ecg,</span>
<span id="cb7-9"><a></a>            <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb7-10"><a></a></span>
<span id="cb7-11"><a></a><span class="co"># comparing intercept only  model to intercept + variables model</span></span>
<span id="cb7-12"><a></a></span>
<span id="cb7-13"><a></a><span class="fu">anova</span>(mod1,mod_glm,<span class="at">test =</span> <span class="st">"LRT"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Disease ~ 1
Model 2: Disease ~ Sex + ECG
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
1        77     107.67                        
2        75      95.90  2   11.769 0.002782 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Disease ~ 1, family = "binomial", data = ecg)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)   0.1542     0.2271   0.679    0.497

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 107.67  on 77  degrees of freedom
Residual deviance: 107.67  on 77  degrees of freedom
AIC: 109.67

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Disease ~ Sex + ECG, family = "binomial", data = ecg)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -1.1747     0.4854  -2.420   0.0155 *
Sex           1.2770     0.4980   2.564   0.0103 *
ECG           1.0545     0.4980   2.118   0.0342 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 107.67  on 77  degrees of freedom
Residual deviance:  95.90  on 75  degrees of freedom
AIC: 101.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># Calculating probabilities and odds ratios.</span></span>
<span id="cb13-2"><a></a></span>
<span id="cb13-3"><a></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>Sex,<span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb13-4"><a></a>emm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Sex  prob     SE  df asymp.LCL asymp.UCL
   0 0.344 0.0853 Inf     0.200     0.523
   1 0.652 0.0740 Inf     0.497     0.781

Results are averaged over the levels of: ECG 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 Sex0 / Sex1      0.279 0.139 Inf     0.105      0.74    1  -2.564  0.0103

Results are averaged over the levels of: ECG 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">"revpairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value
 Sex1 / Sex0       3.59 1.79 Inf      1.35      9.52    1   2.564  0.0103

Results are averaged over the levels of: ECG 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>emm_ecg <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>ECG,<span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb19-2"><a></a>emm_ecg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> ECG  prob     SE  df asymp.LCL asymp.UCL
   0 0.369 0.0880 Inf     0.218     0.551
   1 0.627 0.0764 Inf     0.470     0.761

Results are averaged over the levels of: Sex 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a><span class="fu">contrast</span>(emm_ecg,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 ECG0 / ECG1      0.348 0.173 Inf     0.131     0.924    1  -2.118  0.0342

Results are averaged over the levels of: Sex 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="fu">contrast</span>(emm_ecg,<span class="at">method=</span><span class="st">"revpairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value
 ECG1 / ECG0       2.87 1.43 Inf      1.08      7.62    1   2.118  0.0342

Results are averaged over the levels of: Sex 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
</div>
</div>
<div id="tabset-1-3">
<p>From <code>SAS</code> output: Both chi-square tests had p-values above 0.05, which meant there was no evidence that the errors were not random.</p>
<p>The AIC values for the full model are lower than the intercept-only model, which meant model performance increased after including our covariates.</p>
<p>Assuming the probability of developing CA is given by <span class="math inline">\(\theta_CA\)</span>, the logistic model was estimated to be:</p>
<p><span class="math display">\[
logit~[\hat{\theta}_{CA}] = -1.17 + 1.28*SEX + 1.05*ECG
\]</span></p>
<p>There is a significant effect of sex (<span class="math inline">\(\beta = 1.28\)</span>, p=0.01) and segment depression (<span class="math inline">\(\beta = 1.05\)</span>, p=0.03) on the probability of developing CA disease. In terms of odds ratios, the odds that males develop CA is 3.58 (95% CI: 1.35,9.52) times that of females. Additionally, the odds of developing CA with higher segment depression is 2.87 (95% CI: 1.08, 7.62) times that of patients with lower segment depression in their ECG.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>A simple random sample of individuals from different age groups were asked about their caffeine and exercise habits.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Data</a></li><li><a href="#tabset-2-2">Questions</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<table class="caption-top">
<tbody>
<tr class="odd">
<td>Age Group</td>
<td>Caffeine</td>
<td>Yes Exercise</td>
<td>No Exercise</td>
</tr>
<tr class="even">
<td>Young Adult</td>
<td>Yes Caffeine</td>
<td>121</td>
<td>158</td>
</tr>
<tr class="odd">
<td>Young Adult</td>
<td>No Caffeine</td>
<td>36</td>
<td>97</td>
</tr>
<tr class="even">
<td>Older Adult</td>
<td>Yes Caffeine</td>
<td>44</td>
<td>132</td>
</tr>
<tr class="odd">
<td>Older Adult</td>
<td>No Caffeine</td>
<td>15</td>
<td>130</td>
</tr>
</tbody>
</table>
<p>It is also uploaded as line-level data as <code>exercise_caffeine.csv</code> on Canvas.</p>
</div>
<div id="tabset-2-2">
<ul>
<li>Use logistic regression to estimate the logistic model for the data. Use Young Adult and No caffeine as the reference levels.</li>
<li>Is there a significant age group effect on exercise habits?</li>
<li>Is there a significant effect of caffeine intake on exercise habits?</li>
<li>Calculate and interpret the appropriate odds ratios for age group and caffeine intake.</li>
<li>Does the model fit the data well?</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>A simple random sample of individuals from different age groups were asked about their caffeine and exercise habits.</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">SAS Code</a></li><li><a href="#tabset-3-2">R Code</a></li><li><a href="#tabset-3-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>data caf;</span>
<span id="cb25-2"><a></a>input agegrp  caffeine  exercise  count;</span>
<span id="cb25-3"><a></a>datalines;</span>
<span id="cb25-4"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">121</span></span>
<span id="cb25-5"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">158</span></span>
<span id="cb25-6"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">36</span></span>
<span id="cb25-7"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">97</span></span>
<span id="cb25-8"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">44</span></span>
<span id="cb25-9"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">132</span></span>
<span id="cb25-10"><a></a><span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">15</span></span>
<span id="cb25-11"><a></a><span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">130</span></span>
<span id="cb25-12"><a></a>;</span>
<span id="cb25-13"><a></a></span>
<span id="cb25-14"><a></a>proc logistic;</span>
<span id="cb25-15"><a></a>freq count;</span>
<span id="cb25-16"><a></a>model <span class="fu">exercise</span>(<span class="at">event=</span><span class="st">'1'</span>)<span class="ot">=</span>agegrp caffeine <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb25-17"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-3-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>exercise <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"exercise_caffeine.csv"</span>)</span>
<span id="cb26-2"><a></a><span class="fu">glimpse</span>(exercise)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 733
Columns: 3
$ AgeGrp   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Caffeine &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ Exercise &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Exercise<span class="sc">~</span>AgeGrp<span class="sc">+</span>Caffeine,</span>
<span id="cb28-2"><a></a>               <span class="at">data=</span>exercise,</span>
<span id="cb28-3"><a></a>               <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb28-4"><a></a></span>
<span id="cb28-5"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Exercise ~ AgeGrp + Caffeine, family = "binomial", 
    data = exercise)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0759     0.1711  -6.288 3.22e-10 ***
AgeGrp       -0.9308     0.1789  -5.203 1.96e-07 ***
Caffeine      0.8409     0.1866   4.507 6.58e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 888.82  on 732  degrees of freedom
Residual deviance: 832.30  on 730  degrees of freedom
AIC: 838.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb30-2"><a></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>Caffeine,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb30-3"><a></a>emm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Caffeine  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
        0 0.176 0.0231 Inf     0.136     0.226  0.5  -9.696 &lt;0.0001
        1 0.332 0.0233 Inf     0.288     0.379  0.5  -6.676 &lt;0.0001

Results are averaged over the levels of: AgeGrp 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">'revpairwise'</span>, <span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast              odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio
 Caffeine1 / Caffeine0       2.32 0.433 Inf      1.61      3.34    1   4.507
 p.value
 &lt;0.0001

Results are averaged over the levels of: AgeGrp 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>emm_age <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>AgeGrp,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb34-2"><a></a>emm_age</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> AgeGrp  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
      0 0.342 0.0252 Inf     0.294     0.393  0.5  -5.861 &lt;0.0001
      1 0.170 0.0211 Inf     0.132     0.215  0.5 -10.607 &lt;0.0001

Results are averaged over the levels of: Caffeine 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">contrast</span>(emm_age,<span class="at">method=</span><span class="st">'pairwise'</span>, <span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio
 AgeGrp0 / AgeGrp1       2.54 0.454 Inf      1.79       3.6    1   5.203
 p.value
 &lt;0.0001

Results are averaged over the levels of: Caffeine 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Exercise<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb38-2"><a></a>               <span class="at">data=</span>exercise,</span>
<span id="cb38-3"><a></a>               <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb38-4"><a></a><span class="fu">anova</span>(mod1,mod_glm,<span class="at">test =</span> <span class="st">"LRT"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Exercise ~ 1
Model 2: Exercise ~ AgeGrp + Caffeine
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       732     888.82                          
2       730     832.30  2   56.515 5.345e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Exercise ~ 1, family = "binomial", data = exercise)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.87276    0.08102  -10.77   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 888.82  on 732  degrees of freedom
Residual deviance: 888.82  on 732  degrees of freedom
AIC: 890.82

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Exercise ~ AgeGrp + Caffeine, family = "binomial", 
    data = exercise)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0759     0.1711  -6.288 3.22e-10 ***
AgeGrp       -0.9308     0.1789  -5.203 1.96e-07 ***
Caffeine      0.8409     0.1866   4.507 6.58e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 888.82  on 732  degrees of freedom
Residual deviance: 832.30  on 730  degrees of freedom
AIC: 838.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</div>
<div id="tabset-3-3">
<p>Suppose the probability of exercise is given by <span class="math inline">\(\theta\)</span>,The estimated logistic regression model is: <span class="math inline">\(logit (\theta) = -1.08 -0.93*AGEGRP + 0.84*CAFFEINE\)</span>. The AIC for the full model is lower than that of the intercept only model, indicating better model fit.</p>
<p>There is a significant effect of age in the likelihood of exercising. The odds of an older participant reporting regular exercise is 0.39 (95% CI: 0.28, 0.56; p&lt;0.001) times that of younger participants.</p>
<p>There is a significant effect of caffeine intake on exercise. The odds of a participant reporting regular exercise when they consume caffeine is 2.3 (95% CI: 1.6,3.3; p&lt;0.001) times that of those who do not consume caffeine.</p>
<p><code>SAS</code>: The deviance (p=0.39) and goodness-of-fit chi-square tests (p=0.40) showed no evidence against the randomness of errors, which indicates good model fit. The AIC and SC values also decreased after including covariates, also supporting good fit.</p>
</div>
</div>
</div>
</section>
<section id="sas-class-statement" class="slide level2">
<h2><code>SAS</code>: <code>CLASS</code> statement</h2>
<ul>
<li>The <code>class</code> statement can create dummy variable coding automatically through the LOGISTIC procedure.
<ul>
<li>The REF option allows us to set the reference level for each variable.</li>
</ul></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44" data-code-line-numbers="2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a>proc logistic;</span>
<span id="cb44-2"><a></a>class cat;</span>
<span id="cb44-3"><a></a>model y <span class="ot">=</span> x cat<span class="sc">/</span>scale<span class="ot">=</span>none aggregate;</span>
<span id="cb44-4"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="sas-model-parameterizations" class="slide level2">
<h2><code>SAS</code>: Model parameterizations</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Effect parameterization</strong> produces deviation from the <em>grand mean</em>. The reference level corresponds to <span class="math inline">\(X=-1\)</span>.</p>
<ul>
<li>In <code>R</code>, this is established using <code>contr.sum()</code></li>
<li>In <code>SAS</code>, this is the default parameterization in the <code>LOGISTIC</code> procedure.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Reference cell parameterization</strong> produces measurements based on reference level. The reference level corresponds to <span class="math inline">\(X=0\)</span>.</p>
<ul>
<li>In <code>R</code>, this is established using <code>contr.treatment()</code> or <code>contr.SAS()</code>. This is the default in <code>R</code>.</li>
<li>In <code>SAS</code>, this can be specified in the class statement as <code>param=ref</code> in the <code>LOGISTIC</code> procedure.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>The data is based on a study on prison sentencing for persons convicted of a burglary or larceny. The researchers wanted to test whether the type of crime (nonresidential or other) and prior arrests (some or none) affect whether the offender was sent to prison.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Data</a></li><li><a href="#tabset-4-2">Questions</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p><img data-src="img/sentencing_C8.png" height="200"></p>
</div>
<div id="tabset-4-2">
<ul>
<li>Perform a logistic regression analysis to estimate the appropriate logistic model for the data. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.</li>
<li>Using effect parametrization</li>
<li>Using reference cell parametrization</li>
</ul>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>The data is based on a study on prison sentencing for persons convicted of a burglary or larceny. The researchers wanted to test whether the type of crime (nonresidential or other) and prior arrests (some or none) affect whether the offender was sent to prison.</p>
<ul>
<li>Perform a logistic regression analysis to estimate the appropriate logistic model for the data. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.</li>
<li>Using effect parametrization</li>
<li>Using reference cell parametrization</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">SAS Code</a></li><li><a href="#tabset-5-2">R Code</a></li><li><a href="#tabset-5-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-54"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-54-1"><a href="#annotated-cell-54-1"></a>data sentence;</span>
<span id="annotated-cell-54-2"><a href="#annotated-cell-54-2"></a>input type <span class="sc">$</span> prior <span class="sc">$</span> sentence <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-54-3"><a href="#annotated-cell-54-3"></a>datalines;</span>
<span id="annotated-cell-54-4"><a href="#annotated-cell-54-4"></a>nrb some y <span class="dv">42</span> nrb some n <span class="dv">109</span></span>
<span id="annotated-cell-54-5"><a href="#annotated-cell-54-5"></a>nrb none y <span class="dv">17</span> nrb none n <span class="dv">75</span></span>
<span id="annotated-cell-54-6"><a href="#annotated-cell-54-6"></a>other some y <span class="dv">33</span> other some n <span class="dv">175</span></span>
<span id="annotated-cell-54-7"><a href="#annotated-cell-54-7"></a>other none y <span class="dv">53</span> other none n <span class="dv">359</span></span>
<span id="annotated-cell-54-8"><a href="#annotated-cell-54-8"></a>;</span>
<span id="annotated-cell-54-9"><a href="#annotated-cell-54-9"></a></span>
<span id="annotated-cell-54-10"><a href="#annotated-cell-54-10"></a>proc logistic data<span class="ot">=</span>sentence order<span class="ot">=</span>data;</span>
<span id="annotated-cell-54-11"><a href="#annotated-cell-54-11"></a>title <span class="st">"effect"</span>;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-54" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-54-12" class="code-annotation-target"><a href="#annotated-cell-54-12"></a>class <span class="fu">type</span>(<span class="at">ref=</span><span class="st">"nrb"</span>) <span class="fu">prior</span>(<span class="at">ref=</span><span class="st">"none"</span>) <span class="sc">/</span> ;</span>
<span id="annotated-cell-54-13"><a href="#annotated-cell-54-13"></a>freq count;</span>
<span id="annotated-cell-54-14"><a href="#annotated-cell-54-14"></a>model <span class="fu">sentence</span>(<span class="at">event=</span><span class="st">'y'</span>) <span class="ot">=</span> type prior <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="annotated-cell-54-15"><a href="#annotated-cell-54-15"></a>run;</span>
<span id="annotated-cell-54-16"><a href="#annotated-cell-54-16"></a></span>
<span id="annotated-cell-54-17"><a href="#annotated-cell-54-17"></a></span>
<span id="annotated-cell-54-18"><a href="#annotated-cell-54-18"></a>proc logistic data<span class="ot">=</span>sentence order<span class="ot">=</span>data;</span>
<span id="annotated-cell-54-19"><a href="#annotated-cell-54-19"></a>title <span class="st">"reference"</span>;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-54" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-54-20" class="code-annotation-target"><a href="#annotated-cell-54-20"></a>class <span class="fu">type</span>(<span class="at">ref=</span><span class="st">"nrb"</span>) <span class="fu">prior</span>(<span class="at">ref=</span><span class="st">"none"</span>) <span class="sc">/</span> param<span class="ot">=</span>ref;</span>
<span id="annotated-cell-54-21"><a href="#annotated-cell-54-21"></a>freq count;</span>
<span id="annotated-cell-54-22"><a href="#annotated-cell-54-22"></a>model <span class="fu">sentence</span>(<span class="at">event=</span><span class="st">'y'</span>) <span class="ot">=</span> type prior <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="annotated-cell-54-23"><a href="#annotated-cell-54-23"></a>run;</span>
<span id="annotated-cell-54-24"><a href="#annotated-cell-54-24"></a></span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-54" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-54" data-code-lines="12" data-code-annotation="1">Default: effect parametrization</span>
</dd>
<dt data-target-cell="annotated-cell-54" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-54" data-code-lines="20" data-code-annotation="2">Reference cell parametrization used after <code>param=ref</code> is specified.</span>
</dd>
</dl>
</div>
<div id="tabset-5-2">
<p>We can also use <code>glm()</code> for aggregated counts, but we don’t need to create a contingency table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">type =</span> <span class="fu">c</span>(<span class="st">"nonresidential"</span>,<span class="st">"other"</span>),</span>
<span id="cb45-2"><a></a>                   <span class="at">prior =</span> <span class="fu">c</span>(<span class="st">"none"</span>,<span class="st">"some"</span>))</span>
<span id="cb45-3"><a></a>dat<span class="sc">$</span>prison <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">17</span>,<span class="dv">53</span>,<span class="dv">42</span>,<span class="dv">33</span>)</span>
<span id="cb45-4"><a></a>dat<span class="sc">$</span>noprison <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">75</span>,<span class="dv">359</span>,<span class="dv">109</span>,<span class="dv">175</span>)</span>
<span id="cb45-5"><a></a></span>
<span id="cb45-6"><a></a>dat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            type prior prison noprison
1 nonresidential  none     17       75
2          other  none     53      359
3 nonresidential  some     42      109
4          other  some     33      175</code></pre>
</div>
</div>
<p><strong>Reference Cell Parameterization</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">options</span>(<span class="at">contrasts=</span><span class="fu">c</span>(<span class="st">"contr.treatment"</span>,<span class="st">"contr.poly"</span>))</span>
<span id="cb47-2"><a></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(prison,noprison)<span class="sc">~</span>type <span class="sc">+</span> prior,<span class="at">data=</span>dat,<span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb47-3"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(prison, noprison) ~ type + prior, family = "binomial", 
    data = dat)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.3603     0.1962  -6.933 4.13e-12 ***
typeother    -0.5920     0.1968  -3.008  0.00263 ** 
priorsome     0.3469     0.1906   1.820  0.06875 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 16.59755  on 3  degrees of freedom
Residual deviance:  0.50763  on 1  degrees of freedom
AIC: 27.079

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>type,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb49-2"><a></a>emm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> type            prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
 nonresidential 0.234 0.0274 Inf     0.184     0.292  0.5  -7.747 &lt;0.0001
 other          0.144 0.0146 Inf     0.118     0.175  0.5 -15.051 &lt;0.0001

Results are averaged over the levels of: prior 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">"revpairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio
 other / nonresidential      0.553 0.109 Inf     0.376     0.814    1  -3.008
 p.value
  0.0026

Results are averaged over the levels of: prior 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a>emm_prior <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>prior,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb53-2"><a></a>emm_prior</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> prior  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
 none  0.160 0.0186 Inf     0.127     0.200  0.5 -11.971 &lt;0.0001
 some  0.213 0.0219 Inf     0.173     0.259  0.5 -10.012 &lt;0.0001

Results are averaged over the levels of: type 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">contrast</span>(emm_prior,<span class="at">method=</span><span class="st">"revpairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio   SE  df asymp.LCL asymp.UCL null z.ratio p.value
 some / none       1.41 0.27 Inf     0.974      2.06    1   1.820  0.0687

Results are averaged over the levels of: type 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Try replacing “contr.treatment” with “contr.SAS”. Which parts of the output change? Which parts do not change?</p>
</div>
</div>
</div>
<p><strong>Effect parametrization</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a><span class="fu">options</span>(<span class="at">contrasts=</span><span class="fu">c</span>(<span class="st">"contr.sum"</span>,<span class="st">"contr.poly"</span>))</span>
<span id="cb57-2"><a></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(prison,noprison)<span class="sc">~</span>type <span class="sc">+</span> prior,<span class="at">data=</span>dat,<span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb57-3"><a></a><span class="fu">summary</span>(mod_glm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(prison, noprison) ~ type + prior, family = "binomial", 
    data = dat)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.48282    0.09507 -15.596  &lt; 2e-16 ***
type1        0.29598    0.09838   3.008  0.00263 ** 
prior1      -0.17347    0.09531  -1.820  0.06875 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 16.59755  on 3  degrees of freedom
Residual deviance:  0.50763  on 1  degrees of freedom
AIC: 27.079

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>type,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb59-2"><a></a>emm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> type            prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
 nonresidential 0.234 0.0274 Inf     0.184     0.292  0.5  -7.747 &lt;0.0001
 other          0.144 0.0146 Inf     0.118     0.175  0.5 -15.051 &lt;0.0001

Results are averaged over the levels of: prior 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio
 nonresidential / other       1.81 0.356 Inf      1.23      2.66    1   3.008
 p.value
  0.0026

Results are averaged over the levels of: prior 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a>emm_prior <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mod_glm,<span class="sc">~</span>prior,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span>
<span id="cb63-2"><a></a>emm_prior</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> prior  prob     SE  df asymp.LCL asymp.UCL null z.ratio p.value
 none  0.160 0.0186 Inf     0.127     0.200  0.5 -11.971 &lt;0.0001
 some  0.213 0.0219 Inf     0.173     0.259  0.5 -10.012 &lt;0.0001

Results are averaged over the levels of: type 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
Tests are performed on the logit scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a></a><span class="fu">contrast</span>(emm_prior,<span class="at">method=</span><span class="st">"pairwise"</span>,<span class="at">type=</span><span class="st">"response"</span>,<span class="at">infer=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast    odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 none / some      0.707 0.135 Inf     0.486      1.03    1  -1.820  0.0687

Results are averaged over the levels of: type 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale </code></pre>
</div>
</div>
</div>
<div id="tabset-5-3">
<p>Effect parametrization: <span class="math inline">\(logit (\theta_{ij}) = -1.48 - 0.30 * TYPE +0.17* PRIOR\)</span></p>
<p>Reference Cell parametrization: <span class="math inline">\(logit (\theta_{ij}) = -1.36- 0.59 * TYPE +0.35* PRIOR\)</span></p>
<p>The odds of sending an offender to prison after committing other crimes is 0.55 times (95% CI: 0.38, 0.81) that when committing non-residential crimes. There is strong evidence against the null hypothesis of no difference.</p>
<p>The odds of sending an offender with some prior arrests are 1.42 times (95% CI: 0.974, 2.06) times more likely to be sent to prison than those who have no prior arrests. There is moderate evidence against the null hypothesis of no difference.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Recall the age x caffeine x exercise habits exercise. Use the class statement to perform logistic regression using effect and reference cell parametrization. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.</p>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>Recall the age x caffeine x exercise habits exercise. Use the class statement to perform logistic regression using effect and reference cell parametrization. Comment on the significance of the main effects and estimate the odds ratio and the 95% CI.</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">SAS Code</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a></a>title <span class="st">"effect"</span>;</span>
<span id="cb67-2"><a></a>proc logistic data<span class="ot">=</span>caf;</span>
<span id="cb67-3"><a></a>freq count;</span>
<span id="cb67-4"><a></a>class <span class="fu">agegrp</span> (<span class="at">REF=</span><span class="st">'0'</span>) <span class="fu">caffeine</span> (<span class="at">REF=</span><span class="st">'0'</span>);</span>
<span id="cb67-5"><a></a>model <span class="fu">exercise</span>(<span class="at">event=</span><span class="st">'1'</span>)<span class="ot">=</span>agegrp caffeine <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb67-6"><a></a>run;</span>
<span id="cb67-7"><a></a></span>
<span id="cb67-8"><a></a>title <span class="st">"ref cell"</span>;</span>
<span id="cb67-9"><a></a>proc logistic data<span class="ot">=</span>caf;</span>
<span id="cb67-10"><a></a>freq count;</span>
<span id="cb67-11"><a></a>class <span class="fu">agegrp</span> (<span class="at">REF=</span><span class="st">'0'</span>) <span class="fu">caffeine</span> (<span class="at">REF=</span><span class="st">'0'</span>)<span class="sc">/</span>param<span class="ot">=</span>ref;</span>
<span id="cb67-12"><a></a>model <span class="fu">exercise</span>(<span class="at">event=</span><span class="st">'1'</span>)<span class="ot">=</span>agegrp caffeine <span class="sc">/</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb67-13"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-6-2">
<p>Effect parametrization: <span class="math inline">\(logit (\theta_{ij}) = -1.12 - 0.47 * AGEGRP +0.42* CAFFEINE\)</span></p>
<p>Reference Cell parametrization: <span class="math inline">\(logit (\theta_{ij}) = -1.08- 0.93 * AGEGRP +0.84* CAFFEINE\)</span></p>
<p>There is strong evidence of an effect of age (p&lt;0.001). The odds of older adults reporting regular exercise is 0.39 (95% CI: 0.28, 0.56) times that of younger adults.</p>
<p>There is strong evidence of an association with caffeine consumption (p&lt;0.001). The odds of reporting regular exercise for participants who consumed caffeine is 2.32 times that of those who do not consume caffeine.</p>
</div>
</div>
</div>
</section>
<section id="saturated-models" class="slide level2">
<h2>Saturated models</h2>
<ul>
<li>Saturated models often include an interaction term <span class="math inline">\(A*B\)</span>, which tests the difference of the effect of B in the different levels of <span class="math inline">\(A\)</span>.</li>
</ul>
<div title="Simple Effects">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Simple Effects</strong></p>
</div>
<div class="callout-content">
<p>The effect of <span class="math inline">\(B\)</span> conditional on the level of <span class="math inline">\(A\)</span> is referred to as <em>simple effects</em>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="interaction-models" class="slide level2">
<h2>Interaction Models</h2>
<p>The interaction model in the logistic regression framework can be written as:</p>
<p><span class="math display">\[
logit(\theta) = \alpha + \beta_1 x_1  + \beta_2 x_2 + \beta_{12}x_1x_2
\]</span></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Interaction terms should be tested first (<span class="math inline">\(x_1x_2\)</span>). If the interaction is not significant, it can be dropped from the model, leaving you with a main effects model.</p>
</div>
</div>
</div>
</section>
<section id="interaction-models-1" class="slide level2">
<h2>Interaction models</h2>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Interaction tests</a></li><li><a href="#tabset-7-2">Figure</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<ul>
<li>Interaction tests are Wald chi-square tests with <span class="math inline">\((a-1)(b-1)\)</span> degrees of freedom, where <span class="math inline">\(a\)</span> is the number of levels of A and <span class="math inline">\(b\)</span> is the number of levels of B.</li>
<li>The degrees of freedom is also equal to the number of coefficients that should be allotted to the interactions.
<ul>
<li>Interactions can be visually recognized using interaction plots.</li>
</ul></li>
</ul>
</div>
<div id="tabset-7-2">
<p><img data-src="img/interaction_C8.png"></p>
</div>
</div>
</div>
</section>
<section id="non-dichotomous-explanatory-variables" class="slide level2">
<h2>Non-Dichotomous Explanatory Variables</h2>
<ul>
<li>What if the explanatory variables have more than two levels?
<ul>
<li>Nominal</li>
<li>Ordinal</li>
<li>Continuous</li>
</ul></li>
</ul>
</section>
<section id="non-dichotomous-explanatory-variables-1" class="slide level2">
<h2>Non-Dichotomous Explanatory Variables</h2>
<ul>
<li>Recall: Regression models
<ul>
<li>If an explanatory variable has <span class="math inline">\(n\)</span> levels, <span class="math inline">\((n-1)\)</span> dichotomous dummy variables are needed to be produced to include the explanatory variable in the regression model.</li>
<li>In interaction models, this leads to more interaction terms.</li>
</ul></li>
</ul>
<p>For a variable with <span class="math inline">\((a-1)\)</span> levels <span class="math display">\[
logit(\theta) = \alpha + \beta_1x_{a1} + \beta_2x_{a2} + ... + \beta_{(a-1)}x_{a,a-1}
\]</span></p>
<ul>
<li>The matrix form of the predictor variables is called the Design Matrix.</li>
</ul>
</section>
<section id="non-dichotomous-explanatory-variables-2" class="slide level2">
<h2>Non-Dichotomous Explanatory Variables</h2>
<p>For a model with two variables/factors: one with <span class="math inline">\((a-1)\)</span> levels and the other with <span class="math inline">\((b-1)\)</span> levels, the interaction model can be written as:</p>
<p><span class="math display">\[
logit(\theta) = \alpha + \beta_{a1}x_{a1} + \beta_{a2}x_{a2} + ... + \beta_{a,(a-1)}x_{a,a-1} +  \beta_{b1}x_{b1} + \beta_{b2}x_{b2} + ... + \beta_{b(b-1)}x_{b,b-1} + Interaction
\]</span></p>
<p><span class="math display">\[
Interaction = \beta_{a1b1}x_{a1}x_{b1} + \beta_{a1b2}x_{a1}x_{b2} + \beta_{a2b1}x_{a2}x_{b1} +... + \beta_{a,a-1;b,b-1}x_{a,a-1}x_{b,b-1}
\]</span></p>
</section>
<section id="nominal-explanatory-variables" class="slide level2">
<h2>Nominal Explanatory Variables</h2>
<p>Since there is no order in the levels of explanatory variables, we might be interested in the difference between specific levels</p>
<ul>
<li>Example: How did the difference in placebo and test treatments compare between Hospital 1 and Hospital 2?</li>
<li>Example: How did the difference in placebo and test treatments compare in Hospital 2?</li>
</ul>
</section>
<section id="contrasts" class="slide level2">
<h2>Contrasts</h2>
<ul>
<li>Contrasts are used in performing a formal test for estimable effects</li>
<li>The null hypotheses for these tests are usually the hypothesis of no effect
<ul>
<li>“There is no main effect of Variable/ Factor A”</li>
<li>“There is no interaction”</li>
<li>“The estimated treatment mean of the first level of Factor A and first level of Factor B is zero”</li>
</ul></li>
</ul>
</section>
<section id="contrasts-estimable-effects" class="slide level2">
<h2>Contrasts: Estimable Effects</h2>
<p>Suppose we refer to <span class="math inline">\(logit(\theta_{ij})\)</span> as <span class="math inline">\(\eta_{ij}\)</span>.</p>
<div title="Estimable Effects">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Estimable Effects</strong></p>
</div>
<div class="callout-content">
<p>Estimable effects are effects that can be expressed as the sum or difference of linear predictors <span class="math inline">\(\eta_{ij}\)</span>.</p>
</div>
</div>
</div>
</div>
<p>Example: How did the difference in placebo and test treatments compare between Hospital 1 and Hospital 2?</p>
<ul>
<li>The null hypothesis can be expressed as <span class="math inline">\(\eta_{t1}-\eta_{p1} -(\eta_{t2}-\eta_{p2}) = 0\)</span>. This effect is estimable!</li>
<li>The expression can be expressed in terms of <span class="math inline">\(\beta_i\)</span> by substituting the linear predictor expressions.</li>
</ul>
</section>
<section id="contrasts-joint-tests" class="slide level2">
<h2>Contrasts: Joint Tests</h2>
<p>Suppose we have an explanatory variable/factor <span class="math inline">\(A\)</span> with three levels, which requires <strong>two</strong> different dummy variables. The regression model can be expressed as:</p>
<p><span class="math display">\[
logit (\theta) = \eta = \alpha + \beta_1 X_{a1} + \beta_2 X_{a2}
\]</span></p>
<p>To test for a main effect of <span class="math inline">\(A\)</span>, we need to test the following null hypotheses simultaneously: <span class="math inline">\(\beta_1=0\)</span> and <span class="math inline">\(\beta_2=0\)</span>. These could be done using <strong>joint tests</strong>.</p>
<ul>
<li>The joint tests use Wald statistics similar to an ANOVA.</li>
</ul>
</section>
<section id="contrasts-sas" class="slide level2">
<h2>Contrasts: SAS</h2>
<p>We use the <code>contrast</code> statement in the <code>LOGISTIC</code> procedure to test these contrasts.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In SAS, we focus on the coefficients of each term defined in the linear predictor. Each linear predictor is broken down into the effect and interaction terms and simplified. The resulting <strong>coefficients</strong> would then make it to the contrast statement.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>Suppose we are interested in modeling the mortality rate of cardiothoracic surgery across 4 hospitals. The resulting logistic regression model would be:</p>
<p><span class="math display">\[
\eta = \alpha + \beta_1X_{h1} + \beta_1X_{h2} + \beta_3X_{h3}
\]</span></p>
<p>Suppose we want to test for a difference in mortality between hospital 1 and hospital 4.</p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Reference Cell</a></li><li><a href="#tabset-8-2">Effect</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>The effect due to Hospital 1 corresponds to the case <span class="math inline">\((X_{h1},X_{h2},X_{h3} = 1,0,0)\)</span> yields a regression model given by: <span class="math inline">\(\alpha + \beta_1\)</span>. Hospital 4 corresponds to the case <span class="math inline">\((X_{h1},X_{h2},X_{h3} = 0,0,0)\)</span>, which yields a regression model given by: <span class="math inline">\(\alpha\)</span>.</p>
<p>Then the difference between Hospital 1 and Hospital 4 can be calculated as <span class="math display">\[\alpha +\beta_1 - \alpha = \beta_1 \]</span>. T he corresponding null hypothesis of no difference can the be written as <span class="math display">\[ 1* \beta_1 + 0*\beta_2 + 0*\beta_3 = 0\]</span></p>
<p>In SAS, we can code this as:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a></a>contrast A <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> ;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-8-2">
<p>The effect due to Hospital 1 corresponds to the case <span class="math inline">\((X_{h1},X_{h2},X_{h3} = 1,0,0)\)</span> yields a regression model given by: <span class="math inline">\(\alpha + \beta_1\)</span>. Hospital 4 corresponds to the case <span class="math inline">\((X_{h1},X_{h2},X_{h3} = -1,-1,-1)\)</span>, which yields a regression model given by: <span class="math inline">\(\alpha -\beta_1 - \beta_2 - \beta_3\)</span>.</p>
<p>Then the difference between Hospital 1 and Hospital 4 can be calculated as <span class="math display">\[\alpha +\beta_1 - [\alpha -\beta_1 - \beta_2 - \beta_3] = 2\beta_1 +\beta_2 + \beta_3\]</span>.</p>
<p>The corresponding null hypothesis of no difference can the be written as:</p>
<p><span class="math display">\[
2\beta_1 +1* \beta_2 + 1*\beta_3 = 0
\]</span></p>
<p>In SAS, we can code this as:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a></a>contrast A <span class="dv">2</span> <span class="dv">1</span> <span class="dv">1</span> ;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>Consider a Factor A with three levels <span class="math inline">\((A_1,A_2,A_3)\)</span>, with <span class="math inline">\(A_3\)</span> as the reference level. Provide the corresponding null hypotheses and formulate the SAS contrast statements for both reference cell and effect parametrization.</p>
<ul>
<li>There is no difference between the first and third levels of A.</li>
<li>The mean effect of <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> is equal to the effect of <span class="math inline">\(A_3\)</span>.</li>
</ul>
</section>
<section id="exercise-5" class="slide level2">
<h2>Exercise</h2>
<p>Consider a Factor A with three levels <span class="math inline">\((A_1,A_2,A_3)\)</span>, with <span class="math inline">\(A_3\)</span> as the reference level. Provide the corresponding null hypotheses and formulate the SAS contrast statements for both reference cell and effect parametrization.</p>
<ul>
<li>There is no effect difference between the first and third levels of A.</li>
<li>The mean effect of <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> is equal to the effect of <span class="math inline">\(A_3\)</span>.</li>
</ul>
<p>The logit model can be expressed as:</p>
<p><span class="math display">\[
\eta = \alpha + \beta_1 X_1 + \beta_2 X_2
\]</span></p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Item 1</a></li><li><a href="#tabset-9-2">Item 2</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p>Reference Cell: Effect <span class="math inline">\(A_1 = \alpha + \beta_1\)</span> Effect <span class="math inline">\(A_3 = \alpha\)</span></p>
<p>No effect difference between the first and third levels: <span class="math inline">\(A_1-A_3 = 0 \to \beta_1=0\)</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a></a>contrast A <span class="dv">1</span> <span class="dv">0</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Effect parametrization: Effect <span class="math inline">\(A_1 = \alpha + \beta_1\)</span> Effect <span class="math inline">\(A_3 = \alpha-\beta_1 - \beta_2\)</span></p>
<p>No effect difference between the first and third levels: <span class="math inline">\(A_1-A_3 = 0 \to 2\beta_1 +\beta_2=0\)</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a></a>contrast A <span class="dv">2</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-9-2">
<p>Reference Cell: Effect <span class="math inline">\(A_1 = \alpha + \beta_1\)</span> Effect <span class="math inline">\(A_2 = \alpha + \beta_2\)</span> Effect <span class="math inline">\(A_3 = \alpha\)</span></p>
<p>No effect difference between the first and third levels: <span class="math inline">\((A_1+A_2)/2-A_3 = 0 \to \beta_1+\beta_2=0\)</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a></a>contrast A <span class="dv">1</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Effect parametrization: Effect <span class="math inline">\(A_1 = \alpha + \beta_1\)</span> Effect <span class="math inline">\(A_2 = \alpha + \beta_2\)</span> Effect <span class="math inline">\(A_3 = \alpha-\beta_1 - \beta_2\)</span></p>
<p>No effect difference between the first and third levels: <span class="math inline">\((A_1+A_2)/2-A_3 = 0 \to 1* \beta_1 +1* \beta_2=0\)</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a></a>contrast A <span class="dv">1</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="exercise-6" class="slide level2">
<h2>Exercise</h2>
<p>Consider a Factor A with three levels <span class="math inline">\((A_1,A_2,A_3)\)</span> and Factor B with two levels <span class="math inline">\((B_1,B_2)\)</span>, with <span class="math inline">\(A_3\)</span> and <span class="math inline">\(B_2\)</span> as the reference level. Suppose <span class="math inline">\(\theta\)</span> is a probability of observing success for a dichotomous response variable <span class="math inline">\(y\)</span>.</p>
<ul>
<li>Please write the saturated/interaction logistic model for <span class="math inline">\(\theta\)</span></li>
</ul>
<p>Provide the corresponding null hypothesis and formulate the SAS contrast statements for both reference cell and effect parametrizations.</p>
<ul>
<li>“There is no interaction between A and B”.</li>
</ul>
</section>
<section id="exercise-7" class="slide level2">
<h2>Exercise</h2>
<p>Consider a Factor A with three levels <span class="math inline">\((A_1,A_2,A_3)\)</span> and Factor B with two levels <span class="math inline">\((B_1,B_2)\)</span>, with <span class="math inline">\(A_3\)</span> and <span class="math inline">\(B_2\)</span> as the reference level. Suppose <span class="math inline">\(\theta\)</span> is a probability of observing success for a dichotomous response variable <span class="math inline">\(y\)</span>.</p>
<ul>
<li>Please write the saturated/interaction logistic model for <span class="math inline">\(\theta\)</span></li>
</ul>
<p><span class="math display">\[
\eta = \alpha + \beta_{A1}x_{A1} + \beta_{A2}x_{A2} +
\beta_{B1}x_{B1}  +  \beta_{A1B1}x_{A1}x_{B1} + \beta_{A2B1}x_{A2}x_{B1}
\]</span></p>
<p>Provide the corresponding null hypotheses and formulate the SAS contrast statements for both reference cell and effect parametrizations.</p>
<ul>
<li>“There is no interaction between A and B”.
<ul>
<li>The joint tests of the following hypotheses should be tested: <span class="math inline">\(\beta_{A1B1} = 0\)</span> and <span class="math inline">\(\beta_{A2B1}=0\)</span>.</li>
</ul></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a>contrast A<span class="sc">*</span>B <span class="dv">1</span> <span class="dv">0</span>,</span>
<span id="cb74-2"><a></a>        A<span class="sc">*</span>B <span class="dv">0</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="implementing-qualitative-explanatory-variables-in-sas" class="slide level2">
<h2>Implementing Qualitative Explanatory Variables in SAS</h2>
<ul>
<li>Use the <code>class</code> statement in <code>LOGISTIC</code> procedure to identify qualitative variables.</li>
<li>Interaction between Factors A and B are included in the model as <span class="math inline">\(A*B\)</span>
<ul>
<li>To include the saturated model of Factors A and B, you can write (response variable)=<code>A|B</code>.</li>
<li>You can add more than two factors in these statements.</li>
<li>Three-way interaction: <code>A*B*C</code></li>
<li>Saturated model for a three-factor model: <code>A|B|C</code></li>
</ul></li>
<li>If you wish to only include up to two-way interactions in a three-factor model: <code>A|B|C@2</code></li>
<li>You can introduce contrasts in the <code>contrast</code> statement.</li>
<li><code>effectplot</code> can be used to create interaction plots.</li>
<li><code>oddsratio</code> calculates odds ratios and graphs of confidence limits for odds ratios.</li>
</ul>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>The data set is from a cross-sectional prevalence study conducted to investigate textile worker complaints about respiratory symptoms experienced while working in the mills. Investigators were interested in whether occupational environment was related to prevalence of respiratory ailments associated with the disease byssinosis.</p>
<ul>
<li>Use logistic regression to model the probability of complaining based on workplace condition, years of employment, and smoking history. Include only up to two-way interaction effects.</li>
<li>Is there evidence of any two-way interactions at a significance level of 0.10?</li>
<li>Generate an interaction plot for these cases.</li>
<li>Generate the main effects using contrast statements.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Table</a></li><li><a href="#tabset-10-2">SAS Data Set</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p><img data-src="img/byss_C8.png"></p>
</div>
<div id="tabset-10-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a></a>data byss;</span>
<span id="cb75-2"><a></a>input work <span class="sc">$</span> years <span class="sc">$</span> smoke <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb75-3"><a></a>datalines ;</span>
<span id="cb75-4"><a></a>dusty <span class="sc">&lt;</span><span class="dv">10</span> yes yes <span class="dv">30</span> dusty <span class="sc">&lt;</span><span class="dv">10</span> yes no <span class="dv">203</span></span>
<span id="cb75-5"><a></a>dusty <span class="sc">&lt;</span><span class="dv">10</span> no yes <span class="dv">7</span> dusty <span class="sc">&lt;</span><span class="dv">10</span> no no <span class="dv">119</span></span>
<span id="cb75-6"><a></a>dusty <span class="sc">&gt;=</span><span class="dv">10</span> yes yes <span class="dv">57</span> dusty <span class="sc">&gt;=</span><span class="dv">10</span> yes no <span class="dv">161</span></span>
<span id="cb75-7"><a></a>dusty <span class="sc">&gt;=</span><span class="dv">10</span> no yes <span class="dv">11</span> dusty <span class="sc">&gt;=</span><span class="dv">10</span> no no <span class="dv">81</span></span>
<span id="cb75-8"><a></a>not <span class="sc">&lt;</span><span class="dv">10</span> yes yes <span class="dv">14</span> not <span class="sc">&lt;</span><span class="dv">10</span> yes no <span class="dv">1340</span></span>
<span id="cb75-9"><a></a>not <span class="sc">&lt;</span><span class="dv">10</span> no yes <span class="dv">12</span> not <span class="sc">&lt;</span><span class="dv">10</span> no no <span class="dv">1004</span></span>
<span id="cb75-10"><a></a>not <span class="sc">&gt;=</span><span class="dv">10</span> yes yes <span class="dv">24</span> not <span class="sc">&gt;=</span><span class="dv">10</span> yes no <span class="dv">1360</span></span>
<span id="cb75-11"><a></a>not <span class="sc">&gt;=</span><span class="dv">10</span> no yes <span class="dv">10</span> not <span class="sc">&gt;=</span><span class="dv">10</span> no no <span class="dv">986</span></span>
<span id="cb75-12"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>The data set is from a cross-sectional prevalence study conducted to investigate textile worker complaints about respiratory symptoms experienced while working in the mills. Investigators were interested in whether occupational environment was related to prevalence of respiratory ailments associated with the disease byssinosis.</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">Questions</a></li><li><a href="#tabset-11-2">SAS Code</a></li><li><a href="#tabset-11-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<ul>
<li>Use logistic regression to model the probability of complaining based on workplace condition, years of employment, and smoking history. Include only up to two-way interaction effects.</li>
<li>Is there evidence of any two-way interactions at a significance level of 0.10?</li>
<li>Generate an interaction plot for these cases.</li>
<li>Generate the main effects using contrast statements.</li>
</ul>
</div>
<div id="tabset-11-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a>proc logistic data<span class="ot">=</span>byss;</span>
<span id="cb76-2"><a></a>freq count;</span>
<span id="cb76-3"><a></a>class work <span class="fu">years</span>(<span class="at">ref=</span>first) <span class="fu">smoke</span>(<span class="at">ref=</span>first) <span class="sc">/</span>param<span class="ot">=</span>ref;</span>
<span id="cb76-4"><a></a>model <span class="fu">status</span>(<span class="at">event=</span>last) <span class="ot">=</span> work<span class="sc">|</span>years<span class="sc">|</span>smoke<span class="sc">@</span><span class="dv">2</span> <span class="sc">/</span>scale<span class="ot">=</span>none aggregate;</span>
<span id="cb76-5"><a></a>effectplot <span class="fu">interaction</span> (<span class="at">x=</span>work) <span class="sc">/</span> <span class="fu">at</span>(<span class="at">smoke=</span>all <span class="at">years=</span>all) link noobs;</span>
<span id="cb76-6"><a></a>oddsratios work;</span>
<span id="cb76-7"><a></a>contrast <span class="st">'work'</span> work <span class="dv">1</span>;</span>
<span id="cb76-8"><a></a>contrast <span class="st">'years'</span> years <span class="dv">1</span>;</span>
<span id="cb76-9"><a></a>contrast <span class="st">'smoke'</span> smoke <span class="dv">1</span>;</span>
<span id="cb76-10"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-11-3">
<p><span class="math inline">\(Work*Smoke\)</span> (p = 0.07) is significant at the 0.10 level.</p>
</div>
</div>
</div>
</section>
<section id="exercise-8" class="slide level2">
<h2>Exercise</h2>
<p>The following data come from a study on urinary tract infections. Investigators applied three treatments to patients who had either a complicated or uncomplicated diagnosis of urinary tract infection. Since complicated cases of urinary tract infections are difficult to cure, investigators were interested in whether the pattern of treatment differences is the same across diagnoses.</p>
<ul>
<li>Are we interested in main effects or interaction?</li>
<li>Is there a significant interaction effect?</li>
<li>Calculate the odds ratio between the diagnoses of UTI for different treatments.</li>
<li>Generate plots for the interaction and odds ratios.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">Table</a></li><li><a href="#tabset-12-2">SAS Data Set</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<p><img data-src="img/uti_C8.png"></p>
</div>
<div id="tabset-12-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a></a>data uti;</span>
<span id="cb77-2"><a></a>input diagnosis <span class="sc">:</span> <span class="er">$</span><span class="fl">13.</span> treatment <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb77-3"><a></a>datalines;</span>
<span id="cb77-4"><a></a>complicated A cured <span class="dv">78</span> complicated A not <span class="dv">28</span></span>
<span id="cb77-5"><a></a>complicated B cured <span class="dv">101</span> complicated B not <span class="dv">11</span></span>
<span id="cb77-6"><a></a>complicated C cured <span class="dv">68</span> complicated C not <span class="dv">46</span></span>
<span id="cb77-7"><a></a>uncomplicated A cured <span class="dv">40</span> uncomplicated A not <span class="dv">5</span></span>
<span id="cb77-8"><a></a>uncomplicated B cured <span class="dv">54</span> uncomplicated B not <span class="dv">5</span></span>
<span id="cb77-9"><a></a>uncomplicated C cured <span class="dv">34</span> uncomplicated C not <span class="dv">6</span></span>
<span id="cb77-10"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="exercise-9" class="slide level2">
<h2>Exercise</h2>
<p>The following data come from a study on urinary tract infections. Investigators applied three treatments to patients who had either a complicated or uncomplicated diagnosis of urinary tract infection. Since complicated cases of urinary tract infections are difficult to cure, investigators were interested in whether the pattern of treatment differences is the same across diagnoses.</p>
<ul>
<li>Are we interested in main effects or interaction?</li>
<li>Is there a significant interaction effect?</li>
<li>Calculate the odds ratio between the diagnoses of UTI for different treatments.</li>
<li>Generate plots for the interaction and odds ratios.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-13" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-13-1">SAS Code</a></li><li><a href="#tabset-13-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a>data uti;</span>
<span id="cb78-2"><a></a>input diagnosis <span class="sc">:</span> <span class="er">$</span><span class="fl">13.</span> treatment <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb78-3"><a></a>datalines;</span>
<span id="cb78-4"><a></a>complicated A cured <span class="dv">78</span> complicated A not <span class="dv">28</span></span>
<span id="cb78-5"><a></a>complicated B cured <span class="dv">101</span> complicated B not <span class="dv">11</span></span>
<span id="cb78-6"><a></a>complicated C cured <span class="dv">68</span> complicated C not <span class="dv">46</span></span>
<span id="cb78-7"><a></a>uncomplicated A cured <span class="dv">40</span> uncomplicated A not <span class="dv">5</span></span>
<span id="cb78-8"><a></a>uncomplicated B cured <span class="dv">54</span> uncomplicated B not <span class="dv">5</span></span>
<span id="cb78-9"><a></a>uncomplicated C cured <span class="dv">34</span> uncomplicated C not <span class="dv">6</span></span>
<span id="cb78-10"><a></a>;</span>
<span id="cb78-11"><a></a></span>
<span id="cb78-12"><a></a>proc logistic data<span class="ot">=</span>uti order<span class="ot">=</span>data;</span>
<span id="cb78-13"><a></a>freq count;</span>
<span id="cb78-14"><a></a>class diagnosis treatment <span class="sc">/</span>param<span class="ot">=</span>ref;</span>
<span id="cb78-15"><a></a>model <span class="fu">response</span>(<span class="at">event=</span><span class="st">'cured'</span>) <span class="ot">=</span> diagnosis<span class="sc">|</span>treatment <span class="sc">/</span>scale<span class="ot">=</span>none aggregate;</span>
<span id="cb78-16"><a></a>effectplot <span class="fu">interaction</span> (<span class="at">x=</span>treatment) <span class="sc">/</span> <span class="fu">at</span>(<span class="at">treatment=</span>all) link noobs;</span>
<span id="cb78-17"><a></a>oddsratios diagnosis;</span>
<span id="cb78-18"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-13-2">
<p>We are more interested in the interaction effect.</p>
<p>There is no significant interaction effect between diagnosis and treatment.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/odds_C8.png"></p>
<figcaption>Odds Ratios</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="continuous-and-ordinal-explanatory-variables" class="slide level2">
<h2>Continuous and Ordinal Explanatory Variables</h2>
<ul>
<li>Sometimes, continuous explanatory variables are unique in the data set. The sample size requirements for the goodness-of-fit tests will not be satisfied.
<ul>
<li>Income</li>
<li>Age</li>
<li>Years in University</li>
</ul></li>
<li>There should be at least 5 observations for the rarer outcome per parameter in the full model.
<ul>
<li>If there are 50 observations of the rarer outcome, then the maximum number of parameters supported is 10.</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Continuous variables should <strong>NOT</strong> be included in the class statement.</p>
</div>
</div>
</div>
</section>
<section id="model-selection-logistic-regression" class="slide level2">
<h2>Model Selection: Logistic Regression</h2>
<ul>
<li>We can use the residual score statistic 𝑄<span class="math inline">\(Q_{RS}\)</span> to determine up to what extent does the residuals from the model are linearly associated with other potential explanatory variables.
<ul>
<li>DF: difference in number of parameters between models</li>
</ul></li>
<li>The <code>SELECTION=FORWARD</code> option should be included in the <code>MODEL</code> statement. The <code>LOGISTIC</code> procedure will then start from an intercept model and build it up to the most parsimonious model.
<ul>
<li>The <code>INCLUDE</code> option tells SAS how many of the variables listed should always be included in the model.</li>
</ul></li>
</ul>
</section>
<section id="model-selection-logistic-regression-1" class="slide level2">
<h2>Model Selection: Logistic Regression</h2>
<ul>
<li>SAS also provides the Hosmer and Lemeshow Goodness-of-Fit test that tests the adequacy for these data by including the <code>lackfit</code> option.
<ul>
<li>Null hypothesis: The model is adequate, i.e., the residuals are explained by the model.</li>
</ul></li>
<li>The UNITS option specifies at what increment of the continuous variable will SAS calculate the odds ratios.</li>
</ul>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>The data set CORONARY is from the same study on coronary artery disease as previously analyzed; in addition, the continuous variable AGE is an explanatory variable. The variable ECG is now treated as an ordinal variable, with values 0, 1, and 2. ECG is coded 0 if the ST segment depression is less than 0.1, 1 if it equals 0.1 or higher but less than 0.2, and 2 if the ST segment depression is greater than or equal to 0.2. The variable AGE is age in years.</p>
<ul>
<li>What is the resulting logistic model?</li>
<li>Calculate the odds ratio for patients that differ in age by 10 years.</li>
</ul>
<h3 id="sas-data-set-2">SAS Data Set</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a></a></span>
<span id="cb79-2"><a></a>data coronary;</span>
<span id="cb79-3"><a></a>input sex ecg age ca <span class="sc">@</span><span class="er">@</span> ;</span>
<span id="cb79-4"><a></a>datalines;</span>
<span id="cb79-5"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">28</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">42</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">46</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">45</span> <span class="dv">0</span></span>
<span id="cb79-6"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">34</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">44</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">48</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">45</span> <span class="dv">1</span></span>
<span id="cb79-7"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">38</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">45</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">49</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">45</span> <span class="dv">1</span></span>
<span id="cb79-8"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">41</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">46</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">49</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">46</span> <span class="dv">1</span></span>
<span id="cb79-9"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">44</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">48</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">52</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">48</span> <span class="dv">1</span></span>
<span id="cb79-10"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">45</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">50</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">53</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">57</span> <span class="dv">1</span></span>
<span id="cb79-11"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">46</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">52</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">54</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">57</span> <span class="dv">1</span></span>
<span id="cb79-12"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">47</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">52</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">55</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">59</span> <span class="dv">1</span></span>
<span id="cb79-13"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">50</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">54</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">57</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">60</span> <span class="dv">1</span></span>
<span id="cb79-14"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">51</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">55</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">2</span> <span class="dv">46</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">63</span> <span class="dv">1</span></span>
<span id="cb79-15"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">51</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">59</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">2</span> <span class="dv">48</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">35</span> <span class="dv">0</span></span>
<span id="cb79-16"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">53</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">59</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">2</span> <span class="dv">57</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">37</span> <span class="dv">1</span></span>
<span id="cb79-17"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">55</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">32</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">2</span> <span class="dv">60</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">43</span> <span class="dv">1</span></span>
<span id="cb79-18"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">59</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">37</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">30</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">47</span> <span class="dv">1</span></span>
<span id="cb79-19"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">60</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">38</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">34</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">48</span> <span class="dv">1</span></span>
<span id="cb79-20"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">32</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">38</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">36</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">49</span> <span class="dv">0</span></span>
<span id="cb79-21"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">33</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">42</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">38</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">58</span> <span class="dv">1</span></span>
<span id="cb79-22"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">35</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">43</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">39</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">59</span> <span class="dv">1</span></span>
<span id="cb79-23"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">39</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">43</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">42</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">60</span> <span class="dv">1</span></span>
<span id="cb79-24"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">40</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">44</span> <span class="dv">1</span></span>
<span id="cb79-25"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>The data set CORONARY is from the same study on coronary artery disease as previously analyzed; in addition, the continuous variable AGE is an explanatory variable. The variable ECG is now treated as an ordinal variable, with values 0, 1, and 2. ECG is coded 0 if the ST segment depression is less than 0.1, 1 if it equals 0.1 or higher but less than 0.2, and 2 if the ST segment depression is greater than or equal to 0.2. The variable AGE is age in years.</p>
<div class="panel-tabset">
<ul id="tabset-14" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-14-1">SAS Code</a></li><li><a href="#tabset-14-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-88"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-88-1"><a href="#annotated-cell-88-1"></a>proc logistic descending;</span>
<span id="annotated-cell-88-2"><a href="#annotated-cell-88-2"></a>model ca<span class="ot">=</span>sex ecg age ecg<span class="sc">*</span>ecg age<span class="sc">*</span>age</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-88" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-88-3" class="code-annotation-target"><a href="#annotated-cell-88-3"></a>sex<span class="sc">*</span>ecg sex<span class="sc">*</span>age ecg<span class="sc">*</span>age <span class="sc">/</span>selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">3</span> details lackfit;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-88" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-88-4" class="code-annotation-target"><a href="#annotated-cell-88-4"></a>units age<span class="ot">=</span><span class="dv">10</span>;</span>
<span id="annotated-cell-88-5"><a href="#annotated-cell-88-5"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-88" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-88" data-code-lines="3" data-code-annotation="1"><code>include=3</code> indicates we are including the first three variables in the model. In this case, it’s sex, ecg, and age.</span>
</dd>
<dt data-target-cell="annotated-cell-88" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-88" data-code-lines="4" data-code-annotation="2">Looks at the odds ratio due to a 10-point difference in age.</span>
</dd>
</dl>
</div>
<div id="tabset-14-2">
<p>The logistic model is as follows:</p>
<p><span class="math display">\[
logit(\theta) = -5.64 + 1.35*Sex + 0.873*ECG +0.09*Age
\]</span> The odds of developing a coronary artery disease in patients older than 10 years is 2.5 times higher.</p>
</div>
</div>
</div>
</section>
<section id="exercise-10" class="slide level2">
<h2>Exercise</h2>
<p>Chapter8-Corn.csv includes the data of 82 plants from a randomized controlled trial that tests the effect of a new formulation of pesticide as well as the effect of using cover crops in planting corn. The farmers are also interested if the yield (measured in kg) is associated to the plant discoloration.</p>
<ul>
<li>Use the forward selection approach to determine if an interaction term between cover crop and pesticide needs to be included in the model.</li>
<li>What is the resulting logistic model?</li>
<li>Calculate the odds ratio for corn plants that have a yield difference of 2 kg.</li>
</ul>
</section>
<section id="exercise-11" class="slide level2">
<h2>Exercise</h2>
<p>Chapter8-Corn.csv includes the data of 82 plants from a randomized controlled trial that tests the effect of a new formulation of pesticide as well as the effect of using cover crops in planting corn. The farmers are also interested if the yield (measured in kg) is associated to the plant discoloration.</p>
<div class="panel-tabset">
<ul id="tabset-15" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-15-1">SAS Code</a></li><li><a href="#tabset-15-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a></a>proc logistic data<span class="ot">=</span>corn;</span>
<span id="cb80-2"><a></a>class <span class="fu">pesticide</span> (<span class="at">ref=</span><span class="st">"No"</span>) <span class="fu">covercrop</span> (<span class="at">ref=</span><span class="st">"No"</span>);</span>
<span id="cb80-3"><a></a>model <span class="fu">Discolored</span>(<span class="at">event=</span><span class="st">"Yes"</span>) <span class="ot">=</span> pesticide covercrop yield pesticide<span class="sc">*</span>covercrop<span class="sc">/</span>selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">3</span> details lackfit;</span>
<span id="cb80-4"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-15-2">
<p>There was no evidence to indicate that a pesticide*covercrop interaction needed to be included (<span class="math inline">\(Q_{RS} = 0.08, p=0.78\)</span>). The Hosmer-Lemeshow goodness-of-fit test also provides no evidence against model adequacy (<span class="math inline">\(\chi^2 = 6.9, p=0.55\)</span>).</p>
<p>The resulting logistic model is:</p>
<p><span class="math display">\[
logit(\theta) = 0.38 - 0.68*Pesticide - 1.10 * CoverCrop - 0.27*Yield
\]</span> The odds of discoloration decreases by 0.42 (1-0.58) times when the yield increases by 2 kg.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="model-diagnostics" class="title-slide slide level1 center">
<h1>Model Diagnostics</h1>

</section>
<section id="diagnostics" class="slide level2">
<h2>Diagnostics</h2>
<ul>
<li><p>We are interested in how a model fits our data and the lack of fit.</p>
<ul>
<li>Lack of fit: Should we still consider other variables to include in the model?</li>
</ul></li>
<li><p>Model fit: Pearson chi-square and deviance chi-square tests</p></li>
<li><p>Lack of fit: Pearson <em>residuals</em> and deviance <em>residuals</em></p></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Pearson residuals look at the difference between the observed and expected occurrences in a group. A value of 2 is usually indicative of a lack of fit.</li>
<li>Deviance residuals are the components that make up the deviance statistic</li>
<li>Likelihood residuals: weighted average of standardized Pearson and Deviance residuals</li>
</ul>
</div>
</div>
</div>
</section>
<section id="diagnostics-1" class="slide level2">
<h2>Diagnostics</h2>
<ul>
<li>These residuals can be viewed in graphical form.</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>In SAS, we can view the residual plots by specifying <code>PLOTS=INFLUENCE</code> in the <code>PROC LOGISTIC</code> statement. <code>stdres</code> specifies plots for standardized residuals</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a></a>proc logistic <span class="fu">plots</span>(label)<span class="ot">=</span><span class="fu">influence</span>(unpack stdres);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>Consider a modified version of the UTI data set. Generate the standardized residual plot, likelihood residual plot, and the Pearson chi-square residual plot.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a></a>data uti2;</span>
<span id="cb82-2"><a></a>input diagnosis <span class="sc">:</span> <span class="er">$</span><span class="fl">13.</span> treatment <span class="sc">$</span> response trials;</span>
<span id="cb82-3"><a></a>datalines;</span>
<span id="cb82-4"><a></a>complicated A <span class="dv">78</span> <span class="dv">106</span></span>
<span id="cb82-5"><a></a>complicated B <span class="dv">101</span> <span class="dv">112</span></span>
<span id="cb82-6"><a></a>complicated C <span class="dv">68</span> <span class="dv">114</span></span>
<span id="cb82-7"><a></a>uncomplicated A <span class="dv">40</span> <span class="dv">45</span></span>
<span id="cb82-8"><a></a>uncomplicated B <span class="dv">54</span> <span class="dv">59</span></span>
<span id="cb82-9"><a></a>uncomplicated C <span class="dv">34</span> <span class="dv">40</span></span>
<span id="cb82-10"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-10" class="slide level2">
<h2>Example</h2>
<p>Consider a modified version of the UTI data set. Generate the standardized residual plot, likelihood residual plot, and the Pearson chi-square residual plot.</p>
<div class="panel-tabset">
<ul id="tabset-16" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-16-1">SAS Code</a></li><li><a href="#tabset-16-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-91"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-91-1"><a href="#annotated-cell-91-1"></a>proc logistic data<span class="ot">=</span>uti2 </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-91" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-91-2" class="code-annotation-target"><a href="#annotated-cell-91-2"></a><span class="fu">plots</span>(label)<span class="ot">=</span><span class="fu">influence</span>(unpack stdres);</span>
<span id="annotated-cell-91-3"><a href="#annotated-cell-91-3"></a>class diagnosis treatment <span class="sc">/</span> param<span class="ot">=</span>ref;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-91" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-91-4" class="code-annotation-target"><a href="#annotated-cell-91-4"></a>model response<span class="sc">/</span>trials <span class="ot">=</span> diagnosis treatment;</span>
<span id="annotated-cell-91-5"><a href="#annotated-cell-91-5"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-91" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-91" data-code-lines="2" data-code-annotation="1"><code>plots=influence</code> yield all residual plots. <code>stdres</code> generates the standardized residual plot.</span>
</dd>
<dt data-target-cell="annotated-cell-91" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-91" data-code-lines="4" data-code-annotation="2">The model can also be expressed in terms of # of success/sample size;</span>
</dd>
</dl>
</div>
<div id="tabset-16-2">
<p>Residuals did not exceed 2, which indicate good fit.</p>
</div>
</div>
</div>
</section>
<section id="alternative-estimation-methods" class="slide level2">
<h2>Alternative Estimation Methods</h2>
<ul>
<li>We have been using maximum likelihood (ML) estimation to estimate values of <span class="math inline">\(\beta\)</span>, which leads to odds ratio estimates.
<ul>
<li>What if there are no successes or failures in your data? (Complete separation)</li>
<li>What if there is a small number of successes in the data?</li>
<li>What if the sample size is small?</li>
</ul></li>
<li>These conditions might yield non-converging solutions
<ul>
<li>Infinite odds ratios</li>
<li>Nonsensical odds ratio estimates</li>
</ul></li>
</ul>
</section>
<section id="complete-separation" class="slide level2">
<h2>Complete Separation</h2>

<img data-src="img/complete_C8.png" class="r-stretch quarto-figure-center"><p class="caption">Complete Separation: One level includes all successes or all failures.</p><div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If nearly all the observations have a probability of 1 of being allocated to the correct response group, then the data configuration may be one of <strong>quasi-complete separation</strong>.</p>
</div>
</div>
</div>
</section>
<section id="dealing-with-non-convergence" class="slide level2">
<h2>Dealing with non-convergence</h2>
<ul>
<li>Exact tests
<ul>
<li>Non-convergence due to small cell counts</li>
<li>Quasi-complete separation</li>
</ul></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The <code>EXACT</code> statement calculates the exact p-values for each variable/factor. Adding a <code>joint</code> option performs joint tests for the variables included. We use the results of the joint <em>probability</em> tests as its results are analogous to the Fisher’s exact test.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>The output of the exact statement typically yields a one-sided p-value for median unbiased estimates and one-sided confidence intervals. To get a two-sided 95% confidence interval, we can use a one-sided 97.5% confidence interval by specifying <code>alpha = 0.025</code>.</p>
</div>
</div>
</div>
<ul>
<li>Firth’s penalized likelihood
<ul>
<li>Complete separation/quasi-complete separation when there are continuous explanatory variables</li>
<li>Applies a penalty in the likelihood function.</li>
</ul></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Adding the <code>FIRTH</code> option to the model statement tells SAS to use the Firth penalized likelihood. <code>CLPARM=PL</code> uses the likelihood profile consistent with the Firth penalized likelihood method.</p>
</div>
</div>
</div>
</section>
<section id="example-11" class="slide level2">
<h2>Example</h2>
<p>Consider the following data set:</p>
<ul>
<li>Does this display complete separation, quasi-complete separation, or neither?</li>
<li>Calculate exact p-values for the effect of treatments A and B as well as the joint tests.</li>
<li>Calculate exact estimates for the odds ratio.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a></a>data preclinical;</span>
<span id="cb83-2"><a></a>input treatA <span class="sc">$</span> treatB <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb83-3"><a></a>datalines;</span>
<span id="cb83-4"><a></a>no no yes <span class="dv">0</span> no no no <span class="dv">0</span></span>
<span id="cb83-5"><a></a>yes no yes <span class="dv">8</span> yes no no <span class="dv">0</span></span>
<span id="cb83-6"><a></a>no yes yes <span class="dv">0</span> no yes no <span class="dv">2</span></span>
<span id="cb83-7"><a></a>yes yes yes <span class="dv">21</span> yes yes no <span class="dv">6</span></span>
<span id="cb83-8"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-12" class="slide level2">
<h2>Example</h2>
<p>Consider the following data set:</p>
<ul>
<li>Does this display complete separation, quasi-complete separation, or neither?</li>
<li>Calculate exact p-values for the effect of treatments A and B as well as the joint tests.</li>
<li>Calculate exact estimates for the odds ratio.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-17" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-17-1">SAS Code</a></li><li><a href="#tabset-17-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-17-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a></a>proc logistic data<span class="ot">=</span>preclinical;</span>
<span id="cb84-2"><a></a>freq count;</span>
<span id="cb84-3"><a></a>class <span class="fu">treatA</span> (<span class="at">ref=</span><span class="st">"no"</span>) <span class="fu">treatB</span> (<span class="at">ref=</span><span class="st">"no"</span>) <span class="sc">/</span>param<span class="ot">=</span>ref ;</span>
<span id="cb84-4"><a></a>model <span class="fu">response</span> (<span class="at">event=</span><span class="st">"yes"</span>) <span class="ot">=</span> treatA treatB ;</span>
<span id="cb84-5"><a></a>exact treatA treatB <span class="sc">/</span>joint estimate<span class="ot">=</span>both alpha<span class="ot">=</span><span class="fl">0.025</span>;</span>
<span id="cb84-6"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-17-2">
<p>The data shows quasi-complete separation.</p>
<p>The odds of a successful response is for those who received Treatment A is 7.06 (CI: 0.52, <span class="math inline">\(\infty\)</span>) times that of those who did not receive Treatment A. The exact p-value is 0.07.</p>
<p>The odds of a successful response is for those who received Treatment B is 0.35 (CI: 0, 2.85) times that of those who did not receive Treatment B.The exact p-value is 0.18.</p>
</div>
</div>
</div>
</section>
<section id="example-complete-separation" class="slide level2">
<h2>Example: Complete Separation</h2>
<p>Consider the following data set:</p>
<ul>
<li>Does this display complete separation, quasi-complete separation, or neither?</li>
<li>Calculate exact p-values for the effect of treatments A and B as well as the joint tests.</li>
<li>Calculate estimates for the odds ratio from the Firth penalized likelihood approach.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a></a>data complete;</span>
<span id="cb85-2"><a></a>input gender region count response <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb85-3"><a></a>datalines;</span>
<span id="cb85-4"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">5</span> <span class="dv">0</span></span>
<span id="cb85-5"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span></span>
<span id="cb85-6"><a></a><span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">175</span> <span class="dv">0</span></span>
<span id="cb85-7"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">53</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span></span>
<span id="cb85-8"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-complete-separation-1" class="slide level2">
<h2>Example: Complete Separation</h2>
<p>Consider the following data set:</p>
<ul>
<li>Does this display complete separation, quasi-complete separation, or neither?</li>
<li>Calculate exact p-values for the effect of treatments A and B as well as the joint tests.</li>
<li>Calculate estimates for the odds ratio from the Firth penalized likelihood approach.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-18" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-18-1">SAS Code</a></li><li><a href="#tabset-18-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-18-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a></a>proc logistic data<span class="ot">=</span>complete;</span>
<span id="cb86-2"><a></a>freq count;</span>
<span id="cb86-3"><a></a>model response <span class="ot">=</span> gender region <span class="sc">/</span> firth clparm<span class="ot">=</span>pl;</span>
<span id="cb86-4"><a></a>exact gender region<span class="sc">/</span>estimate<span class="ot">=</span>both;</span>
<span id="cb86-5"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-18-2">
<p>Based on the exact tests, there appears to be no effect of gender (p=0.5). However, there is an effect of region.</p>
<p>There is complete separation in region. We can use the penalized likelihood approach to calculate odds ratio estimates. The estimated odds ratio between region=1 and region = 0 is 10.5 (95% CI: 7.55, 16.26).</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="the-genmod-procedure" class="title-slide slide level1 center">
<h1>The <code>GENMOD</code> procedure</h1>

</section>
<section id="the-genmod-procedure-1" class="slide level2">
<h2>The <code>GENMOD</code> procedure</h2>
<ul>
<li>The <code>GENMOD</code> procedure uses generalized estimating equations in performing logistic regression when the responses are correlated.
<ul>
<li>Similar syntax as the <code>LOGISTIC</code> procedure.</li>
</ul></li>
<li>Reference levels are included in the estimates, but are automatically zeroed out by the <code>GENMOD</code> procedure.
<ul>
<li>You can set the reference levels by applying the <code>ref</code> option to each variable in the class statement.</li>
</ul></li>
</ul>
<h3 id="sample-code">Sample Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-11"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-11-1"><a href="#annotated-cell-11-1"></a>proc genmod;</span>
<span id="annotated-cell-11-2"><a href="#annotated-cell-11-2"></a>freq count;</span>
<span id="annotated-cell-11-3"><a href="#annotated-cell-11-3"></a>class A B;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-4" class="code-annotation-target"><a href="#annotated-cell-11-4"></a>model response <span class="ot">=</span> A B A<span class="sc">*</span>B<span class="sc">/</span>link<span class="ot">=</span>logit dist<span class="ot">=</span>binomial type3 aggregate;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-11-5" class="code-annotation-target"><a href="#annotated-cell-11-5"></a>estimate <span class="st">'[NAME OF CONTRAST]'</span> A <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>exp cl;</span>
<span id="annotated-cell-11-6"><a href="#annotated-cell-11-6"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="4" data-code-annotation="1">We need to specify the link function and the distribution as <code>GENMOD</code> can be used to model other distributions like Poisson. <code>type3</code> invokes the Type III tests of fixed effects, which looks at partial testing of each effect.</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="5" data-code-annotation="2"><code>GENMOD</code> does not output odds ratio by default. Hence, we use the <code>estimate</code> statement. The <code>estimate</code> statement follows the <code>contrast</code> statement, but since it calculates effect sizes, fractions cannot be eliminated by multiplying a factor unlike contrast statements.</span>
</dd>
</dl>
</section>
<section id="example-13" class="slide level2">
<h2>Example</h2>
<p>Consider the UTI example. Perform a logistic regression analysis using PROC GENMOD.</p>
</section>
<section id="example-14" class="slide level2">
<h2>Example</h2>
<p>Consider the UTI example. Perform a logistic regression analysis using PROC GENMOD.</p>
<h3 id="sas-code-11">SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-12"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1"></a>proc genmod data<span class="ot">=</span>uti;</span>
<span id="annotated-cell-12-2"><a href="#annotated-cell-12-2"></a>freq count;</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3"></a>class diagnosis treatment;</span>
<span id="annotated-cell-12-4"><a href="#annotated-cell-12-4"></a>model response <span class="ot">=</span> diagnosis treatment <span class="sc">/</span>link<span class="ot">=</span>logit dist<span class="ot">=</span>binomial type3 aggregate;</span>
<span id="annotated-cell-12-5"><a href="#annotated-cell-12-5"></a>contrast <span class="st">'treatment'</span> treatment <span class="dv">1</span> <span class="dv">0</span> <span class="sc">-</span><span class="dv">1</span> ,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-12-6" class="code-annotation-target"><a href="#annotated-cell-12-6"></a>                     treatment <span class="dv">0</span> <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span>;</span>
<span id="annotated-cell-12-7"><a href="#annotated-cell-12-7"></a>contrast <span class="st">'A-B'</span> treatment <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span> <span class="dv">0</span>;</span>
<span id="annotated-cell-12-8"><a href="#annotated-cell-12-8"></a>contrast <span class="st">'A-C'</span> treatment <span class="dv">1</span> <span class="dv">0</span> <span class="sc">-</span><span class="dv">1</span>;</span>
<span id="annotated-cell-12-9"><a href="#annotated-cell-12-9"></a>estimate <span class="st">'odds ratio of diagnosis'</span> diagnosis <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>exp;</span>
<span id="annotated-cell-12-10"><a href="#annotated-cell-12-10"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="6" data-code-annotation="1">This contrast should yield the same values as that of the Type 3 test for treatment.</span>
</dd>
</dl>
</section>
<section id="exercise-12" class="slide level2">
<h2>Exercise</h2>
<p>Consider the Byssinosis example. Perform a logistic regression analysis by applying an interaction model that includes up to two-way interactions in PROC GENMOD.</p>
<ul>
<li>Test for the main effect of workplace condition using contrasts. Compare the chi-square and p-values obtained through the Type 3 tests.</li>
<li>Test for the interaction of years of employment and smoking for dusty workplace conditions.</li>
<li>Calculate the odds ratio of developing byssinosis between the two work conditions.</li>
</ul>
<h3 id="sas-data-set-3">SAS Data Set</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a></a>data byss;</span>
<span id="cb87-2"><a></a>input work <span class="sc">$</span> years <span class="sc">$</span> smoke <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb87-3"><a></a>datalines ;</span>
<span id="cb87-4"><a></a>dusty <span class="sc">&lt;</span><span class="dv">10</span> yes yes <span class="dv">30</span> dusty <span class="sc">&lt;</span><span class="dv">10</span> yes no <span class="dv">203</span></span>
<span id="cb87-5"><a></a>dusty <span class="sc">&lt;</span><span class="dv">10</span> no yes <span class="dv">7</span> dusty <span class="sc">&lt;</span><span class="dv">10</span> no no <span class="dv">119</span></span>
<span id="cb87-6"><a></a>dusty <span class="sc">&gt;=</span><span class="dv">10</span> yes yes <span class="dv">57</span> dusty <span class="sc">&gt;=</span><span class="dv">10</span> yes no <span class="dv">161</span></span>
<span id="cb87-7"><a></a>dusty <span class="sc">&gt;=</span><span class="dv">10</span> no yes <span class="dv">11</span> dusty <span class="sc">&gt;=</span><span class="dv">10</span> no no <span class="dv">81</span></span>
<span id="cb87-8"><a></a>not <span class="sc">&lt;</span><span class="dv">10</span> yes yes <span class="dv">14</span> not <span class="sc">&lt;</span><span class="dv">10</span> yes no <span class="dv">1340</span></span>
<span id="cb87-9"><a></a>not <span class="sc">&lt;</span><span class="dv">10</span> no yes <span class="dv">12</span> not <span class="sc">&lt;</span><span class="dv">10</span> no no <span class="dv">1004</span></span>
<span id="cb87-10"><a></a>not <span class="sc">&gt;=</span><span class="dv">10</span> yes yes <span class="dv">24</span> not <span class="sc">&gt;=</span><span class="dv">10</span> yes no <span class="dv">1360</span></span>
<span id="cb87-11"><a></a>not <span class="sc">&gt;=</span><span class="dv">10</span> no yes <span class="dv">10</span> not <span class="sc">&gt;=</span><span class="dv">10</span> no no <span class="dv">986</span></span>
<span id="cb87-12"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="exercise-13" class="slide level2">
<h2>Exercise</h2>
<p>Consider the Byssinosis example. Perform a logistic regression analysis by applying an interaction model that includes up to two-way interactions in PROC GENMOD.</p>
<div class="panel-tabset">
<ul id="tabset-19" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-19-1">SAS Code</a></li><li><a href="#tabset-19-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-19-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a></a>proc genmod data<span class="ot">=</span>byss;</span>
<span id="cb88-2"><a></a>freq count;</span>
<span id="cb88-3"><a></a>class work years smoke;</span>
<span id="cb88-4"><a></a>model <span class="fu">status</span>(<span class="at">event=</span><span class="st">'yes'</span>) <span class="ot">=</span> work years smoke work<span class="sc">*</span>years work<span class="sc">*</span>smoke years<span class="sc">*</span>smoke <span class="sc">/</span>link<span class="ot">=</span>logit dist<span class="ot">=</span>binomial type3 aggregate;</span>
<span id="cb88-5"><a></a>contrast <span class="st">'work'</span> work <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span>; <span class="sc">*</span> same as the Type <span class="dv">3</span> Tests;</span>
<span id="cb88-6"><a></a>contrast <span class="st">'interaction'</span> work<span class="sc">*</span>years <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span> <span class="dv">1</span>;</span>
<span id="cb88-7"><a></a>estimate <span class="st">'OR for work'</span> work <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>e exp;</span>
<span id="cb88-8"><a></a>run; </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-19-2">
<p>The workplace effect has a <span class="math inline">\(\chi^2\)</span> = 114.10, p&lt;.0001. There is sufficient evidence of a workplace main effect.</p>
<p>The interaction term between years of work and smoking yielded a <span class="math inline">\(\chi^2= 0.91\)</span>, p=0.34. There is insufficient evidence of a workplace main effect.</p>
<p>The estimated odds of developing byssinosis for dusty work places is 11.6 (95% CI: 7.96, 17.03) times that of non-dusty places</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Chapter 8 - <a href="https://madfudolig.quarto.pub/eab770slides/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            // Attach click handler to the DT
            const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
            for (const annoteDlNode of annoteDls) {
              annoteDlNode.addEventListener('click', (event) => {
                const clickedEl = event.target;
                if (clickedEl !== selectedAnnoteEl) {
                  unselectCodeLines();
                  const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                  if (activeEl) {
                    activeEl.classList.remove('code-annotation-active');
                  }
                  selectCodeLines(clickedEl);
                  clickedEl.classList.add('code-annotation-active');
                } else {
                  // Unselect the line
                  unselectCodeLines();
                  clickedEl.classList.remove('code-annotation-active');
                }
              });
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>