<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Miguel Fudolig">
  <title>EAB770: Applied Statistical Methods for Categorical Data – EAB 770 - Chapter 2</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-146a52615c86749306b5caa224a9b489.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">EAB 770 - Chapter 2</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Miguel Fudolig 
</div>
</div>
</div>

</section>
<section>
<section id="chapter-2-2times2-tables" class="title-slide slide level1 center">
<h1>Chapter 2: <span class="math inline">\(2\times2\)</span> tables</h1>

</section>
<section id="outline" class="slide level2 smaller">
<h2>Outline</h2>
<ul>
<li>Contingency Tables</li>
<li>Chi-Square Statistics</li>
<li>Exact Tests</li>
<li>Difference in Proportions</li>
<li>Odds Ratio and Relative Risk</li>
<li>Sensitivity and Specificity</li>
<li>McNemar’s Test</li>
<li>Incidence Densities</li>
<li>Power Analysis</li>
</ul>
</section></section>
<section>
<section id="contingency-tables" class="title-slide slide level1 center">
<h1>Contingency Tables</h1>

</section>
<section id="x2-contingency-tables" class="slide level2">
<h2>2x2 Contingency Tables</h2>
<div class="columns">
<div class="column" style="width:40%; font-size: 75%">
<ul>
<li>Summarizes categorical data
<ul>
<li>Response variable has two levels</li>
<li>Exploratory variable has two levels</li>
</ul></li>
<li>Example:
<ul>
<li>Treatment/Placebo in RCT</li>
<li>Case/Control in a retrospective study</li>
</ul></li>
</ul>
</div><div class="column" style="width:60%">
<p><img data-src="img/ContingencyTable.png"></p>
</div></div>
</section>
<section id="contingency-tables-1" class="slide level2">
<h2>Contingency Tables</h2>
<p>We wish to determine whether there is an association between the row and column variables using the frequencies observed in each category.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Is the risk variable associated with the prevalence rate?</p>
</div>
</div>
</div>
<p>Recall: Intro to Statistics</p>
<ul>
<li>Chi-square tests of homogeneity <span class="math inline">\(H_0\)</span>: The two populations (rows) have the same distribution of the column variable</li>
<li>Chi-square tests of independence <span class="math inline">\(H_0\)</span>: The row and column variables are independent of each other.</li>
</ul>
</section>
<section id="contingency-tables-convention" class="slide level2">
<h2>Contingency Tables: Convention</h2>
<p>The indices of contingency tables denote the row and column of each number. For a total sample size of <span class="math inline">\(n\)</span>,</p>
<div class="columns">
<div class="column" style="width:40%; font-size: 85%">
<ul>
<li><span class="math inline">\(n_{xy}\)</span> denotes the number at row <span class="math inline">\(x\)</span> and column <span class="math inline">\(y\)</span>, also referred to as a joint frequency.</li>
<li>Seeing a (+) sign indicates that it is a marginal sum, also referred to as marginal frequencies.
<ul>
<li><span class="math inline">\(n_{x+}\)</span> denotes the sum of all columns in row <span class="math inline">\(x\)</span>.</li>
<li><span class="math inline">\(n_{+y}\)</span> denotes the sum of all rows in column <span class="math inline">\(y\)</span>.</li>
</ul></li>
<li>The placement of the + sign denotes the margin in which it was summed.</li>
</ul>
</div><div class="column" style="width:60%">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/ContingencyTable2.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div></div>
</section>
<section id="sas-example-contingency-table" class="slide level2">
<h2><code>SAS</code> Example: Contingency Table</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 125%">
<pre><code>data respire;
length treat $7. outcome $1. ;
input treat $ outcome $ count;
datalines;
placebo f 16
placebo u 48
test f 40
test u 20
;
run;

proc freq data=respire order=data;
weight count;
tables treat*outcome;
run;</code></pre>
</div><div class="column" style="width:50%; font-size: 75%">
<ul>
<li><code>proc freq</code> calls the <code>FREQ</code> procedure in <code>SAS</code>.
<ul>
<li>Not defining <code>data=respire</code> means <code>SAS</code> will automatically use the most recently run data set.</li>
</ul></li>
<li><code>order=data</code> means we are creating the rows and columns based on how the data was inputted, not alphabetical order.</li>
<li><code>weight</code> tells <code>SAS</code> the number of counts for each count</li>
<li><code>tables</code> creates the contingency table with row, column, and total percentages.</li>
<li><code>run;</code> tells <code>SAS</code> to run the code. <strong>This is important!</strong></li>
</ul>
</div></div>
</section>
<section id="contingency-tables-in-sas--long-format" class="slide level2">
<h2>Contingency Tables in <code>SAS</code>- Long Format</h2>
<p>When the data is not aggregated, the <code>FREQ</code> procedure can still be used to create contingency tables. We can use the import data procedure in SAS ODA to create <code>work.spore</code> from <code>Spore.csv</code> uploaded on Canvas.</p>
<pre><code>proc freq order=data data=severe;
weight count;
tables treat*outcome / chisq nocol;
exact or;
run;</code></pre>
</section>
<section id="contingency-tables-in-r" class="slide level2">
<h2>Contingency Tables in <code>R</code></h2>
<p>To create your own contingency table, you can use the <code>data.frame()</code> and <code>xtabs()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>count_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Row =</span> <span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>),</span>
<span id="cb3-2"><a></a>                         <span class="at">Column =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>,<span class="st">"X"</span>,<span class="st">"Y"</span>),</span>
<span id="cb3-3"><a></a>                         <span class="at">Count =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>))</span>
<span id="cb3-4"><a></a>count_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Row Column Count
1   A      X     2
2   A      Y     4
3   B      X     6
4   B      Y     8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">xtabs</span>(Count<span class="sc">~</span>Row<span class="sc">+</span>Column,<span class="at">data=</span>count_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Column
Row X Y
  A 2 4
  B 6 8</code></pre>
</div>
</div>
<p>You can also use the <code>expand.grid()</code> function to create combinations of variable levels.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>count_data <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Row =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"B"</span>), <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"B"</span>)),</span>
<span id="cb7-2"><a></a>                         <span class="at">Column =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>)))</span>
<span id="cb7-3"><a></a></span>
<span id="cb7-4"><a></a>count_data<span class="sc">$</span>Count <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>)</span>
<span id="cb7-5"><a></a></span>
<span id="cb7-6"><a></a>count_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Row Column Count
1   A      X     2
2   B      X     4
3   A      Y     6
4   B      Y     8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">xtabs</span>(Count<span class="sc">~</span>Row<span class="sc">+</span>Column,<span class="at">data=</span>count_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Column
Row X Y
  A 2 6
  B 4 8</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>ordered</code> can also be used to account for ordering in the row and column variables.</p>
</div>
</div>
</div>
</section>
<section id="contingency-tables-in-r--long-format" class="slide level2">
<h2>Contingency Tables in <code>R</code>- Long Format</h2>
<p>When the data is not aggregated, the <code>xtabs</code> function can still be used to create contingency tables. First, we import <code>Spore.csv</code> from Canvas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>spore <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Spore.csv"</span>,<span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a></a>spore</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ID Treatment         Period Spore
1   1      Test  Pre-Treatment  Full
2   1      Test  Mid-Treatment  Some
3   1      Test Post-Treatment  Some
4   2      Test  Pre-Treatment  Full
5   2      Test  Mid-Treatment  None
6   2      Test Post-Treatment  None
7   3      Test  Pre-Treatment  Full
8   3      Test  Mid-Treatment  Some
9   3      Test Post-Treatment  Some
10  4      Test  Pre-Treatment  Full
11  4      Test  Mid-Treatment  Some
12  4      Test Post-Treatment      
13  5      Test  Pre-Treatment  Full
14  5      Test  Mid-Treatment  None
15  5      Test Post-Treatment  None
16  1   Placebo  Pre-Treatment  Full
17  1   Placebo  Mid-Treatment  Full
18  1   Placebo Post-Treatment  Full
19  2   Placebo  Pre-Treatment  Full
20  2   Placebo  Mid-Treatment  Some
21  2   Placebo Post-Treatment  Some
22  3   Placebo  Pre-Treatment  Full
23  3   Placebo  Mid-Treatment  Some
24  3   Placebo Post-Treatment  Some
25  4   Placebo  Pre-Treatment  Full
26  4   Placebo  Mid-Treatment  Some
27  4   Placebo Post-Treatment  Some
28  5   Placebo  Pre-Treatment  Some
29  5   Placebo  Mid-Treatment      
30  5   Placebo Post-Treatment      
31  6      Test  Pre-Treatment  Full
32  6      Test  Mid-Treatment  Some
33  6      Test Post-Treatment  Some
34  7      Test  Pre-Treatment  Full
35  7      Test  Mid-Treatment  None
36  7      Test Post-Treatment  None
37  8      Test  Pre-Treatment  Full
38  8      Test  Mid-Treatment  Some
39  8      Test Post-Treatment  Some
40  9      Test  Pre-Treatment  Full
41  9      Test  Mid-Treatment  Some
42  9      Test Post-Treatment  None
43 10      Test  Pre-Treatment  Full
44 10      Test  Mid-Treatment  Some
45 10      Test Post-Treatment  Some
46  6   Placebo  Pre-Treatment  Full
47  6   Placebo  Mid-Treatment  Full
48  6   Placebo Post-Treatment  Full
49  7   Placebo  Pre-Treatment  Full
50  7   Placebo  Mid-Treatment  Full
51  7   Placebo Post-Treatment  Full
52  8   Placebo  Pre-Treatment  Full
53  8   Placebo  Mid-Treatment  Full
54  8   Placebo Post-Treatment  Full
55  9   Placebo  Pre-Treatment  Full
56  9   Placebo  Mid-Treatment  Some
57  9   Placebo Post-Treatment  Some
58 10   Placebo  Pre-Treatment  Full
59 10   Placebo  Mid-Treatment  Some
60 10   Placebo Post-Treatment  Some
61 11      Test  Pre-Treatment  Full
62 11      Test  Mid-Treatment  Some
63 11      Test Post-Treatment  None
64 12      Test  Pre-Treatment  Full
65 12      Test  Mid-Treatment  Some
66 12      Test Post-Treatment  None
67 13      Test  Pre-Treatment  Full
68 13      Test  Mid-Treatment  Some
69 13      Test Post-Treatment  Some
70 14      Test  Pre-Treatment  Full
71 14      Test  Mid-Treatment  None
72 14      Test Post-Treatment  None
73 15      Test  Pre-Treatment  Full
74 15      Test  Mid-Treatment  None
75 15      Test Post-Treatment  None
76 11   Placebo  Pre-Treatment  Full
77 11   Placebo  Mid-Treatment  Some
78 11   Placebo Post-Treatment  Some
79 12   Placebo  Pre-Treatment  Full
80 12   Placebo  Mid-Treatment  Some
81 12   Placebo Post-Treatment  Some
82 13   Placebo  Pre-Treatment  Full
83 13   Placebo  Mid-Treatment  Some
84 13   Placebo Post-Treatment  Some
85 14   Placebo  Pre-Treatment  Full
86 14   Placebo  Mid-Treatment  Full
87 14   Placebo Post-Treatment  Full
88 15   Placebo  Pre-Treatment  Full
89 15   Placebo  Mid-Treatment  Full
90 15   Placebo Post-Treatment  Full</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">xtabs</span>(<span class="sc">~</span>Treatment<span class="sc">+</span>Spore,<span class="at">data=</span>spore)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Spore
Treatment    Full None Some
  Placebo  2   26    0   17
  Test     1   15   13   16</code></pre>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Suppose a survey asking sophomores and senior students whether they agree with the statement “I enjoyed my in-person classes this semester.” yielded the following results.</p>
<p>Enter the data in <code>SAS</code> using the data step and generate the contingency tables. Name the data set <code>enjoy</code>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Strongly Agree</th>
<th style="text-align: center;">Agree</th>
<th style="text-align: center;">Neutral</th>
<th style="text-align: center;">Disagree</th>
<th style="text-align: center;">Strongly Disagree</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sophomore</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">Seniors</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">21</td>
</tr>
</tbody>
</table>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1"><code>R</code> Code</a></li><li><a href="#tabset-1-2"><code>SAS</code> Code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>OR</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>enjoy <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">year=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Sophomore"</span>,<span class="st">"Seniors"</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Sophomore"</span>,<span class="st">"Seniors"</span>)),</span>
<span id="cb15-2"><a></a>                     <span class="at">response =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"SA"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"D"</span>,<span class="st">"SD"</span>),<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"SA"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"D"</span>,<span class="st">"SD"</span>)))</span>
<span id="cb15-3"><a></a>enjoy<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">24</span>,<span class="dv">19</span>,<span class="dv">43</span>,<span class="dv">37</span>,<span class="dv">12</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">32</span>,<span class="dv">12</span>,<span class="dv">21</span>)</span>
<span id="cb15-4"><a></a><span class="fu">xtabs</span>(Count<span class="sc">~</span>year<span class="sc">+</span>response,<span class="at">data=</span>enjoy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           response
year        SA  A  N  D SD
  Sophomore 24 43 12 25 12
  Seniors   19 37 24 32 21</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2">
<p>There are many ways to code the <code>data</code> step. Here’s one way to do it!</p>
<pre><code>data enjoy;
length year $9. response $2.;
input year $ response $ count @@;
datalines;
sophomore SA 24 sophomore A 43
sophomore N 12
sophomore D 25 sophomore SD 12
senior SA 19 senior A 37
senior N 24
senior D 32 senior SD 21
;

proc freq order=data data=enjoy;
weight count;
tables year*response;
run;</code></pre>
</div>
</div>
</div>
</section>
<section id="independence" class="slide level2">
<h2>Independence</h2>
<p>If the two categorical variables are independent of each other, they are not associated.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Independence also means that the joint probability <span class="math inline">\(p_{ij}\)</span> can be determined solely on the basis of the marginal probabilities. These can be estimated using sample data.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="chi-square-statistics" class="title-slide slide level1 center">
<h1>Chi-square Statistics</h1>

</section>
<section id="chi-square-statistics-1" class="slide level2">
<h2>Chi-square Statistics</h2>
<p>The null hypothesis of no association (independence or homogeneity) between row and column variables imply that the totals are fixed. The probabilities of realization of each cell is determined by the hypergeometric distribution.</p>
</section>
<section id="chi-square-distribution" class="slide level2">
<h2>Chi-square distribution</h2>
<div class="columns">
<div class="column" style="width:60%; font-size: 85%">
<ul>
<li>The chi-square distribution, <span class="math inline">\(\chi_k^2\)</span>, is defined by the number of degrees of freedom 𝑘, where 𝑘≥1.</li>
<li>Properties include:
<ul>
<li>The value of <span class="math inline">\(\chi^2\)</span> can only assume non-negative values.</li>
<li>The <span class="math inline">\(\chi^2\)</span> distribution is asymmetric.</li>
<li>The sum of two or more independent chi-square variables also follows a chi-square distribution.</li>
<li>Mean: <span class="math inline">\(k\)</span>, Variance: <span class="math inline">\(2k\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%">
<p><img data-src="img/Chi-square.png"></p>
</div></div>
</section>
<section id="pearson-chi-square-statistic" class="slide level2">
<h2>Pearson Chi-square Statistic</h2>
<p>The Pearson Chi-square statistic can be written in terms of the joint frequency <code>n_ij</code> and the expected frequency <code>m_ij</code>.</p>
<p><span class="math display">\[Q_P = \sum_{i=1}^2\sum_{j=1}^2 \frac{(n_{ij}-m_{ij})^2}{m_{ij}}\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(m_{ij}\)</span> is the expected value of the number of observations in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>, <span class="math inline">\(n_{ij}\)</span>. The expected frequency <span class="math inline">\(m_{ij}\)</span> can be calculated based on the null hypothesis assumption.</p>
<ul>
<li>Independence: <span class="math inline">\(p_{ij}=p_{i+}p_{+j} \to m_{ij} = \frac{n_{i+}n_{+j}}{n}\)</span></li>
<li>Homogeneity: <span class="math inline">\(p_{i+}=n_{i+}/n; p_{+j}=n_{+j}/n\to m_{ij} = \frac{n_{i+}n_{+j}}{n}\)</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="mantel-haenszel-chi-square-statistic" class="slide level2 smaller">
<h2>Mantel-Haenszel Chi-square statistic</h2>
<p>Another form of the Chi-square statistic is the Mantel-Haenszel chi-square statistic, <span class="math inline">\(Q\)</span>. For <span class="math inline">\(2\times 2\)</span> contingency tables,</p>
<p><span class="math display">\[Q =  \frac{(n_{11}-m_{11})^2}{v_{11}}\]</span></p>
<p><span class="math display">\[m_{11} = n_{1+}n_{+1}/n; v_{11} = \frac{n_{1+}n_{2+}n_{+1}n_{+2}}{n^2(n-1)}\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(Q\)</span>, also known as the randomization chi-square, is based on the condition that all marginal totals are fixed and the probability distribution of random allocation of units to groups is given by the hypergeometric distribution. <span class="math inline">\(m_{11}\)</span> and <span class="math inline">\(v_{11}\)</span> are the mean and variance of the hypergeometric distribution based on the <span class="math inline">\(2 \times 2\)</span> table, respectively.</p>
</div>
</div>
</div>
</section>
<section id="pearson-chi-square-vs.-mantel-haenszel-chi-square" class="slide level2">
<h2>Pearson Chi-square vs.&nbsp;Mantel-Haenszel Chi-square</h2>
<p>The relationship can also be approximated by the following relation:</p>
<p><span class="math display">\[Q_P = \frac{n}{n-1}Q\]</span></p>
<p>For large <span class="math inline">\(n\)</span>, both the MH chi-square and the Pearson chi-square approach a chi-square distribution with <span class="math inline">\(1\)</span> degree of freedom (<span class="math inline">\(\chi^2_1\)</span>).</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Rule of thumb for <span class="math inline">\(Q_P\)</span>: The expected value for each cell should be at least 5, i.e.&nbsp;<span class="math inline">\(m_{ij} \geq 5\)</span> for all <span class="math inline">\(i,j\)</span></p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Because the MH chi-square statistic comes from a hypergeometric distribution, the MH chi-square statistic can be used for small samples using exact calculations of p-values from the hypergeometric distribution. This is not possible with the Pearson chi-square.</p>
<p>The MH chi-square statistic can also be extended for use in the presence of covariates/stratifying variables.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing" class="slide level2">
<h2>Hypothesis testing</h2>
<p>The null hypothesis of no association states that there is no association between row and column variables. - Assuming this is true and assumptions are satisfied, <span class="math inline">\(Q\)</span> and <span class="math inline">\(Q_P\)</span> follow a <span class="math inline">\(\chi^2_1\)</span> distribution for <span class="math inline">\(2\times2\)</span> tables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The p-values are given by <span class="math inline">\(P(\chi^2 &gt; Q_P)\)</span> and <span class="math inline">\(P(\chi^2 &gt; Q)\)</span> for Pearson and MH Chi-squares, respectively.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing-sas" class="slide level2">
<h2>Hypothesis Testing: SAS</h2>

<img data-src="img/Freq_vcd.png" class="r-stretch"></section>
<section id="sas-freq-procedure" class="slide level2">
<h2><code>SAS</code>: FREQ procedure</h2>
<ul>
<li>The <code>weight</code> statement tells SAS if there is an aggregated count variable present in the data set.</li>
<li>The <code>tables</code> statement tells SAS to create a contingency table using the stated variables.
<ul>
<li>Under tables, you can include the <code>cmh</code> or the <code>chisq</code> option to calculate the randomization and Pearson chi-square values.</li>
</ul></li>
</ul>
<p>Shown below is a sample <code>SAS</code> code.</p>
<pre><code>proc freq;
weight count;
tables a*b/ cmh chisq;
run;</code></pre>
</section>
<section id="r-vcdextra" class="slide level2">
<h2><code>R</code>: <code>vcdExtra</code></h2>
<p>In <code>R</code>, the <code>vcdExtra</code> package is required to perform the Mantel-Haenszel chi-square tests. The function <code>CMHtest()</code> provides the value of the Mantel-Haenszel statistic, while <code>chisq.test()</code> provides the Pearson chi-square statistic.</p>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>The table shows the information from a randomized clinical trial that compared an experimental treatment to a placebo treatment for a respiratory disorder.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb19-2"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Test"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Test"</span>)),</span>
<span id="cb19-3"><a></a>                  <span class="at">Outcome =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>)))</span>
<span id="cb19-4"><a></a></span>
<span id="cb19-5"><a></a>dat<span class="sc">$</span>count <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">40</span>,<span class="dv">48</span>,<span class="dv">20</span>)</span>
<span id="cb19-6"><a></a></span>
<span id="cb19-7"><a></a><span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Placebo        16          48
  Test           40          20</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Questions</a></li><li><a href="#tabset-2-2">SAS Code</a></li><li><a href="#tabset-2-3">R Code</a></li><li><a href="#tabset-2-4">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<ul>
<li>What is the Pearson chi-square value?</li>
<li>What is the Mantel-Haenszel chi-square value?</li>
<li>Is there strong evidence of an association between treatment and outcome?</li>
</ul>
</div>
<div id="tabset-2-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21" data-code-line-numbers="3,11,13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>SAScode <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb21-2"><a></a><span class="st">data respire;</span></span>
<span id="cb21-3"><a></a><span class="st">input treat $ outcome $ count; </span></span>
<span id="cb21-4"><a></a><span class="st">datalines;</span></span>
<span id="cb21-5"><a></a><span class="st">test f 40</span></span>
<span id="cb21-6"><a></a><span class="st">test u 20</span></span>
<span id="cb21-7"><a></a><span class="st">placebo f 16</span></span>
<span id="cb21-8"><a></a><span class="st">placebo u 48</span></span>
<span id="cb21-9"><a></a><span class="st">;</span></span>
<span id="cb21-10"><a></a></span>
<span id="cb21-11"><a></a><span class="st">proc freq data=respire order=data; </span></span>
<span id="cb21-12"><a></a><span class="st">weight count;</span></span>
<span id="cb21-13"><a></a><span class="st">tables treat*outcome/chisq; </span></span>
<span id="cb21-14"><a></a><span class="st">run;</span></span>
<span id="cb21-15"><a></a><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-2-3">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Test"</span>),</span>
<span id="cb22-2"><a></a>                  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a></a><span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">40</span>,<span class="dv">48</span>,<span class="dv">20</span>))</span>
<span id="cb22-4"><a></a></span>
<span id="cb22-5"><a></a><span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat) <span class="ot">-&gt;</span> dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Pearson Chi-square (without continuity adjustment)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb23-2"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb23-3"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Test"</span>),</span>
<span id="cb23-4"><a></a>                  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb23-5"><a></a><span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">40</span>,<span class="dv">48</span>,<span class="dv">20</span>))</span>
<span id="cb23-6"><a></a></span>
<span id="cb23-7"><a></a><span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Placebo        16          48
  Test           40          20</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">chisq.test</span>(dat_cc,<span class="at">correct=</span>F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  dat_cc
X-squared = 21.709, df = 1, p-value = 3.174e-06</code></pre>
</div>
</div>
<p>Randomization Chi-square</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="co"># install.packages("vcdExtra")</span></span>
<span id="cb27-2"><a></a><span class="fu">library</span>(vcdExtra)</span>
<span id="cb27-3"><a></a>CMH_CC <span class="ot">&lt;-</span><span class="fu">CMHtest</span>(dat_cc) </span>
<span id="cb27-4"><a></a>CMH_CC</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Treatment by Outcome 

                 AltHypothesis  Chisq Df       Prob
cor        Nonzero correlation 21.534  1 3.4768e-06
rmeans  Row mean scores differ 21.534  1 3.4768e-06
cmeans  Col mean scores differ 21.534  1 3.4768e-06
general    General association 21.534  1 3.4768e-06</code></pre>
</div>
</div>
</div>
<div id="tabset-2-4">
<ul>
<li><p>What is the Pearson chi-square value? <strong>21.7</strong></p></li>
<li><p>What is the Mantel-Haenszel chi-square value? <strong>21.53</strong></p></li>
<li><p>Is there strong evidence of an association between treatment and outcome?</p>
<ul>
<li><em>p &lt; 0.0001</em>; There is strong evidence of an association between the test treatment and the outcome.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>Suppose we wish to determine if the frequency of falls is related to wheelchair use for Polio survivors. The data is shown in the table.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Wheelchair
Fall         Yes  No
  Fallers     62 121
  Nonfallers  18  32</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Questions</a></li><li><a href="#tabset-3-2"><code>SAS</code> code</a></li><li><a href="#tabset-3-3"><code>R</code></a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ul>
<li>Write the code to enter the data and analyze using the FREQ procedure.</li>
<li>What is the Pearson chi-square value?</li>
<li>What is the Mantel-Haenszel chi-square value?</li>
<li>Using a significance level of 0.05, do we have sufficient evidence to warrant the conclusion that wheelchair use and falling are associated?</li>
</ul>
</div>
<div id="tabset-3-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30" data-code-line-numbers="2,10,12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a>data wheelchair;</span>
<span id="cb30-2"><a></a>input fall <span class="sc">$</span> wheelchair <span class="sc">$</span> count;</span>
<span id="cb30-3"><a></a>datalines;</span>
<span id="cb30-4"><a></a>f yes <span class="dv">62</span></span>
<span id="cb30-5"><a></a>n yes <span class="dv">18</span></span>
<span id="cb30-6"><a></a>f no <span class="dv">121</span></span>
<span id="cb30-7"><a></a>n no <span class="dv">32</span></span>
<span id="cb30-8"><a></a>;</span>
<span id="cb30-9"><a></a></span>
<span id="cb30-10"><a></a>proc freq data<span class="ot">=</span>wheelchair order<span class="ot">=</span>data;</span>
<span id="cb30-11"><a></a>weight count;</span>
<span id="cb30-12"><a></a>tables fall<span class="sc">*</span>wheelchair<span class="sc">/</span>chisq;</span>
<span id="cb30-13"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-3-3">
<p>Pearson Chi-square (without continuity adjustment)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb31-2"><a></a></span>
<span id="cb31-3"><a></a><span class="fu">chisq.test</span>(dat_cc, <span class="at">correct =</span> F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  dat_cc
X-squared = 0.078299, df = 1, p-value = 0.7796</code></pre>
</div>
</div>
<p>Randomization Chi-square</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="co"># install.packages("vcdExtra")</span></span>
<span id="cb33-2"><a></a>CMH_CC <span class="ot">&lt;-</span><span class="fu">CMHtest</span>(dat_cc) </span>
<span id="cb33-3"><a></a>CMH_CC<span class="sc">$</span>table </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Chisq Df     Prob
cor     0.07796307  1 0.780077
rmeans  0.07796307  1 0.780077
cmeans  0.07796307  1 0.780077
general 0.07796307  1 0.780077</code></pre>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="exact-methods" class="title-slide slide level1 center">
<h1>Exact Methods</h1>

</section>
<section id="fishers-exact-test" class="slide level2">
<h2>Fisher’s Exact Test</h2>
<p>The chi-square distribution assumption for <span class="math inline">\(Q\)</span> and <span class="math inline">\(Q_P\)</span> includes a large sample assumption.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>What if <span class="math inline">\(m_{ij} &lt; 5\)</span>?</p>
</div>
</div>
</div>
<p>The <strong>Fisher’s Exact Test</strong> can be used to analyze these contingency tables.</p>
</section>
<section id="fishers-exact-test-1" class="slide level2">
<h2>Fisher’s Exact Test</h2>
<p>Fisher’s Exact Test is based on the hypergeometric distribution. The test calculates an <em>exact</em> p-value, unlike the chi-square test which only uses an approximation.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The test is easy to calculate for <span class="math inline">\(2 \times 2\)</span> and total sample sizes below 50, but computationally expensive as the number increases.</p>
</div>
</div>
</div>
<p>The p-value can be calculated using the hypergeometric distribution with the following parameters: <span class="math inline">\(Hyper(N=n,m=n_{+1},k=n_{1+})\)</span></p>
</section>
<section id="fishers-exact-test-hypotheses" class="slide level2">
<h2>Fisher’s Exact Test: Hypotheses</h2>
<p>Null hypothesis <span class="math inline">\(H_0\)</span>: there is no association between the row and column variables</p>
<ul>
<li><p>One sided <span class="math inline">\(H_a\)</span>: There is a positive/negative association between the row and column variables. OR One combination of the row and column variable levels is more favored compared to the others.</p></li>
<li><p>Two-sided <span class="math inline">\(H_a\)</span>: there is an association between the row and column variables.</p></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>To solve the exact p-value using the hypergeometric distribution, only add probabilities of outcomes that have lower probabilities than the observed value in the direction of the alternative hypotheses.</p>
</div>
</div>
</div>
</section>
<section id="fishers-exact-test-sas" class="slide level2">
<h2>Fisher’s Exact Test: SAS</h2>
<p>Including the <code>exact</code> or the <code>chisq</code> option under the <code>tables</code> statement will yield the results of the exact test.</p>
<pre><code>proc freq;
weight count;
tables a*b/ exact chisq;
run;</code></pre>
</section>
<section id="fishers-exact-test-r" class="slide level2">
<h2>Fisher’s Exact Test: R</h2>
<p>The <code>fisher.test()</code> can perform Fisher’s exact test in <code>R</code> using a contingency table as input.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">fisher.test</span>(contingency_table,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The table shown shows data from a study on treatments for healing severe infections. Calculate the exact p-value of this contingency table using the Fisher’s Exact Test.</p>
<ul>
<li>Under the alternative hypothesis: The test treatment is positively associated with the outcome.</li>
<li>Under the alternative hypothesis: The test treatment is associated with the outcome.</li>
<li>At a significance level of 0.10, do you have enough evidence to conclude that the treatment is associated with the outcome?</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Test            5           1
  Control         1           3</code></pre>
</div>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">SAS Code</a></li><li><a href="#tabset-4-2">R Code</a></li><li><a href="#tabset-4-3">Manual p-values: 1-sided</a></li><li><a href="#tabset-4-4">Manual p-values: 2-sided</a></li><li><a href="#tabset-4-5">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>data severe;</span>
<span id="cb38-2"><a></a>input treat <span class="sc">$</span> outcome <span class="sc">$</span> count;</span>
<span id="cb38-3"><a></a>datalines;</span>
<span id="cb38-4"><a></a>Test f <span class="dv">5</span></span>
<span id="cb38-5"><a></a>Test u <span class="dv">1</span></span>
<span id="cb38-6"><a></a>Control f <span class="dv">1</span></span>
<span id="cb38-7"><a></a>Control u <span class="dv">3</span></span>
<span id="cb38-8"><a></a>;</span>
<span id="cb38-9"><a></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>severe;</span>
<span id="cb38-10"><a></a>weight count;</span>
<span id="cb38-11"><a></a>tables treat<span class="sc">*</span>outcome <span class="sc">/</span> chisq nocol;</span>
<span id="cb38-12"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Test"</span>,<span class="st">"Control"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Test"</span>,<span class="st">"Control"</span>)),</span>
<span id="cb39-2"><a></a>                  <span class="at">Outcome =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>))) </span>
<span id="cb39-3"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>)</span>
<span id="cb39-4"><a></a></span>
<span id="cb39-5"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat) </span>
<span id="cb39-6"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Test            5           1
  Control         1           3</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">fisher.test</span>(dat_cc, <span class="at">alternative =</span> <span class="st">"greater"</span>) <span class="co"># one-sided</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  dat_cc
p-value = 0.119
alternative hypothesis: true odds ratio is greater than 1
95 percent confidence interval:
 0.5819    Inf
sample estimates:
odds ratio 
  10.29391 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a><span class="fu">fisher.test</span>(dat_cc,<span class="at">alternative=</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  dat_cc
p-value = 0.1905
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.40161 930.24692
sample estimates:
odds ratio 
  10.29391 </code></pre>
</div>
</div>
</div>
<div id="tabset-4-3">
<ul>
<li>One-sided hypothesis (+) corresponds to the the probabilities <span class="math inline">\(P(X&gt;=5)\)</span> which are equal to or less than <span class="math inline">\(P(X=5)\)</span>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>N <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">+</span><span class="dv">1</span><span class="sc">+</span><span class="dv">1</span><span class="sc">+</span><span class="dv">3</span></span>
<span id="cb45-2"><a></a>m <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb45-3"><a></a>k <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb45-4"><a></a></span>
<span id="cb45-5"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">5</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1142857</code></pre>
</div>
</div>
<p>For X &gt; 5, the only possible value of X is 6.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">6</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004761905</code></pre>
</div>
</div>
<p>The p-value is then the sum of these two probabilities:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">5</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">6</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1190476</code></pre>
</div>
</div>
</div>
<div id="tabset-4-4">
<ul>
<li>Two-sided hypothesis need to include values <span class="math inline">\(P(X&lt;5)\)</span> that have probabilities lower than <span class="math inline">\(P(X=5)\)</span>. These probabilities will be added to the one-sided p-value to get the two-sided p-value.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">4</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4285714</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">3</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3809524</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">2</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07142857</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">1</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><span class="math inline">\(P(X=0)\)</span>, <span class="math inline">\(P(X=1)\)</span>, and <span class="math inline">\(P(X=2)\)</span> have lower probabilities compared to <span class="math inline">\(P(X=5)\)</span>. Hence, we add these probabilities to the one-sided p-value to get the two-sided p-value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">5</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">6</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">2</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">1</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1904762</code></pre>
</div>
</div>
</div>
<div id="tabset-4-5">
<ul>
<li>Under the alternative hypothesis: The test treatment is positively associated with the outcome. p=0.119</li>
<li>Under the alternative hypothesis: The test treatment is associated with the outcome. p= 0.1905</li>
<li>At a significance level of 0.10, do you have enough evidence to conclude that the treatment is associated with the outcome? <strong>At</strong> <span class="math inline">\(\alpha = 0.10\)</span>, <strong>we do not have sufficient evidence to conclude that treatment is associated with the outcomes in healing severe infections.</strong></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In SAS, be careful when selecting which one-sided alternative hypothesis to interpret from the results!</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Fisher’s experiment: A number of individuals gathered together for afternoon tea. A lady in the group said that she could differentiate between whether the milk or the tea was poured first into a cup. Fisher suggested to pour tea first into four cups and to pour milk first into four cups. The lady was blinded to which cups had milk or tea poured first, but she knew there were four of each. The contingency table is shown below. At <span class="math inline">\(\alpha=0.05\)</span>, do we have sufficient evidence to conclude that the lady can differentiate tea based on how they were poured?</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Contingency Table</a></li><li><a href="#tabset-5-2">SAS Code</a></li><li><a href="#tabset-5-3">R <code>fisher.exact()</code></a></li><li><a href="#tabset-5-4">Hypergeometric: <code>R</code></a></li><li><a href="#tabset-5-5">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      Guess
Actual Milk Tea
  Milk    3   1
  Tea     1   3</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a></a>data tea;</span>
<span id="cb64-2"><a></a>input actual<span class="sc">$</span> guess <span class="sc">$</span> count;</span>
<span id="cb64-3"><a></a>datalines;</span>
<span id="cb64-4"><a></a>milk milk <span class="dv">3</span></span>
<span id="cb64-5"><a></a>milk tea <span class="dv">1</span></span>
<span id="cb64-6"><a></a>tea milk <span class="dv">1</span></span>
<span id="cb64-7"><a></a>tea tea <span class="dv">3</span></span>
<span id="cb64-8"><a></a>;</span>
<span id="cb64-9"><a></a></span>
<span id="cb64-10"><a></a>proc freq data<span class="ot">=</span>tea order<span class="ot">=</span>data;</span>
<span id="cb64-11"><a></a>weight count;</span>
<span id="cb64-12"><a></a>tables actual<span class="sc">*</span>guess<span class="sc">/</span>chisq;</span>
<span id="cb64-13"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Direction is specified, hence we need to use the “&gt;” one-sided p-value.</p>
</div>
<div id="tabset-5-3">
<p>Direction is specified, hence we need to use the “&gt;” one-sided p-value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Actual=</span><span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Milk"</span>,<span class="st">"Tea"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Milk"</span>,<span class="st">"Tea"</span>)),</span>
<span id="cb65-2"><a></a>                  <span class="at">Guess =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Milk"</span>,<span class="st">"Tea"</span>),<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Milk"</span>,<span class="st">"Tea"</span>)))</span>
<span id="cb65-3"><a></a></span>
<span id="cb65-4"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>)</span>
<span id="cb65-5"><a></a></span>
<span id="cb65-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat)</span>
<span id="cb65-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Guess
Actual Milk Tea
  Milk    3   1
  Tea     1   3</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a></a><span class="fu">fisher.test</span>(dat_cc, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  dat_cc
p-value = 0.2429
alternative hypothesis: true odds ratio is greater than 1
95 percent confidence interval:
 0.3135693       Inf
sample estimates:
odds ratio 
  6.408309 </code></pre>
</div>
</div>
</div>
<div id="tabset-5-4">
<p>Direction is specified, hence we need to use the “&gt;” one-sided p-value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a></a>N <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb69-2"><a></a>m <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb69-3"><a></a>k <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb69-4"><a></a></span>
<span id="cb69-5"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">3</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2285714</code></pre>
</div>
</div>
<p>The only other possible value of <span class="math inline">\(X\)</span> is <span class="math inline">\(X=4\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">4</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01428571</code></pre>
</div>
</div>
<p>To get the one-sided p-value, we need to add these two probabilities:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a></a><span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">3</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k) <span class="sc">+</span> <span class="fu">dhyper</span>(<span class="at">x=</span><span class="dv">4</span>,<span class="at">m=</span>m,<span class="at">n=</span>N<span class="sc">-</span>m,<span class="at">k=</span>k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2428571</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Note that we needed to add <span class="math inline">\(P(X=4)\)</span> because its value is less than that of <span class="math inline">\(P(X=3)\)</span>.</p>
</div>
</div>
</div>
</div>
<div id="tabset-5-5">
<p>The resulting p-value is 0.2429. At significance level <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. We have no sufficient evidence to conclude that the lady can differentiate tea based on how they were poured.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="difference-in-proportions" class="title-slide slide level1 center">
<h1>Difference in Proportions</h1>

</section>
<section id="difference-in-proportions-1" class="slide level2">
<h2>Difference in Proportions</h2>
<p>We are often interested in comparing two independent populations. For binary responses, we can compare proportions of success.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Recall from Intro to Stats course: we can estimate the confidence intervals and standardized statistics for the difference of two proportions.</p>
</div>
</div>
</div>
</section>
<section id="difference-in-proportions-estimation" class="slide level2">
<h2>Difference in Proportions: Estimation</h2>
<p>Estimating the difference of the two proportions involves calculating the confidence intervals. There are different methods to calculate the confidence interval for the difference in proportion.</p>

<img data-src="img/DiffProp1.png" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Independence of the two populations (Groups 1 and 2) mean that we have two independent binomial distributions.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-wald" class="slide level2">
<h2>Confidence Intervals: Wald</h2>
<p>The commonly used confidence interval in estimating difference in proportions is the <strong>Wald</strong> confidence interval.</p>
<p><span class="math display">\[p_1-p_2 \pm z_{1-\alpha/2}\sqrt{\frac{p_1(1-p_1)}{n_{1+}} + \frac{p_2(1-p_2)}{n_{2+}}}\]</span></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>This CI fails when <span class="math inline">\(p_1\)</span> or <span class="math inline">\(p_2\)</span> are close to the extreme values (0 and 1). this CI does not account for the discreteness of the data.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-corrected-wald" class="slide level2">
<h2>Confidence Intervals: Corrected Wald</h2>
<p>We introduce a correction term to the Wald confidence interval to account for the continuity of the data.</p>
<p><span class="math display">\[p_1-p_2 \pm z_{1-\alpha/2}\sqrt{\frac{p_1(1-p_1)}{n_{1+}} + \frac{p_2(1-p_2)}{n_{2+}}} +1/2 (1/n_{1+} +1/n_{2+} )\]</span></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>This CI still fails when <span class="math inline">\(p_1\)</span> or <span class="math inline">\(p_2\)</span> are close to the extreme values (0 and 1).</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-agresti-caffo" class="slide level2">
<h2>Confidence Intervals: Agresti-Caffo</h2>
<p>We introduce a correction term to the Wald confidence interval to account for the extreme values.</p>
<p><span class="math display">\[p_1-p_2 \pm z_{1-\alpha/2}\sqrt{\frac{\tilde{p}_1(1-\tilde{p}_1)}{n_{1+}+2} + \frac{\tilde{p}_2(1-\tilde{p}_2)}{n_{2+}+2}}  \]</span> where</p>
<p><span class="math display">\[\tilde{p}_1 = (n_{11}+1)/(n_{1+}+2) ; \tilde{p}_2 = (n_{21}+1)/(n_{2+}+2)\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This correction keeps the coverage of the confidence interval at 95% for all possible values of <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="other-confidence-intervals" class="slide level2">
<h2>Other Confidence Intervals</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 26%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Confidence Intervals</th>
<th>SAS code</th>
<th>R code</th>
<th>Adjustment Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wald</td>
<td><code>wald</code></td>
<td>“wald”</td>
<td>Default</td>
</tr>
<tr class="even">
<td>Corrected Wald</td>
<td><code>correct</code></td>
<td>“waldcc”</td>
<td>Continuity correction</td>
</tr>
<tr class="odd">
<td>Agresti-Caffo</td>
<td><code>ac</code></td>
<td>“ac”</td>
<td>Improved Coverage</td>
</tr>
<tr class="even">
<td>Miettinen-Nurminen</td>
<td><code>mn</code></td>
<td>“mn”</td>
<td>Uses goodness-of-fit to improve coverage</td>
</tr>
<tr class="odd">
<td>Newcombe</td>
<td><code>newcombe</code></td>
<td>“scorecc”</td>
<td>hybrid interval that does well for small counts</td>
</tr>
<tr class="even">
<td>Hauck-Anderson</td>
<td><code>ha</code></td>
<td>“ha”</td>
<td>Accounts for row totals</td>
</tr>
</tbody>
</table>
</section>
<section id="confidence-intervals-sas" class="slide level2">
<h2>Confidence Intervals: <code>SAS</code></h2>
<ul>
<li>The FREQ procedure has all mentioned confidence intervals
<ul>
<li>The options included in the <code>tables</code> statement are included in the previous slide.</li>
<li>The <code>riskdiff</code> option of the <code>tables</code> statement allows us to specify which confidence intervals we need for the difference as well as the estimates for the group proportions.</li>
<li>The <code>alpha</code> option can be used to change the confidence level.</li>
</ul></li>
</ul>
<p>Sample SAS code:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb75" data-code-line-numbers="3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a></a>proc freq;</span>
<span id="cb75-2"><a></a>weight count;</span>
<span id="cb75-3"><a></a>tables treat<span class="sc">*</span>outcome<span class="sc">/</span><span class="fu">riskdiff</span>(correct <span class="at">cl=</span>(mn ac)) alpha<span class="ot">=</span><span class="fl">0.05</span>;</span>
<span id="cb75-4"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="confidence-intervals-r" class="slide level2">
<h2>Confidence Intervals: <code>R</code></h2>
<p>The <code>BinomDiffCI()</code> function in the <code>DescTools</code> package in <code>R</code> can calculate these confidence intervals.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a><span class="co"># install.packages("DescTools")</span></span>
<span id="cb76-2"><a></a><span class="fu">library</span>(DescTools)</span>
<span id="cb76-3"><a></a><span class="fu">BinomDiffCI</span>(<span class="at">x1=</span>n11, <span class="at">n1 =</span> row1sum, <span class="at">x2 =</span> n21, <span class="at">n2=</span>row2sum,</span>
<span id="cb76-4"><a></a>            <span class="at">conf.level=</span><span class="fl">0.95</span>, </span>
<span id="cb76-5"><a></a>            <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"ac"</span>, <span class="st">"wald"</span>, <span class="st">"waldcc"</span>, <span class="st">"score"</span>, <span class="st">"scorecc"</span>, <span class="st">"mn"</span>,</span>
<span id="cb76-6"><a></a>                       <span class="st">"mee"</span>, <span class="st">"blj"</span>, <span class="st">"ha"</span>, <span class="st">"hal"</span>, <span class="st">"jp"</span>) </span>
<span id="cb76-7"><a></a>            )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>The contingency table shows the information from a randomized clinical trial that compared an experimental treatment to a placebo treatment for a respiratory disorder.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Placebo        16          48
  Test           40          20</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Question</a></li><li><a href="#tabset-6-2">SAS Code</a></li><li><a href="#tabset-6-3">R Code</a></li><li><a href="#tabset-6-4">Answers</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p>Calculate the 95% confidence interval for the difference in proportion of favorable outcomes for both treatment groups.</p>
<ul>
<li>Wald</li>
<li>Corrected Wald</li>
<li>Agresti-Caffo</li>
<li>Miettinen-Nurminen</li>
</ul>
</div>
<div id="tabset-6-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb78" data-code-line-numbers="12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a>data respire;</span>
<span id="cb78-2"><a></a>input treat <span class="sc">$</span> outcome <span class="sc">$</span> count; </span>
<span id="cb78-3"><a></a>datalines;</span>
<span id="cb78-4"><a></a>test f <span class="dv">40</span></span>
<span id="cb78-5"><a></a>test u <span class="dv">20</span></span>
<span id="cb78-6"><a></a>placebo f <span class="dv">16</span></span>
<span id="cb78-7"><a></a>placebo u <span class="dv">48</span></span>
<span id="cb78-8"><a></a>;</span>
<span id="cb78-9"><a></a></span>
<span id="cb78-10"><a></a>proc freq data<span class="ot">=</span>respire order<span class="ot">=</span>data; </span>
<span id="cb78-11"><a></a>weight count; </span>
<span id="cb78-12"><a></a>tables treat<span class="sc">*</span>outcome<span class="sc">/</span><span class="fu">riskdiff</span>(<span class="at">cl=</span>(mn ac)) alpha<span class="ot">=</span><span class="fl">0.05</span>; </span>
<span id="cb78-13"><a></a>tables treat<span class="sc">*</span>outcome<span class="sc">/</span><span class="fu">riskdiff</span>(correct) alpha<span class="ot">=</span><span class="fl">0.05</span>; </span>
<span id="cb78-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-6-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Test"</span>),</span>
<span id="cb79-2"><a></a>                  <span class="at">Outcome =</span> <span class="fu">c</span>(<span class="st">"Favorable"</span>,<span class="st">"Unfavorable"</span>)) </span>
<span id="cb79-3"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">40</span>,<span class="dv">48</span>,<span class="dv">20</span>)</span>
<span id="cb79-4"><a></a></span>
<span id="cb79-5"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count <span class="sc">~</span> .,<span class="at">data=</span>dat)</span>
<span id="cb79-6"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Placebo        16          48
  Test           40          20</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a></a><span class="fu">library</span>(DescTools)</span>
<span id="cb81-2"><a></a><span class="fu">BinomDiffCI</span>(<span class="at">x1=</span><span class="dv">40</span>,</span>
<span id="cb81-3"><a></a>            <span class="at">n1 =</span> <span class="dv">40</span><span class="sc">+</span><span class="dv">20</span>,</span>
<span id="cb81-4"><a></a>            <span class="at">x2=</span><span class="dv">16</span>,</span>
<span id="cb81-5"><a></a>            <span class="at">n2=</span><span class="dv">16</span><span class="sc">+</span><span class="dv">48</span>,</span>
<span id="cb81-6"><a></a>            <span class="at">method=</span><span class="fu">c</span>(<span class="st">'wald'</span>,<span class="st">'waldcc'</span>,<span class="st">'ac'</span>,<span class="st">'mn'</span>),</span>
<span id="cb81-7"><a></a>            <span class="at">conf.level =</span> <span class="fl">0.95</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             est    lwr.ci    upr.ci
wald   0.4166667 0.2570362 0.5762972
waldcc 0.4166667 0.2408903 0.5924430
ac     0.4166667 0.2455745 0.5618546
mn     0.4166667 0.2460145 0.5626554</code></pre>
</div>
</div>
</div>
<div id="tabset-6-4">
<p>The estimated difference in proportion is 0.4167 with the following 95% confidence intervals: - Wald: <strong>0.2570-0.5763</strong> - Corrected Wald: <strong>0.2409-0.5924</strong> - Agresti-Caffo: <strong>0.2456-0.5416</strong> - Miettinen-Nurminen <strong>0.2460-0.5627</strong></p>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>One of the most famous and largest clinical trials ever performed was in 1954. The data obtained from this RCT is shown in the contingency table.</p>

<img data-src="img/DiffProp2.png" class="r-stretch"><div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Problem</a></li><li><a href="#tabset-7-2"><code>SAS</code> Code</a></li><li><a href="#tabset-7-3"><code>R</code> Code</a></li><li><a href="#tabset-7-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<p>Calculate the <em>90%</em> confidence interval for the difference in proportion of polio-free children between the vaccine and placebo group.</p>
<ul>
<li>Corrected Wald</li>
<li>Miettinen-Nurminen</li>
<li>Newcombe</li>
</ul>
</div>
<div id="tabset-7-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb83" data-code-line-numbers="14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a></a>data vaxx;</span>
<span id="cb83-2"><a></a>length treat <span class="sc">$</span><span class="fl">7.</span>;</span>
<span id="cb83-3"><a></a>input treat <span class="sc">$</span> outcome <span class="sc">$</span> count; </span>
<span id="cb83-4"><a></a>datalines;</span>
<span id="cb83-5"><a></a>vax n <span class="dv">200688</span></span>
<span id="cb83-6"><a></a>vax p <span class="dv">57</span></span>
<span id="cb83-7"><a></a>placebo n <span class="dv">201087</span></span>
<span id="cb83-8"><a></a>placebo p <span class="dv">142</span></span>
<span id="cb83-9"><a></a>;</span>
<span id="cb83-10"><a></a></span>
<span id="cb83-11"><a></a>proc freq data<span class="ot">=</span>vaxx order<span class="ot">=</span>data;</span>
<span id="cb83-12"><a></a>weight count;</span>
<span id="cb83-13"><a></a>tables treat<span class="sc">*</span>outcome<span class="sc">/</span><span class="fu">riskdiff</span>(correct <span class="at">cl=</span>(mn newcombe)) </span>
<span id="cb83-14"><a></a>alpha<span class="ot">=</span><span class="fl">0.10</span>;</span>
<span id="cb83-15"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-7-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a></a><span class="fu">library</span>(DescTools)</span>
<span id="cb84-2"><a></a><span class="fu">BinomDiffCI</span>(<span class="at">x1=</span><span class="dv">142</span>,</span>
<span id="cb84-3"><a></a>            <span class="at">n1=</span><span class="dv">201087</span><span class="sc">+</span><span class="dv">142</span>,</span>
<span id="cb84-4"><a></a>            <span class="at">x2=</span><span class="dv">57</span>,</span>
<span id="cb84-5"><a></a>            <span class="at">n2 =</span> <span class="dv">57</span><span class="sc">+</span><span class="dv">200688</span>,</span>
<span id="cb84-6"><a></a>            <span class="at">method=</span><span class="fu">c</span>(<span class="st">'waldcc'</span>,<span class="st">'mn'</span>,<span class="st">'newcombe'</span>),</span>
<span id="cb84-7"><a></a>            <span class="at">conf.level =</span> <span class="fl">0.9</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                est       lwr.ci       upr.ci
waldcc 0.0004217214 0.0003013909 0.0005420518
mn     0.0004217214 0.0003084844 0.0005405825</code></pre>
</div>
</div>
</div>
<div id="tabset-7-4">
<p>The estimated difference in proportion is 0.0004.</p>
<ul>
<li>Corrected Wald <strong>(0.0003,0.0005)</strong></li>
<li>Miettinen-Nurminen <strong>(0.0003,0.0005)</strong></li>
<li>Newcombe <strong>(0.0003,0.0005)</strong></li>
</ul>
</div>
</div>
</div>
</section></section>
<section>
<section id="odds-ratio-and-relative-risk" class="title-slide slide level1 center">
<h1>Odds Ratio and Relative Risk</h1>

</section>
<section id="odds-ratio-or" class="slide level2">
<h2>Odds Ratio (OR)</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Odds of success</strong></p>
</div>
<div class="callout-content">
<p>The ratio of probability of success and failure of an outcome is referred to as the odds.</p>
<p><span class="math display">\[
Odds = p/(1-p)
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Odds Ratio</strong></p>
</div>
<div class="callout-content">
<p>The ratio of the odds of success for Group 1 and Group 2 is referred to as the odds ratio. <span class="math display">\[
OR = \frac{p_1/(1-p_1)}{p_2/(1-p_2)} = (n_{11}n_{22}/n_{21}n_{12})
\]</span></p>
<p>The odds ratio is commonly used as an effect size for retrospective studies. This statistic is also used in logistic regression techniques, which will be discussed later.</p>
</div>
</div>
</div>
</section>
<section id="relative-risk-rr" class="slide level2">
<h2>Relative Risk (RR)</h2>
<p>The ratio of the risk developing a particular condition for individuals with risk factors present and absent is called the <em>relative risk</em>.</p>
<p><span class="math display">\[
RR = p_1/p_2 = \frac{(n_{11}/n_{1+})}{(n_{21}/n_{2+})}
\]</span></p>
<p>The relative risk is commonly used as an effect size in prospective studies.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>For cross-sectional data, the relative risk is known as the prevalence ratio because the disease and risk factor are assessed at the same time.</p>
</div>
</div>
</div>
</section>
<section id="odds-ratio-relative-risk" class="slide level2">
<h2>Odds Ratio &amp; Relative Risk</h2>
<ul>
<li>When OR, RR &gt; 1, Group 1 is <strong>more likely</strong> than Group 2 to record success.</li>
<li>When OR, RR&lt; 1, Group 1 is <strong>less likely</strong> to record success.</li>
<li>When OR, RR= 1, there is <strong>no association</strong> between group and success because the two groups are equally likely to record success.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>When the condition is rare, the OR is approximately equal to the RR.</p>
</div>
</div>
</div>
</section>
<section id="odds-ratio-relative-risk-sas" class="slide level2">
<h2>Odds Ratio &amp; Relative Risk: <code>SAS</code></h2>
<ul>
<li>OR and RR are calculated using the measures option in the TABLES statement in PROC FREQ.</li>
<li>For small sample sizes, the exact confidence limits can be calculated for the odds ratios.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb86" data-code-line-numbers="3,4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a></a>proc freq;</span>
<span id="cb86-2"><a></a>weight count;</span>
<span id="cb86-3"><a></a>tables a<span class="sc">*</span>b<span class="sc">/</span>measures;</span>
<span id="cb86-4"><a></a>exact or rr;</span>
<span id="cb86-5"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="odds-ratio-relative-risk-r" class="slide level2">
<h2>Odds Ratio &amp; Relative Risk: <code>R</code></h2>
<p>The odds ratio and relative risk can be calculated using functions from the <code>epitools</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb87-2"><a></a><span class="fu">oddsratio</span>(contingency_table,</span>
<span id="cb87-3"><a></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb87-4"><a></a>          <span class="at">method=</span><span class="fu">c</span>(<span class="st">"fisher"</span>,<span class="st">"wald"</span>)</span>
<span id="cb87-5"><a></a>)</span>
<span id="cb87-6"><a></a></span>
<span id="cb87-7"><a></a><span class="fu">riskratio</span>(contingency_table,</span>
<span id="cb87-8"><a></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb87-9"><a></a>          <span class="at">method=</span><span class="fu">c</span>(<span class="st">"fisher"</span>,<span class="st">"wald"</span>)</span>
<span id="cb87-10"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The <code>fisher</code> method provides exact confidence intervals for relative risk and odds ratio. The <code>fisher.test()</code> function provides an exact confidence interval for the odds ratio based on the hypergeometric distribution, but it does not include the relative risk.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>The contingency table shows data from a study on treatments for severe infections. Calculate the asymptotic and exact confidence limits for the odds ratio of favorable outcomes for test and control groups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Test           10           2
  Control         2           4</code></pre>
</div>
</div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>The data set <code>severe_long.csv</code> includes data from a study on treatments for severe infections.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"severe_long.csv"</span>)</span>
<span id="cb89-2"><a></a><span class="fu">head</span>(dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Treatment   Outcome
1      Test Favorable
2      Test Favorable
3      Test Favorable
4      Test Favorable
5      Test Favorable
6      Test Favorable</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Problem</a></li><li><a href="#tabset-8-2"><code>SAS</code> Code</a></li><li><a href="#tabset-8-3"><code>R</code> Code</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Calculate the asymptotic and exact confidence limits for the odds ratio of favorable outcomes for test and control groups.</p>
</div>
<div id="tabset-8-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb91"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a></a></span>
<span id="cb91-2"><a></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>severe;</span>
<span id="cb91-3"><a></a>weight count;</span>
<span id="cb91-4"><a></a>tables treat<span class="sc">*</span>outcome <span class="sc">/</span> chisq nocol;</span>
<span id="cb91-5"><a></a>exact or;</span>
<span id="cb91-6"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th>Value and CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asymptotic</td>
<td>10 (1.0256, 97.5005)</td>
</tr>
<tr class="even">
<td>Exact</td>
<td>10 (0.6896,166.3562)</td>
</tr>
</tbody>
</table>
<p><strong>The two methods lead to different conclusions.</strong></p>
</div>
<div id="tabset-8-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span>Treatment<span class="sc">+</span>Outcome,<span class="at">data=</span>dat)</span>
<span id="cb92-2"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Favorable Unfavorable
  Control         2           4
  Test           10           2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb94-2"><a></a></span>
<span id="cb94-3"><a></a><span class="fu">oddsratio</span>(dat_cc,</span>
<span id="cb94-4"><a></a>          <span class="at">method=</span><span class="fu">c</span>(<span class="st">"wald"</span>),</span>
<span id="cb94-5"><a></a>          <span class="at">conf.level=</span><span class="fl">0.95</span>,</span>
<span id="cb94-6"><a></a>          <span class="at">rev=</span><span class="st">"rows"</span> <span class="co">#Reverses the rows</span></span>
<span id="cb94-7"><a></a>          )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
         Outcome
Treatment Favorable Unfavorable Total
  Test           10           2    12
  Control         2           4     6
  Total          12           6    18

$measure
         odds ratio with 95% C.I.
Treatment estimate    lower    upper
  Test           1       NA       NA
  Control       10 1.025636 97.50049

$p.value
         two-sided
Treatment midp.exact fisher.exact chi.square
  Test            NA           NA         NA
  Control 0.06119371    0.1070351 0.03389485

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a></a><span class="fu">oddsratio</span>(dat_cc,</span>
<span id="cb96-2"><a></a>          <span class="at">method=</span><span class="fu">c</span>(<span class="st">"fisher"</span>),</span>
<span id="cb96-3"><a></a>          <span class="at">conf.level=</span><span class="fl">0.95</span>,</span>
<span id="cb96-4"><a></a>          <span class="at">rev=</span><span class="st">"rows"</span> <span class="co">#Reverses the rows</span></span>
<span id="cb96-5"><a></a>          )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
         Outcome
Treatment Favorable Unfavorable Total
  Test           10           2    12
  Control         2           4     6
  Total          12           6    18

$measure
         odds ratio with 95% C.I.
Treatment estimate     lower    upper
  Test    1.000000        NA       NA
  Control 8.457238 0.6896384 166.4345

$p.value
         two-sided
Treatment midp.exact fisher.exact chi.square
  Test            NA           NA         NA
  Control 0.06119371    0.1070351 0.03389485

$correction
[1] FALSE

attr(,"method")
[1] "Conditional MLE &amp; exact CI from 'fisher.test'"</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We report the <strong>estimate</strong> of the odds ratio from the <code>"wald"</code> method, but use the <code>"fisher"</code> confidence interval as the exact confidence interval.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>Two groups having the same symptoms of respiratory illness were sampled. One group was treated with an experimental treatment and the other group was treated with a placebo. The participants were asked whether there was an overall treatment in overall respiration.</p>
<ul>
<li>Calculate the odds ratio of respiratory improvement between test and placebo groups.</li>
<li>What is the relative risk of having respiratory improvement if we consider the treatment as a risk factor?</li>
<li>Calculate the asymptotic 95% CI for each answer.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Yes No
  Test     29 16
  Placebo  14 31</code></pre>
</div>
</div>
</section>
<section id="exercise-5" class="slide level2">
<h2>Exercise</h2>
<p>Two groups having the same symptoms of respiratory illness were sampled. One group was treated with an experimental treatment and the other group was treated with a placebo. The participants were asked whether there was an overall treatment in overall respiration.</p>
<ul>
<li>Calculate the odds ratio of respiratory improvement between test and placebo groups.<strong>4.01 (1.67,9.66)</strong></li>
<li>What is the relative risk of having respiratory improvement if we consider the treatment as a risk factor? <strong>2.07 (1.27,3.37)</strong></li>
<li>Calculate the asymptotic 95% CI for each answer.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Treatment Yes No
  Test     29 16
  Placebo  14 31</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">SAS Code</a></li><li><a href="#tabset-9-2">R Code</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb100"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a></a>data resp;</span>
<span id="cb100-2"><a></a>input  Treatment <span class="sc">$</span> Outcome  <span class="sc">$</span> count;</span>
<span id="cb100-3"><a></a>datalines;</span>
<span id="cb100-4"><a></a>Test Yes <span class="dv">29</span></span>
<span id="cb100-5"><a></a>Placebo Yes <span class="dv">14</span></span>
<span id="cb100-6"><a></a>Test No <span class="dv">16</span></span>
<span id="cb100-7"><a></a>Placebo No <span class="dv">31</span></span>
<span id="cb100-8"><a></a>;</span>
<span id="cb100-9"><a></a>proc freq data<span class="ot">=</span>resp order<span class="ot">=</span>data;</span>
<span id="cb100-10"><a></a>weight count;</span>
<span id="cb100-11"><a></a>tables treatment<span class="sc">*</span>outcome<span class="sc">/</span>measures;</span>
<span id="cb100-12"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-9-2">
<p>Odds ratio</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a></a><span class="fu">library</span>(epitools)</span>
<span id="cb101-2"><a></a>dat_cc <span class="sc">|&gt;</span> <span class="fu">oddsratio</span>(<span class="at">rev=</span><span class="fu">c</span>(<span class="st">"both"</span>), <span class="at">method=</span><span class="st">"wald"</span>,<span class="at">conf.level=</span><span class="fl">0.95</span>) <span class="ot">-&gt;</span> or</span>
<span id="cb101-3"><a></a>or<span class="sc">$</span>measure</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         odds ratio with 95% C.I.
Treatment estimate    lower    upper
  Placebo 1.000000       NA       NA
  Test    4.013393 1.668039 9.656441</code></pre>
</div>
</div>
<p>Relative Risk</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a></a>dat_cc <span class="sc">|&gt;</span> <span class="fu">riskratio</span>(<span class="at">rev=</span><span class="fu">c</span>(<span class="st">"both"</span>),<span class="at">method=</span><span class="st">"wald"</span>)<span class="ot">-&gt;</span>rr</span>
<span id="cb103-2"><a></a>rr<span class="sc">$</span>measure</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         risk ratio with 95% C.I.
Treatment estimate    lower    upper
  Placebo 1.000000       NA       NA
  Test    2.071429 1.274194 3.367474</code></pre>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="sensitivity-and-specificity" class="title-slide slide level1 center">
<h1>Sensitivity and specificity</h1>

</section>
<section id="sensitivity" class="slide level2">
<h2>Sensitivity</h2>
<p>True proportion of positive results that a test elicits when performed on subjects known to have the disease.</p>
<p><span class="math display">\[Sens=TP/(TP+FN) = n_{11}/n_{1+}\]</span> Sensitivity is the conditional probability of a positive test given that the subject has the disease (<span class="math inline">\(P(PT|HD)\)</span>)</p>
</section>
<section id="specificity" class="slide level2">
<h2>Specificity</h2>
<p>True proportion of negative results that a test elicits when performed on subjects known to be disease free.</p>
<p><span class="math display">\[Sens=TN/(TN+FP) = n_{22}/n_{2+}\]</span> Specificity is the conditional probability of a negative test when the subject does not have the disease (<span class="math inline">\(P(NT|ND)\)</span>).</p>
</section>
<section id="sensitivity-and-specificity-sas" class="slide level2">
<h2>Sensitivity and Specificity: SAS</h2>
<p>The <code>FREQ</code> procedure can also calculate sensitivity and specificity.</p>
<ul>
<li><code>riskdiff</code> approximates these metrics using the risk estimates.
<ul>
<li>Sensitivity: Row 1 risk estimate for Column 1</li>
<li>Specificity: Row 2 risk estimate for Column 2</li>
</ul></li>
</ul>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>The following table shows the results of a study investigating a new screening device for a skin disease. Calculate the sensitivity and specificity of the screening device.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Test
Status            Positive Negative
  Disease Present       52        8
  Disease Absent        20      100</code></pre>
</div>
</div>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>The following table shows the results of a study investigating a new screening device for a skin disease. Calculate the sensitivity and specificity of the screening device.</p>
<ul>
<li>Sensitivity: 0.87 (0.75,0.94)</li>
<li>Specificity: 0.83 (0.75,0.90)</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Test
Status            Positive Negative
  Disease Present       52        8
  Disease Absent        20      100</code></pre>
</div>
</div>
<p>SAS Code</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a></a>data screening;</span>
<span id="cb107-2"><a></a>input disease <span class="sc">$</span> outcome <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb107-3"><a></a>datalines;</span>
<span id="cb107-4"><a></a>present <span class="sc">+</span> <span class="dv">52</span> present <span class="sc">-</span> <span class="dv">8</span></span>
<span id="cb107-5"><a></a>absent <span class="sc">+</span> <span class="dv">20</span> absent <span class="sc">-</span> <span class="dv">100</span></span>
<span id="cb107-6"><a></a>;</span>
<span id="cb107-7"><a></a>proc freq data<span class="ot">=</span>screening order<span class="ot">=</span>data;</span>
<span id="cb107-8"><a></a>weight count;</span>
<span id="cb107-9"><a></a>tables disease<span class="sc">*</span>outcome <span class="sc">/</span> riskdiff;</span>
<span id="cb107-10"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="exercise-6" class="slide level2">
<h2>Exercise</h2>
<p>A pharmaceutical company developed a screening test that can be used to detect infection of the Lassa (virus). The newly developed test was said to be cheaper than the tests currently available to the public, but its performance was yet to be evaluated. The screening test was applied to 115 diagnosed cases (w/ Lassa virus) and 120 control participants (w/o Lassa virus) of the Lassa fever. The resulting contingency table is shown in the table.</p>
<ul>
<li>What is the sensitivity of the test?</li>
<li>What is the specificity of the test?</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Test
Status            Positive Negative
  Disease Present       97       18
  Disease Absent        45       75</code></pre>
</div>
</div>
</section>
<section id="exercise-7" class="slide level2">
<h2>Exercise</h2>
<p>A pharmaceutical company developed a screening test that can be used to detect infection of the Lassa (virus). The newly developed test was said to be cheaper than the tests currently available to the public, but its performance was yet to be evaluated. The screening test was applied to 115 diagnosed cases (w/ Lassa virus) and 120 control participants (w/o Lassa virus) of the Lassa fever. The resulting contingency table is shown in the table.</p>
<ul>
<li>What is the sensitivity of the test? <strong>0.8435 (0.76, 0.90)</strong></li>
<li>What is the specificity of the test? <strong>0.6250 (0.53, 0.71)</strong></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 Test
Status            Positive Negative
  Disease Present       97       18
  Disease Absent        45       75</code></pre>
</div>
</div>
<h3 id="sas-code-9">SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb110"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a></a>data screening;</span>
<span id="cb110-2"><a></a>input disease <span class="sc">$</span> outcome <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb110-3"><a></a>datalines;</span>
<span id="cb110-4"><a></a>present <span class="sc">+</span> <span class="dv">97</span> present <span class="sc">-</span> <span class="dv">18</span></span>
<span id="cb110-5"><a></a>absent <span class="sc">+</span> <span class="dv">45</span> absent <span class="sc">-</span> <span class="dv">75</span></span>
<span id="cb110-6"><a></a>;</span>
<span id="cb110-7"><a></a>proc freq data<span class="ot">=</span>screening order<span class="ot">=</span>data;</span>
<span id="cb110-8"><a></a>weight count;</span>
<span id="cb110-9"><a></a>tables disease<span class="sc">*</span>outcome <span class="sc">/</span> riskdiff;</span>
<span id="cb110-10"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section></section>
<section>
<section id="mcnemars-test" class="title-slide slide level1 center">
<h1>McNemar’s Test</h1>

</section>
<section id="mcnemars-test-1" class="slide level2">
<h2>McNemar’s Test</h2>
<ul>
<li><p>When the 2x2 table provides information from matched pairs, the two responses are related to each other. Hence, independence cannot be assumed.</p></li>
<li><p>Null hypothesis: The marginal probabilities of each outcome are the same.</p></li>
<li><p>The test statistic for the McNemar’s test is <span class="math inline">\(Q_M\)</span> given by</p></li>
</ul>
<p><span class="math display">\[Q_M = (n_{12}-n_{21})^2/(n_{12}+n_{21})\]</span></p>
</section>
<section id="mcnemars-test-sas" class="slide level2">
<h2>McNemar’s Test: SAS</h2>
<ul>
<li>The <code>agree</code> option in the <code>tables</code> statement can be used to perform the McNemar’s test.</li>
<li>Exact p-values can be calculated using the <code>exact</code> statement.</li>
</ul>
<h3 id="sample-sas-code">Sample SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb111"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a></a>proc freq;</span>
<span id="cb111-2"><a></a>weight count;</span>
<span id="cb111-3"><a></a>tables a<span class="sc">*</span>b<span class="sc">/</span>agree;</span>
<span id="cb111-4"><a></a>exact mcnem;</span>
<span id="cb111-5"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>The table displays data collected by political science researchers who polled husbands and wives on whether they approved of one of their U.S. senators. The cell counts represent the number of pairs of husbands and wives who fit the configurations indicated by the row and column levels. Use the McNemar’s test to determine whether there is no difference in husband and wife approvals on the state senator.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Wife
Husband Yes No
    Yes  20  5
    No   10 10</code></pre>
</div>
</div>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>The table displays data collected by political science researchers who polled husbands and wives on whether they approved of one of their U.S. senators. The cell counts represent the number of pairs of husbands and wives who fit the configurations indicated by the row and column levels. Use the McNemar’s test to determine whether there is no difference in husband and wife approvals on the state senator.</p>
<ul>
<li>Exact p-value = 0.3018, which implies that there is no evidence of a difference between the senator approval ratings of the husbands and wives.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Wife
Husband Yes No
    Yes  20  5
    No   10 10</code></pre>
</div>
</div>
<h3 id="sas-code-10">SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb114" data-code-line-numbers="12,13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a></a>data approval;</span>
<span id="cb114-2"><a></a>input hus_resp <span class="sc">$</span> wif_resp <span class="sc">$</span> count;</span>
<span id="cb114-3"><a></a>datalines;</span>
<span id="cb114-4"><a></a>yes yes <span class="dv">20</span></span>
<span id="cb114-5"><a></a>yes no <span class="dv">5</span></span>
<span id="cb114-6"><a></a>no yes <span class="dv">10</span></span>
<span id="cb114-7"><a></a>no no <span class="dv">10</span></span>
<span id="cb114-8"><a></a>;</span>
<span id="cb114-9"><a></a></span>
<span id="cb114-10"><a></a>proc freq order<span class="ot">=</span>data;</span>
<span id="cb114-11"><a></a>weight count;</span>
<span id="cb114-12"><a></a>tables hus_resp<span class="sc">*</span>wif_resp <span class="sc">/</span> agree;</span>
<span id="cb114-13"><a></a>exact mcnem;</span>
<span id="cb114-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="exercise-8" class="slide level2">
<h2>Exercise</h2>
<p>The tables show the data from a study that compared the diagnostic accuracy of magnetic resonance imaging (MRI) and ultrasound in patients who had been established as having localized prostate cancer by a gold standard test.</p>
<ul>
<li>Use the McNemar’s test to determine whether the two methods have a different probabilities in diagnosing localized prostate cancer. (<em>Hint: Small cell counts</em>)</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           Ultrasound
MRI         Localized Advanced
  Localized         4        6
  Advanced          3        3</code></pre>
</div>
</div>
</section>
<section id="exercise-9" class="slide level2">
<h2>Exercise</h2>
<p>The tables show the data from a study that compared the diagnostic accuracy of magnetic resonance imaging (MRI) and ultrasound in patients who had been established as having localized prostate cancer by a gold standard test.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           Ultrasound
MRI         Localized Advanced
  Localized         4        6
  Advanced          3        3</code></pre>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Answer</a></li><li><a href="#tabset-10-2">SAS Code</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<ul>
<li>Use the McNemar’s test to determine whether the two methods have a different probabilities in diagnosing localized prostate cancer. (<em>Hint: Small cell counts</em>)
<ul>
<li>Use exact p-value</li>
<li><span class="math inline">\(p=0.5078\)</span>. No evidence of any difference in probabilities in correctly diagnosing localized prostate cancer.</li>
</ul></li>
</ul>
</div>
<div id="tabset-10-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb117"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a></a>data imaging;</span>
<span id="cb117-2"><a></a>input mri <span class="sc">$</span> ult <span class="sc">$</span> count;</span>
<span id="cb117-3"><a></a>datalines;</span>
<span id="cb117-4"><a></a>loc loc <span class="dv">4</span></span>
<span id="cb117-5"><a></a>loc adv <span class="dv">6</span></span>
<span id="cb117-6"><a></a>adv loc <span class="dv">3</span></span>
<span id="cb117-7"><a></a>adv adv <span class="dv">3</span></span>
<span id="cb117-8"><a></a>;</span>
<span id="cb117-9"><a></a></span>
<span id="cb117-10"><a></a>proc freq order<span class="ot">=</span>data;</span>
<span id="cb117-11"><a></a>weight count;</span>
<span id="cb117-12"><a></a>tables mri<span class="sc">*</span>ult <span class="sc">/</span> agree;</span>
<span id="cb117-13"><a></a>exact mcnem;</span>
<span id="cb117-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section></section>
<section>
<section id="incidence-densities" class="title-slide slide level1 center">
<h1>Incidence Densities</h1>

</section>
<section id="incidence-densities-1" class="slide level2 smaller">
<h2>Incidence Densities</h2>
<ul>
<li>Counts of subjects who responded within a duration of exposure to an event.</li>
<li>Poisson distribution: counts</li>
<li>Examples:
<ul>
<li>Bacteria colony count</li>
<li>Disease incidence</li>
<li>Accidents</li>
<li>Vaccine failure</li>
</ul></li>
<li>Common measure of duration of exposure/ time-at-risk: person-time</li>
</ul>
</section>
<section id="poisson-distribution" class="slide level2">
<h2>Poisson Distribution</h2>
<p>Recall that the Poisson distribution is described by the following density function:</p>
<p><span class="math display">\[P(x)= e^{-\lambda}\lambda^x/x!\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the expected number of events at a given unit of time.</p>
<ul>
<li>is also referred to as incidence density.</li>
<li>For <span class="math inline">\(t\)</span> units of time, the expected number of events scales to <span class="math inline">\(\lambda t\)</span>.</li>
<li>Main assumption: The time to event is a random variable following an exponential distribution.</li>
</ul>
</section>
<section id="incidence-density-ratios" class="slide level2">
<h2>Incidence Density Ratios</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 85%">
<ul>
<li>The table shows the number of infections (events) and person years for participants of an RCT.
<ul>
<li><span class="math inline">\(n_v\)</span> and <span class="math inline">\(n_p\)</span> are Poisson random variables with respective incidence densities equal to <span class="math inline">\(\lambda_v\)</span> and <span class="math inline">\(\lambda_p\)</span></li>
</ul></li>
<li>If <span class="math inline">\(\lambda_v\)</span> is the incidence density for the vaccine group, then the expected number of events is <span class="math inline">\(\lambda_v N_v\)</span>.</li>
<li>Similarly, the expected number of events in the placebo group is <span class="math inline">\(\lambda_p N_p\)</span></li>
<li>We are interested in testing the null hypothesis <span class="math inline">\(\lambda_v/\lambda_p = 1\)</span>.
<ul>
<li><span class="math inline">\(\lambda_v/\lambda_p\)</span> is referred to as the <strong>Incidence Density Ratio (IDR)</strong></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<p><img data-src="img/IDR.png"></p>
</div></div>
</section>
<section id="incidence-density-ratios-1" class="slide level2">
<h2>Incidence Density Ratios</h2>
<p>The IDR can be estimated using conditional binomial distributions assuming <span class="math inline">\(n_v\)</span> and <span class="math inline">\(n_p\)</span> are independent Poisson processes.</p>
<p><span class="math display">\[P(n_v|n_v+n_p) \sim Bin\left(N=n_v + n_p, p = \frac{\lambda_vN_v}{\lambda_vN_v+\lambda_pN_p}\right)\]</span></p>
</section>
<section id="incidence-density-ratios-confidence-interval" class="slide level2">
<h2>Incidence Density Ratios: Confidence Interval</h2>
<p>The binomial proportion can be estimated using the proportion of events in the treatment group:</p>
<p><span class="math display">\[p = \frac{n_v}{n_v+n_p} = \frac{IDR(N_v/N_p)}{1+(IDR)(N_v/N_p)}\]</span> Using algebra (Problem Set 1), <em>it is easy to show that</em>:</p>
<p><span class="math display">\[IDR = \frac{p}{1-p}\left(N_p/N_v\right)\]</span></p>
</section>
<section id="incidence-density-ratios-confidence-interval-1" class="slide level2">
<h2>Incidence Density Ratios: Confidence Interval</h2>
<p>You can calculate the confidence interval estimates for <span class="math inline">\(p\)</span> using the binomial distribution assumption (<span class="math inline">\(p_L,p_U\)</span>) and apply the scaling factor to each confidence limit.</p>
<p><span class="math display">\[95\% CI: \left(\frac{p_L}{1-p_L}(N_p/N_v),\frac{p_U}{1-p_U}(N_p/N_v)\right)\]</span></p>
</section>
<section id="incidence-density-ratios-sas" class="slide level2">
<h2>Incidence Density Ratios: SAS</h2>
<ul>
<li>The <code>binomial</code> option in the <code>tables</code> statement produces the estimate and exact confidence limits for the binomial proportion <span class="math inline">\(p\)</span>, i.e.&nbsp;<span class="math inline">\(p_L\)</span> and <span class="math inline">\(p_U\)</span>.</li>
<li>We use the estimate and exact confidence limits of <span class="math inline">\(p\)</span> in calculating the IDR.</li>
<li>The <code>IML</code> procedure, which is the procedure used to perform mathematical equations, is used to calculate the IDR confidence limits.
<ul>
<li>Later on, we will use the <code>GENMOD</code> procedure to calculate exact confidence intervals for the IDR.</li>
</ul></li>
</ul>
</section>
<section id="example-10" class="slide level2">
<h2>Example</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 95%">
<p>The table shows the results of an international study of the effect of a rotavirus vaccine in nearly 70,000 infants on health care events. The events counted were hospitalizations or emergency room visits.</p>
<ul>
<li>Estimate the IDR of hospitalization/emergency room visits between the two groups.</li>
<li>Calculate the 95% CI.</li>
</ul>
</div><div class="column" style="width:50%;">
<p><img data-src="img/IDR.png"></p>
</div></div>
</section>
<section id="example-11" class="slide level2">
<h2>Example</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 95%">
<p>The table shows the results of an international study of the effect of a rotavirus vaccine in nearly 70,000 infants on health care events. The events counted were hospitalizations or emergency room visits.</p>
<ul>
<li>Estimate the IDR of hospitalization/emergency room visits between the two groups. <strong>IDR = 0.05</strong></li>
<li>Calculate the 95% CI. <strong>(0.01, 0.15)</strong></li>
</ul>
</div><div class="column" style="width:50%;">
<p><img data-src="img/IDR2.png"></p>
</div></div>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">SAS Code</a></li><li><a href="#tabset-11-2">R Code</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-118" data-code-line-numbers="12,13,16-27"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-118-1"><a href="#annotated-cell-118-1"></a>data vaccine2;</span>
<span id="annotated-cell-118-2"><a href="#annotated-cell-118-2"></a>input Outcome <span class="sc">$</span> Count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-118-3"><a href="#annotated-cell-118-3"></a>datalines;</span>
<span id="annotated-cell-118-4"><a href="#annotated-cell-118-4"></a>vaccine <span class="dv">3</span> placebo <span class="dv">58</span></span>
<span id="annotated-cell-118-5"><a href="#annotated-cell-118-5"></a>;</span>
<span id="annotated-cell-118-6"><a href="#annotated-cell-118-6"></a></span>
<span id="annotated-cell-118-7"><a href="#annotated-cell-118-7"></a>ods select BinomialCLs; <span class="sc">*</span>this statement filters the output.;</span>
<span id="annotated-cell-118-8"><a href="#annotated-cell-118-8"></a></span>
<span id="annotated-cell-118-9"><a href="#annotated-cell-118-9"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-118" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-118-10" class="code-annotation-target"><a href="#annotated-cell-118-10"></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>vaccine2;</span>
<span id="annotated-cell-118-11"><a href="#annotated-cell-118-11"></a>weight count;</span>
<span id="annotated-cell-118-12"><a href="#annotated-cell-118-12"></a>tables Outcome <span class="sc">/</span> <span class="fu">binomial</span> (exact); <span class="sc">*</span>calculates the exact confidence limits <span class="cf">for</span> the binomial proportion;</span>
<span id="annotated-cell-118-13"><a href="#annotated-cell-118-13"></a>ods output BinomialCLs<span class="ot">=</span>BinomialCLs; <span class="sc">*</span>outputs a dataset that includes the binomial CLs.;</span>
<span id="annotated-cell-118-14"><a href="#annotated-cell-118-14"></a>run;</span>
<span id="annotated-cell-118-15"><a href="#annotated-cell-118-15"></a></span>
<span id="annotated-cell-118-16"><a href="#annotated-cell-118-16"></a>proc iml ;</span>
<span id="annotated-cell-118-17"><a href="#annotated-cell-118-17"></a>Use BinomialCLs var{LowerCL UpperCL};</span>
<span id="annotated-cell-118-18"><a href="#annotated-cell-118-18"></a>read all into CL;</span>
<span id="annotated-cell-118-19"><a href="#annotated-cell-118-19"></a>print CL;</span>
<span id="annotated-cell-118-20"><a href="#annotated-cell-118-20"></a>q <span class="ot">=</span> { <span class="dv">3</span>, <span class="dv">7500</span>, <span class="dv">58</span> , <span class="dv">7250</span> }; <span class="sc">*</span>vector of numbers from the table;</span>
<span id="annotated-cell-118-21"><a href="#annotated-cell-118-21"></a>C<span class="ot">=</span> q[<span class="dv">2</span>]<span class="sc">/</span>q[<span class="dv">4</span>]; <span class="sc">*</span>q[i] represents the ith number <span class="cf">in</span> the q vector defined above. C is the person<span class="sc">-</span>years ratio Nv<span class="sc">/</span>Np;</span>
<span id="annotated-cell-118-22"><a href="#annotated-cell-118-22"></a>P<span class="ot">=</span> q[<span class="dv">1</span>]<span class="sc">/</span> (q[<span class="dv">1</span>] <span class="sc">+</span> q[<span class="dv">3</span>]); <span class="sc">*</span>estimate of the binomial distribution;</span>
<span id="annotated-cell-118-23"><a href="#annotated-cell-118-23"></a>R<span class="ot">=</span> P<span class="sc">/</span> ((<span class="dv">1</span><span class="sc">-</span>P) <span class="sc">*</span>C) ; <span class="sc">*</span> IDR estimate;</span>
<span id="annotated-cell-118-24"><a href="#annotated-cell-118-24"></a>CI<span class="ot">=</span> CL[<span class="dv">1</span>]<span class="sc">/</span>((<span class="dv">1</span><span class="sc">-</span>CL[<span class="dv">1</span>])<span class="sc">*</span>C) <span class="sc">||</span> CL[<span class="dv">2</span>]<span class="sc">/</span>((<span class="dv">1</span><span class="sc">-</span>CL[<span class="dv">2</span>])<span class="sc">*</span>C) ; <span class="sc">*</span>IDR CL;</span>
<span id="annotated-cell-118-25"><a href="#annotated-cell-118-25"></a>print r CI;</span>
<span id="annotated-cell-118-26"><a href="#annotated-cell-118-26"></a>quit;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-118" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-118" data-code-lines="10" data-code-annotation="1"><code>order=data</code> is important so as to keep the proportions consistent.</span>
</dd>
</dl>
</div>
<div id="tabset-11-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a></a>events <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">58</span>)</span>
<span id="cb118-2"><a></a>person_years <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7500</span>, <span class="dv">7250</span>)</span>
<span id="cb118-3"><a></a></span>
<span id="cb118-4"><a></a>mult <span class="ot">&lt;-</span> person_years[<span class="dv">2</span>]<span class="sc">/</span>person_years[<span class="dv">1</span>] <span class="co">#multiplier</span></span>
<span id="cb118-5"><a></a>DescTools<span class="sc">::</span><span class="fu">BinomCI</span>(events[<span class="dv">1</span>],<span class="fu">sum</span>(events),<span class="at">method =</span> <span class="st">"clopper-pearson"</span>) <span class="ot">-&gt;</span> p_est</span>
<span id="cb118-6"><a></a></span>
<span id="cb118-7"><a></a></span>
<span id="cb118-8"><a></a></span>
<span id="cb118-9"><a></a><span class="fu">data.frame</span>(<span class="at">IDR =</span> p_est[<span class="dv">1</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">1</span>])<span class="sc">*</span>mult,</span>
<span id="cb118-10"><a></a>           <span class="at">IDR_lower =</span> p_est[<span class="dv">2</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">2</span>])<span class="sc">*</span>mult,</span>
<span id="cb118-11"><a></a>          <span class="at">IDR_higher =</span> p_est[<span class="dv">3</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">3</span>])<span class="sc">*</span>mult) <span class="sc">|&gt;</span> gt<span class="sc">::</span><span class="fu">gt</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="wqrzaiitik" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#wqrzaiitik table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wqrzaiitik thead, #wqrzaiitik tbody, #wqrzaiitik tfoot, #wqrzaiitik tr, #wqrzaiitik td, #wqrzaiitik th {
  border-style: none;
}

#wqrzaiitik p {
  margin: 0;
  padding: 0;
}

#wqrzaiitik .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wqrzaiitik .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wqrzaiitik .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wqrzaiitik .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wqrzaiitik .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wqrzaiitik .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrzaiitik .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wqrzaiitik .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wqrzaiitik .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wqrzaiitik .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wqrzaiitik .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wqrzaiitik .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wqrzaiitik .gt_spanner_row {
  border-bottom-style: hidden;
}

#wqrzaiitik .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wqrzaiitik .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wqrzaiitik .gt_from_md > :first-child {
  margin-top: 0;
}

#wqrzaiitik .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wqrzaiitik .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wqrzaiitik .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrzaiitik .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wqrzaiitik .gt_row_group_first td {
  border-top-width: 2px;
}

#wqrzaiitik .gt_row_group_first th {
  border-top-width: 2px;
}

#wqrzaiitik .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrzaiitik .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wqrzaiitik .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wqrzaiitik .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrzaiitik .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrzaiitik .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wqrzaiitik .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wqrzaiitik .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wqrzaiitik .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrzaiitik .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wqrzaiitik .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrzaiitik .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wqrzaiitik .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrzaiitik .gt_left {
  text-align: left;
}

#wqrzaiitik .gt_center {
  text-align: center;
}

#wqrzaiitik .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wqrzaiitik .gt_font_normal {
  font-weight: normal;
}

#wqrzaiitik .gt_font_bold {
  font-weight: bold;
}

#wqrzaiitik .gt_font_italic {
  font-style: italic;
}

#wqrzaiitik .gt_super {
  font-size: 65%;
}

#wqrzaiitik .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wqrzaiitik .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wqrzaiitik .gt_indent_1 {
  text-indent: 5px;
}

#wqrzaiitik .gt_indent_2 {
  text-indent: 10px;
}

#wqrzaiitik .gt_indent_3 {
  text-indent: 15px;
}

#wqrzaiitik .gt_indent_4 {
  text-indent: 20px;
}

#wqrzaiitik .gt_indent_5 {
  text-indent: 25px;
}

#wqrzaiitik .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#wqrzaiitik div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="IDR" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR</th>
<th id="IDR_lower" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR_lower</th>
<th id="IDR_higher" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR_higher</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="IDR">0.05</td>
<td class="gt_row gt_right" headers="IDR_lower">0.01002014</td>
<td class="gt_row gt_right" headers="IDR_higher">0.1535468</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-10" class="slide level2">
<h2>Exercise</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 85%">
<p>The table lists the number of accidents for day and night shift workers at a certain factory in Southeast Asia. The company wants you to investigate if there is any evidence of night shift workers having a higher accident density, i.e., higher incidence density of accidents, compared to the day shift.</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Metric
Shift   Accidents Person-Hours
  Night        25         1150
  Day          20         1240</code></pre>
</div>
</div>
</div></div>
</section>
<section id="exercise-11" class="slide level2">
<h2>Exercise</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 85%">
<p>The table lists the number of accidents for day and night shift workers at a certain factory in Southeast Asia. The company wants you to investigate if there is any evidence of night shift workers having a higher accident density, i.e., higher incidence density of accidents, compared to the day shift.</p>
<ul>
<li>IDR: 1.37</li>
<li>95% CI: (0.72,2.56)</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Metric
Shift   Accidents Person-Hours
  Night        25         1150
  Day          20         1240</code></pre>
</div>
</div>
</div></div>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">SAS Code</a></li><li><a href="#tabset-12-2">R Code</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-122"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-122-1"><a href="#annotated-cell-122-1"></a>data accident;</span>
<span id="annotated-cell-122-2"><a href="#annotated-cell-122-2"></a><span class="sc">/</span><span class="er">*</span>data only has the events. Person<span class="sc">-</span>Hours are used later.<span class="sc">*</span><span class="er">/</span></span>
<span id="annotated-cell-122-3"><a href="#annotated-cell-122-3"></a>input Outcome <span class="sc">$</span> Count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-122-4"><a href="#annotated-cell-122-4"></a>datalines;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-122" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-122-5" class="code-annotation-target"><a href="#annotated-cell-122-5"></a>night <span class="dv">25</span> day <span class="dv">20</span></span>
<span id="annotated-cell-122-6"><a href="#annotated-cell-122-6"></a>;</span>
<span id="annotated-cell-122-7"><a href="#annotated-cell-122-7"></a></span>
<span id="annotated-cell-122-8"><a href="#annotated-cell-122-8"></a>ods select BinomialCLs; <span class="sc">*</span>this statement filters the output.;</span>
<span id="annotated-cell-122-9"><a href="#annotated-cell-122-9"></a></span>
<span id="annotated-cell-122-10"><a href="#annotated-cell-122-10"></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>accident;</span>
<span id="annotated-cell-122-11"><a href="#annotated-cell-122-11"></a>weight count;</span>
<span id="annotated-cell-122-12"><a href="#annotated-cell-122-12"></a>tables Outcome <span class="sc">/</span> <span class="fu">binomial</span> (exact) alpha<span class="ot">=</span><span class="fl">0.05</span>; <span class="sc">*</span>calculates the exact confidence limits <span class="cf">for</span> the binomial proportion;</span>
<span id="annotated-cell-122-13"><a href="#annotated-cell-122-13"></a>ods output BinomialCLs<span class="ot">=</span>BinomialCLs; <span class="sc">*</span>outputs a dataset that includes the binomial CLs.;</span>
<span id="annotated-cell-122-14"><a href="#annotated-cell-122-14"></a>run;</span>
<span id="annotated-cell-122-15"><a href="#annotated-cell-122-15"></a></span>
<span id="annotated-cell-122-16"><a href="#annotated-cell-122-16"></a>proc iml ;</span>
<span id="annotated-cell-122-17"><a href="#annotated-cell-122-17"></a>Use BinomialCLs var{LowerCL UpperCL};</span>
<span id="annotated-cell-122-18"><a href="#annotated-cell-122-18"></a>read all into CL;</span>
<span id="annotated-cell-122-19"><a href="#annotated-cell-122-19"></a>print CL;</span>
<span id="annotated-cell-122-20"><a href="#annotated-cell-122-20"></a>q <span class="ot">=</span> { <span class="dv">25</span> <span class="dv">1150</span> <span class="dv">20</span> <span class="dv">1240</span> }; <span class="sc">*</span>vector of numbers from the table;</span>
<span id="annotated-cell-122-21"><a href="#annotated-cell-122-21"></a>C<span class="ot">=</span> q[<span class="dv">2</span>]<span class="sc">/</span>q[<span class="dv">4</span>]; <span class="sc">*</span>q[i] represents the ith number <span class="cf">in</span> the q vector defined above. C is the person<span class="sc">-</span>years ratio Nv<span class="sc">/</span>Np;</span>
<span id="annotated-cell-122-22"><a href="#annotated-cell-122-22"></a>P<span class="ot">=</span> q[<span class="dv">1</span>]<span class="sc">/</span> (q[<span class="dv">1</span>] <span class="sc">+</span> q[<span class="dv">3</span>]); <span class="sc">*</span>estimate of the binomial distribution;</span>
<span id="annotated-cell-122-23"><a href="#annotated-cell-122-23"></a>R<span class="ot">=</span> P<span class="sc">/</span> ((<span class="dv">1</span><span class="sc">-</span>P) <span class="sc">*</span>C) ; <span class="sc">*</span> IDR estimate;</span>
<span id="annotated-cell-122-24"><a href="#annotated-cell-122-24"></a>CI<span class="ot">=</span> CL[<span class="dv">1</span>]<span class="sc">/</span>((<span class="dv">1</span><span class="sc">-</span>CL[<span class="dv">1</span>])<span class="sc">*</span>C) <span class="sc">||</span> CL[<span class="dv">2</span>]<span class="sc">/</span>((<span class="dv">1</span><span class="sc">-</span>CL[<span class="dv">2</span>])<span class="sc">*</span>C) ; <span class="sc">*</span>IDR CL;</span>
<span id="annotated-cell-122-25"><a href="#annotated-cell-122-25"></a>print r CI;</span>
<span id="annotated-cell-122-26"><a href="#annotated-cell-122-26"></a>quit;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-122" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-122" data-code-lines="5" data-code-annotation="1">“Success” is an event happening during the night shift.</span>
</dd>
</dl>
</div>
<div id="tabset-12-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a></a>events <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">20</span>)</span>
<span id="cb121-2"><a></a>person_years <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1150</span>,<span class="dv">1240</span>)</span>
<span id="cb121-3"><a></a></span>
<span id="cb121-4"><a></a>mult <span class="ot">&lt;-</span> person_years[<span class="dv">2</span>]<span class="sc">/</span>person_years[<span class="dv">1</span>] <span class="co">#multiplier</span></span>
<span id="cb121-5"><a></a>DescTools<span class="sc">::</span><span class="fu">BinomCI</span>(events[<span class="dv">1</span>],<span class="fu">sum</span>(events),<span class="at">method =</span> <span class="st">"clopper-pearson"</span>) <span class="ot">-&gt;</span> p_est</span>
<span id="cb121-6"><a></a></span>
<span id="cb121-7"><a></a></span>
<span id="cb121-8"><a></a></span>
<span id="cb121-9"><a></a><span class="fu">data.frame</span>(<span class="at">IDR =</span> p_est[<span class="dv">1</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">1</span>])<span class="sc">*</span>mult,</span>
<span id="cb121-10"><a></a>           <span class="at">IDR_lower =</span> p_est[<span class="dv">2</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">2</span>])<span class="sc">*</span>mult,</span>
<span id="cb121-11"><a></a>          <span class="at">IDR_higher =</span> p_est[<span class="dv">3</span>]<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_est[<span class="dv">3</span>])<span class="sc">*</span>mult) <span class="sc">|&gt;</span> gt<span class="sc">::</span><span class="fu">gt</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="zbvyrzjghl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#zbvyrzjghl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zbvyrzjghl thead, #zbvyrzjghl tbody, #zbvyrzjghl tfoot, #zbvyrzjghl tr, #zbvyrzjghl td, #zbvyrzjghl th {
  border-style: none;
}

#zbvyrzjghl p {
  margin: 0;
  padding: 0;
}

#zbvyrzjghl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zbvyrzjghl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zbvyrzjghl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zbvyrzjghl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zbvyrzjghl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zbvyrzjghl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zbvyrzjghl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zbvyrzjghl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zbvyrzjghl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zbvyrzjghl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zbvyrzjghl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zbvyrzjghl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zbvyrzjghl .gt_spanner_row {
  border-bottom-style: hidden;
}

#zbvyrzjghl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zbvyrzjghl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zbvyrzjghl .gt_from_md > :first-child {
  margin-top: 0;
}

#zbvyrzjghl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zbvyrzjghl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zbvyrzjghl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zbvyrzjghl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zbvyrzjghl .gt_row_group_first td {
  border-top-width: 2px;
}

#zbvyrzjghl .gt_row_group_first th {
  border-top-width: 2px;
}

#zbvyrzjghl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zbvyrzjghl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zbvyrzjghl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zbvyrzjghl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zbvyrzjghl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zbvyrzjghl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zbvyrzjghl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zbvyrzjghl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zbvyrzjghl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zbvyrzjghl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zbvyrzjghl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zbvyrzjghl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zbvyrzjghl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zbvyrzjghl .gt_left {
  text-align: left;
}

#zbvyrzjghl .gt_center {
  text-align: center;
}

#zbvyrzjghl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zbvyrzjghl .gt_font_normal {
  font-weight: normal;
}

#zbvyrzjghl .gt_font_bold {
  font-weight: bold;
}

#zbvyrzjghl .gt_font_italic {
  font-style: italic;
}

#zbvyrzjghl .gt_super {
  font-size: 65%;
}

#zbvyrzjghl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zbvyrzjghl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zbvyrzjghl .gt_indent_1 {
  text-indent: 5px;
}

#zbvyrzjghl .gt_indent_2 {
  text-indent: 10px;
}

#zbvyrzjghl .gt_indent_3 {
  text-indent: 15px;
}

#zbvyrzjghl .gt_indent_4 {
  text-indent: 20px;
}

#zbvyrzjghl .gt_indent_5 {
  text-indent: 25px;
}

#zbvyrzjghl .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#zbvyrzjghl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="IDR" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR</th>
<th id="IDR_lower" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR_lower</th>
<th id="IDR_higher" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">IDR_higher</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="IDR">1.347826</td>
<td class="gt_row gt_right" headers="IDR_lower">0.7187612</td>
<td class="gt_row gt_right" headers="IDR_higher">2.559057</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="power-analysis" class="title-slide slide level1 center">
<h1>Power Analysis</h1>

</section>
<section id="power-analysis-1" class="slide level2">
<h2>Power Analysis</h2>
<ul>
<li>Power is defined as the probability of rejecting the null hypothesis when it is false.
<ul>
<li>Acceptable range: 80% and above.</li>
</ul></li>
<li>Also known as (a priori) Sample Size Calculations
<ul>
<li>How many samples do I need to detect a set difference between the treatment and placebo group at a significance level of 0.05?</li>
</ul></li>
</ul>
</section>
<section id="power-analysis-sas" class="slide level2">
<h2>Power Analysis: SAS</h2>
<ul>
<li>The <code>POWER</code> procedure enables us to calculate how many samples are needed to detect a set effect size in examining the difference between two proportions from two different populations.</li>
<li>Specifically, the TWOSAMPLEFREQ option
<ul>
<li>RCT: treatment vs.&nbsp;control</li>
</ul></li>
<li>We need to set an effect size (theory-based), significance level, and power level.
<ul>
<li>Other options can be found <a href="https://documentation.sas.com/doc/en/statug/15.2/statug_power_syntax83.htm">here</a></li>
</ul></li>
</ul>
</section>
<section id="example-12" class="slide level2">
<h2>Example</h2>
<p>Suppose prior literature states that the incidence rate of a chronic disease is 0.40. Suppose we want to perform a prospective study to test the association between the disease incidence and family history, i.e.&nbsp;whether other family members were diagnosed with the chronic disease. We want to detect a proportion difference of 0.10 between groups with power of 80% (0.80) at a significance level of 0.05.</p>
</section>
<section id="example-13" class="slide level2">
<h2>Example</h2>
<p>Suppose prior literature states that the incidence rate of a chronic disease is 0.40. Suppose we want to perform a prospective study to test the association between the disease incidence and family history, i.e.&nbsp;whether other family members were diagnosed with the chronic disease. We want to detect a proportion difference of 0.10 between groups with power of 80% (0.80) at a significance level of 0.05.</p>
<ul>
<li>We need 388 units per group (family +, family -). This brings us to 776 total units.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-13" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-13-1">SAS Code</a></li><li><a href="#tabset-13-2">R Code</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb122"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a></a>proc power ;</span>
<span id="cb122-2"><a></a>twosamplefreq</span>
<span id="cb122-3"><a></a>    refproportion<span class="ot">=</span><span class="fl">0.4</span> </span>
<span id="cb122-4"><a></a>    alpha<span class="ot">=</span><span class="fl">0.05</span></span>
<span id="cb122-5"><a></a>    power<span class="ot">=</span><span class="fl">0.80</span></span>
<span id="cb122-6"><a></a>    proportiondiff<span class="ot">=</span><span class="fl">0.1</span></span>
<span id="cb122-7"><a></a>    npergroup<span class="ot">=</span>.;</span>
<span id="cb122-8"><a></a></span>
<span id="cb122-9"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-13-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a></a><span class="fu">power.prop.test</span>(<span class="at">p1=</span><span class="fl">0.4</span>,<span class="at">p2=</span><span class="fl">0.5</span>,<span class="at">power=</span><span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample comparison of proportions power calculation 

              n = 387.3385
             p1 = 0.4
             p2 = 0.5
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Chapter 2- <a href="https://madfudolig.quarto.pub/eab770slides/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            // Attach click handler to the DT
            const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
            for (const annoteDlNode of annoteDls) {
              annoteDlNode.addEventListener('click', (event) => {
                const clickedEl = event.target;
                if (clickedEl !== selectedAnnoteEl) {
                  unselectCodeLines();
                  const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                  if (activeEl) {
                    activeEl.classList.remove('code-annotation-active');
                  }
                  selectCodeLines(clickedEl);
                  clickedEl.classList.add('code-annotation-active');
                } else {
                  // Unselect the line
                  unselectCodeLines();
                  clickedEl.classList.remove('code-annotation-active');
                }
              });
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>