<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Miguel Fudolig">
  <title>EAB770: Applied Statistical Methods for Categorical Data – EAB 770 - Chapter 5</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-146a52615c86749306b5caa224a9b489.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">EAB 770 - Chapter 5</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Miguel Fudolig 
</div>
</div>
</div>

</section>
<section>
<section id="s-times-r-tables" class="title-slide slide level1 center">
<h1><span class="math inline">\(s \times r\)</span> tables</h1>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<ul>
<li>Association
<ul>
<li>Test for General Association</li>
<li>Mean Score Test</li>
<li>Correlation Test</li>
<li>Exact Tests</li>
</ul></li>
<li>Measures of Association
<ul>
<li>Ordinal</li>
<li>Nominal</li>
</ul></li>
<li>Observer Agreement (inter-rater reliability)</li>
<li>Test for Ordered Differences</li>
</ul>
</section></section>
<section>
<section id="what-if-there-are-more-than-two-groups-outcomes" class="title-slide slide level1 center">
<h1>What if there are more than two groups outcomes?</h1>

</section>
<section id="multiple-categorical-outcomes" class="slide level2">
<h2>Multiple Categorical Outcomes</h2>
<p>Common examples include Likert Scale (Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree) responses and parts of a whole (None, Some, All).</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We would need more than two columns in our contingency table to account for these other outcomes. Variables can be forced to be “binary”, but some important information can be lost.</p>
</div>
</div>
</div>
</section>
<section id="multiple-groups" class="slide level2">
<h2>Multiple Groups</h2>
<p>It is also common to compare responses from multiple groups such as Race, Income Status, and Exposure levels. Dichotomizing these variables to fit into a 2x2 will also result in loss of information.</p>
</section></section>
<section>
<section id="associations-in-s-times-r-tables" class="title-slide slide level1 center">
<h1>Associations in <span class="math inline">\(s \times r\)</span> tables</h1>

</section>
<section id="s-times-r-tables-1" class="slide level2">
<h2><span class="math inline">\(s \times r\)</span> tables</h2>
<p>We now evolve the contingency table from a <span class="math inline">\(2 \times 2 \to  s  \times r\)</span>, where <span class="math inline">\(s\)</span> is the number of rows and <span class="math inline">\(r\)</span> is the number of columns. Both <span class="math inline">\(s\)</span> and <span class="math inline">\(r\)</span> are expected to be at least 2.</p>

<img data-src="img/sxr_C5.png" class="r-stretch"></section>
<section id="general-association-statistic" class="slide level2">
<h2>General Association Statistic</h2>
<p>When the groups and the response variable categories can be nominally scaled, we can only test for general association.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Statistical Hypotheses</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(H_0\)</span>: there is no general association between the groups and response variables.</li>
<li><span class="math inline">\(H_A\)</span>: there is a general association between the two variables</li>
</ul>
</div>
</div>
</div>
</section>
<section id="general-association-statistic-1" class="slide level2">
<h2>General Association Statistic</h2>
<p>The randomization statistic based on Mantel-Haenszel statistics can be calculated from the Pearson chi-square statistic, <span class="math inline">\(Q_P\)</span>.</p>
<p><span class="math display">\[
Q = \left(\frac{n-1}{n}\right) Q_P
\]</span></p>
<p>where,</p>
<p><span class="math display">\[
Q_P = \sum_{i=1}^s\sum_{j=1}^r \frac{(n_{ij}-m_{ij})^2}{m_{ij}}
\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">\(n\)</span> is large, <span class="math inline">\(Q \approx Q_P\)</span>. Like the Pearson chi-square, <span class="math inline">\(Q\)</span> follows a chi-square distribution with <span class="math inline">\((s-1)(r-1)\)</span> degrees of freedom.</p>
</div>
</div>
</div>
</section>
<section id="mosaic-plot" class="slide level2">
<h2>Mosaic Plot</h2>
<p>A mosaic plot visualizes the proportion in each cell of the contingency table.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The horizontal space is divided by sizes corresponding to the relative count of x-axis variable levels, while the vertical space is divided up according to relative sizes of the y-axis variable levels.</p>
</div>
</div>
</div>
</section>
<section id="mosaic-plot-in-r" class="slide level2">
<h2>Mosaic Plot in <code>R</code></h2>
<p>The <code>mosaic()</code> function in the <code>vcd</code> package creates a mosaic plot for data frames/contingency tables. Shown below is the mosaic plot for the <code>UCBAdmissions</code> data set, which shows the aggregate data on applicants to graduate school at UC Berkeley in 1973.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Plot</a></li><li><a href="#tabset-1-2">Notes</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(vcd)</span>
<span id="cb1-2"><a></a><span class="fu">mosaic</span>(<span class="sc">~</span>Admit <span class="sc">+</span>Dept,</span>
<span id="cb1-3"><a></a>       <span class="at">highlighting=</span><span class="st">"Admit"</span>,</span>
<span id="cb1-4"><a></a>       <span class="at">highlighting_fill=</span><span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>),</span>
<span id="cb1-5"><a></a>       <span class="at">data=</span>UCBAdmissions)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Chapter5_files/figure-revealjs/unnamed-chunk-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The <code>highlighting</code> option provides <code>mosaic</code> information about which variables need to be shaded. The <code>highlighting_fill</code> provides the colors you want to use the highlight these variables.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="general-association-sas" class="slide level2">
<h2>General Association: SAS</h2>
<ul>
<li>In SAS, the Pearson chi-square statistic <span class="math inline">\(Q_P\)</span> is the value referred to as ‘Chi-square”</li>
<li>Note that <span class="math inline">\(Q\)</span> is <strong>NOT</strong> the Mantel-Haenszel statistic in the <code>chisq</code> output in SAS.
<ul>
<li><span class="math inline">\(Q\)</span> is the “General Association” cell in the <code>cmh</code> output.</li>
</ul></li>
<li>We can use the <code>plots</code> option in the <code>tables</code> statement to create a mosaic plot.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-1"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1"></a>proc freq;</span>
<span id="annotated-cell-1-2"><a href="#annotated-cell-1-2"></a>weight count;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-1-3" class="code-annotation-target"><a href="#annotated-cell-1-3"></a>tables a<span class="sc">*</span>b<span class="sc">/</span>cmh plots<span class="ot">=</span>mosaicplot;</span>
<span id="annotated-cell-1-4"><a href="#annotated-cell-1-4"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="3" data-code-annotation="1"><code>cmh</code> calculates the general association Cochran-Mantel-Haenszel statistic. <code>plots=mosaicplot</code> tells SAS to create a mosaic plot with <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>.</span>
</dd>
</dl>
</section>
<section id="general-association-r" class="slide level2">
<h2>General Association: <code>R</code></h2>
<p>The <code>CMHtest()</code> function provides the general association Cochram-Mantel-Haenszel statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">CMHtest</span>(contingencytable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>The table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Questions</a></li><li><a href="#tabset-2-2"><code>SAS</code></a></li><li><a href="#tabset-2-3"><code>R</code> Data</a></li><li><a href="#tabset-2-4"><code>R</code> Code</a></li><li><a href="#tabset-2-5">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<ul>
<li>What is the Pearson chi-square value?</li>
<li>What is the randomization statistic?</li>
<li>Is there sufficient evidence of an association between political party and neighborhood?</li>
<li>Create a mosaic plot for this problem.</li>
</ul>
<p><img data-src="img/party_C5.png"></p>
</div>
<div id="tabset-2-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-9"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-9-1"><a href="#annotated-cell-9-1"></a>data neighbor;</span>
<span id="annotated-cell-9-2"><a href="#annotated-cell-9-2"></a>length party <span class="sc">$</span> <span class="dv">11</span> neighborhood <span class="sc">$</span> <span class="dv">10</span>;</span>
<span id="annotated-cell-9-3"><a href="#annotated-cell-9-3"></a>input party <span class="sc">$</span> neighborhood <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-9-4"><a href="#annotated-cell-9-4"></a>datalines;</span>
<span id="annotated-cell-9-5"><a href="#annotated-cell-9-5"></a>democrat longview <span class="dv">360</span> democrat bayside <span class="dv">221</span></span>
<span id="annotated-cell-9-6"><a href="#annotated-cell-9-6"></a>democrat sheffeld <span class="dv">140</span> democrat highland <span class="dv">160</span></span>
<span id="annotated-cell-9-7"><a href="#annotated-cell-9-7"></a>republican longview <span class="dv">316</span> republican bayside <span class="dv">208</span></span>
<span id="annotated-cell-9-8"><a href="#annotated-cell-9-8"></a>republican sheffeld <span class="dv">97</span> republican highland <span class="dv">106</span></span>
<span id="annotated-cell-9-9"><a href="#annotated-cell-9-9"></a>independent longview <span class="dv">160</span> independent bayside <span class="dv">200</span></span>
<span id="annotated-cell-9-10"><a href="#annotated-cell-9-10"></a>independent sheffeld <span class="dv">311</span> independent highland <span class="dv">291</span></span>
<span id="annotated-cell-9-11"><a href="#annotated-cell-9-11"></a>;</span>
<span id="annotated-cell-9-12"><a href="#annotated-cell-9-12"></a></span>
<span id="annotated-cell-9-13"><a href="#annotated-cell-9-13"></a>proc freq data<span class="ot">=</span>neighbor;</span>
<span id="annotated-cell-9-14"><a href="#annotated-cell-9-14"></a>weight count;</span>
<span id="annotated-cell-9-15"><a href="#annotated-cell-9-15"></a>tables party<span class="sc">*</span>neighborhood <span class="sc">/</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-9-16" class="code-annotation-target"><a href="#annotated-cell-9-16"></a>plots<span class="ot">=</span>mosaicplot chisq cmh nocol nopct;</span>
<span id="annotated-cell-9-17"><a href="#annotated-cell-9-17"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="16" data-code-annotation="1">Included both <code>chisq</code> and <code>cmh</code> to show discrepancy.</span>
</dd>
</dl>
</div>
<div id="tabset-2-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Party=</span><span class="fu">c</span>(<span class="st">"Democrat"</span>,<span class="st">"Independent"</span>,<span class="st">"Republican"</span>),</span>
<span id="cb3-2"><a></a>                   <span class="at">Neighborhood =</span> <span class="fu">c</span>(<span class="st">"Bayside"</span>,<span class="st">"Highland"</span>,<span class="st">"Longview"</span>,<span class="st">"Sheffield"</span>))</span>
<span id="cb3-3"><a></a></span>
<span id="cb3-4"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">221</span>,<span class="dv">200</span>,<span class="dv">208</span>,<span class="dv">160</span>,<span class="dv">291</span>,<span class="dv">106</span>,<span class="dv">360</span>,<span class="dv">160</span>,<span class="dv">316</span>,<span class="dv">140</span>,<span class="dv">311</span>,<span class="dv">97</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-2-4">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count<span class="sc">~</span>Party<span class="sc">+</span>Neighborhood,<span class="at">data=</span>dat)</span>
<span id="cb4-2"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Neighborhood
Party         Bayside Highland Longview Sheffield
  Democrat        221      160      360       140
  Independent     200      291      160       311
  Republican      208      106      316        97</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">mosaic</span>(<span class="at">data=</span>dat_cc,</span>
<span id="cb6-2"><a></a>       <span class="sc">~</span>Party<span class="sc">+</span>Neighborhood,</span>
<span id="cb6-3"><a></a>       <span class="at">highlighting=</span><span class="st">"Party"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Chapter5_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Pearson chi-square:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">chisq.test</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  dat_cc
X-squared = 273.92, df = 6, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Randomization Statistic (use general association):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">CMHtest</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Party by Neighborhood 

                 AltHypothesis     Chisq Df       Prob
cor        Nonzero correlation   0.81238  1 3.6742e-01
rmeans  Row mean scores differ  13.89377  2 9.6163e-04
cmeans  Col mean scores differ   3.15865  3 3.6781e-01
general    General association 273.81223  6 3.3158e-56</code></pre>
</div>
</div>
</div>
<div id="tabset-2-5">
<p><span class="math inline">\(Q_P\)</span> = 273.92, <span class="math inline">\(Q\)</span> = 273.81. The corresponding p-value <span class="math inline">\(p&lt;0.001\)</span> suggests there is an association between party affiliation and neighborhood.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In SAS, note that the Mantel-Haenszel statistic reported in the <code>chisq</code> output corresponds to the correlation statistic which doesn’t make sense in this case (discussed later).</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Secondary school teachers were randomly sampled from four school districts in Nevada and asked what marker color they used in grading students’ work.</p>
<ul>
<li>What is the Pearson chi-square statistic?</li>
<li>What is the randomization statistic?</li>
<li>Generate a mosaic plot for this example. Can you see a trend between the colors and/or the counties?</li>
<li>At a significance level of 0.05, do we have sufficient evidence of a general association between the two variables?</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Data</a></li><li><a href="#tabset-3-2">SAS Code</a></li><li><a href="#tabset-3-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>data color;</span>
<span id="cb11-2"><a></a>input county <span class="sc">$</span> color <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb11-3"><a></a>datalines;</span>
<span id="cb11-4"><a></a>cl blu <span class="dv">22</span> cl red <span class="dv">57</span> cl green <span class="dv">12</span> cl blk <span class="dv">15</span></span>
<span id="cb11-5"><a></a>ca blu <span class="dv">12</span> ca red <span class="dv">30</span> ca green <span class="dv">6</span> ca blk <span class="dv">15</span></span>
<span id="cb11-6"><a></a>do blu <span class="dv">17</span> do red <span class="dv">34</span> do green <span class="dv">17</span> do blk <span class="dv">10</span></span>
<span id="cb11-7"><a></a>wa blu <span class="dv">5</span> wa red <span class="dv">56</span> wa green <span class="dv">7</span> wa blk <span class="dv">9</span></span>
<span id="cb11-8"><a></a>;</span>
<span id="cb11-9"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">county=</span><span class="fu">c</span>(<span class="st">"clark"</span>,<span class="st">"carson"</span>,<span class="st">"douglas"</span>,<span class="st">"washoe"</span>),</span>
<span id="cb12-2"><a></a>                   <span class="at">color =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>,<span class="st">"green"</span>,<span class="st">"black"</span>)) </span>
<span id="cb12-3"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">22</span>,<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">5</span>,<span class="dv">57</span>,<span class="dv">30</span>,<span class="dv">34</span>,<span class="dv">56</span>,<span class="dv">12</span>,<span class="dv">6</span>,<span class="dv">17</span>,<span class="dv">7</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">10</span>,<span class="dv">9</span>)</span>
<span id="cb12-4"><a></a></span>
<span id="cb12-5"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count<span class="sc">~</span>county<span class="sc">+</span>color,<span class="at">data=</span>dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-3-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a></span>
<span id="cb13-2"><a></a>data color;</span>
<span id="cb13-3"><a></a>input county <span class="sc">$</span> color <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb13-4"><a></a>datalines;</span>
<span id="cb13-5"><a></a>cl blu <span class="dv">22</span> cl red <span class="dv">57</span> cl green <span class="dv">12</span> cl blk <span class="dv">15</span></span>
<span id="cb13-6"><a></a>ca blu <span class="dv">12</span> ca red <span class="dv">30</span> ca green <span class="dv">6</span> ca blk <span class="dv">15</span></span>
<span id="cb13-7"><a></a>do blu <span class="dv">17</span> do red <span class="dv">34</span> do green <span class="dv">17</span> do blk <span class="dv">10</span></span>
<span id="cb13-8"><a></a>wa blu <span class="dv">5</span> wa red <span class="dv">56</span> wa green <span class="dv">7</span> wa blk <span class="dv">9</span></span>
<span id="cb13-9"><a></a>;</span>
<span id="cb13-10"><a></a>run;</span>
<span id="cb13-11"><a></a></span>
<span id="cb13-12"><a></a>proc freq data<span class="ot">=</span>color;</span>
<span id="cb13-13"><a></a>weight count;</span>
<span id="cb13-14"><a></a>tables county<span class="sc">*</span>color<span class="sc">/</span></span>
<span id="cb13-15"><a></a>plots<span class="ot">=</span>mosaicplot chisq cmh nocol nopct measures cl;</span>
<span id="cb13-16"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-3-3">
<p><span class="math inline">\(Q_P\)</span>= 24.36, <span class="math inline">\(Q\)</span> = 24.28, p = 0.004, which means there is strong evidence of an association between school district and marker color used for grading.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">county=</span><span class="fu">c</span>(<span class="st">"clark"</span>,<span class="st">"carson"</span>,<span class="st">"douglas"</span>,<span class="st">"washoe"</span>),</span>
<span id="cb14-2"><a></a>                   <span class="at">color =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>,<span class="st">"green"</span>,<span class="st">"black"</span>)) </span>
<span id="cb14-3"><a></a>dat<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">22</span>,<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">5</span>,<span class="dv">57</span>,<span class="dv">30</span>,<span class="dv">34</span>,<span class="dv">56</span>,<span class="dv">12</span>,<span class="dv">6</span>,<span class="dv">17</span>,<span class="dv">7</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">10</span>,<span class="dv">9</span>)</span>
<span id="cb14-4"><a></a></span>
<span id="cb14-5"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(count<span class="sc">~</span>county<span class="sc">+</span>color,<span class="at">data=</span>dat)</span>
<span id="cb14-6"><a></a></span>
<span id="cb14-7"><a></a><span class="fu">mosaic</span>(<span class="at">data=</span>dat_cc,</span>
<span id="cb14-8"><a></a>       <span class="sc">~</span>color <span class="sc">+</span> county,</span>
<span id="cb14-9"><a></a>       <span class="at">highlighting=</span><span class="st">"color"</span>,</span>
<span id="cb14-10"><a></a>       <span class="at">highlighting_fill=</span><span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>,<span class="st">"green"</span>,<span class="st">"black"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Chapter5_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="associations-involving-ordinal-variables" class="slide level2">
<h2>Associations Involving Ordinal Variables</h2>
<p>Suppose the column variable is ordinal such that <span class="math inline">\(A_j\)</span> is the <span class="math inline">\(j^{th}\)</span> outcome level. Since <span class="math inline">\(A_J\)</span> is ordinal, then <span class="math inline">\(A_1 &lt; A_2 &lt; A_3 &lt;... A_r\)</span>.</p>
<p>To account for ordinality, we assign a set of scores <span class="math inline">\(\mathbf{a}\)</span> reflecting the relationship between response levels.</p>
<p><span class="math display">\[
\mathbf{a} = \{a_1, a_2, a_3,... a_r\} : a_1 &lt; a_2 &lt; ...&lt; a_r
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The relationship can be <span class="math inline">\(\leq\)</span> instead of <span class="math inline">\(&lt;\)</span> as long as at least one pair is a strict inequality.</p>
</div>
</div>
</div>
</section>
<section id="row-mean-scores" class="slide level2">
<h2>Row Mean Scores</h2>
<p>Consider the following contingency table:</p>

<img data-src="img/2xr_C4.png" class="r-stretch"><p>We can define a group mean for <span class="math inline">\(X_1\)</span>, denoted by <span class="math inline">\(\bar{f}_1\)</span>.</p>
<p><span class="math display">\[
\bar{f}_1 = \sum_{j=1}^r \frac{a_j n_{1j}}{n_{1+}}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The scores <span class="math inline">\(\bar{f}_j\)</span> are referred to as <strong>row mean scores</strong>. The random variable <span class="math inline">\(\bar{f}_j\)</span> approximately has a normal distribution when the central limit theorem is imposed. This occurs when the row sums are high.</p>
<p>The term <span class="math inline">\(a_j\)</span> are the assigned scores for the columns. These can be regular integral scores (0,1,2,3,…) or based on rank. Rank-based scores yield midranks for tied values and are standardized for tied values.</p>
</div>
</div>
</div>
</section>
<section id="mean-score-tests-null-hypothesis" class="slide level2">
<h2>Mean Score Tests: Null Hypothesis</h2>
<p>The null hypothesis for tests involving the row mean scores is <span class="math inline">\(H_0\)</span>: There is no association between the row (X) and column (A) variables. Under the null hypothesis, the expected value of the row mean scores, <span class="math inline">\(\mu_a\)</span>, can be calculated as:</p>
<p><span class="math display">\[
\mu_a =  \sum_{j=1}^r \frac{a_j n_{+j}}{n}
\]</span></p>
<p>The corresponding alternative hypothesis is <span class="math inline">\(H_a:\)</span> There is a location shift across the groups. ## Mean Score Tests: Test Statistic</p>
<p>The test statistic is the mean score statistic <span class="math inline">\(Q_S\)</span> for an <span class="math inline">\(s \times r\)</span> table is given by:</p>
<p><span class="math display">\[
Q_S = \frac{(n-1)\sum_{i=1}^sn_{i+}(f_i-\mu_a)^2}{nv_a}
\]</span></p>
<p>where <span class="math inline">\(v_a = \sum_{j=1}^r(a_j-\mu_a)^2(n_{+j}/n)\)</span> is the variance of the row mean scores. This is consistent with an ANOVA approach in comparing means across each group.</p>
</section>
<section id="mean-score-tests-sample-considerations" class="slide level2">
<h2>Mean Score Tests: Sample Considerations</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">\(Q_S\)</span> sample size condition is less stringent:</p>
<ul>
<li>The row totals should be greater than 20.</li>
<li>Choose one or more cutpoints <span class="math inline">\(j = (2,3,...(r-1))\)</span>, add the first through <span class="math inline">\(j^{th}\)</span> columns together and add the <span class="math inline">\((j+1)^{th}\)</span> through <span class="math inline">\(r^{th}\)</span> columns together. If both of these sums are 5 or greater for at least one cutpoint in each row, then the sample size is adequate.</li>
</ul>
</div>
</div>
</div>
<p>If the sample size conditions are reached, <span class="math inline">\(Q_S\)</span> approximately follows a chi-square distribution with <span class="math inline">\((s-1)\)</span> degrees of freedom, where <span class="math inline">\(s\)</span> is the number of rows.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The mean score test uses less degrees of freedom compared to the general association test and the Pearson chi-square test.</p>
</div>
</div>
</div>
</section>
<section id="mean-score-tests-sas" class="slide level2">
<h2>Mean Score Tests: <code>SAs</code></h2>
<p>Included in the <code>cmh</code> table as “Row Mean Scores Differ”.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Use <code>scores=ridit</code> to use standardized rank scores or <code>scores=modridit</code> to use the expected valurs of the order statistics of the uniform distribution on (0,1).</p>
</div>
</div>
</div>
</section>
<section id="mean-score-tests-r" class="slide level2">
<h2>Mean Score Tests: <code>R</code></h2>
<p>The <code>CMHtest()</code> default output includes the <code>Row mean scores differ</code> row in the analysis. Ensure that the ordinal variable is assigned as the column variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">CMHtest</span>(contingencytable,</span>
<span id="cb15-2"><a></a>        <span class="at">cscores=</span><span class="st">"midrank"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The Col mean scores differ functions similarly with the ordinal variable assigned as the rows.</p>
<p>The <code>cscores</code> argument lets <code>R</code> know what <span class="math inline">\(a_j\)</span> to use for the columns. <code>CMHtest</code> will use integers as scores, which assumes the ordinal variable is equally spaced. To use rank-based scores, we can specify <code>cscores="midrank"</code>.</p>
</div>
</div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The data shown comes from a study on headache pain relief. A new treatment was compared with the standard treatment and a placebo. Researchers measured the number of hours of substantial relief from headache pain</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Question + Data</a></li><li><a href="#tabset-4-2">SAS Code</a></li><li><a href="#tabset-4-3">R Code</a></li><li><a href="#tabset-4-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<ul>
<li>Is the chi-square approximation valid for this case?</li>
<li>What kind of scoring method is most appropriate for this data set?</li>
<li>Make the appropriate conclusion based on the result of the mean score tests using a significance level <span class="math inline">\(\alpha=0.05\)</span>.</li>
</ul>
<p><img data-src="img/pain_C5.png"></p>
</div>
<div id="tabset-4-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>data pain;</span>
<span id="cb16-2"><a></a>input treatment <span class="sc">$</span> hours count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb16-3"><a></a>datalines;</span>
<span id="cb16-4"><a></a>placebo <span class="dv">0</span> <span class="dv">6</span> placebo <span class="dv">1</span> <span class="dv">9</span> placebo <span class="dv">2</span> <span class="dv">6</span> placebo <span class="dv">3</span> <span class="dv">3</span> placebo <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb16-5"><a></a>standard <span class="dv">0</span> <span class="dv">1</span> standard <span class="dv">1</span> <span class="dv">4</span> standard <span class="dv">2</span> <span class="dv">6</span> standard <span class="dv">3</span> <span class="dv">6</span> standard <span class="dv">4</span> <span class="dv">8</span></span>
<span id="cb16-6"><a></a>test <span class="dv">0</span> <span class="dv">2</span> test <span class="dv">1</span> <span class="dv">5</span> test <span class="dv">2</span> <span class="dv">6</span> test <span class="dv">3</span> <span class="dv">8</span> test <span class="dv">4</span> <span class="dv">6</span></span>
<span id="cb16-7"><a></a>;</span>
<span id="cb16-8"><a></a></span>
<span id="cb16-9"><a></a>proc freq data<span class="ot">=</span>pain order<span class="ot">=</span>data;</span>
<span id="cb16-10"><a></a>weight count;</span>
<span id="cb16-11"><a></a>tables treatment<span class="sc">*</span>hours<span class="sc">/</span> cmh nocol nopct;</span>
<span id="cb16-12"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-4-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment =</span> <span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Standard"</span>,<span class="st">"Test"</span>),</span>
<span id="cb17-2"><a></a>                   <span class="at">Hours =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb17-3"><a></a></span>
<span id="cb17-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">1</span>,<span class="dv">8</span>,<span class="dv">6</span>)</span>
<span id="cb17-5"><a></a></span>
<span id="cb17-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>Treatment<span class="sc">+</span>Hours,<span class="at">data=</span>dat)</span>
<span id="cb17-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Hours
Treatment  0 1 2 3 4
  Placebo  6 9 6 3 1
  Standard 1 4 6 6 8
  Test     2 5 6 8 6</code></pre>
</div>
</div>
<p>Now we can perform the mean score test. The integer scoring method is most appropriate because of the equal distance between the ordinal column variable values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="fu">CMHtest</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Treatment by Hours 

                 AltHypothesis   Chisq Df      Prob
cor        Nonzero correlation  8.0668  1 0.0045084
rmeans  Row mean scores differ 13.7346  2 0.0010413
cmeans  Col mean scores differ  8.4151  4 0.0775017
general    General association 14.4030  8 0.0718470</code></pre>
</div>
</div>
</div>
<div id="tabset-4-4">
<ul>
<li><p>Use column 3 (Hours = 2) as cutoff. The use of the chi-square approximation is justified!</p></li>
<li><p>The integer scoring method is most appropriate.</p></li>
<li><p><span class="math inline">\(Q_S\)</span> = 13.7, df=2, p=0.001. At <span class="math inline">\(\alpha=0.05\)</span>, there is sufficient evidence to conclude that at least one treatment group is different compared to the others.</p></li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>If we used the general association test, we would end up with p=0.07 and failing to reject the null hypothesis instead.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>The table shows data from a study that investigates intent to breastfeed of women who are interested in having children. The women who participated in the study were asked if they intended to breastfeed your child up to 6 months after birth. The researchers want to know if there is an effect of the order of pregnancy on their intent to breastfeed.</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">SAS Data</a></li><li><a href="#tabset-5-2">SAS Code</a></li><li><a href="#tabset-5-3">R Data</a></li><li><a href="#tabset-5-4">R Code</a></li><li><a href="#tabset-5-5">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>data preg;</span>
<span id="cb21-2"><a></a>input pregnancy <span class="sc">$</span>  outcome <span class="sc">$</span> score  count <span class="sc">@</span><span class="er">@</span> ;</span>
<span id="cb21-3"><a></a>datalines;</span>
<span id="cb21-4"><a></a>npnc sd <span class="dv">1</span> <span class="dv">8</span> npnc d <span class="dv">2</span> <span class="dv">22</span> npnc n <span class="dv">3</span> <span class="dv">24</span> npnc a <span class="dv">4</span> <span class="dv">27</span> npnc sa <span class="dv">5</span> <span class="dv">15</span></span>
<span id="cb21-5"><a></a>npc sd <span class="dv">1</span> <span class="dv">15</span> npc d <span class="dv">2</span> <span class="dv">23</span> npc n <span class="dv">3</span> <span class="dv">15</span> npc a <span class="dv">4</span> <span class="dv">19</span> npc sa <span class="dv">5</span> <span class="dv">9</span></span>
<span id="cb21-6"><a></a>fp sd <span class="dv">1</span> <span class="dv">18</span> fp d <span class="dv">2</span> <span class="dv">8</span> fp n <span class="dv">3</span> <span class="dv">22</span> fp a <span class="dv">4</span> <span class="dv">23</span> fp sa <span class="dv">5</span> <span class="dv">11</span></span>
<span id="cb21-7"><a></a>pwc sd <span class="dv">1</span> <span class="dv">35</span> pwc d <span class="dv">2</span> <span class="dv">13</span> pwc n <span class="dv">3</span> <span class="dv">10</span> pwc a <span class="dv">4</span> <span class="dv">9</span> pwc sa <span class="dv">5</span> <span class="dv">6</span></span>
<span id="cb21-8"><a></a>; </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variables</strong></p>
</div>
<div class="callout-content">
<ul>
<li>npnc: not pregnant, no children</li>
<li>npc: not pregnant with children</li>
<li>fp: first pregnancy</li>
<li>pwc: pregnant with children</li>
<li>sd: strongly disagree</li>
<li>d: disagree</li>
<li>n: neutral</li>
<li>a: agree</li>
<li>sa: strongly agree</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-5-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-28"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-28-1"><a href="#annotated-cell-28-1"></a>proc freq data<span class="ot">=</span>preg order<span class="ot">=</span>data;</span>
<span id="annotated-cell-28-2"><a href="#annotated-cell-28-2"></a>weight count;</span>
<span id="annotated-cell-28-3"><a href="#annotated-cell-28-3"></a>tables pregnancy<span class="sc">*</span>outcome <span class="sc">/</span> cmh nocol nopct;</span>
<span id="annotated-cell-28-4"><a href="#annotated-cell-28-4"></a>run;</span>
<span id="annotated-cell-28-5"><a href="#annotated-cell-28-5"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-28" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-28-6" class="code-annotation-target"><a href="#annotated-cell-28-6"></a>proc means data<span class="ot">=</span>preg order<span class="ot">=</span>data;</span>
<span id="annotated-cell-28-7"><a href="#annotated-cell-28-7"></a>freq count;</span>
<span id="annotated-cell-28-8"><a href="#annotated-cell-28-8"></a>class pregnancy;</span>
<span id="annotated-cell-28-9"><a href="#annotated-cell-28-9"></a>var score;</span>
<span id="annotated-cell-28-10"><a href="#annotated-cell-28-10"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-28" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-28" data-code-lines="6" data-code-annotation="1">The <code>means</code> procedure is shown to display the mean scores and how they indeed differ for each pregnancy order.</span>
</dd>
</dl>
</div>
<div id="tabset-5-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Pregnancy =</span> <span class="fu">c</span>(<span class="st">"NPNC"</span>,<span class="st">"NPC"</span>,<span class="st">"FP"</span>,<span class="st">"PWC"</span>),</span>
<span id="cb22-2"><a></a>                   <span class="at">Outcome =</span><span class="fu">c</span>(<span class="st">"S Disagree"</span>,<span class="st">"Disagree"</span>,<span class="st">"Neutral"</span>,<span class="st">"Agree"</span>,<span class="st">"S Agree"</span>))</span>
<span id="cb22-3"><a></a></span>
<span id="cb22-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">15</span>,<span class="dv">18</span>,<span class="dv">35</span>,<span class="dv">22</span>,<span class="dv">23</span>,<span class="dv">8</span>,<span class="dv">13</span>,<span class="dv">24</span>,<span class="dv">15</span>,<span class="dv">22</span>,<span class="dv">10</span>,<span class="dv">27</span>,<span class="dv">19</span>,<span class="dv">23</span>,<span class="dv">9</span>,<span class="dv">15</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">6</span>)</span>
<span id="cb22-5"><a></a></span>
<span id="cb22-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>Pregnancy<span class="sc">+</span>Outcome,<span class="at">data=</span>dat)</span>
<span id="cb22-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Outcome
Pregnancy S Disagree Disagree Neutral Agree S Agree
     NPNC          8       22      24    27      15
     NPC          15       23      15    19       9
     FP           18        8      22    23      11
     PWC          35       13      10     9       6</code></pre>
</div>
</div>
</div>
<div id="tabset-5-4">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">CMHtest</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Pregnancy by Outcome 

                 AltHypothesis  Chisq Df       Prob
cor        Nonzero correlation 18.634  1 1.5837e-05
rmeans  Row mean scores differ 27.200  3 5.3462e-06
cmeans  Col mean scores differ 33.731  4 8.4615e-07
general    General association 48.794 12 2.2725e-06</code></pre>
</div>
</div>
</div>
<div id="tabset-5-5">
<p><span class="math inline">\(Q_S= 27.2\)</span>, df=3, p=5.35e-6. There is sufficient evidence of an effect of pregnancy order on intent to breastfeed.</p>
</div>
</div>
</div>
</section>
<section id="ordinal-row-and-column-variables" class="slide level2">
<h2>Ordinal Row and Column Variables</h2>
<p>When the row variable is also ordinal, we can assign row scores <span class="math inline">\(c_j\)</span> such that</p>
<p><span class="math display">\[
\mathbf{c} = \{c_1, c_2, c_3,... c_s\} : c_1 &lt; c_2 &lt; ...&lt; c_s
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Because both variables are ordinal, we can test for correlation between the two variables.</p>
</div>
</div>
</div>
<p>Then for each cell, the expected frequency, <span class="math inline">\(\bar{f}\)</span> can be written as:</p>
<p><span class="math display">\[
\bar{f} = \sum_{i=1}^s\sum_{j=1}^r \frac{c_ia_jn_{ij}}{n}
\]</span></p>
</section>
<section id="correlation-tests" class="slide level2">
<h2>Correlation Tests</h2>
<p>The null hypothesis for the association tests remains to be <span class="math inline">\(H_0\)</span>: There is no association between the two variables. To test this hypothesis, we can use a randomization statistic <span class="math inline">\(Q_{CS}\)</span> that accounts for the ordinality of both variables.</p>
<p><span class="math display">\[
Q_{CS} = \frac{(\bar{f}-\mu_c\mu_a)^2}{v_cv_a/(n-1)} = (n-1)r_{ac}^2
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(\mu_c\)</span> is the expected value of the row scores</li>
<li><span class="math inline">\(\mu_a\)</span> is the expected value of the column scores.</li>
<li><span class="math inline">\(v_c\)</span> is the variance of the row scores</li>
<li><span class="math inline">\(v_a\)</span> is variance of the column scores</li>
</ul>
<p><span class="math inline">\(r_{ac}\)</span> is the Pearson correlation coefficient, which measures the correlation between the ordinal variables.</p>
</div>
</div>
</div>
</section>
<section id="correlation-tests-1" class="slide level2">
<h2>Correlation Tests</h2>
<p><span class="math inline">\(Q_{CS}\)</span> follows a chi-square distribution with 1 degree of freedom, regardless of the size of the table, when the sample size is at least 20.</p>
</section>
<section id="correlation-tests-sas" class="slide level2">
<h2>Correlation Tests: <code>SAS</code></h2>
<p><span class="math inline">\(Q_{CS}\)</span> is the Mantel-Haenszel chi-square statistic displayed by the <code>chisq</code> and <code>cmh</code> output.</p>
</section>
<section id="correlation-tests-r" class="slide level2">
<h2>Correlation Tests: <code>R</code></h2>
<p><span class="math inline">\(Q_{CS}\)</span> is part of the <code>CMHtest()</code> output.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The default scores for the row and column scores are integer scores. Specify <code>rscores</code>/<code>cscores</code> as <code>midrank</code> to use rank-based scores.</p>
</div>
</div>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>A water treatment company is studying water additives and investigating how they affect clothes washing. The treatments studied were no treatment (plain water), the standard treatment, and a double dose of the standard treatment, called super. Washability was measured as low, medium, and high. The company claims that the dose of water treatment affects the washability of water. Do we have sufficient evidence to support this claim?</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Data</a></li><li><a href="#tabset-6-2">SAS Code</a></li><li><a href="#tabset-6-3">R Code</a></li><li><a href="#tabset-6-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p><img data-src="img/wash_C5.png"></p>
</div>
<div id="tabset-6-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>data wash;</span>
<span id="cb26-2"><a></a>input treatment <span class="sc">$</span> washability <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb26-3"><a></a>datalines;</span>
<span id="cb26-4"><a></a>water low <span class="dv">27</span> water medium <span class="dv">14</span> water high <span class="dv">5</span></span>
<span id="cb26-5"><a></a>standard low <span class="dv">10</span> standard medium <span class="dv">17</span> standard high <span class="dv">26</span></span>
<span id="cb26-6"><a></a>super low <span class="dv">5</span> super medium <span class="dv">12</span> super high <span class="dv">50</span></span>
<span id="cb26-7"><a></a>;</span>
<span id="cb26-8"><a></a></span>
<span id="cb26-9"><a></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>wash;</span>
<span id="cb26-10"><a></a>weight count;</span>
<span id="cb26-11"><a></a>tables treatment<span class="sc">*</span>washability <span class="sc">/</span> chisq cmh;</span>
<span id="cb26-12"><a></a>tables treatment<span class="sc">*</span>washability <span class="sc">/</span> scores<span class="ot">=</span>modridit cmh</span>
<span id="cb26-13"><a></a>noprint nocol nopct;</span>
<span id="cb26-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-6-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Treatment=</span><span class="fu">c</span>(<span class="st">"Water"</span>,<span class="st">"Standard"</span>,<span class="st">"Super"</span>),</span>
<span id="cb27-2"><a></a>                   <span class="at">Washability=</span><span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"Medium"</span>,<span class="st">"High"</span>))</span>
<span id="cb27-3"><a></a></span>
<span id="cb27-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">27</span>,<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">14</span>,<span class="dv">17</span>,<span class="dv">12</span>,<span class="dv">5</span>,<span class="dv">26</span>,<span class="dv">50</span>)</span>
<span id="cb27-5"><a></a></span>
<span id="cb27-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>Treatment<span class="sc">+</span>Washability,<span class="at">data=</span>dat)</span>
<span id="cb27-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Washability
Treatment  Low Medium High
  Water     27     14    5
  Standard  10     17   26
  Super      5     12   50</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a><span class="fu">CMHtest</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Treatment by Washability 

                 AltHypothesis  Chisq Df       Prob
cor        Nonzero correlation 50.602  1 1.1315e-12
rmeans  Row mean scores differ 52.779  2 3.4616e-12
cmeans  Col mean scores differ 50.782  2 9.3945e-12
general    General association 54.756  4 3.6548e-11</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">CMHtest</span>(dat_cc,</span>
<span id="cb31-2"><a></a>        <span class="at">rscores=</span><span class="st">"midrank"</span>,</span>
<span id="cb31-3"><a></a>        <span class="at">cscores=</span><span class="st">"midrank"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Treatment by Washability 

                 AltHypothesis  Chisq Df       Prob
cor        Nonzero correlation 49.541  1 1.9427e-12
rmeans  Row mean scores differ 52.515  2 3.9496e-12
cmeans  Col mean scores differ 49.572  2 1.7205e-11
general    General association 54.756  4 3.6548e-11</code></pre>
</div>
</div>
</div>
<div id="tabset-6-4">
<p><span class="math inline">\(Q_{CS}=50.6\)</span>, p&lt;0.0001. There is sufficient evidence to claim that the dose of water treatment is associated with the washability of the water.</p>
<p>If modridit scores are used, <span class="math inline">\(Q_{CS}=49.5\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>A random sample of 400 college students are classified according to class status and drinking habits. Test the null hypothesis that class status and drinking habits are not correlated to each other.</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">Data</a></li><li><a href="#tabset-7-2">R Code</a></li><li><a href="#tabset-7-3">SAS Code</a></li><li><a href="#tabset-7-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<div title="Variables">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variables</strong></p>
</div>
<div class="callout-content">
<p>non: nondrinkers; mod: moderate; hea: heavy; fres: freshman; soph: sophomore; jun: junior; sen:senior</p>
</div>
</div>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>data drink; </span>
<span id="cb33-2"><a></a>input habit <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb33-3"><a></a>datalines;</span>
<span id="cb33-4"><a></a>non fres <span class="dv">55</span> non soph <span class="dv">34</span> non jun <span class="dv">27</span> non sen <span class="dv">17</span></span>
<span id="cb33-5"><a></a>mod fres <span class="dv">32</span> mod soph <span class="dv">29</span> mod jun <span class="dv">36</span> mod sen <span class="dv">39</span></span>
<span id="cb33-6"><a></a>hea fres <span class="dv">29</span> hea soph <span class="dv">41</span> hea jun <span class="dv">33</span> hea sen <span class="dv">28</span></span>
<span id="cb33-7"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">habit =</span> <span class="fu">c</span>(<span class="st">"Nondrinkers"</span>,<span class="st">"Moderate"</span>,<span class="st">"Heavy"</span>),</span>
<span id="cb34-2"><a></a>                   <span class="at">Status =</span> <span class="fu">c</span>(<span class="st">"Freshmen"</span>,<span class="st">"Sophomore"</span>,<span class="st">"Junior"</span>,<span class="st">"Senior"</span>))</span>
<span id="cb34-3"><a></a></span>
<span id="cb34-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">55</span>,<span class="dv">32</span>,<span class="dv">29</span>,<span class="dv">34</span>,<span class="dv">29</span>,<span class="dv">41</span>,<span class="dv">27</span>,<span class="dv">36</span>,<span class="dv">33</span>,<span class="dv">17</span>,<span class="dv">39</span>,<span class="dv">28</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>habit<span class="sc">+</span>Status,<span class="at">data=</span>dat)</span>
<span id="cb35-2"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Status
habit         Freshmen Sophomore Junior Senior
  Nondrinkers       55        34     27     17
  Moderate          32        29     36     39
  Heavy             29        41     33     28</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">CMHtest</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for habit by Status 

                 AltHypothesis  Chisq Df       Prob
cor        Nonzero correlation  9.182  1 0.00244408
rmeans  Row mean scores differ 18.147  2 0.00011468
cmeans  Col mean scores differ 12.249  3 0.00657745
general    General association 22.325  6 0.00105692</code></pre>
</div>
</div>
</div>
<div id="tabset-7-3">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>data drink;</span>
<span id="cb39-2"><a></a>input habit <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb39-3"><a></a>datalines;</span>
<span id="cb39-4"><a></a>non f <span class="dv">55</span> non soph <span class="dv">34</span> non j <span class="dv">27</span> non sen <span class="dv">17</span></span>
<span id="cb39-5"><a></a>mod f <span class="dv">32</span> mod soph <span class="dv">29</span> mod j <span class="dv">36</span> mod sen <span class="dv">39</span></span>
<span id="cb39-6"><a></a>hea f <span class="dv">29</span> hea soph <span class="dv">41</span> hea j <span class="dv">33</span> hea sen <span class="dv">28</span></span>
<span id="cb39-7"><a></a>;</span>
<span id="cb39-8"><a></a></span>
<span id="cb39-9"><a></a>proc freq data<span class="ot">=</span>drink order<span class="ot">=</span>data;</span>
<span id="cb39-10"><a></a>weight count;</span>
<span id="cb39-11"><a></a>tables habit<span class="sc">*</span>status<span class="sc">/</span>cmh chisq;</span>
<span id="cb39-12"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-7-4">
<p>Table Scores: <span class="math inline">\(Q_{CS}\)</span> = 9.18, p=0.0024. At <span class="math inline">\(\alpha=0.05\)</span>, here is sufficient evidence to support the claim that class status and drinking habits are correlated to each other.</p>
</div>
</div>
</div>
</section>
<section id="exact-tests" class="slide level2">
<h2>Exact Tests</h2>
<p>For a 2x2 contingency table, we have Fisher’s Exact Test. The Fisher’s Exact test can be generalized to larger contingency tables using a multivariate hypergeometric distribution. Unlike Fisher’s Exact Test for 2x2 tables, there are no one-sided alternative hypothesis.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Exact p-value is the sum of p-values associated with contingency tables where the test statistic is larger than the observed table.</p>
</div>
</div>
</div>
</section>
<section id="exact-tests-sas" class="slide level2">
<h2>Exact Tests: SAS</h2>
<ul>
<li>The <code>exact</code> statement can be used to calculate exact p-values and perform exact tests.
<ul>
<li><code>Fisher</code> – Fisher’s exact test</li>
<li><code>PCHI</code> – Pearson chi-square statistic</li>
<li><code>LRCHI</code> – likelihood ratio chi-square statistic</li>
<li><code>MHCHI</code> - Mantel-Haenszel statistic (Correlation tests)</li>
</ul></li>
</ul>
</section>
<section id="exact-tests-sas-1" class="slide level2">
<h2>Exact Tests: SAS</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Exact tests are computationally intensive. More cells lead to more calculations, which makes exact computation not feasible.</p>
<ul>
<li>You can set the <code>MAXTIME</code> option in the exact statement to tell SAS to stop computations beyond a certain number of seconds.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exact-tests-r" class="slide level2">
<h2>Exact Tests: <code>R</code></h2>
<p>If the sample size is small enough, the <code>fisher.test()</code> function can be used to implement exact tests.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><code>SAS</code> has better functions to perform exact tests for the Pearson and randomization statistics.</p>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>A marketing research firm organized a focus group to consider issues of new car marketing. Members of the group included people who had purchased a car from a local dealer in the last month. Researchers were interested in whether there was an association between the type of car bought and how group members found out about the car in the media. Cars were classified as sedans, sporty, and utility. The types of media included television, magazines, newspapers, and radio.</p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Data</a></li><li><a href="#tabset-8-2">SAS Code</a></li><li><a href="#tabset-8-3">R Code</a></li><li><a href="#tabset-8-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p><img data-src="img/car_C5.png"></p>
</div>
<div id="tabset-8-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>data market;</span>
<span id="cb40-2"><a></a>length AdSource <span class="sc">$</span> <span class="fl">9.</span> ;</span>
<span id="cb40-3"><a></a>input car <span class="sc">$</span> AdSource <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb40-4"><a></a>datalines;</span>
<span id="cb40-5"><a></a>sporty paper <span class="dv">3</span> sporty radio <span class="dv">4</span> sporty tv <span class="dv">0</span> sporty magazine <span class="dv">3</span></span>
<span id="cb40-6"><a></a>sedan paper <span class="dv">0</span> sedan radio <span class="dv">2</span> sedan tv <span class="dv">4</span> sedan magazine <span class="dv">0</span></span>
<span id="cb40-7"><a></a>utility paper <span class="dv">2</span> utility radio <span class="dv">2</span> utility tv <span class="dv">5</span> utility magazine <span class="dv">5</span></span>
<span id="cb40-8"><a></a>;</span>
<span id="cb40-9"><a></a>proc freq;</span>
<span id="cb40-10"><a></a>weight count;</span>
<span id="cb40-11"><a></a>table car<span class="sc">*</span>AdSource <span class="sc">/</span> norow nocol nopct;</span>
<span id="cb40-12"><a></a>exact fisher pchi lrchi;</span>
<span id="cb40-13"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-8-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a>dat<span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Car=</span><span class="fu">c</span>(<span class="st">"Sedan"</span>,<span class="st">"Sporty"</span>,<span class="st">"Utility"</span>),</span>
<span id="cb41-2"><a></a>                  <span class="at">AdSource=</span><span class="fu">c</span>(<span class="st">"TV"</span>,<span class="st">"Magazine"</span>,<span class="st">"Newspaper"</span>,<span class="st">"Radio"</span>))</span>
<span id="cb41-3"><a></a></span>
<span id="cb41-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">5</span>,<span class="dv">0</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">0</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">2</span>)</span>
<span id="cb41-5"><a></a></span>
<span id="cb41-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>Car<span class="sc">+</span>AdSource,<span class="at">data=</span>dat)</span>
<span id="cb41-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         AdSource
Car       TV Magazine Newspaper Radio
  Sedan    4        0         0     2
  Sporty   0        3         3     4
  Utility  5        5         2     2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a><span class="fu">fisher.test</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  dat_cc
p-value = 0.04734
alternative hypothesis: two.sided</code></pre>
</div>
</div>
</div>
<div id="tabset-8-4">
<p>We need to use Fisher’s exact test because of the small sample size. The p-value was calculated to be 0.047, which is sufficient evidence to conclude that there is an association between car type and media at the 0.05 level of significance.</p>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>A university professor wanted to test the general association between the most used social media app and the type of high school attended by freshmen. The professor asked 23 students in his class about their social media habits and respective high schools.</p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Data</a></li><li><a href="#tabset-9-2">SAS Code</a></li><li><a href="#tabset-9-3">R Code</a></li><li><a href="#tabset-9-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Tiktok</th>
<th>Instagram</th>
<th>Snapchat</th>
<th>Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Priv., in-state</td>
<td>3</td>
<td>2</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td>Pub., in-state</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Priv., out-of-state</td>
<td>4</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Pub., out-of-state</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-9-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>data sm;</span>
<span id="cb45-2"><a></a>input school <span class="sc">$</span> social <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb45-3"><a></a>datalines;</span>
<span id="cb45-4"><a></a>Pr_IS t <span class="dv">3</span> Pr_IS i <span class="dv">2</span> Pr_IS s <span class="dv">3</span> Pr_IS o <span class="dv">0</span></span>
<span id="cb45-5"><a></a>Pu_IS t <span class="dv">3</span> Pu_IS i <span class="dv">1</span> Pu_IS s <span class="dv">0</span> Pu_IS o <span class="dv">0</span></span>
<span id="cb45-6"><a></a>Pr_OS t <span class="dv">4</span> Pr_OS i <span class="dv">1</span> Pr_OS s <span class="dv">0</span> Pr_OS o <span class="dv">1</span></span>
<span id="cb45-7"><a></a>Pu_OS t <span class="dv">1</span> Pu_OS i <span class="dv">0</span> Pu_OS s <span class="dv">0</span> Pu_OS o <span class="dv">1</span></span>
<span id="cb45-8"><a></a>;</span>
<span id="cb45-9"><a></a></span>
<span id="cb45-10"><a></a>proc freq data<span class="ot">=</span>sm order<span class="ot">=</span>data;</span>
<span id="cb45-11"><a></a>weight count;</span>
<span id="cb45-12"><a></a>tables school<span class="sc">*</span>social;</span>
<span id="cb45-13"><a></a>exact fisher pchi lrchi;</span>
<span id="cb45-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-9-3">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">School=</span><span class="fu">c</span>(<span class="st">"Priv_In"</span>,<span class="st">"Public_In"</span>,<span class="st">"Priv_Out"</span>,<span class="st">"Public_Out"</span>),</span>
<span id="cb46-2"><a></a>                   <span class="at">Social=</span><span class="fu">c</span>(<span class="st">"Tiktok"</span>,<span class="st">"Instagram"</span>,<span class="st">"Snapchat"</span>,<span class="st">"Other"</span>))</span>
<span id="cb46-3"><a></a></span>
<span id="cb46-4"><a></a>dat<span class="sc">$</span>Count <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb46-5"><a></a></span>
<span id="cb46-6"><a></a>dat_cc <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(Count<span class="sc">~</span>School<span class="sc">+</span>Social,<span class="at">data=</span>dat)</span>
<span id="cb46-7"><a></a>dat_cc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Social
School       Tiktok Instagram Snapchat Other
  Priv_In         3         2        3     0
  Public_In       3         1        0     0
  Priv_Out        4         1        0     1
  Public_Out      1         0        0     1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">fisher.test</span>(dat_cc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  dat_cc
p-value = 0.4878
alternative hypothesis: two.sided</code></pre>
</div>
</div>
</div>
<div id="tabset-9-4">
<p>The Fisher’s exact test yielded p=0.4878, which means there is insufficient evidence to claim that social media habits are associated with the type of high school attended by the students.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="measures-of-association" class="title-slide slide level1 center">
<h1>Measures of Association</h1>

</section>
<section id="measures-of-association-1" class="slide level2">
<h2>Measures of Association</h2>
<p>We only have information on whether the row and column variables are associated, but not by how much.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We only have the standardized statistic and the p-value (ex. t-statistic, p-value), but not the strength of association (ex. Pearson correlation)</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The strength of association depends on the scale of the measurements (Ordinal vs.&nbsp;Nominal). For ordinal variables, the appropriate score assignment should also be considered.</p>
</div>
</div>
</div>
</section>
<section id="ordinal-variables" class="slide level2">
<h2>Ordinal variables</h2>
<p>When both row and column variables are ordinal, we can use correlation coefficients.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>When scores are equally spaced, the <strong>Pearson</strong> correlation coefficient is appropriate. For data without an obvious scale, the <strong>Spearman</strong> correlation coefficient is more appropriate.</p>
<p>These are not calculable in <code>R</code> for contingency tables.</p>
</div>
</div>
</div>
</section>
<section id="ordinal-variables-1" class="slide level2">
<h2>Ordinal Variables</h2>
<ul>
<li>Association can also be measured by classifying all possible pairs of subjects as concordant or discordant pairs.
<ul>
<li>Concordant: Subject ranks higher on the row variable also ranks higher on the column variable</li>
<li>Discordant: Subject that ranks higher on the row variable also ranks lower on the column variable</li>
<li>Depends on relative ordering of the levels of variables</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Measures of association that use these pairs are Gamma <span class="math inline">\(\gamma\)</span>, Kendall’s <span class="math inline">\(\tau_B\)</span>, Stuart’s <span class="math inline">\(\tau_C\)</span>, Somers’ Delta.</p>
<ul>
<li>All measures range from -1 to 1, inclusive.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="measures-of-association-2" class="slide level2">
<h2>Measures of Association</h2>
<p>These measures differ in adjusting for ties and sample size.</p>
<ul>
<li>Somers’ D depends on the location of the explanatory variable.</li>
<li>Stuart’s <span class="math inline">\(\tau_C\)</span> includes an adjustment for table size to a correction for ties. Recommended when two ordinal variables under consideration have different numbers of values.</li>
<li>Kendall’s <span class="math inline">\(\tau_B\)</span> is preferred when the contingency table is square (<span class="math inline">\(m\times m\)</span>)</li>
<li>Gamma does not account for ties, so it is only recommended if there are no ties.</li>
</ul>
</section>
<section id="measures-of-association-3" class="slide level2">
<h2>Measures of Association</h2>
<p>When the sample size is large enough, 95% confidence intervals can be calculated for these measures using a normal approximation.</p>
<p><span class="math display">\[
measure \pm 1.96*ASE
\]</span></p>
<p>where ASE is the asymptotic standard error reported in the <code>measures</code> output from the <code>freq</code> procedure. - The confidence interval can be calculated using the <code>cl</code> option in the <code>freq</code> procedure.</p>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>Consider the water treatment example. Calculate the following measures of association with the corresponding 95% CI.</p>
<ul>
<li>Pearson correlation</li>
<li>Spearman Correlation</li>
<li>Gamma</li>
<li>Kendall’s <span class="math inline">\(\tau_b\)</span></li>
<li>Stuart’s <span class="math inline">\(\tau_c\)</span></li>
<li>Somers’ Delta</li>
</ul>

<img data-src="img/wash_C5.png" class="r-stretch"></section>
<section id="exercise-5" class="slide level2">
<h2>Exercise</h2>
<p>Consider the water treatment example. Calculate the following measures of association with the corresponding 95% CI.</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">SAS Code</a></li><li><a href="#tabset-10-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a>data wash;</span>
<span id="cb50-2"><a></a>input treatment <span class="sc">$</span> washability <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb50-3"><a></a>datalines;</span>
<span id="cb50-4"><a></a>water low <span class="dv">27</span> water medium <span class="dv">14</span> water high <span class="dv">5</span></span>
<span id="cb50-5"><a></a>standard low <span class="dv">10</span> standard medium <span class="dv">17</span> standard high <span class="dv">26</span></span>
<span id="cb50-6"><a></a>super low <span class="dv">5</span> super medium <span class="dv">12</span> super high <span class="dv">50</span></span>
<span id="cb50-7"><a></a>;</span>
<span id="cb50-8"><a></a>proc freq order<span class="ot">=</span>data data<span class="ot">=</span>wash;</span>
<span id="cb50-9"><a></a>weight count;</span>
<span id="cb50-10"><a></a>tables treatment<span class="sc">*</span>washability <span class="sc">/</span>  measures cl;</span>
<span id="cb50-11"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-10-2">
<ul>
<li>Pearson Correlation: 0.55 (0.44,0.67)</li>
<li>Spearman Correlation: 0.55 (0.43, 0.66)</li>
<li>Gamma: 0.6974 (0.57-0.82)</li>
<li><span class="math inline">\(\tau_b\)</span>: 0.50 (0.39,0.61)</li>
<li><span class="math inline">\(\tau_C\)</span>: 0.48 (0.37,0.59)</li>
<li>Somers’ D C|R: 0.49 (0.38,0.59)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-6" class="slide level2">
<h2>Exercise</h2>
<p>A random sample of 400 college students are classified according to class status and drinking habits. Calculate the following measures of association and the 95% CI.</p>
<ul>
<li>Pearson correlation</li>
<li>Spearman Correlation</li>
<li>Gamma</li>
<li>Kendall’s <span class="math inline">\(\tau_b\)</span></li>
<li>Stuart’s <span class="math inline">\(\tau_c\)</span></li>
<li>Somers’ Delta</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-4"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-4-1" class="code-annotation-target"><a href="#annotated-cell-4-1"></a>data drink;</span>
<span id="annotated-cell-4-2"><a href="#annotated-cell-4-2"></a>input habit <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-4-3"><a href="#annotated-cell-4-3"></a>datalines;</span>
<span id="annotated-cell-4-4"><a href="#annotated-cell-4-4"></a>non fres <span class="dv">55</span> non soph <span class="dv">34</span> non jun <span class="dv">27</span> non sen <span class="dv">17</span></span>
<span id="annotated-cell-4-5"><a href="#annotated-cell-4-5"></a>mod fres <span class="dv">32</span> mod soph <span class="dv">29</span> mod jun <span class="dv">36</span> mod sen <span class="dv">39</span></span>
<span id="annotated-cell-4-6"><a href="#annotated-cell-4-6"></a>hea fres <span class="dv">29</span> hea soph <span class="dv">41</span> hea jun <span class="dv">33</span> hea sen <span class="dv">28</span></span>
<span id="annotated-cell-4-7"><a href="#annotated-cell-4-7"></a>;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-4" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="1" data-code-annotation="1">non: nondrinkers; mod: moderate; hea: heavy; fres: freshman; soph: sophomore; jun: junior; sen:senior</span>
</dd>
</dl>
</section>
<section id="exercise-7" class="slide level2">
<h2>Exercise</h2>
<p>A random sample of 400 college students are classified according to class status and drinking habits. Calculate the following measures of association and the 95% CI.</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">SAS Code</a></li><li><a href="#tabset-11-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>data drink;</span>
<span id="cb51-2"><a></a>input habit <span class="sc">$</span> status <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb51-3"><a></a>datalines;</span>
<span id="cb51-4"><a></a>non f <span class="dv">55</span> non soph <span class="dv">34</span> non j <span class="dv">27</span> non sen <span class="dv">17</span></span>
<span id="cb51-5"><a></a>mod f <span class="dv">32</span> mod soph <span class="dv">29</span> mod j <span class="dv">36</span> mod sen <span class="dv">39</span></span>
<span id="cb51-6"><a></a>hea f <span class="dv">29</span> hea soph <span class="dv">41</span> hea j <span class="dv">33</span> hea sen <span class="dv">28</span></span>
<span id="cb51-7"><a></a>;</span>
<span id="cb51-8"><a></a></span>
<span id="cb51-9"><a></a>proc freq data<span class="ot">=</span>drink order<span class="ot">=</span>data;</span>
<span id="cb51-10"><a></a>weight count;</span>
<span id="cb51-11"><a></a>tables habit<span class="sc">*</span>status<span class="sc">/</span>measures cl;</span>
<span id="cb51-12"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-11-2">
<ul>
<li>Pearson Correlation: 0.15 (0.06,0.25)</li>
<li>Spearman Correlation: 0.16 (0.06, 0.25)</li>
<li>Gamma: 0.18 (0.07,0.30)</li>
<li><span class="math inline">\(\tau_b\)</span>: 0.13 (0.05,0.21)</li>
<li><span class="math inline">\(\tau_C\)</span>: 0.14 (0.05,0.22)</li>
<li>Somers’ D C|R: 0.14 (0.05,0.22)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="nominal-variables" class="slide level2">
<h2>Nominal Variables</h2>
<p>It is slightly tricky to define association between two nominal variables. There are two measures of association that could measure the strength of association between nominal variables.</p>
<ul>
<li>Lambda <span class="math inline">\(\lambda\)</span></li>
<li>Uncertainty coefficients</li>
</ul>
<p>Both of these measures are included in the <code>measures</code> output.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Note that SAS will calculate all measures despite the nature of the variables. It is your job as an analyst to only report the relevant measures.</p>
<p>Do not use ordinal measures for nominal variables. Do not use nominal measures for ordinal variables</p>
</div>
</div>
</div>
</section>
<section id="lambda-lambda" class="slide level2">
<h2>Lambda <span class="math inline">\(\lambda\)</span></h2>
<p>Lambda measures the probable improvement in predicting the column variable given knowledge of the row variable.</p>
<ul>
<li>Asymmetric: Can be C|R or R|C depending on where the explanatory variable is located</li>
<li>Symmetric: weighted average of the two asymmetric <span class="math inline">\(\lambda\)</span> values.</li>
</ul>
</section>
<section id="uncertainty-coefficient" class="slide level2">
<h2>Uncertainty coefficient</h2>
<p>The uncertainty coefficient, similar to <span class="math inline">\(R^2\)</span>, measures the proportion of uncertainty in column variable as explained by the row variable.</p>
<ul>
<li>Asymmetric: Can be C|R or R|C depending on where the explanatory variable is located</li>
<li>Symmetric: weighted average of the two asymmetric uncertainty coefficients.</li>
</ul>
</section>
<section id="exercise-8" class="slide level2">
<h2>Exercise</h2>
<div class="columns">
<div class="column" style="width:40%; font-size: 75%">
<p>The table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.</p>
<ul>
<li>What are the appropriate measures of association to report?</li>
<li>Provide the estimate and the 95% CI of these measures.</li>
</ul>
</div><div class="column" style="width:60%">
<p><img data-src="img/party_C5.png"></p>
</div></div>
</section>
<section id="exercise-9" class="slide level2">
<h2>Exercise</h2>
<p>The table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.</p>
<ul>
<li>What are the appropriate measures of association to report?</li>
<li>Provide the estimate and the 95% CI of these measures.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">SAS Code</a></li><li><a href="#tabset-12-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a>data neighbor;</span>
<span id="cb52-2"><a></a>length party <span class="sc">$</span> <span class="dv">11</span> neighborhood <span class="sc">$</span> <span class="dv">10</span>;</span>
<span id="cb52-3"><a></a>input party <span class="sc">$</span> neighborhood <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb52-4"><a></a>datalines;</span>
<span id="cb52-5"><a></a>democrat longview <span class="dv">360</span> democrat bayside <span class="dv">221</span></span>
<span id="cb52-6"><a></a>democrat sheffeld <span class="dv">140</span> democrat highland <span class="dv">160</span></span>
<span id="cb52-7"><a></a>republican longview <span class="dv">316</span> republican bayside <span class="dv">208</span></span>
<span id="cb52-8"><a></a>republican sheffeld <span class="dv">97</span> republican highland <span class="dv">106</span></span>
<span id="cb52-9"><a></a>independent longview <span class="dv">160</span> independent bayside <span class="dv">200</span></span>
<span id="cb52-10"><a></a>independent sheffeld <span class="dv">311</span> independent highland <span class="dv">291</span></span>
<span id="cb52-11"><a></a>;</span>
<span id="cb52-12"><a></a></span>
<span id="cb52-13"><a></a>proc freq data<span class="ot">=</span>neighbor;</span>
<span id="cb52-14"><a></a>weight count;</span>
<span id="cb52-15"><a></a>tables party<span class="sc">*</span>neighborhood <span class="sc">/</span></span>
<span id="cb52-16"><a></a>measures cl;</span>
<span id="cb52-17"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-12-2">
<p>You can choose to report the asymmetric <span class="math inline">\(\lambda\)</span>, symmetric <span class="math inline">\(\lambda\)</span>, asymmetric uncertainty coefficient, or the symmetric uncertainty coefficient.</p>
<p>The asymmetric uncertainty coefficient R|C is estimated to be 0.05 (95% CI: 0.04,0.06). The estimated proportion of uncertainty in party affiliation explained by the neighborhood is estimated to be 0.05.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="observer-agreement" class="title-slide slide level1 center">
<h1>Observer Agreement</h1>

</section>
<section id="observer-agreement-1" class="slide level2">
<h2>Observer Agreement</h2>
<p>Errors are inevitable in making measurements!</p>
<ul>
<li>Biggest error: Observer error</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>How do we account for observer error, especially for multiple observer measurements?</p>
</div>
</div>
</div>
</section>
<section id="observer-agreement-kappa" class="slide level2">
<h2>Observer Agreement: <span class="math inline">\(\kappa\)</span></h2>
<p>The kappa statistic <span class="math inline">\(\kappa\)</span> measures the extent of agreement between two observers.</p>
<ul>
<li><span class="math inline">\(\kappa\)</span>=0: any agreement is made by chance</li>
<li><span class="math inline">\(\kappa\)</span>=1: perfect agreement</li>
<li><span class="math inline">\(\kappa \geq\)</span> 0.8: excellent agreement</li>
<li><span class="math inline">\(\kappa \geq\)</span> 0.4: moderate agreement</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>This is similar to the intraclass correlation coefficient in ANOVA models.</p>
</div>
</div>
</div>
</section>
<section id="observer-agreement-kappa-1" class="slide level2">
<h2>Observer Agreement: <span class="math inline">\(\kappa\)</span></h2>
<p><span class="math inline">\(\kappa\)</span> is calculated from the following equation:</p>
<p><span class="math display">\[
\kappa = (\Pi_O - \Pi_E)/(1-\Pi_E)
\]</span> where <span class="math inline">\(\Pi_O\)</span> is the probability that observers agreed based on the data, <span class="math inline">\(\Pi_E\)</span> is the expected probability of agreement if the two observer ratings are assumed to be independent.</p>
</section>
<section id="observer-agreement-2" class="slide level2">
<h2>Observer Agreement</h2>
<ul>
<li>When there is order in the categories, we might need to account how different the disagreements are.</li>
<li>We can use weighted <span class="math inline">\(\kappa\)</span> measurements such as:
<ul>
<li>Cicchetti-Allison weights puts more weight on cells closest to the diagonal.</li>
<li>Fleiss-Cohen kappa weights use a squared distance between categories, which penalizes highly discordant pairs.</li>
</ul></li>
</ul>
</section>
<section id="bowkers-test" class="slide level2">
<h2>Bowker’s Test</h2>
<ul>
<li>Tests whether the contingency table is symmetric about the diagonals.
<ul>
<li>Works for square tables</li>
<li>Same as McNemar’s test when the table is <span class="math inline">\(2\times 2\)</span></li>
</ul></li>
</ul>
</section>
<section id="observer-agreement-sas" class="slide level2">
<h2>Observer Agreement: SAS</h2>
<ul>
<li>The <code>AGREE</code> option in the tables statement generates the kappa statistics and Bowker’s symmetry test.
<ul>
<li><code>AGREE (WT=FC)</code> specifies to use the <em>Fleiss-Cohen</em> criterion for the Weighted Kappa statistic.</li>
</ul></li>
<li>The agreement plot is also shown.
<ul>
<li>Comparison of shaded portions of the rectangles to the entire area of the rectangle provides information about the agreement between the two raters.</li>
</ul></li>
<li>Exact testing can also be done by specifying <code>KAPPA</code> in the <code>EXACT</code> statement.
<ul>
<li>Small cell counts with multiple 0 cell counts.</li>
</ul></li>
</ul>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<ul>
<li>The data comes from a study concerning the diagnostic classification of multiple sclerosis patients. Patients from Winnipeg and New Orleans were classified into one of four diagnostic classes by both a Winnipeg neurologist and a New Orleans neurologist.
<ul>
<li>Calculate the estimate and 95% confidence interval for the simple and weighted Kappa statistic.</li>
<li>What can you say about the agreement between the New Orleans and Winnipeg neurologists?</li>
</ul></li>
</ul>

<img data-src="img/neuro_C5.png" class="r-stretch"><h3 id="sas-code-10">SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a>data classify;</span>
<span id="cb53-2"><a></a>input no_rater w_rater count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb53-3"><a></a>datalines;</span>
<span id="cb53-4"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">38</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">5</span> <span class="dv">1</span> <span class="dv">3</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb53-5"><a></a><span class="dv">2</span> <span class="dv">1</span> <span class="dv">33</span> <span class="dv">2</span> <span class="dv">2</span> <span class="dv">11</span> <span class="dv">2</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">2</span> <span class="dv">4</span> <span class="dv">0</span></span>
<span id="cb53-6"><a></a><span class="dv">3</span> <span class="dv">1</span> <span class="dv">10</span> <span class="dv">3</span> <span class="dv">2</span> <span class="dv">14</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">5</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">6</span></span>
<span id="cb53-7"><a></a><span class="dv">4</span> <span class="dv">1</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">2</span> <span class="dv">7</span> <span class="dv">4</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">4</span> <span class="dv">10</span></span>
<span id="cb53-8"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<ul>
<li>The data comes from a study concerning the diagnostic classification of multiple sclerosis patients. Patients from Winnipeg and New Orleans were classified into one of four diagnostic classes by both a Winnipeg neurologist and a New Orleans neurologist.
<ul>
<li>Calculate the estimate and 95% confidence interval for the simple and weighted Kappa statistic.</li>
<li>What can you say about the agreement between the New Orleans and Winnipeg neurologists?</li>
</ul></li>
</ul>
<div class="panel-tabset">
<ul id="tabset-13" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-13-1">SAS Code</a></li><li><a href="#tabset-13-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a>data classify;</span>
<span id="cb54-2"><a></a>input no_rater w_rater count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb54-3"><a></a>datalines;</span>
<span id="cb54-4"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">38</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">5</span> <span class="dv">1</span> <span class="dv">3</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb54-5"><a></a><span class="dv">2</span> <span class="dv">1</span> <span class="dv">33</span> <span class="dv">2</span> <span class="dv">2</span> <span class="dv">11</span> <span class="dv">2</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">2</span> <span class="dv">4</span> <span class="dv">0</span></span>
<span id="cb54-6"><a></a><span class="dv">3</span> <span class="dv">1</span> <span class="dv">10</span> <span class="dv">3</span> <span class="dv">2</span> <span class="dv">14</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">5</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">6</span></span>
<span id="cb54-7"><a></a><span class="dv">4</span> <span class="dv">1</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">2</span> <span class="dv">7</span> <span class="dv">4</span> <span class="dv">3</span> <span class="dv">3</span> <span class="dv">4</span> <span class="dv">4</span> <span class="dv">10</span></span>
<span id="cb54-8"><a></a>;</span>
<span id="cb54-9"><a></a></span>
<span id="cb54-10"><a></a></span>
<span id="cb54-11"><a></a>proc freq;</span>
<span id="cb54-12"><a></a>weight count;</span>
<span id="cb54-13"><a></a>tables no_rater<span class="sc">*</span>w_rater <span class="sc">/</span> agree norow nocol nopct;</span>
<span id="cb54-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-13-2">
<p>Simple <span class="math inline">\(\kappa\)</span>: 0.21 (0.11,0.31) Weighted <span class="math inline">\(\kappa\)</span>: 0.38 (0.28,0.48)</p>
<p>Since the weighted <span class="math inline">\(\kappa\)</span> is higher than the simple <span class="math inline">\(\kappa\)</span>, we can infer that there were more disagreements closer to the diagonal. There is a slight to moderate agreement between the two neurologists.</p>
</div>
</div>
</div>
</section>
<section id="exercise-10" class="slide level2">
<h2>Exercise</h2>
<p>Two radiologists rated 85 patients with respect to liver lesions. The ratings were designated on an ordinal scale as:</p>
<p>0 =‘Normal’; 1 =‘Benign’ ; 2 =’Suspected’; 3 =’Cancer’</p>
<ul>
<li>Calculate the simple and weighted kappa statistics and the corresponding 95% confidence intervals.</li>
<li>Compare the asymptotic and exact p-values in testing whether there is an agreement between the two radiologists.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a></span>
<span id="cb55-2"><a></a>data radiology;</span>
<span id="cb55-3"><a></a>input rater1 rater2 count;</span>
<span id="cb55-4"><a></a>cards;</span>
<span id="cb55-5"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">21</span></span>
<span id="cb55-6"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">12</span></span>
<span id="cb55-7"><a></a><span class="dv">0</span> <span class="dv">2</span>  <span class="dv">0</span></span>
<span id="cb55-8"><a></a><span class="dv">0</span> <span class="dv">3</span>  <span class="dv">0</span></span>
<span id="cb55-9"><a></a><span class="dv">1</span> <span class="dv">0</span>  <span class="dv">4</span></span>
<span id="cb55-10"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">17</span></span>
<span id="cb55-11"><a></a><span class="dv">1</span> <span class="dv">2</span>  <span class="dv">1</span></span>
<span id="cb55-12"><a></a><span class="dv">1</span> <span class="dv">3</span>  <span class="dv">0</span></span>
<span id="cb55-13"><a></a><span class="dv">2</span> <span class="dv">0</span>  <span class="dv">3</span></span>
<span id="cb55-14"><a></a><span class="dv">2</span> <span class="dv">1</span>  <span class="dv">9</span></span>
<span id="cb55-15"><a></a><span class="dv">2</span> <span class="dv">2</span> <span class="dv">15</span></span>
<span id="cb55-16"><a></a><span class="dv">2</span> <span class="dv">3</span>  <span class="dv">2</span></span>
<span id="cb55-17"><a></a><span class="dv">3</span> <span class="dv">0</span>  <span class="dv">0</span></span>
<span id="cb55-18"><a></a><span class="dv">3</span> <span class="dv">1</span>  <span class="dv">0</span></span>
<span id="cb55-19"><a></a><span class="dv">3</span> <span class="dv">2</span>  <span class="dv">0</span></span>
<span id="cb55-20"><a></a><span class="dv">3</span> <span class="dv">3</span>  <span class="dv">1</span></span>
<span id="cb55-21"><a></a>;</span>
<span id="cb55-22"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="exercise-11" class="slide level2">
<h2>Exercise</h2>
<p>Two radiologists rated 85 patients with respect to liver lesions. The ratings were designated on an ordinal scale as:</p>
<p>0 =‘Normal’; 1 =‘Benign’ ; 2 =’Suspected’; 3 =’Cancer’</p>
<ul>
<li>Calculate the simple and weighted kappa statistics and the corresponding 95% confidence intervals.</li>
<li>Compare the asymptotic and exact p-values in testing whether there is an agreement between the two radiologists.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-14" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-14-1">SAS Code</a></li><li><a href="#tabset-14-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a></a>data radiology;</span>
<span id="cb56-2"><a></a>input rater1 rater2 count;</span>
<span id="cb56-3"><a></a>cards;</span>
<span id="cb56-4"><a></a><span class="dv">0</span> <span class="dv">0</span> <span class="dv">21</span></span>
<span id="cb56-5"><a></a><span class="dv">0</span> <span class="dv">1</span> <span class="dv">12</span></span>
<span id="cb56-6"><a></a><span class="dv">0</span> <span class="dv">2</span>  <span class="dv">0</span></span>
<span id="cb56-7"><a></a><span class="dv">0</span> <span class="dv">3</span>  <span class="dv">0</span></span>
<span id="cb56-8"><a></a><span class="dv">1</span> <span class="dv">0</span>  <span class="dv">4</span></span>
<span id="cb56-9"><a></a><span class="dv">1</span> <span class="dv">1</span> <span class="dv">17</span></span>
<span id="cb56-10"><a></a><span class="dv">1</span> <span class="dv">2</span>  <span class="dv">1</span></span>
<span id="cb56-11"><a></a><span class="dv">1</span> <span class="dv">3</span>  <span class="dv">0</span></span>
<span id="cb56-12"><a></a><span class="dv">2</span> <span class="dv">0</span>  <span class="dv">3</span></span>
<span id="cb56-13"><a></a><span class="dv">2</span> <span class="dv">1</span>  <span class="dv">9</span></span>
<span id="cb56-14"><a></a><span class="dv">2</span> <span class="dv">2</span> <span class="dv">15</span></span>
<span id="cb56-15"><a></a><span class="dv">2</span> <span class="dv">3</span>  <span class="dv">2</span></span>
<span id="cb56-16"><a></a><span class="dv">3</span> <span class="dv">0</span>  <span class="dv">0</span></span>
<span id="cb56-17"><a></a><span class="dv">3</span> <span class="dv">1</span>  <span class="dv">0</span></span>
<span id="cb56-18"><a></a><span class="dv">3</span> <span class="dv">2</span>  <span class="dv">0</span></span>
<span id="cb56-19"><a></a><span class="dv">3</span> <span class="dv">3</span>  <span class="dv">1</span></span>
<span id="cb56-20"><a></a>;</span>
<span id="cb56-21"><a></a>run;</span>
<span id="cb56-22"><a></a></span>
<span id="cb56-23"><a></a>proc freq data<span class="ot">=</span>radiology;</span>
<span id="cb56-24"><a></a>tables rater1<span class="sc">*</span>rater2<span class="sc">/</span>norow nocol nopct agree;</span>
<span id="cb56-25"><a></a>weight count;</span>
<span id="cb56-26"><a></a>test kappa;</span>
<span id="cb56-27"><a></a>exact kappa;</span>
<span id="cb56-28"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-14-2">
<p>Simple <span class="math inline">\(\kappa\)</span>: 0.47 (0.33,0.62) Weighted <span class="math inline">\(\kappa\)</span>: 0.57 (0.44,0.70)</p>
<p>The exact p-value is p&lt;0.001, which shows there is sufficient evidence of an agreement between the radiologists. Based on the simple and weighted kappa values, there is moderate agreement between the two radiologists.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="ordered-differences" class="title-slide slide level1 center">
<h1>Ordered Differences</h1>

</section>
<section id="test-for-ordered-differences" class="slide level2">
<h2>Test for Ordered Differences</h2>
<ul>
<li>What if the columns are ordinal but the rows are nominal?
<ul>
<li>Recall: rows could pertain to different groups.</li>
<li>Recall: Mean score tests account for location shifts in the mean response</li>
</ul></li>
<li>What if we want to know if the mean scores are monotonously increasing or decreasing across levels of the row variable?
<ul>
<li>Example: Showing increasing prevalence of disease in specific environments.</li>
</ul></li>
</ul>
</section>
<section id="test-for-ordered-differences-1" class="slide level2">
<h2>Test for Ordered Differences</h2>
<p>The Jonckheere-Terpstra test is a nonparametric test that is based on sums of Mann-Whitney test statistics</p>
<ul>
<li>Rank-based test</li>
</ul>
<p>This test detects whether there are differences in the trend of group effects.</p>
<ul>
<li>Are the scores strictly increasing or decreasing?</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The null hypothesis <span class="math inline">\(H_0\)</span> assumes that the distribution of ordered responses is the same for all groups. For one-sided tests, this tests detect whether <span class="math inline">\(d_1 \leq d_2 \leq... d_s\)</span> where <span class="math inline">\(d_i\)</span> corresponds to the <span class="math inline">\(i^{th}\)</span> group effect.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The Jonckheere-Terpstra test can be performed by adding the <code>JT</code> option to the <code>tables</code> statement. An exact implementation of the Jonckheere-Terpstra test can also be performed by adding the <code>JT</code> option to the <code>exact</code> statement.</p>
</div>
</div>
</div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>Investigators conducted a randomized clinical trial in four hospitals, where patients were assigned to one of four surgical procedures for the treatment of severe duodenal ulcers. The treatments include:</p>
<ul>
<li>v + d: vagotomy and drainage</li>
<li>v + a: vagotomy and antrectomy (removal of 25% of gastric tissue)</li>
<li>v + h: vagatomy and hemigastrectomy (removal of 50% of gastric tissue)</li>
<li>gre: gastric resection (removal of 75% of gastric tissue)</li>
</ul>
<p>The response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is increasing as the amount of gastric tissue removed increased. Ignore hospital effects.</p>
<h3 id="sas-code-13">SAS Code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>data operate;</span>
<span id="cb57-2"><a></a>input hospital trt <span class="sc">$</span> severity <span class="sc">$</span> wt <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb57-3"><a></a>datalines;</span>
<span id="cb57-4"><a></a><span class="dv">1</span> v<span class="sc">+</span>d none <span class="dv">23</span> <span class="dv">1</span> v<span class="sc">+</span>d slight <span class="dv">7</span> <span class="dv">1</span> v<span class="sc">+</span>d moderate <span class="dv">2</span></span>
<span id="cb57-5"><a></a><span class="dv">1</span> v<span class="sc">+</span>a none <span class="dv">23</span> <span class="dv">1</span> v<span class="sc">+</span>a slight <span class="dv">10</span> <span class="dv">1</span> v<span class="sc">+</span>a moderate <span class="dv">5</span></span>
<span id="cb57-6"><a></a><span class="dv">1</span> v<span class="sc">+</span>h none <span class="dv">20</span> <span class="dv">1</span> v<span class="sc">+</span>h slight <span class="dv">13</span> <span class="dv">1</span> v<span class="sc">+</span>h moderate <span class="dv">5</span></span>
<span id="cb57-7"><a></a><span class="dv">1</span> gre none <span class="dv">24</span> <span class="dv">1</span> gre slight <span class="dv">10</span> <span class="dv">1</span> gre moderate <span class="dv">6</span></span>
<span id="cb57-8"><a></a><span class="dv">2</span> v<span class="sc">+</span>d none <span class="dv">18</span> <span class="dv">2</span> v<span class="sc">+</span>d slight <span class="dv">6</span> <span class="dv">2</span> v<span class="sc">+</span>d moderate <span class="dv">1</span></span>
<span id="cb57-9"><a></a><span class="dv">2</span> v<span class="sc">+</span>a none <span class="dv">18</span> <span class="dv">2</span> v<span class="sc">+</span>a slight <span class="dv">6</span> <span class="dv">2</span> v<span class="sc">+</span>a moderate <span class="dv">2</span></span>
<span id="cb57-10"><a></a><span class="dv">2</span> v<span class="sc">+</span>h none <span class="dv">13</span> <span class="dv">2</span> v<span class="sc">+</span>h slight <span class="dv">13</span> <span class="dv">2</span> v<span class="sc">+</span>h moderate <span class="dv">2</span></span>
<span id="cb57-11"><a></a><span class="dv">2</span> gre none <span class="dv">9</span> <span class="dv">2</span> gre slight <span class="dv">15</span> <span class="dv">2</span> gre moderate <span class="dv">2</span></span>
<span id="cb57-12"><a></a><span class="dv">3</span> v<span class="sc">+</span>d none <span class="dv">8</span> <span class="dv">3</span> v<span class="sc">+</span>d slight <span class="dv">6</span> <span class="dv">3</span> v<span class="sc">+</span>d moderate <span class="dv">3</span></span>
<span id="cb57-13"><a></a><span class="dv">3</span> v<span class="sc">+</span>a none <span class="dv">12</span> <span class="dv">3</span> v<span class="sc">+</span>a slight <span class="dv">4</span> <span class="dv">3</span> v<span class="sc">+</span>a moderate <span class="dv">4</span></span>
<span id="cb57-14"><a></a><span class="dv">3</span> v<span class="sc">+</span>h none <span class="dv">11</span> <span class="dv">3</span> v<span class="sc">+</span>h slight <span class="dv">6</span> <span class="dv">3</span> v<span class="sc">+</span>h moderate <span class="dv">2</span></span>
<span id="cb57-15"><a></a><span class="dv">3</span> gre none <span class="dv">7</span> <span class="dv">3</span> gre slight <span class="dv">7</span> <span class="dv">3</span> gre moderate <span class="dv">4</span></span>
<span id="cb57-16"><a></a><span class="dv">4</span> v<span class="sc">+</span>d none <span class="dv">12</span> <span class="dv">4</span> v<span class="sc">+</span>d slight <span class="dv">9</span> <span class="dv">4</span> v<span class="sc">+</span>d moderate <span class="dv">1</span></span>
<span id="cb57-17"><a></a><span class="dv">4</span> v<span class="sc">+</span>a none <span class="dv">15</span> <span class="dv">4</span> v<span class="sc">+</span>a slight <span class="dv">3</span> <span class="dv">4</span> v<span class="sc">+</span>a moderate <span class="dv">2</span></span>
<span id="cb57-18"><a></a><span class="dv">4</span> v<span class="sc">+</span>h none <span class="dv">14</span> <span class="dv">4</span> v<span class="sc">+</span>h slight <span class="dv">8</span> <span class="dv">4</span> v<span class="sc">+</span>h moderate <span class="dv">3</span></span>
<span id="cb57-19"><a></a><span class="dv">4</span> gre none <span class="dv">13</span> <span class="dv">4</span> gre slight <span class="dv">6</span> <span class="dv">4</span> gre moderate <span class="dv">4</span></span>
<span id="cb57-20"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>Investigators conducted a randomized clinical trial in four hospitals, where patients were assigned to one of four surgical procedures for the treatment of severe duodenal ulcers. The treatments include:</p>
<ul>
<li>v + d: vagotomy and drainage</li>
<li>v + a: vagotomy and antrectomy (removal of 25% of gastric tissue)</li>
<li>v + h: vagatomy and hemigastrectomy (removal of 50% of gastric tissue)</li>
<li>gre: gastric resection (removal of 75% of gastric tissue)</li>
</ul>
<p>The response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is different across all treatments, ignoring the hospital effects.</p>
<div class="panel-tabset">
<ul id="tabset-15" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-15-1">SAS Code</a></li><li><a href="#tabset-15-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a></a>data operate;</span>
<span id="cb58-2"><a></a>input hospital trt <span class="sc">$</span> severity <span class="sc">$</span> wt <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb58-3"><a></a>datalines;</span>
<span id="cb58-4"><a></a><span class="dv">1</span> v<span class="sc">+</span>d none <span class="dv">23</span> <span class="dv">1</span> v<span class="sc">+</span>d slight <span class="dv">7</span> <span class="dv">1</span> v<span class="sc">+</span>d moderate <span class="dv">2</span></span>
<span id="cb58-5"><a></a><span class="dv">1</span> v<span class="sc">+</span>a none <span class="dv">23</span> <span class="dv">1</span> v<span class="sc">+</span>a slight <span class="dv">10</span> <span class="dv">1</span> v<span class="sc">+</span>a moderate <span class="dv">5</span></span>
<span id="cb58-6"><a></a><span class="dv">1</span> v<span class="sc">+</span>h none <span class="dv">20</span> <span class="dv">1</span> v<span class="sc">+</span>h slight <span class="dv">13</span> <span class="dv">1</span> v<span class="sc">+</span>h moderate <span class="dv">5</span></span>
<span id="cb58-7"><a></a><span class="dv">1</span> gre none <span class="dv">24</span> <span class="dv">1</span> gre slight <span class="dv">10</span> <span class="dv">1</span> gre moderate <span class="dv">6</span></span>
<span id="cb58-8"><a></a><span class="dv">2</span> v<span class="sc">+</span>d none <span class="dv">18</span> <span class="dv">2</span> v<span class="sc">+</span>d slight <span class="dv">6</span> <span class="dv">2</span> v<span class="sc">+</span>d moderate <span class="dv">1</span></span>
<span id="cb58-9"><a></a><span class="dv">2</span> v<span class="sc">+</span>a none <span class="dv">18</span> <span class="dv">2</span> v<span class="sc">+</span>a slight <span class="dv">6</span> <span class="dv">2</span> v<span class="sc">+</span>a moderate <span class="dv">2</span></span>
<span id="cb58-10"><a></a><span class="dv">2</span> v<span class="sc">+</span>h none <span class="dv">13</span> <span class="dv">2</span> v<span class="sc">+</span>h slight <span class="dv">13</span> <span class="dv">2</span> v<span class="sc">+</span>h moderate <span class="dv">2</span></span>
<span id="cb58-11"><a></a><span class="dv">2</span> gre none <span class="dv">9</span> <span class="dv">2</span> gre slight <span class="dv">15</span> <span class="dv">2</span> gre moderate <span class="dv">2</span></span>
<span id="cb58-12"><a></a><span class="dv">3</span> v<span class="sc">+</span>d none <span class="dv">8</span> <span class="dv">3</span> v<span class="sc">+</span>d slight <span class="dv">6</span> <span class="dv">3</span> v<span class="sc">+</span>d moderate <span class="dv">3</span></span>
<span id="cb58-13"><a></a><span class="dv">3</span> v<span class="sc">+</span>a none <span class="dv">12</span> <span class="dv">3</span> v<span class="sc">+</span>a slight <span class="dv">4</span> <span class="dv">3</span> v<span class="sc">+</span>a moderate <span class="dv">4</span></span>
<span id="cb58-14"><a></a><span class="dv">3</span> v<span class="sc">+</span>h none <span class="dv">11</span> <span class="dv">3</span> v<span class="sc">+</span>h slight <span class="dv">6</span> <span class="dv">3</span> v<span class="sc">+</span>h moderate <span class="dv">2</span></span>
<span id="cb58-15"><a></a><span class="dv">3</span> gre none <span class="dv">7</span> <span class="dv">3</span> gre slight <span class="dv">7</span> <span class="dv">3</span> gre moderate <span class="dv">4</span></span>
<span id="cb58-16"><a></a><span class="dv">4</span> v<span class="sc">+</span>d none <span class="dv">12</span> <span class="dv">4</span> v<span class="sc">+</span>d slight <span class="dv">9</span> <span class="dv">4</span> v<span class="sc">+</span>d moderate <span class="dv">1</span></span>
<span id="cb58-17"><a></a><span class="dv">4</span> v<span class="sc">+</span>a none <span class="dv">15</span> <span class="dv">4</span> v<span class="sc">+</span>a slight <span class="dv">3</span> <span class="dv">4</span> v<span class="sc">+</span>a moderate <span class="dv">2</span></span>
<span id="cb58-18"><a></a><span class="dv">4</span> v<span class="sc">+</span>h none <span class="dv">14</span> <span class="dv">4</span> v<span class="sc">+</span>h slight <span class="dv">8</span> <span class="dv">4</span> v<span class="sc">+</span>h moderate <span class="dv">3</span></span>
<span id="cb58-19"><a></a><span class="dv">4</span> gre none <span class="dv">13</span> <span class="dv">4</span> gre slight <span class="dv">6</span> <span class="dv">4</span> gre moderate <span class="dv">4</span></span>
<span id="cb58-20"><a></a>;</span>
<span id="cb58-21"><a></a></span>
<span id="cb58-22"><a></a>proc freq data<span class="ot">=</span>operate order<span class="ot">=</span>data;</span>
<span id="cb58-23"><a></a>weight wt;</span>
<span id="cb58-24"><a></a>tables trt<span class="sc">*</span>severity <span class="sc">/</span>  jt;</span>
<span id="cb58-25"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-15-2">
<p>The JT statistic was estimated to be 35,697, corresponding to a one-sided p-value <span class="math inline">\(p=0.005\)</span>, which is sufficient evidence to claim that the severity of the duodenal ulcer increases with the amount of gastric tissue removed.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Chapter 5- <a href="https://miguelfudolig.github.io/EAB770-Slides-Website/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            // Attach click handler to the DT
            const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
            for (const annoteDlNode of annoteDls) {
              annoteDlNode.addEventListener('click', (event) => {
                const clickedEl = event.target;
                if (clickedEl !== selectedAnnoteEl) {
                  unselectCodeLines();
                  const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                  if (activeEl) {
                    activeEl.classList.remove('code-annotation-active');
                  }
                  selectCodeLines(clickedEl);
                  clickedEl.classList.add('code-annotation-active');
                } else {
                  // Unselect the line
                  unselectCodeLines();
                  clickedEl.classList.remove('code-annotation-active');
                }
              });
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>