<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Miguel Fudolig">
  <title>EAB770: Applied Statistical Methods for Categorical Data – EAB 770 - Chapter 4</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-d58ca6e55452da357bd4996cb6e3aa10.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">EAB 770 - Chapter 4</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Miguel Fudolig 
</div>
</div>
</div>

</section>
<section>
<section id="r-and-s-times-2-tables" class="title-slide slide level1 center">
<h1>$ 2 r$ and <span class="math inline">\(s \times 2\)</span> tables</h1>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<ul>
<li><span class="math inline">\(2 \times r\)</span> table</li>
<li>Sets of <span class="math inline">\(2 \times r\)</span> tables</li>
<li><span class="math inline">\(s \times 2\)</span> table</li>
<li>Sets of <span class="math inline">\(s \times 2\)</span> tables
<ul>
<li>Relationships between Sets of Tables</li>
<li>Exact Analysis of Association (<span class="math inline">\(s \times 2\)</span>) tables)</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="what-if-there-are-more-than-two-outcomes" class="title-slide slide level1 center">
<h1>what if there are more than two outcomes?</h1>

</section>
<section id="multiple-categorical-outcomes" class="slide level2">
<h2>Multiple Categorical Outcomes</h2>
<ul>
<li>Likert Scale (Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree)</li>
<li>Part of a whole (None, Some, All)</li>
<li>We would need more than two columns in our contingency table to account for these other outcomes.
<ul>
<li>Variables can be forced to be “binary”, but some important information can be lost.</li>
</ul></li>
<li>If there are <span class="math inline">\(r\)</span> outcome levels and <span class="math inline">\(2\)</span> levels of the exploratory variable, we use a <span class="math inline">\(2 \times r\)</span> contingency table.
<ul>
<li>Focus on outcomes being ordinally scaled.</li>
</ul></li>
</ul>
</section>
<section id="times-r-table" class="slide level2">
<h2><span class="math inline">\(2\times r\)</span> table</h2>
<div class="columns">
<div class="column" style="width:40%; font-size: 75%">
<p>Let <span class="math inline">\(A_j\)</span> be the <span class="math inline">\(j^{th}\)</span> outcome level.</p>
<ul>
<li>Since <span class="math inline">\(A_J\)</span> is ordinal, then <span class="math inline">\(A_1 &lt; A_2 &lt; A_3 &lt;... A_r\)</span>.
<ul>
<li>The <span class="math inline">\(\leq\)</span> can replace <span class="math inline">\(&lt;\)</span> as long as at least one is a strict inequality</li>
</ul></li>
</ul>
<p>To account for ordinality, we assign a set of scores <span class="math inline">\(\mathbf{a}\)</span> reflecting the relationship between response levels.</p>
<p><span class="math display">\[
\mathbf{a} = \{a_1, a_2, a_3,... a_r\} : a_1 &lt; a_2 &lt; ...&lt; a_r
\]</span></p>
</div><div class="column" style="width:60%">
<p><img data-src="img/2xr_C4.png"></p>
</div></div>
</section>
<section id="row-mean-scores" class="slide level2">
<h2>Row Mean Scores</h2>
<p>We can define a group mean for <span class="math inline">\(X_1\)</span>, denoted by <span class="math inline">\(\bar{f}_1\)</span>.</p>
<p><span class="math display">\[
\bar{f}_1 = \sum_{j=1}^r \frac{a_j n_{1j}}{n_{1+}}
\]</span></p>
<p>The random variable <span class="math inline">\(\bar{f}_1\)</span> approximately has a normal distribution when the central limit theorem is imposed.</p>
<ul>
<li>High row sum</li>
</ul>
<p>We refer to these scores as <strong>Row Mean Scores</strong></p>
</section>
<section id="r-table-null-hypothesis" class="slide level2">
<h2>2 r table: Null hypothesis</h2>
<p>Null hypothesis <span class="math inline">\(H_0\)</span>: There is no association between the row (X) and column (A) variables.</p>
<p>Under the null hypothesis:</p>
<ul>
<li>The expected value of the mean can be calculated as:</li>
</ul>
<p><span class="math display">\[
\mu_a =  \sum_{j=1}^r \frac{a_j n_{+j}}{n}
\]</span></p>
</section>
<section id="mean-score-statistic" class="slide level2">
<h2>Mean Score Statistic</h2>
<p>We can define a mean score statistic, <span class="math inline">\(Q_S\)</span>, given by</p>
<p><span class="math display">\[
Q_S = \frac{(\bar{f}_1 - \mu_1)^2}{V}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(V\)</span> is the variance of <span class="math inline">\(\bar{f}_1\)</span> under the null hypothesis.</li>
<li><span class="math inline">\(Q_S\)</span> follows a chi-square distribution with one degree of freedom.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="mean-score-statistic-1" class="slide level2">
<h2>Mean Score Statistic</h2>
<ul>
<li>Targets alternative hypothesis of mean shifts to the hypothesis of no association
<ul>
<li>Uses fewer degrees of freedom compared to Pearson chi-square</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Pearson chi-square requires <span class="math inline">\((r-1)\)</span> degrees of freedom compared to 1 degree of freedom for <span class="math inline">\(Q_S\)</span></p>
</div>
</div>
</div>
<ul>
<li>The mean score statistic can also be used to determine the tendency of one group having better scores compared to the other.</li>
<li>The <span class="math inline">\(Q_S\)</span> sample size condition is less stringent:</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Choose one or more cutpoints $ j = (2,3,…(r-1))$, add the first through <span class="math inline">\(j^{th}\)</span> columns together and add the <span class="math inline">\((j-1)^{th}\)</span> through <span class="math inline">\(r^{th}\)</span> columns together. If both of these sums are 5 or greater for at least one cutpoint in each row, then the sample size is adequate.</p>
</div>
</div>
</div>
</section>
<section id="times-r-analysis-sas" class="slide level2 smaller">
<h2><span class="math inline">\(2 \times r\)</span> analysis: SAS</h2>
<ul>
<li>Data should be encoded in increasing order of the outcome variable.</li>
<li>The <code>FREQ</code> procedure will give us the mean score statistic:
<ul>
<li><strong>ORDER=DATA should be included in the code with the <code>PROC FREQ</code> statement. (See sample code)</strong></li>
</ul></li>
<li>Can be obtained using the <code>cmh</code> option or <code>chisq</code> option in the <code>tables</code> statement
<ul>
<li><span class="math inline">\(Q_S\)</span>: Mantel-Haesnzel Chi-square statistic in the SAS output</li>
<li><code>CMH</code>: “<em>Row Mean Scores Differ</em>” statistic.</li>
<li>The CMH values would now display different values unlike the <span class="math inline">\(2 \times 2\)</span> tables.</li>
</ul></li>
</ul>
</section>
<section id="example" class="slide level2 smaller">
<h2>Example</h2>
<p>The data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.</p>
<ul>
<li>Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group?</li>
</ul>

<img data-src="img/arthritis_C4.png" class="r-stretch"></section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>The data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.</p>
<ul>
<li>Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group?</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">SAS Code</a></li><li><a href="#tabset-1-2">R Code</a></li><li><a href="#tabset-1-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>data arth;</span>
<span id="cb1-2"><a></a>input treat <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb1-3"><a></a>datalines;</span>
<span id="cb1-4"><a></a>active none <span class="dv">13</span> active some <span class="dv">7</span> active marked <span class="dv">21</span></span>
<span id="cb1-5"><a></a>placebo none <span class="dv">29</span> placebo some <span class="dv">7</span> placebo marked <span class="dv">7</span></span>
<span id="cb1-6"><a></a>;</span>
<span id="cb1-7"><a></a>proc freq data<span class="ot">=</span>arth order<span class="ot">=</span>data;</span>
<span id="cb1-8"><a></a>weight count;</span>
<span id="cb1-9"><a></a>tables treat<span class="sc">*</span>response <span class="sc">/</span> cmh chisq nocol nopct;</span>
<span id="cb1-10"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Response
Treat     None Some Marked
  Active    13    7     21
  Placebo   29    7      7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Treat by Response 

                 AltHypothesis  Chisq Df       Prob
general    General association 12.900  2 0.00158084
rmeans  Row mean scores differ 12.859  1 0.00033586
cmeans  Col mean scores differ 12.900  2 0.00158084
cor        Nonzero correlation 12.859  1 0.00033586</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3">
<p><span class="math inline">\(Q_S\)</span> = 12.86, p=0.0003. We have strong evidence to conclude that the active treatment displayed higher improvement compared to the placebo group.</p>
<ul>
<li>The active group has a higher proportion of marked + some improvement, which enables us to formulate the following conclusion.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>A survey was administered to students at a US-based university who are habitual smokers to determine the likelihood of using a mobile app to help them quit smoking. Is there sufficient evidence to conclude that heavy smokers are less likely to use a mobile app compared to light smokers?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Response
Smokers Very Unlikely Unlikely Likely Very Likely
  Heavy            36       75     56          17
  Light            38       59     64          23</code></pre>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>A survey was administered to students at a US-based university who are habitual smokers to determine the likelihood of using a mobile app to help them quit smoking. Is there sufficient evidence to conclude that heavy smokers are less likely to use a mobile app compared to light smokers?</p>

<img data-src="Chapter4_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"><div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">SAS Code</a></li><li><a href="#tabset-2-2">R Code</a></li><li><a href="#tabset-2-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>data smoke;</span>
<span id="cb5-2"><a></a>input treat <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb5-3"><a></a>datalines;</span>
<span id="cb5-4"><a></a>heavy vu <span class="dv">36</span> heavy u <span class="dv">75</span> heavy l <span class="dv">56</span> heavy vl <span class="dv">17</span></span>
<span id="cb5-5"><a></a>light vu <span class="dv">38</span> light u <span class="dv">59</span> light l <span class="dv">64</span> light vl <span class="dv">23</span></span>
<span id="cb5-6"><a></a>;</span>
<span id="cb5-7"><a></a></span>
<span id="cb5-8"><a></a>proc freq data<span class="ot">=</span>smoke order<span class="ot">=</span>data;</span>
<span id="cb5-9"><a></a>weight count;</span>
<span id="cb5-10"><a></a>tables treat<span class="sc">*</span>response <span class="sc">/</span> cmh chisq nocol nopct;</span>
<span id="cb5-11"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-2-2">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Cochran-Mantel-Haenszel Statistics for Smokers by Response 

                AltHypothesis  Chisq Df    Prob
rmeans Row mean scores differ 1.0394  1 0.30795</code></pre>
</div>
</div>
</div>
<div id="tabset-2-3">
<p><span class="math inline">\(Q_S\)</span> = 1.04, p=0.31. There is insufficient evidence that heavy smokers are less likely to use a mobile app compared to light smokers.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="sets-of-2times-r-tables" class="title-slide slide level1 center">
<h1>Sets of <span class="math inline">\(2\times r\)</span> tables</h1>

</section>
<section id="sets-of-2times-r-tables-1" class="slide level2">
<h2>Sets of <span class="math inline">\(2\times r\)</span> tables</h2>
<ul>
<li>We extend the Mantel-Haenszel strategy to <span class="math inline">\(2\times r\)</span> tables for ordinal responses</li>
<li>Compute mean scores for the responses
<ul>
<li>Calculate mean score differences across tables</li>
<li>Similar approach to the difference in proportions (<span class="math inline">\(Q_S\)</span>)</li>
</ul></li>
<li>Assume hypergeometric distributions for the contingency tables in the different strata.
<ul>
<li>Also assume that the across-strata sample sizes are sufficiently large for each group (row sums)</li>
</ul></li>
</ul>
</section>
<section id="extended-mean-score-statistic" class="slide level2">
<h2>Extended Mean Score Statistic</h2>
<ul>
<li><span class="math inline">\(Q_{SMH}\)</span> is the extended Mantel-Haenszel mean score statistic.
<ul>
<li>Also known as the ANOVA statistic</li>
<li>Function of the weighted average of the differences in mean scores of the two treatments for all strata.</li>
</ul></li>
<li><span class="math inline">\(Q_{SMH}\)</span> is good for detecting consistent patterns of differences across strata.</li>
<li>Sample size requirements involve collapsing each stratum table into a 2x2 table by choosing cutpoints (Just like that in <span class="math inline">\(Q_S\)</span>), then apply the Mantel-Fleiss criterion.</li>
</ul>
</section>
<section id="different-types-of-scores" class="slide level2">
<h2>Different Types of Scores</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Integer Scores</a></li><li><a href="#tabset-3-2">Rank</a></li><li><a href="#tabset-3-3">Standardized Midranks</a></li><li><a href="#tabset-3-4">Logrank Scores</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ul>
<li>(0,1,2,…)</li>
<li>Response levels are ordered categories that correspond to discrete counts.</li>
<li>Produce same results regardless of starting number.</li>
<li>Default in SAS.</li>
</ul>
</div>
<div id="tabset-3-2">
<ul>
<li>Rank scores based on the row totals.</li>
<li>In stratified analysis, rank scores are not robust when there are large strata.</li>
</ul>
<p><span class="math display">\[
R_i^1 = \sum_{k&lt;i} n_{k+} + \frac{n_{i+}+1}{2}
\]</span> ### Ridit - Ridit scores are standardized rank scores based on the sample size</p>
<p><span class="math display">\[
R_i^3 = 1/(n+1) \left[\sum_{k&lt;i} n_{k+} + \frac{n_{i+}+1}{2}\right]
\]</span></p>
</div>
<div id="tabset-3-3">
<ul>
<li>Also known as modified ridit scores.</li>
<li>Constrained to lie between 0 and 1.</li>
<li>Requires no scaling of response levels.</li>
<li>Used when there is no argument for equal spaces between ordinal levels</li>
</ul>
<p><span class="math display">\[
R_i^3 = 1/(n+1) \left[\sum_{k&lt;i} n_{k+} + \frac{n_{i+}+1}{2}\right]
\]</span></p>
</div>
<div id="tabset-3-4">
<ul>
<li>Useful when the distribution is L-shaped.</li>
<li>Need to apply the logarithmic transformation of the rank scores before applying to the <code>tables</code> statement.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="different-types-of-scores-1" class="slide level2">
<h2>Different Types of Scores</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>When there is no strata, the rank, ridit, and modridit scores correspond to the Wilcoxon rank-sum test.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In stratified analyses, the <em>modridit scores</em> are preferred out of these rank-based scores because it produces an extension of the Wilcoxon rank-sum test.</p>
</div>
</div>
</div>
</section>
<section id="measures-of-association-in-sets-of-2-r-tables" class="slide level2">
<h2>Measures of Association in Sets of $ 2 r$ tables</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Somers’ D</a></li><li><a href="#tabset-4-2">Mann-Whitney rank measure of association</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<ul>
<li>Measure of association for ordinally scaled data.</li>
<li>For ordinal scores with two groups, let <span class="math inline">\(G1\)</span> be the score of group 1 and <span class="math inline">\(G2\)</span> be the score of group 2</li>
</ul>
<p><span class="math display">\[
D = \frac{P(G1 &gt; G2) - P(G1 &lt; G2)}{P(G1&gt;G2)+P(G1&lt;G2) + P(G1=G2)}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>SAS will provide two values of the Somers’D: <span class="math inline">\(D(R|C)\)</span> and <span class="math inline">\(D(C|R)\)</span></p>
<ul>
<li><span class="math inline">\(D(R|C)\)</span> treats the <em>column</em> as the independent variable.</li>
<li><span class="math inline">\(D(C|R)\)</span> treats the <em>row</em> as the independent variable</li>
</ul>
</div>
</div>
</div>
</div>
<div id="tabset-4-2">
<ul>
<li>Assesses association between a dichotomous predictor variable and an ordinal outcome.</li>
<li>Can be calculated from Somers’D</li>
</ul>
<p><span class="math display">\[
g_h = (D+1)/2
\]</span> where the standard error of <span class="math inline">\(g_h\)</span> is <span class="math inline">\(v_h = v_D/2\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="extension-of-the-mann-whitney-rank-measure" class="slide level2">
<h2>Extension of the Mann-Whitney Rank Measure</h2>
<ul>
<li>When there are <span class="math inline">\(q\)</span> strata, we can calculate a test statistic <span class="math inline">\(Q_H\)</span> such that</li>
</ul>
<p><span class="math display">\[
Q_H = \sum_{h=1}^q (g_h-\tilde{g})^2/v_h  
\]</span> <span class="math display">\[
\tilde{g} = \frac{\sum_{h=1}^q g_h\left(n_{h1}n_{h2}/(n_{h1}+n_{h2})\right)}{\sum_{h=1}^q \left(n_{h1}n_{h2}/(n_{h1}+n_{h2})\right)}
\]</span></p>
<ul>
<li>This is an extension of the van Elteren’s rank sum test.</li>
</ul>
</section>
<section id="scores-sas" class="slide level2">
<h2>Scores: SAS</h2>
<ul>
<li>The default score used in SAS are integer/table scores</li>
<li>Scoring method can be specified using the SCORES option in SAS
<ul>
<li>TABLE: integer</li>
<li>RIDIT: midranks</li>
<li>MODRIDIT: standardized midranks</li>
<li>RANK: rank scores.</li>
</ul></li>
<li>Use the Cochran-Mantel-Haenszel table (CMH) in testing the hypothesis
<ul>
<li>Difference in mean scores: “Row means differ”</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>proc freq;</span>
<span id="cb7-2"><a></a>tables A<span class="sc">*</span>B<span class="sc">/</span>scores<span class="ot">=</span>MODRIDIT;</span>
<span id="cb7-3"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="somers-d-sas" class="slide level2">
<h2>Somers’ D: SAS</h2>
<ul>
<li><code>measures</code> includes the Somers’ D estimate with the standard errors (<code>ASE</code> column).</li>
<li>The Mann-Whitney rank-sum statistic can be calculated using PROC IML.</li>
<li>The <code>cl</code> option calculates confidence intervals for Somers’ D</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>proc freq;</span>
<span id="cb8-2"><a></a>tables A<span class="sc">*</span>B<span class="sc">/</span>scores<span class="ot">=</span>MODRIDIT measures cl;</span>
<span id="cb8-3"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="mann-whitney-sas-optional" class="slide level2">
<h2>Mann-Whitney: SAS (optional)</h2>
<div class="sourceCode" id="annotated-cell-3"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-3-1"><a href="#annotated-cell-3-1"></a>proc freq ;</span>
<span id="annotated-cell-3-2"><a href="#annotated-cell-3-2"></a>weight count;</span>
<span id="annotated-cell-3-3"><a href="#annotated-cell-3-3"></a>tables S<span class="sc">*</span>A<span class="sc">*</span>B<span class="sc">/</span> measures scores<span class="ot">=</span>modridit;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-3-4" class="code-annotation-target"><a href="#annotated-cell-3-4"></a>output out<span class="ot">=</span>somerout smdcr;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-3-5" class="code-annotation-target"><a href="#annotated-cell-3-5"></a>ods output CrosstabFreqs<span class="ot">=</span>myFreqs;</span>
<span id="annotated-cell-3-6"><a href="#annotated-cell-3-6"></a>run;</span>
<span id="annotated-cell-3-7"><a href="#annotated-cell-3-7"></a>data ns;</span>
<span id="annotated-cell-3-8"><a href="#annotated-cell-3-8"></a>set myFreqs; where _type_<span class="ot">=</span><span class="st">"110"</span>;</span>
<span id="annotated-cell-3-9"><a href="#annotated-cell-3-9"></a>run;</span>
<span id="annotated-cell-3-10"><a href="#annotated-cell-3-10"></a></span>
<span id="annotated-cell-3-11"><a href="#annotated-cell-3-11"></a>proc iml;</span>
<span id="annotated-cell-3-12"><a href="#annotated-cell-3-12"></a>use somerout var{_SMDCR_ E_SMDCR};</span>
<span id="annotated-cell-3-13"><a href="#annotated-cell-3-13"></a>read all into combined;</span>
<span id="annotated-cell-3-14"><a href="#annotated-cell-3-14"></a>use ns var{Frequency};</span>
<span id="annotated-cell-3-15"><a href="#annotated-cell-3-15"></a>read all into total;</span>
<span id="annotated-cell-3-16"><a href="#annotated-cell-3-16"></a>print total;</span>
<span id="annotated-cell-3-17"><a href="#annotated-cell-3-17"></a>WH<span class="ot">=</span>(total[<span class="dv">1</span>,]<span class="co">#total[2,]) / (total[1,]+total[2,]) //</span></span>
<span id="annotated-cell-3-18"><a href="#annotated-cell-3-18"></a>(total[<span class="dv">3</span>,]<span class="co">#total[4,]) / (total[3,]+total[4,]);</span></span>
<span id="annotated-cell-3-19"><a href="#annotated-cell-3-19"></a>print wh;</span>
<span id="annotated-cell-3-20"><a href="#annotated-cell-3-20"></a><span class="at">GH=</span>(combined[,<span class="dv">1</span>]<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span>;</span>
<span id="annotated-cell-3-21"><a href="#annotated-cell-3-21"></a><span class="at">SEGH=</span>(combined[,<span class="dv">2</span>])<span class="sc">/</span><span class="dv">2</span>;</span>
<span id="annotated-cell-3-22"><a href="#annotated-cell-3-22"></a>print wh GH SEGH;</span>
<span id="annotated-cell-3-23"><a href="#annotated-cell-3-23"></a><span class="at">QH=</span> (GH[<span class="dv">1</span>] <span class="sc">-</span> GH[<span class="dv">2</span>])<span class="sc">**</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">SSQ</span>(SEGH);</span>
<span id="annotated-cell-3-24"><a href="#annotated-cell-3-24"></a><span class="at">pvalue=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">probchi</span>(QH,<span class="dv">1</span>);</span>
<span id="annotated-cell-3-25"><a href="#annotated-cell-3-25"></a>print GH SEGH QH pvalue;</span>
<span id="annotated-cell-3-26"><a href="#annotated-cell-3-26"></a><span class="at">gtilde1=</span><span class="fu">sum</span>(GH <span class="co"># WH);</span></span>
<span id="annotated-cell-3-27"><a href="#annotated-cell-3-27"></a><span class="at">gtilde2=</span><span class="fu">sum</span>(WH);</span>
<span id="annotated-cell-3-28"><a href="#annotated-cell-3-28"></a><span class="at">gtilde=</span>gtilde1<span class="sc">/</span>gtilde2;</span>
<span id="annotated-cell-3-29"><a href="#annotated-cell-3-29"></a><span class="at">gtildevar=</span>(<span class="fu">sum</span>(WH<span class="do">##2 # SEGH##2)) /((sum(WH))**2);</span></span>
<span id="annotated-cell-3-30"><a href="#annotated-cell-3-30"></a><span class="at">segtilde=</span><span class="fu">sqrt</span>(gtildevar);</span>
<span id="annotated-cell-3-31"><a href="#annotated-cell-3-31"></a><span class="at">qgtilde=</span>(gtilde<span class="fl">-.5</span>)<span class="sc">**</span><span class="dv">2</span><span class="sc">/</span>gtildevar;</span>
<span id="annotated-cell-3-32"><a href="#annotated-cell-3-32"></a>print gtilde gtildevar qgtilde;</span>
<span id="annotated-cell-3-33"><a href="#annotated-cell-3-33"></a>quit;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="4" data-code-annotation="1">Outputs somers’D(C|R) and error</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="5" data-code-annotation="2">crosstabs outputs the contigency table</span>
</dd>
</dl>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 75%">
<p>The data shown in the table comes from a randomized, double-blind clinical trial investigating a new treatment for rheumatoid arthritis. Investigators compared the new treatment with a placebo; the response measured was whether there was no, some, or marked improvement in the symptoms of rheumatoid arthritis when the active treatment was administered.</p>
<ul>
<li>Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group after controlling for gender?</li>
<li>Compare the results using table scores and modridit scores.</li>
</ul>
</div><div class="column" style="width:50%">
<p><img data-src="img/arth2_C4.png"></p>
</div></div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<div class="columns">
<div class="column" style="width:50%; font-size: 75%">
<ul>
<li>Is there sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group after controlling for gender?</li>
<li>Compare the results using table scores and modridit scores.</li>
</ul>
</div><div class="column" style="width:50%">
<p><img data-src="img/arth2_C4.png"></p>
</div></div>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">SAS Code</a></li><li><a href="#tabset-5-2">R Code</a></li><li><a href="#tabset-5-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<div class="sourceCode" id="annotated-cell-12"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1"></a>data arth;</span>
<span id="annotated-cell-12-2"><a href="#annotated-cell-12-2"></a>input gender <span class="sc">$</span> treat <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3"></a>datalines;</span>
<span id="annotated-cell-12-4"><a href="#annotated-cell-12-4"></a>female active none <span class="dv">6</span> female active some <span class="dv">5</span> female active marked <span class="dv">16</span></span>
<span id="annotated-cell-12-5"><a href="#annotated-cell-12-5"></a>female placebo none <span class="dv">19</span> female placebo some <span class="dv">7</span> female placebo marked <span class="dv">6</span></span>
<span id="annotated-cell-12-6"><a href="#annotated-cell-12-6"></a>male active none <span class="dv">7</span> male active some <span class="dv">2</span> male active marked <span class="dv">5</span></span>
<span id="annotated-cell-12-7"><a href="#annotated-cell-12-7"></a>male placebo none <span class="dv">10</span> male placebo some <span class="dv">0</span> male placebo marked <span class="dv">1</span></span>
<span id="annotated-cell-12-8"><a href="#annotated-cell-12-8"></a>;</span>
<span id="annotated-cell-12-9"><a href="#annotated-cell-12-9"></a></span>
<span id="annotated-cell-12-10"><a href="#annotated-cell-12-10"></a>proc freq data<span class="ot">=</span>arth order<span class="ot">=</span>data;</span>
<span id="annotated-cell-12-11"><a href="#annotated-cell-12-11"></a>weight count;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-12-12" class="code-annotation-target"><a href="#annotated-cell-12-12"></a>tables gender<span class="sc">*</span>treat<span class="sc">*</span>response <span class="sc">/</span> cmh nocol nopct;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-12-13" class="code-annotation-target"><a href="#annotated-cell-12-13"></a>tables gender<span class="sc">*</span>treat<span class="sc">*</span>response <span class="sc">/</span> cmh nocol nopct scores<span class="ot">=</span>modridit;</span>
<span id="annotated-cell-12-14"><a href="#annotated-cell-12-14"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="12" data-code-annotation="1">Table Scores</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="13" data-code-annotation="2">Modridit scores (Standardized Midranks)</span>
</dd>
</dl>
</div>
<div id="tabset-5-2">
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-13"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-13-1"><a href="#annotated-cell-13-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Improvement=</span><span class="fu">c</span>(<span class="st">"None"</span>,<span class="st">"Some"</span>,<span class="st">"Marked"</span>),</span>
<span id="annotated-cell-13-2"><a href="#annotated-cell-13-2"></a>            <span class="at">Treatment =</span> <span class="fu">c</span>(<span class="st">"Active"</span>,<span class="st">"Placebo"</span>),</span>
<span id="annotated-cell-13-3"><a href="#annotated-cell-13-3"></a>            <span class="at">gender=</span><span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>)</span>
<span id="annotated-cell-13-4"><a href="#annotated-cell-13-4"></a>            ) <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-13-5"><a href="#annotated-cell-13-5"></a><span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">16</span>,<span class="dv">19</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="annotated-cell-13-6"><a href="#annotated-cell-13-6"></a><span class="fu">xtabs</span>(count <span class="sc">~</span>  Treatment <span class="sc">+</span> Improvement <span class="sc">+</span> gender  ,<span class="at">data=</span>dat) <span class="ot">-&gt;</span> dat_cc</span>
<span id="annotated-cell-13-7"><a href="#annotated-cell-13-7"></a>dat_cc</span>
<span id="annotated-cell-13-8"><a href="#annotated-cell-13-8"></a><span class="fu">CMHtest</span>(dat_cc,</span>
<span id="annotated-cell-13-9"><a href="#annotated-cell-13-9"></a>        <span class="at">types=</span><span class="st">"ALL"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-13" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-13-10" class="code-annotation-target"><a href="#annotated-cell-13-10"></a>        <span class="at">cscores =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(dat_cc),</span>
<span id="annotated-cell-13-11"><a href="#annotated-cell-13-11"></a>        <span class="at">overall=</span>T, <span class="at">strata=</span><span class="st">"gender"</span>)</span>
<span id="annotated-cell-13-12"><a href="#annotated-cell-13-12"></a></span>
<span id="annotated-cell-13-13"><a href="#annotated-cell-13-13"></a><span class="fu">CMHtest</span>(dat_cc,</span>
<span id="annotated-cell-13-14"><a href="#annotated-cell-13-14"></a>        <span class="at">types=</span><span class="st">"ALL"</span>,</span>
<span id="annotated-cell-13-15"><a href="#annotated-cell-13-15"></a>        <span class="at">overall=</span>T,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-13" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-13-16" class="code-annotation-target"><a href="#annotated-cell-13-16"></a>        <span class="at">cscores=</span><span class="st">"midrank"</span>,</span>
<span id="annotated-cell-13-17"><a href="#annotated-cell-13-17"></a>        <span class="at">strata=</span><span class="st">"gender"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-13" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-13" data-code-lines="10" data-code-annotation="1">table scores</span>
</dd>
<dt data-target-cell="annotated-cell-13" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-13" data-code-lines="16" data-code-annotation="2">standardized midrank scores</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>, , gender = Female

         Improvement
Treatment None Some Marked
  Active     6    5     16
  Placebo   19    7      6

, , gender = Male

         Improvement
Treatment None Some Marked
  Active     7    2      5
  Placebo   10    0      1

$`gender:Female`
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    in stratum gender:Female 

                 AltHypothesis  Chisq Df       Prob
general    General association 11.105  2 0.00387828
rmeans  Row mean scores differ 10.935  1 0.00094361
cmeans  Col mean scores differ 11.105  2 0.00387828
cor        Nonzero correlation 10.935  1 0.00094361


$`gender:Male`
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    in stratum gender:Male 

                 AltHypothesis  Chisq Df     Prob
general    General association 4.7105  2 0.094871
rmeans  Row mean scores differ 3.7128  1 0.053997
cmeans  Col mean scores differ 4.7105  2 0.094871
cor        Nonzero correlation 3.7128  1 0.053997


$ALL
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    Overall tests, controlling for all strata 

                 AltHypothesis  Chisq Df       Prob
general    General association 14.632  2 0.00066473
rmeans  Row mean scores differ 14.632  1 0.00013068
cmeans  Col mean scores differ 14.632  2 0.00066473
cor        Nonzero correlation 14.632  1 0.00013068


$`gender:Female`
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    in stratum gender:Female 

                 AltHypothesis  Chisq Df       Prob
general    General association 11.105  2 0.00387828
rmeans  Row mean scores differ 10.879  1 0.00097249
cmeans  Col mean scores differ 11.105  2 0.00387828
cor        Nonzero correlation 10.879  1 0.00097249


$`gender:Male`
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    in stratum gender:Male 

                 AltHypothesis  Chisq Df     Prob
general    General association 4.7105  2 0.094871
rmeans  Row mean scores differ 4.1469  1 0.041712
cmeans  Col mean scores differ 4.7105  2 0.094871
cor        Nonzero correlation 4.1469  1 0.041712


$ALL
Cochran-Mantel-Haenszel Statistics for Treatment by Improvement 
    Overall tests, controlling for all strata 

                 AltHypothesis  Chisq Df       Prob
general    General association 14.632  2 0.00066473
rmeans  Row mean scores differ 15.004  1 0.00010728
cmeans  Col mean scores differ 14.632  2 0.00066473
cor        Nonzero correlation 15.004  1 0.00010728</code></pre>
</div>
</div>
</div>
<div id="tabset-5-3">
<p><span class="math inline">\(Q_{SMH} = 14.6\)</span>, p&lt;0.001. There is sufficient evidence to conclude that the active treatment group has higher improvement compared to the placebo group.</p>
<p>When using the modridit scores, <span class="math inline">\(Q_{SMH}=15.00, p&lt;0.001\)</span>. Same conclusion with a slight deviation between statistics.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>The following data is obtained from the 2003 Programme for International Student Assessment (PISA) study.</p>
<ul>
<li>Use the appropriate analysis to determine whether the attitude toward school is different between students in the US and Korea after controlling for gender.</li>
<li>Calculate the relevant Somers’ D values for each gender.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">Contingency Table</a></li><li><a href="#tabset-6-2">SAS Data</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<p><img data-src="img/pisa_C4.png"></p>
</div>
<div id="tabset-6-2">
<div class="sourceCode" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>data school;</span>
<span id="cb10-2"><a></a>input gender <span class="sc">$</span> location <span class="sc">$</span> response <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb10-3"><a></a>datalines;</span>
<span id="cb10-4"><a></a>female US sd <span class="dv">1253</span> female US d <span class="dv">1227</span> female US a <span class="dv">125</span> female US sa <span class="dv">38</span></span>
<span id="cb10-5"><a></a>female korea sd <span class="dv">578</span> female korea d <span class="dv">1415</span> female korea a <span class="dv">199</span> female korea sa <span class="dv">26</span></span>
<span id="cb10-6"><a></a>male US sd <span class="dv">922</span> male US d <span class="dv">1369</span> male US a <span class="dv">249</span> male US sa <span class="dv">102</span></span>
<span id="cb10-7"><a></a>male korea sd <span class="dv">897</span> male korea d <span class="dv">1942</span> male korea a <span class="dv">281</span> male korea sa <span class="dv">58</span></span>
<span id="cb10-8"><a></a>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>The following data is obtained from the 2003 Programme for International Student Assessment (PISA) study.</p>
<ul>
<li>Use the appropriate analysis to determine whether the attitude toward school is different between students in the US and Korea after controlling for gender.</li>
<li>Calculate the relevant Somers’ D values for each gender.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">SAS Code</a></li><li><a href="#tabset-7-2">R Code</a></li><li><a href="#tabset-7-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>proc freq data<span class="ot">=</span>school order<span class="ot">=</span>data;</span>
<span id="cb11-2"><a></a>weight count;</span>
<span id="cb11-3"><a></a>tables gender<span class="sc">*</span>location<span class="sc">*</span>response<span class="sc">/</span>all nocol nopct measures cl;</span>
<span id="cb11-4"><a></a>tables gender<span class="sc">*</span>location<span class="sc">*</span>response<span class="sc">/</span>all nocol nopct measures scores<span class="ot">=</span>modridit cl;</span>
<span id="cb11-5"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>dat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Rating=</span><span class="fu">c</span>(<span class="st">"StD"</span>,<span class="st">"D"</span>,<span class="st">"A"</span>,<span class="st">"StA"</span>),</span>
<span id="cb12-2"><a></a>            <span class="at">gender=</span><span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>), </span>
<span id="cb12-3"><a></a>            <span class="at">country =</span> <span class="fu">c</span>(<span class="st">"US"</span>,<span class="st">"Korea"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb12-4"><a></a><span class="fu">mutate</span>(<span class="at">count =</span> <span class="fu">c</span>(<span class="dv">1253</span>,<span class="dv">1227</span>,<span class="dv">125</span>,<span class="dv">38</span>,<span class="dv">922</span>,<span class="dv">1369</span>,<span class="dv">249</span>,<span class="dv">102</span>,<span class="dv">578</span>,<span class="dv">1415</span>,<span class="dv">199</span>,<span class="dv">26</span>,<span class="dv">897</span>,<span class="dv">1942</span>,<span class="dv">281</span>,<span class="dv">58</span>))</span>
<span id="cb12-5"><a></a></span>
<span id="cb12-6"><a></a><span class="fu">xtabs</span>(count <span class="sc">~</span>  country <span class="sc">+</span>Rating <span class="sc">+</span> gender  ,<span class="at">data=</span>dat) <span class="ot">-&gt;</span> dat_cc</span>
<span id="cb12-7"><a></a>dat_cc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , gender = Female

       Rating
country  StD    D    A  StA
  US    1253 1227  125   38
  Korea  578 1415  199   26

, , gender = Male

       Rating
country  StD    D    A  StA
  US     922 1369  249  102
  Korea  897 1942  281   58</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">CMHtest</span>(dat_cc,</span>
<span id="cb14-2"><a></a>        <span class="at">types=</span><span class="st">"ALL"</span>,</span>
<span id="cb14-3"><a></a>        <span class="at">cscores =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(dat_cc), </span>
<span id="cb14-4"><a></a>        <span class="at">overall=</span>T, <span class="at">strata=</span><span class="st">"gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`gender:Female`
Cochran-Mantel-Haenszel Statistics for country by Rating 
    in stratum gender:Female 

                 AltHypothesis  Chisq Df       Prob
general    General association 246.04  3 4.6999e-53
rmeans  Row mean scores differ 182.24  1 1.5754e-41
cmeans  Col mean scores differ 246.04  3 4.6999e-53
cor        Nonzero correlation 182.24  1 1.5754e-41


$`gender:Male`
Cochran-Mantel-Haenszel Statistics for country by Rating 
    in stratum gender:Male 

                 AltHypothesis   Chisq Df       Prob
general    General association 64.7130  3 5.7775e-14
rmeans  Row mean scores differ  1.2096  1 2.7140e-01
cmeans  Col mean scores differ 64.7130  3 5.7775e-14
cor        Nonzero correlation  1.2096  1 2.7140e-01


$ALL
Cochran-Mantel-Haenszel Statistics for country by Rating 
    Overall tests, controlling for all strata 

                 AltHypothesis  Chisq Df       Prob
general    General association 246.36  3 4.0051e-53
rmeans  Row mean scores differ 91.317  1  1.224e-21
cmeans  Col mean scores differ 246.36  3 4.0051e-53
cor        Nonzero correlation 91.317  1  1.224e-21</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">CMHtest</span>(dat_cc,</span>
<span id="cb16-2"><a></a>        <span class="at">types=</span><span class="st">"ALL"</span>,</span>
<span id="cb16-3"><a></a>        <span class="at">overall=</span>T,</span>
<span id="cb16-4"><a></a>        <span class="at">cscores=</span><span class="st">"midrank"</span>,</span>
<span id="cb16-5"><a></a>        <span class="at">strata=</span><span class="st">"gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`gender:Female`
Cochran-Mantel-Haenszel Statistics for country by Rating 
    in stratum gender:Female 

                 AltHypothesis  Chisq Df       Prob
general    General association 246.04  3 4.6999e-53
rmeans  Row mean scores differ 223.84  1 1.3178e-50
cmeans  Col mean scores differ 246.04  3 4.6999e-53
cor        Nonzero correlation 223.84  1 1.3178e-50


$`gender:Male`
Cochran-Mantel-Haenszel Statistics for country by Rating 
    in stratum gender:Male 

                 AltHypothesis   Chisq Df       Prob
general    General association 64.7130  3 5.7775e-14
rmeans  Row mean scores differ  8.4411  1 3.6683e-03
cmeans  Col mean scores differ 64.7130  3 5.7775e-14
cor        Nonzero correlation  8.4411  1 3.6683e-03


$ALL
Cochran-Mantel-Haenszel Statistics for country by Rating 
    Overall tests, controlling for all strata 

                 AltHypothesis  Chisq Df       Prob
general    General association 246.36  3 4.0051e-53
rmeans  Row mean scores differ 149.89  1 1.8367e-34
cmeans  Col mean scores differ 246.36  3 4.0051e-53
cor        Nonzero correlation 149.89  1 1.8367e-34</code></pre>
</div>
</div>
</div>
<div id="tabset-7-3">
<p>Using MODRIDIT scores, we get <span class="math inline">\(Q_{SMH} = 149.88, p&lt;0.001\)</span>. Using TABLE scores, we get <span class="math inline">\(Q_{SMH} = 91.3, p&lt;0.001\)</span>. There is sufficient evidence that there is a difference in the attitude toward school between the students from US and Korea.</p>
<ul>
<li><p>I would use the modridit scores because the spacing between ratings is non-uniform.</p></li>
<li><p>You can use multiple scores and see whether the resulting inference is the same.</p></li>
<li><p>The Somers’ D (C|R) for females is 0.22 (0.19,0.25)</p></li>
<li><p>The Somer’s D (C|R) for males is 0.04 (0.01,0.07)</p></li>
</ul>
</div>
</div>
</div>
</section></section>
<section>
<section id="s-times-2-table" class="title-slide slide level1 center">
<h1><span class="math inline">\(s \times 2\)</span> table</h1>

</section>
<section id="s-times-2-table-1" class="slide level2">
<h2><span class="math inline">\(s \times 2\)</span> table</h2>
<ul>
<li>Used when there are multiple groups defined by an ordinal variable with a dichotomous outcome.</li>
<li>Example: Degree of gambling experience, degree of smoking experience, Educational Attainment</li>
</ul>
</section>
<section id="s-times-2-table-2" class="slide level2">
<h2><span class="math inline">\(s \times 2\)</span> table</h2>
<div class="columns">
<div class="column" style="width:40%; font-size: 75%">
<p>Assume <span class="math inline">\(X\)</span> is an ordinal variable.</p>
<p>To account for ordinality, we assign a set of scores <span class="math inline">\(\mathbf{c}\)</span> reflecting the relationship between response levels.</p>
<p><span class="math display">\[
\mathbf{c} = \{c_1, c_2, c_3,... c_s\} : c_1 &lt; c_2 &lt; ...&lt; c_s
\]</span></p>
<p>In <span class="math inline">\(2 \times r\)</span> tables, <span class="math inline">\(\mathbf{a} = (a_1,a_2)\)</span> is effectively (0,1)</p>
</div><div class="column" style="width:60%">
<p><img data-src="img/sx2_C4.png"></p>
</div></div>
</section>
<section id="s-times-2-table-3" class="slide level2">
<h2><span class="math inline">\(s \times 2\)</span> table</h2>
<p>The expected frequency can be expressed as</p>
<p><span class="math display">\[
\bar{f} = \sum_{i=1}^s\sum_{j=1}^2 \frac{c_ia_jn_{ij}}{n}
\]</span></p>
</section>
<section id="s-times-2-table-4" class="slide level2">
<h2><span class="math inline">\(s \times 2\)</span> table</h2>
<p>The null hypothesis <span class="math inline">\(H_0\)</span>: There is no association between the two variables. To test this hypothesis, we can use a randomization statistic <span class="math inline">\(Q_{CS}\)</span> such that</p>
<p><span class="math display">\[
Q_{CS} = \frac{(\bar{f}-\mu_c\mu_a)^2}{v_cv_a/(n-1)} = (n-1)r_{ac}^2
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(\mu_c\)</span> is the expected value of the row scores</li>
<li><span class="math inline">\(\mu_a\)</span> is the expected value of the column scores.</li>
<li><span class="math inline">\(v_c\)</span> is the variance of the row scores</li>
<li><span class="math inline">\(v_a\)</span> is variance of the column scores</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(Q_{CS}\)</span> is also referred to the correlation statistic. <span class="math inline">\(Q_{CS}\)</span> follows a chi-square distribution with one degree of freedom.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(Q_{CS}\)</span> is related to the Pearson correlation coefficient <span class="math inline">\(r_{ac}\)</span></p>
</div>
</div>
</div>
</section>
<section id="cochran-armitage-test" class="slide level2">
<h2>Cochran-Armitage test</h2>
<p>A similar statistic to the correlation statistic is the <span class="math inline">\(z^2\)</span> statistic used in the Cochran-Armitage test.</p>
<ul>
<li>The Cochran-Armitage trend test tests for trends in binomial proportions across levels of an ordinal covariate.</li>
</ul>
<p><span class="math display">\[
z^2 = Q_{CS} \left[\frac{n}{n-1}\right]
\]</span></p>
</section>
<section id="s-times-2-analysis-sas" class="slide level2">
<h2><span class="math inline">\(s \times 2\)</span> analysis: SAS</h2>
<ul>
<li>The correlation statistic can be found in the SAS Output as the Mantel-Haenszel chi-square statistic from the <code>chisq</code> option.</li>
<li>SAS can also perform the Cochran-Armitage trend test by including the <code>trend</code> option in the <code>tables</code> statement.</li>
<li>The Pearson correlation coefficient and the Somers’ D(C|R) are of particular interest in the <code>measures</code> output since both metrics account for ordinality.</li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>proc freq;</span>
<span id="cb18-2"><a></a>weight count;</span>
<span id="cb18-3"><a></a>tables a<span class="sc">*</span>b<span class="sc">/</span>trend chisq measures;</span>
<span id="cb18-4"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>A random sample of 200 married men, all retired, were classified according to education and number of children. The data is shown in the table.</p>
<ul>
<li>Is there sufficient evidence of association between the father’s educational attainment and the number of children?</li>
<li>Using the Cochran-Armitage trend test to determine if there is an increasing trend in number of children with increasing educational attainment.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           Kids
education   At most 3 More than 3
  secondary        51          32
  college          61          17
  graduate         29          10</code></pre>
</div>
</div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>A random sample of 200 married men, all retired, were classified according to education and number of children. The data is shown in the table.</p>
<ul>
<li>Is there sufficient evidence of association between the father’s educational attainment and the number of children?</li>
<li>Using the Cochran-Armitage trend test to determine if there is an increasing trend in number of children with increasing educational attainment.</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">SAS Code</a></li><li><a href="#tabset-8-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<div class="sourceCode" id="annotated-cell-24"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-24-1"><a href="#annotated-cell-24-1"></a>data educ;</span>
<span id="annotated-cell-24-2"><a href="#annotated-cell-24-2"></a>input education <span class="sc">$</span> kids3 <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-24-3"><a href="#annotated-cell-24-3"></a>datalines;</span>
<span id="annotated-cell-24-4"><a href="#annotated-cell-24-4"></a>secondary leq <span class="dv">51</span> secondary g <span class="dv">32</span></span>
<span id="annotated-cell-24-5"><a href="#annotated-cell-24-5"></a>college leq <span class="dv">61</span> college g <span class="dv">17</span></span>
<span id="annotated-cell-24-6"><a href="#annotated-cell-24-6"></a>graduate leq <span class="dv">29</span> graduate g <span class="dv">10</span></span>
<span id="annotated-cell-24-7"><a href="#annotated-cell-24-7"></a>;</span>
<span id="annotated-cell-24-8"><a href="#annotated-cell-24-8"></a>run;</span>
<span id="annotated-cell-24-9"><a href="#annotated-cell-24-9"></a></span>
<span id="annotated-cell-24-10"><a href="#annotated-cell-24-10"></a>proc freq data<span class="ot">=</span> educ order<span class="ot">=</span>data;</span>
<span id="annotated-cell-24-11"><a href="#annotated-cell-24-11"></a>weight count;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-24" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-24-12" class="code-annotation-target"><a href="#annotated-cell-24-12"></a>tables education<span class="sc">*</span>kids3<span class="sc">/</span>chisq measures trend cl;</span>
<span id="annotated-cell-24-13"><a href="#annotated-cell-24-13"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-24" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-24" data-code-lines="12" data-code-annotation="1"><code>chisq</code> gives <span class="math inline">\(Q_{CS}\)</span>, <code>measure</code>s provides Somers and pearson, <code>trend</code> gives cochran-armitage, <code>cl</code> calculates confidence intervals.</span>
</dd>
</dl>
</div>
<div id="tabset-8-2">
<p><span class="math inline">\(Q_{CS} = 3.47, p =0.06\)</span>. There is weak evidence of association between the father’s educational attainment and number of offspring.</p>
<p>The one-sided Cochran-Armitage test yielded a p-value = 0.03, which is sufficient evidence to support a decreasing trend in number of children with increasing educational attainment.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="sets-of-s-times-2-tables" class="title-slide slide level1 center">
<h1>Sets of <span class="math inline">\(s \times 2\)</span> tables</h1>

</section>
<section id="sets-of-s-times-2-tables-1" class="slide level2">
<h2>Sets of <span class="math inline">\(s \times 2\)</span> tables</h2>
<ul>
<li>Just like 2xr tables, there is also a statistic for the association of two ordinal variables for a combined set of strata called the extended Mantel-Haenszel correlation statistic (<span class="math inline">\(Q_{CSMH}\)</span>).
<ul>
<li><span class="math inline">\(Q_{CSMH}\)</span> approximately follows a chi-square distribution with df=1 when the combined strata sample sizes is greater than or equal to 40 (sufficiently large).</li>
</ul></li>
</ul>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>The table contains two contingency tables of risk perception (minimal, moderate, and substantial) and adolescent tobacco usage by father’s usage.</p>
<ul>
<li>Comment on whether there is an association between risk perception and adolescent usage when the father does not use tobacco.</li>
<li>Is there a discernible trend in the proportions of adolescent usage over the levels of risk perception after controlling for father’s tobacco usage?</li>
</ul>

<img data-src="img/tobaccoset_C4.png" class="r-stretch"></section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>The table contains two contingency tables of risk perception (minimal, moderate, and substantial) and adolescent tobacco usage by father’s usage.</p>
<ul>
<li>Comment on whether there is an association between risk perception and adolescent usage when the father does not use tobacco.</li>
<li>Is there a discernible trend in the proportions of adolescent usage over the levels of risk perception after controlling for father’s tobacco usage?</li>
</ul>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">Contingency table</a></li><li><a href="#tabset-9-2">SAS Code</a></li><li><a href="#tabset-9-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<p><img data-src="img/tobaccoset_C4.png"></p>
</div>
<div id="tabset-9-2">
<div class="sourceCode" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>data tobacco;</span>
<span id="cb20-2"><a></a>length risk <span class="sc">$</span><span class="fl">11.</span> ;</span>
<span id="cb20-3"><a></a>input f_usage <span class="sc">$</span> risk <span class="sc">$</span> usage <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb20-4"><a></a>datalines;</span>
<span id="cb20-5"><a></a>no minimal no <span class="dv">59</span> no minimal yes <span class="dv">25</span></span>
<span id="cb20-6"><a></a>no moderate no <span class="dv">169</span> no moderate yes <span class="dv">29</span></span>
<span id="cb20-7"><a></a>no substantial no <span class="dv">196</span> no substantial yes <span class="dv">9</span></span>
<span id="cb20-8"><a></a>yes minimal no <span class="dv">11</span> yes minimal yes <span class="dv">8</span></span>
<span id="cb20-9"><a></a>yes moderate no <span class="dv">33</span> yes moderate yes <span class="dv">11</span></span>
<span id="cb20-10"><a></a>yes substantial no <span class="dv">22</span> yes substantial yes <span class="dv">2</span></span>
<span id="cb20-11"><a></a>;</span>
<span id="cb20-12"><a></a>proc freq;</span>
<span id="cb20-13"><a></a>weight count;</span>
<span id="cb20-14"><a></a>tables f_usage<span class="sc">*</span>risk<span class="sc">*</span>usage <span class="sc">/</span>cmh chisq measures trend;</span>
<span id="cb20-15"><a></a>tables f_usage<span class="sc">*</span>risk<span class="sc">*</span>usage <span class="sc">/</span>cmh scores<span class="ot">=</span>modridit;</span>
<span id="cb20-16"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-9-3">
<p>When the father is not a tobacco user, <span class="math inline">\(Q_{CS}=34.3, p&lt;0.001\)</span>, which means there is sufficient evidence of an association between risk perception and participant tobacco use.</p>
<p><span class="math inline">\(Q_{CSMH}=39.3\)</span> using modified ridit scores (<span class="math inline">\(Q_{CSMH}=40.7\)</span> for table scores), resulting to a p-value p&lt;0.001. There is sufficient evidence of an association between risk perception and participant tobacco use.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="s-times-2-exact-analysis" class="title-slide slide level1 center">
<h1><span class="math inline">\(s \times 2\)</span>: Exact Analysis</h1>

</section>
<section id="exact-analysis" class="slide level2">
<h2>Exact Analysis</h2>
<ul>
<li>For small sample sizes, <span class="math inline">\(Q_{CS}\)</span> does not satisfy the asymptotic requirements.</li>
<li>We use exact tests to calculate the correct Mantel-Haenszel statistics.</li>
<li>We manually calculate the Wilcoxon rank and logrank scores for each row.
<ul>
<li>Wilcoxon vs logrank: Logrank is better when there are more counts in the lower end of the row ordinal variable.</li>
</ul></li>
</ul>
</section>
<section id="exact-analysis-sas" class="slide level2">
<h2>Exact Analysis: SAS</h2>
<ul>
<li>The <code>exact</code> statement is used to perform an exact test on the correlation statistic.
<ul>
<li><code>exact mhchi</code> would perform the statement on the Mantel-Haenszel statistic.</li>
<li><code>scorout</code> outputs the scores used in the exact analysis</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>proc freq;</span>
<span id="cb21-2"><a></a>tables a<span class="sc">*</span>b <span class="sc">/</span>scorout;</span>
<span id="cb21-3"><a></a>exact mhchi;</span>
<span id="cb21-4"><a></a>run;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>The table shows data from a study of mice who were exposed to a bacterial challenge and treated with the drugs carbenicillin or cefotaxmine (Bowdre, et al.&nbsp;1983). Surviving mice were assessed at intervals of 6 to 24 hours. Is there evidence that there is a difference in performance between the two drugs?</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Contingency Table</a></li><li><a href="#tabset-10-2">SAS Data</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p><img data-src="img/mice_C4.png"></p>
</div>
<div id="tabset-10-2">
<div class="sourceCode" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>data mice;</span>
<span id="cb22-2"><a></a>input LogRank Treatment <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb22-3"><a></a>datalines;</span>
<span id="cb22-4"><a></a><span class="fl">0.909</span> Ca <span class="dv">1</span> <span class="fl">0.909</span> Ce <span class="dv">1</span></span>
<span id="cb22-5"><a></a><span class="fl">0.709</span> Ca <span class="dv">3</span> <span class="fl">0.709</span> Ce <span class="dv">1</span></span>
<span id="cb22-6"><a></a><span class="fl">0.334</span> Ca <span class="dv">5</span> <span class="fl">0.334</span> Ce <span class="dv">1</span></span>
<span id="cb22-7"><a></a><span class="fl">0.234</span> Ca <span class="dv">1</span> <span class="fl">0.234</span> Ce <span class="dv">0</span></span>
<span id="cb22-8"><a></a><span class="sc">-</span><span class="fl">0.099</span> Ca <span class="dv">1</span> <span class="sc">-</span><span class="fl">0.099</span> Ce <span class="dv">2</span></span>
<span id="cb22-9"><a></a><span class="sc">-</span><span class="fl">0.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">0.433</span> Ce <span class="dv">2</span></span>
<span id="cb22-10"><a></a><span class="sc">-</span><span class="fl">0.933</span> Ca <span class="dv">1</span> <span class="sc">-</span><span class="fl">0.933</span> Ce <span class="dv">1</span></span>
<span id="cb22-11"><a></a><span class="sc">-</span><span class="fl">1.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">1.433</span> Ce <span class="dv">1</span></span>
<span id="cb22-12"><a></a><span class="sc">-</span><span class="fl">2.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">2.433</span> Ce <span class="dv">1</span></span>
<span id="cb22-13"><a></a>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>The table shows data from a study of mice who were exposed to a bacterial challenge and treated with the drugs carbenicillin or cefotaxmine (Bowdre, et al.&nbsp;1983). Surviving mice were assessed at intervals of 6 to 24 hours. Is there evidence that there is a difference in performance between the two drugs?</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">SAS Code</a></li><li><a href="#tabset-11-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<div class="sourceCode" id="annotated-cell-27"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-27-1"><a href="#annotated-cell-27-1"></a>data mice;</span>
<span id="annotated-cell-27-2"><a href="#annotated-cell-27-2"></a>input LogRank Treatment <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="annotated-cell-27-3"><a href="#annotated-cell-27-3"></a>datalines;</span>
<span id="annotated-cell-27-4"><a href="#annotated-cell-27-4"></a><span class="fl">0.909</span> Ca <span class="dv">1</span> <span class="fl">0.909</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-5"><a href="#annotated-cell-27-5"></a><span class="fl">0.709</span> Ca <span class="dv">3</span> <span class="fl">0.709</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-6"><a href="#annotated-cell-27-6"></a><span class="fl">0.334</span> Ca <span class="dv">5</span> <span class="fl">0.334</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-7"><a href="#annotated-cell-27-7"></a><span class="fl">0.234</span> Ca <span class="dv">1</span> <span class="fl">0.234</span> Ce <span class="dv">0</span></span>
<span id="annotated-cell-27-8"><a href="#annotated-cell-27-8"></a><span class="sc">-</span><span class="fl">0.099</span> Ca <span class="dv">1</span> <span class="sc">-</span><span class="fl">0.099</span> Ce <span class="dv">2</span></span>
<span id="annotated-cell-27-9"><a href="#annotated-cell-27-9"></a><span class="sc">-</span><span class="fl">0.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">0.433</span> Ce <span class="dv">2</span></span>
<span id="annotated-cell-27-10"><a href="#annotated-cell-27-10"></a><span class="sc">-</span><span class="fl">0.933</span> Ca <span class="dv">1</span> <span class="sc">-</span><span class="fl">0.933</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-11"><a href="#annotated-cell-27-11"></a><span class="sc">-</span><span class="fl">1.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">1.433</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-12"><a href="#annotated-cell-27-12"></a><span class="sc">-</span><span class="fl">2.433</span> Ca <span class="dv">0</span> <span class="sc">-</span><span class="fl">2.433</span> Ce <span class="dv">1</span></span>
<span id="annotated-cell-27-13"><a href="#annotated-cell-27-13"></a>;</span>
<span id="annotated-cell-27-14"><a href="#annotated-cell-27-14"></a></span>
<span id="annotated-cell-27-15"><a href="#annotated-cell-27-15"></a>proc freq order<span class="ot">=</span>data;</span>
<span id="annotated-cell-27-16"><a href="#annotated-cell-27-16"></a>weight count;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-27-17" class="code-annotation-target"><a href="#annotated-cell-27-17"></a>tables LogRank<span class="sc">*</span>Treatment <span class="sc">/</span> norow nocol nopct scorout chisq;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-27-18" class="code-annotation-target"><a href="#annotated-cell-27-18"></a>tables LogRank<span class="sc">*</span>Treatment <span class="sc">/</span> noprint scores<span class="ot">=</span>rank scorout chisq;</span>
<span id="annotated-cell-27-19"><a href="#annotated-cell-27-19"></a>exact mhchi;</span>
<span id="annotated-cell-27-20"><a href="#annotated-cell-27-20"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-27" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="17" data-code-annotation="1">Using Logranks</span>
</dd>
<dt data-target-cell="annotated-cell-27" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="18" data-code-annotation="2">using ranks. Note that logranks preserves the order of the original data set.</span>
</dd>
</dl>
</div>
<div id="tabset-11-2">
<p>The exact logrank analysis showed that <span class="math inline">\(Q_{CS}=4.06, p=0.04\)</span>, which means we have sufficient evidence of an association/difference between the treatment and specimen survival.</p>
<p>However, the exact <em>rank</em> analysis showed that <span class="math inline">\(Q_{CS}=3.51, p=0.06\)</span>, which means we have weak evidence of an association/difference between the treatment and specimen survival.</p>
<p>I would favor the logrank analysis better because it encapsulates the data better and accounts for the higher representation of the lower end of the ordinal variable.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Chapter 4- <a href="https://madfudolig.quarto.pub/eab770slides/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/madfudolig\.quarto\.pub\/eab770slides");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
          let selectedAnnoteEl;
          const selectorForAnnotation = ( cell, annotation) => {
            let cellAttr = 'data-code-cell="' + cell + '"';
            let lineAttr = 'data-code-annotation="' +  annotation + '"';
            const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
            return selector;
          }
          const selectCodeLines = (annoteEl) => {
            const doc = window.document;
            const targetCell = annoteEl.getAttribute("data-target-cell");
            const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
            const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            const lines = annoteSpan.getAttribute("data-code-lines").split(",");
            const lineIds = lines.map((line) => {
              return targetCell + "-" + line;
            })
            let top = null;
            let height = null;
            let parent = null;
            if (lineIds.length > 0) {
                //compute the position of the single el (top and bottom and make a div)
                const el = window.document.getElementById(lineIds[0]);
                top = el.offsetTop;
                height = el.offsetHeight;
                parent = el.parentElement.parentElement;
              if (lineIds.length > 1) {
                const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                height = bottom - top;
              }
              if (top !== null && height !== null && parent !== null) {
                // cook up a div (if necessary) and position it 
                let div = window.document.getElementById("code-annotation-line-highlight");
                if (div === null) {
                  div = window.document.createElement("div");
                  div.setAttribute("id", "code-annotation-line-highlight");
                  div.style.position = 'absolute';
                  parent.appendChild(div);
                }
                div.style.top = top - 2 + "px";
                div.style.height = height + 4 + "px";
                div.style.left = 0;
                let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                if (gutterDiv === null) {
                  gutterDiv = window.document.createElement("div");
                  gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                  gutterDiv.style.position = 'absolute';
                  const codeCell = window.document.getElementById(targetCell);
                  const gutter = codeCell.querySelector('.code-annotation-gutter');
                  gutter.appendChild(gutterDiv);
                }
                gutterDiv.style.top = top - 2 + "px";
                gutterDiv.style.height = height + 4 + "px";
              }
              selectedAnnoteEl = annoteEl;
            }
          };
          const unselectCodeLines = () => {
            const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
            elementsIds.forEach((elId) => {
              const div = window.document.getElementById(elId);
              if (div) {
                div.remove();
              }
            });
            selectedAnnoteEl = undefined;
          };
            // Handle positioning of the toggle
        window.addEventListener(
          "resize",
          throttle(() => {
            elRect = undefined;
            if (selectedAnnoteEl) {
              selectCodeLines(selectedAnnoteEl);
            }
          }, 10)
        );
        function throttle(fn, ms) {
        let throttle = false;
        let timer;
          return (...args) => {
            if(!throttle) { // first call gets through
                fn.apply(this, args);
                throttle = true;
            } else { // all the others get throttled
                if(timer) clearTimeout(timer); // cancel #2
                timer = setTimeout(() => {
                  fn.apply(this, args);
                  timer = throttle = false;
                }, ms);
            }
          };
        }
          // Attach click handler to the DT
          const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
          for (const annoteDlNode of annoteDls) {
            annoteDlNode.addEventListener('click', (event) => {
              const clickedEl = event.target;
              if (clickedEl !== selectedAnnoteEl) {
                unselectCodeLines();
                const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                if (activeEl) {
                  activeEl.classList.remove('code-annotation-active');
                }
                selectCodeLines(clickedEl);
                clickedEl.classList.add('code-annotation-active');
              } else {
                // Unselect the line
                unselectCodeLines();
                clickedEl.classList.remove('code-annotation-active');
              }
            });
          }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>