<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Miguel Fudolig">
  <title>EAB770: Applied Statistical Methods for Categorical Data – EAB 770 - Chapter 9</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-146a52615c86749306b5caa224a9b489.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">EAB 770 - Chapter 9</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Miguel Fudolig 
</div>
</div>
</div>

</section>
<section>
<section id="logistic-regression---polytomous-response" class="title-slide slide level1 center">
<h1>Logistic Regression - Polytomous Response</h1>

</section>
<section id="outline" class="slide level2">
<h2>Outline</h2>
<ul>
<li>Ordinal Response
<ul>
<li>Proportional Odds Model</li>
<li>Multiple Qualitative Explanatory Variables</li>
<li>Partial Proportional Odds Model</li>
</ul></li>
<li>Nominal Response
<ul>
<li>Generalized Logits Model</li>
<li>Exact Methods: Generalized Logits Model</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="ordinal-response-variables" class="title-slide slide level1 center">
<h1>Ordinal Response Variables</h1>

</section>
<section id="polytomous-variables" class="slide level2">
<h2>Polytomous Variables?</h2>
<p>Recall Chapter 8: dichotomous response variables can be analyzed using logistic regression.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>What if the response variable has more than two levels?</p>
</div>
</div>
</div>
</section>
<section id="polytomous-variables-1" class="slide level2">
<h2>Polytomous variables</h2>
<ul>
<li>Polytomous variables are usually described by the <a href="https://online.stat.psu.edu/stat504/book/export/html/667">multinomial distribution</a></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Unlike the binomial distribution where we only need one probability of success, more than one probability of success is needed to be defined in multinomial distributions.</p>
</div>
</div>
</div>
</section>
<section id="cumulative-probabilities" class="slide level2">
<h2>Cumulative probabilities</h2>
<p>Consider <span class="math inline">\(\pi_{hij}\)</span> as the probability of success of the <span class="math inline">\(h^{th}\)</span> strata and <span class="math inline">\(i^{th}\)</span> explanatory variables and the <span class="math inline">\(j^{th}\)</span> level of the response variable. We can define <span class="math inline">\(\theta_{hij}\)</span> such that:</p>
<p><span class="math display">\[
\theta_{hiJ} = \sum_{j=1}^{J} \pi_{hij}
\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If <span class="math inline">\(J=1\)</span>, then <span class="math inline">\(\theta_{hi1} = \pi_{hi1}\)</span>. If <span class="math inline">\(J=2\)</span>, then <span class="math inline">\(\theta_{hi2} = \pi_{hi1} + \pi_{hi2}\)</span>. <span class="math inline">\(\theta_{hiJ}\)</span> is the <em>cumulative probability</em> of the response levels from <span class="math inline">\(j=1\)</span> to <span class="math inline">\(j=J\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If there are <span class="math inline">\(J+1\)</span> levels, then <span class="math inline">\(\pi_{J+1}\)</span> = 1-_{hiJ}$.</p>
</div>
</div>
</div>
</section>
<section id="cumulative-logits" class="slide level2">
<h2>Cumulative logits</h2>
<p>Cumulative logits can be defined based on the cumulative probabilities <span class="math inline">\(\theta_{hij}\)</span>. For a specific level <span class="math inline">\(k\)</span> out of <span class="math inline">\(K\)</span> levels,</p>
<p><span class="math display">\[
logit(\theta_{hik}) = \log\left(\frac{\theta_{hik}}{1-\theta_{hik}}\right) = \log\left(\frac{\sum_{j=1}^k\pi_{hij}}{1-\sum_{j=1}^k\pi_{hij}}\right) = \log\left(\frac{\sum_{j=1}^k\pi_{hij}}{\sum_{j=k+1}^K\pi_{hij}}\right)
\]</span></p>
</section>
<section id="cumulative-logits-1" class="slide level2">
<h2>Cumulative logits</h2>
<p>Suppose we define a linear predictor <span class="math inline">\(\eta_{hij}\)</span> such that</p>
<p><span class="math display">\[
\eta_{hij} = logit(\theta_{hij}) = \alpha_j + \mathbf{x'_{hi}\beta_k}
\]</span></p>
<p>where <span class="math inline">\(x'_{hi}\beta_k\)</span> represents the matrix product of the explanatory/strata variables <span class="math inline">\(x_{hi}\)</span> and the coefficients for each response level <span class="math inline">\(\beta_k\)</span>.</p>
</section>
<section id="proportional-odds-assumption" class="slide level2">
<h2>Proportional Odds Assumption</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Proportional Odds</strong></p>
</div>
<div class="callout-content">
<p>The proportional odds assumption applies the following condition for a response variable with <span class="math inline">\(K\)</span> total variable levels:</p>
<p><span class="math display">\[
\mathbf{\beta_1} = \mathbf{\beta_2} = \mathbf{\beta_3} = ... = \mathbf{\beta_{K}} = \mathbf{\beta}
\]</span></p>
</div>
</div>
</div>
<p>Key assumption: the effect of the explanatory variables should not be disproportionate across all levels.</p>
</section>
<section id="proportional-odds-1" class="slide level2">
<h2>Proportional Odds</h2>
<p>A consequence of the proportional odds assumption is that the difference between the levels of the explanatory variables are the same across different response levels.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>Consider comparing the <span class="math inline">\(m^{th}\)</span> and <span class="math inline">\(n^{th}\)</span> level of the explanatory variable in the <span class="math inline">\(h^{th}\)</span> strata for the first and second level of the response variable.</p>
<p><span class="math display">\[
\eta_{hm1}-\eta_{hn1} = (\mathbf{x'_{hm} - x'_{hn}})\mathbf{\beta_1} = (\mathbf{x'_{hm} - x'_{hn}})\mathbf{\beta}
\]</span></p>
<p><span class="math display">\[
\eta_{hm2}-\eta_{hn2} = (\mathbf{x'_{hm} - x'_{hn}})\mathbf{\beta_2} = (\mathbf{x'_{hm} - x'_{hn}})\mathbf{\beta}
\]</span> These are the same across all levels of the response variable. The difference between <span class="math inline">\(\eta\)</span> correspond to the log odds, hence the odds ratios between explanatory variables are the same across all response levels.</p>
</div>
</div>
</div>
</section>
<section id="proportional-odds-2" class="slide level2">
<h2>Proportional Odds</h2>
<p>Another consequence of the proportional odds assumption is that the difference between the response levels does not depend on the strata or explanatory variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>Consider comparing the first and second level of the response variable.</p>
<p><span class="math display">\[
\eta_{hm1}-\eta_{hm2} = \alpha _ 1 - \alpha _2 +  (\mathbf{x'_{hm}\beta - x'_{hm}}\beta) = \alpha_1-\alpha_2
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The proportional odds assumption can be tested using the Brant test. The null hypothesis of the test is that the proportional odds assumption holds. For the proportional odds assumption to hold, we must fail to reject the null hypothesis.</p>
</div>
</div>
</div>
</section>
<section id="solving-for-individual-probabilities" class="slide level2">
<h2>Solving for Individual Probabilities</h2>
<p>Individual probabilities can be calculated by taking the differences between cumulative logits.</p>
<p><span class="math display">\[
\pi_1 = \theta_1; \pi_2 = \theta_2-\theta_1; \pi_{k} = \theta_{k}-\theta_{k-1}
\]</span></p>
</section>
<section id="proportional-odds-model-in-sas" class="slide level2">
<h2>Proportional Odds Model in SAS</h2>
<ul>
<li>We can use the <code>LOGISTIC</code>, <code>GENMOD</code>, and <code>GLIMMIX</code> procedures to fit the proportional odds model.</li>
<li>Dealing with ordinal variables means we need to specify order of the data.</li>
<li>We can use the ESTIMATE and CONTRAST statements to determine and test the odds ratios between response levels, explanatory variable levels, and strata.
<ul>
<li><code>ESTIMATE: EXP</code> option to get the estimated odds ratio, <code>ILINK</code> option to get the estimated cumulative probability <span class="math inline">\(\theta\)</span>.</li>
<li>CL option is used to get the confidence limits for odds ratio or estimated probabilities.</li>
</ul></li>
</ul>
</section>
<section id="proportional-odds-model-in-r" class="slide level2">
<h2>Proportional Odds Model in <code>R</code></h2>
<p>The <code>polr()</code> function in the <code>MASS</code> package in <code>R</code> performs the proportional odds model in <code>R</code>. Marginal/conditional means can still be calculated using <code>emmeans()</code> from the <code>emmeans</code> package.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The <code>poTest()</code> function in <code>car</code> tests whether the proportional odds assumption holds.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Because the <code>polr()</code> function uses a slightly different link between the cumulative logits, the interpretation for these numbers will be different from that of <code>SAS</code>. Calculating odds ratios will provide the odds ratio of recording higher level of outcomes between the two predictor levels.</p>
</div>
</div>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>Male and female subjects received an active or placebo treatment for their arthritis pain, and the subsequent extent of improvement was recorded as marked, some, or none.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Questions</a></li><li><a href="#tabset-1-2">Data</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<ul>
<li>Write the correct form of the linear predictor.</li>
<li>Use the proportional odds model to determine whether there is an effect of sex and treatment.</li>
<li>List the odds ratio estimates, 95% confidence intervals, and corresponding interpretations.</li>
<li>Estimate the probability of marked improvement for females in the active group.</li>
</ul>
</div>
<div id="tabset-1-2">
<p><img data-src="img/arthritis_C9.png" style="width:200.0%"> ### R Data Set</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 84
Columns: 3
$ Treatment   &lt;fct&gt; Active, Active, Active, Active, Active, Active, Active, Ac…
$ Sex         &lt;fct&gt; Female, Female, Female, Female, Female, Female, Female, Fe…
$ Improvement &lt;fct&gt; Marked, Marked, Marked, Marked, Marked, Marked, Marked, Ma…</code></pre>
</div>
</div>
<p>It is important to check if the factor levels follow the order we want.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Marked" "None"   "Some"  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Active"  "Placebo"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Female" "Male"  </code></pre>
</div>
</div>
<p>The code below fixes this.</p>
</div>
</div>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Male and female subjects received an active or placebo treatment for their arthritis pain, and the subsequent extent of improvement was recorded as marked, some, or none.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1"><code>SAS</code> Data Set</a></li><li><a href="#tabset-2-2">SAS Code</a></li><li><a href="#tabset-2-3">R Code</a></li><li><a href="#tabset-2-4">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>data arthritis;</span>
<span id="cb5-2"><a></a>input sex <span class="sc">$</span> treatment <span class="sc">$</span> improve <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb5-3"><a></a>datalines;</span>
<span id="cb5-4"><a></a>female active marked <span class="dv">16</span> female active some <span class="dv">5</span> female active none <span class="dv">6</span></span>
<span id="cb5-5"><a></a>female placebo marked <span class="dv">6</span> female placebo some <span class="dv">7</span> female placebo none <span class="dv">19</span></span>
<span id="cb5-6"><a></a>male active marked <span class="dv">5</span> male active some <span class="dv">2</span> male active none <span class="dv">7</span></span>
<span id="cb5-7"><a></a>male placebo marked <span class="dv">1</span> male placebo some <span class="dv">0</span> male placebo none <span class="dv">10</span></span>
<span id="cb5-8"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-2-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-7"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-7-1" class="code-annotation-target"><a href="#annotated-cell-7-1"></a>proc logistic data<span class="ot">=</span>arthritis order<span class="ot">=</span>data plots<span class="ot">=</span><span class="fu">effect</span>(polybar <span class="at">x=</span>treatment<span class="sc">*</span>sex);</span>
<span id="annotated-cell-7-2"><a href="#annotated-cell-7-2"></a>freq count;</span>
<span id="annotated-cell-7-3"><a href="#annotated-cell-7-3"></a>class treatment sex <span class="sc">/</span> param<span class="ot">=</span>ref; </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-7-4" class="code-annotation-target"><a href="#annotated-cell-7-4"></a>model improve <span class="ot">=</span> sex treatment sex<span class="sc">*</span>treatment<span class="sc">/</span> selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">2</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="annotated-cell-7-5"><a href="#annotated-cell-7-5"></a>estimate <span class="st">"odds between marked vs. some+no improvement for female in placebo group"</span> intercept <span class="dv">1</span> sex <span class="dv">1</span> <span class="sc">/</span>exp cl category<span class="ot">=</span><span class="st">'marked'</span>;</span>
<span id="annotated-cell-7-6"><a href="#annotated-cell-7-6"></a>estimate <span class="st">"odds between marked+some vs. no improvement for female in placebo group"</span> intercept <span class="dv">1</span> sex <span class="dv">1</span> <span class="sc">/</span>exp cl category<span class="ot">=</span><span class="st">'some'</span>;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-7-7" class="code-annotation-target"><a href="#annotated-cell-7-7"></a>estimate <span class="st">"probability of marked improvement for female in the placebo group"</span> intercept <span class="dv">1</span> sex <span class="dv">1</span><span class="sc">/</span>ilink cl category<span class="ot">=</span><span class="st">'marked'</span>;</span>
<span id="annotated-cell-7-8"><a href="#annotated-cell-7-8"></a>estimate <span class="st">"probability of marked improvement for female in the active trt group"</span> intercept <span class="dv">1</span> sex <span class="dv">1</span> treatment <span class="dv">1</span><span class="sc">/</span>ilink cl category<span class="ot">=</span><span class="st">'marked'</span>;</span>
<span id="annotated-cell-7-9"><a href="#annotated-cell-7-9"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-7" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="1" data-code-annotation="1">The polybar plot creates stacked bar plots showing probability and cumulative probability plots for each level dictated by x.</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="4" data-code-annotation="2"><code>selection=forward include=2</code> tests whether the interaction is needed to be included in the model.</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="7" data-code-annotation="3">The <code>ilink</code> option calculates the cumulative probability, while <code>exp</code> calculates odds ratios. The reason it returns the probability for marked is that the marked level was inputted as the lowest level.</span>
</dd>
</dl>
</div>
<div id="tabset-2-3">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = Improvement ~ Treatment + Sex, data = arthritis, 
    Hess = TRUE)

Coefficients:
                 Value Std. Error t value
TreatmentActive  1.797     0.4718   3.809
SexMale         -1.319     0.5381  -2.451

Intercepts:
            Value   Std. Error t value
None|Some    0.4941  0.3369     1.4665
Some|Marked  1.3485  0.3667     3.6768

Residual Deviance: 150.0294 
AIC: 158.0294 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>TreatmentActive         SexMale 
      6.0330950       0.2674786 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tests for Proportional Odds
polr(formula = Improvement ~ Treatment + Sex, data = arthritis, 
    Hess = TRUE)

                 b[polr] b[&gt;None] b[&gt;Some] Chisquare df Pr(&gt;Chisq)
Overall                                         1.83  2       0.40
TreatmentActive  1.79726  1.78168  1.81602      0.01  1       0.94
SexMale         -1.31872 -1.46865 -0.93005      1.58  1       0.21</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II tests)

Response: Improvement
          LR Chisq Df Pr(&gt;Chisq)    
Treatment  16.0812  1  6.068e-05 ***
Sex         6.5766  1    0.01033 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>cut = None|Some:
 Treatment Sex    cumprob     SE  df asymp.LCL asymp.UCL
 Placebo   Female   0.621 0.0793 Inf    0.4657     0.776
 Active    Female   0.214 0.0658 Inf    0.0847     0.343
 Placebo   Male     0.860 0.0682 Inf    0.7260     0.993
 Active    Male     0.504 0.1180 Inf    0.2725     0.735

cut = Some|Marked:
 Treatment Sex    cumprob     SE  df asymp.LCL asymp.UCL
 Placebo   Female   0.794 0.0600 Inf    0.6763     0.912
 Active    Female   0.390 0.0870 Inf    0.2192     0.560
 Placebo   Male     0.935 0.0368 Inf    0.8629     1.007
 Active    Male     0.705 0.0999 Inf    0.5090     0.900

Confidence level used: 0.95 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Improvement = None:
 Treatment Sex      prob     SE  df asymp.LCL asymp.UCL
 Placebo   Female 0.6211 0.0793 Inf   0.46567     0.776
 Active    Female 0.2136 0.0658 Inf   0.08466     0.343
 Placebo   Male   0.8597 0.0682 Inf   0.72603     0.993
 Active    Male   0.5039 0.1180 Inf   0.27255     0.735

Improvement = Some:
 Treatment Sex      prob     SE  df asymp.LCL asymp.UCL
 Placebo   Female 0.1728 0.0457 Inf   0.08315     0.262
 Active    Female 0.1760 0.0474 Inf   0.08320     0.269
 Placebo   Male   0.0754 0.0361 Inf   0.00454     0.146
 Active    Male   0.2008 0.0519 Inf   0.09904     0.303

Improvement = Marked:
 Treatment Sex      prob     SE  df asymp.LCL asymp.UCL
 Placebo   Female 0.2061 0.0600 Inf   0.08850     0.324
 Active    Female 0.6104 0.0870 Inf   0.43990     0.781
 Placebo   Male   0.0649 0.0368 Inf  -0.00724     0.137
 Active    Male   0.2953 0.0999 Inf   0.09954     0.491

Confidence level used: 0.95 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Chapter9_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>To calculate the odds ratio, we can use <code>contrast()</code> but we have to manually exponentiate the confidence limits.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          contrast estimate        SE  df asymp.LCL asymp.UCL  z.ratio
1 Active - Placebo  1.79726 0.4717993 Inf 0.8725504   2.72197 3.809374
       p.value       OR   OR.LCL   OR.UCL
1 0.0001393191 6.033095 2.393006 15.21025</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       contrast estimate        SE  df asymp.LCL asymp.UCL  z.ratio    p.value
1 Female - Male 1.318716 0.5380997 Inf 0.2640599  2.373372 2.450691 0.01425824
        OR   OR.LCL   OR.UCL
1 3.738617 1.302206 10.73352</code></pre>
</div>
</div>
</div>
<div id="tabset-2-4">
<p>The linear predictor can be written as</p>
<p><span class="math display">\[
\eta_k = \alpha_k + \beta_{f}x_{f} + \beta_{a}x_{a}
\]</span> where <span class="math inline">\(x_f = 1\)</span> when the participant identifies as female, <span class="math inline">\(x_a=1\)</span> when the participant is in the active treatment group. Using the residual chi-square test, the interaction term is not significant <span class="math inline">\((\chi^2=0.28, p=0.60)\)</span>.</p>
<p>Using the proportional odds model, we determine that there is a significant effect of sex (<span class="math inline">\(\chi^2=6.2, p=0.01\)</span>) and treatment (<span class="math inline">\(\chi^2=14.4, p=0.001\)</span>).</p>
<p>Females have 3.74 (95% CI: 1.33, 10.55) times the odds of marked improvement compared to males.</p>
<p>The odds of improvement after undergoing active treatment is 6.03 (95% CI: 2.39, 15.2) times that of the placebo group.</p>
</div>
</div>
</div>
</section>
<section id="exercise" class="slide level2">
<h2>Exercise</h2>
<p>Researchers collected information on subjects’ exposure to general air pollution, exposure to pollution in their jobs, and whether they smoked. The response measured was chronic respiratory disease status. Subjects were assigned to one of four possible categories.</p>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">Questions</a></li><li><a href="#tabset-3-2">Data Set</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<ul>
<li>Use the proportional odds main effects model to test the effect of air pollution, job exposure, and smoking status in the response.</li>
<li>Estimate the odds ratio between Response I+II+III vs.&nbsp;IV for current vs.&nbsp;ex-smokers.</li>
<li>Estimate the probability of developing a response level III for an ex-smoker in a high air pollution environment with job exposure.</li>
</ul>
</div>
<div id="tabset-3-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>data respire;</span>
<span id="cb14-2"><a></a>input air <span class="sc">$</span> exposure <span class="sc">$</span> smoking <span class="sc">$</span> level <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb14-3"><a></a>datalines;</span>
<span id="cb14-4"><a></a>low no non <span class="dv">1</span> <span class="dv">158</span> low no non <span class="dv">2</span> <span class="dv">9</span></span>
<span id="cb14-5"><a></a>low no ex <span class="dv">1</span> <span class="dv">167</span> low no ex <span class="dv">2</span> <span class="dv">19</span></span>
<span id="cb14-6"><a></a>low no cur <span class="dv">1</span> <span class="dv">307</span> low no cur <span class="dv">2</span> <span class="dv">102</span></span>
<span id="cb14-7"><a></a>low yes non <span class="dv">1</span> <span class="dv">26</span> low yes non <span class="dv">2</span> <span class="dv">5</span></span>
<span id="cb14-8"><a></a>low yes ex <span class="dv">1</span> <span class="dv">38</span> low yes ex <span class="dv">2</span> <span class="dv">12</span></span>
<span id="cb14-9"><a></a>low yes cur <span class="dv">1</span> <span class="dv">94</span> low yes cur <span class="dv">2</span> <span class="dv">48</span></span>
<span id="cb14-10"><a></a>high no non <span class="dv">1</span> <span class="dv">94</span> high no non <span class="dv">2</span> <span class="dv">7</span></span>
<span id="cb14-11"><a></a>high no ex <span class="dv">1</span> <span class="dv">67</span> high no ex <span class="dv">2</span> <span class="dv">8</span></span>
<span id="cb14-12"><a></a>high no cur <span class="dv">1</span> <span class="dv">184</span> high no cur <span class="dv">2</span> <span class="dv">65</span></span>
<span id="cb14-13"><a></a>high yes non <span class="dv">1</span> <span class="dv">32</span> high yes non <span class="dv">2</span> <span class="dv">3</span></span>
<span id="cb14-14"><a></a>high yes ex <span class="dv">1</span> <span class="dv">39</span> high yes ex <span class="dv">2</span> <span class="dv">11</span></span>
<span id="cb14-15"><a></a>high yes cur <span class="dv">1</span> <span class="dv">77</span> high yes cur <span class="dv">2</span> <span class="dv">48</span></span>
<span id="cb14-16"><a></a>low no non <span class="dv">3</span> <span class="dv">5</span> low no non <span class="dv">4</span> <span class="dv">0</span></span>
<span id="cb14-17"><a></a>low no ex <span class="dv">3</span> <span class="dv">5</span> low no ex <span class="dv">4</span> <span class="dv">3</span></span>
<span id="cb14-18"><a></a>low no cur <span class="dv">3</span> <span class="dv">83</span> low no cur <span class="dv">4</span> <span class="dv">68</span></span>
<span id="cb14-19"><a></a>low yes non <span class="dv">3</span> <span class="dv">5</span> low yes non <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb14-20"><a></a>low yes ex <span class="dv">3</span> <span class="dv">4</span> low yes ex <span class="dv">4</span> <span class="dv">4</span></span>
<span id="cb14-21"><a></a>low yes cur <span class="dv">3</span> <span class="dv">46</span> low yes cur <span class="dv">4</span> <span class="dv">60</span></span>
<span id="cb14-22"><a></a>high no non <span class="dv">3</span> <span class="dv">5</span> high no non <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb14-23"><a></a>high no ex <span class="dv">3</span> <span class="dv">4</span> high no ex <span class="dv">4</span> <span class="dv">3</span></span>
<span id="cb14-24"><a></a>high no cur <span class="dv">3</span> <span class="dv">33</span> high no cur <span class="dv">4</span> <span class="dv">36</span></span>
<span id="cb14-25"><a></a>high yes non <span class="dv">3</span> <span class="dv">6</span> high yes non <span class="dv">4</span> <span class="dv">1</span></span>
<span id="cb14-26"><a></a>high yes ex <span class="dv">3</span> <span class="dv">4</span> high yes ex <span class="dv">4</span> <span class="dv">2</span></span>
<span id="cb14-27"><a></a>high yes cur <span class="dv">3</span> <span class="dv">39</span> high yes cur <span class="dv">4</span> <span class="dv">51</span></span>
<span id="cb14-28"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A <code>csv</code> file is uploaded on Canvas as <code>air_pollution.csv</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,089
Columns: 4
$ Air      &lt;fct&gt; high, high, high, high, high, high, high, high, high, high, h…
$ Exposure &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, y…
$ Smoking  &lt;fct&gt; cur, cur, cur, cur, cur, cur, cur, cur, cur, cur, cur, cur, c…
$ Level    &lt;ord&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="slide level2">
<h2>Exercise</h2>
<p>Researchers collected information on subjects’ exposure to general air pollution, exposure to pollution in their jobs, and whether they smoked. The response measured was chronic respiratory disease status. Subjects were assigned to one of four possible categories.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">SAS Code</a></li><li><a href="#tabset-4-2">R Code</a></li><li><a href="#tabset-4-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>proc logistic data<span class="ot">=</span>respire order<span class="ot">=</span>data plots<span class="ot">=</span><span class="fu">effect</span>(polybar <span class="at">x=</span>air<span class="sc">*</span>exposure<span class="sc">*</span>smoking);; </span>
<span id="cb16-2"><a></a>freq count;</span>
<span id="cb16-3"><a></a>class air exposure smoking <span class="sc">/</span> param<span class="ot">=</span>reference;</span>
<span id="cb16-4"><a></a>model level <span class="ot">=</span> air exposure smoking air<span class="sc">*</span>exposure exposure<span class="sc">*</span>smoking air<span class="sc">*</span>smoking air<span class="sc">*</span>exposure<span class="sc">*</span>smoking<span class="sc">/</span> selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">3</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb16-5"><a></a>estimate <span class="st">"odds between I+II+III vs. IV for current vs. ex smokers"</span> smoking <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">/</span>exp cl category<span class="ot">=</span><span class="st">"3"</span>;</span>
<span id="cb16-6"><a></a>estimate <span class="st">"probability of at most III level for ex smoker, high air pollution, job exposure"</span> intercept <span class="dv">1</span> air <span class="dv">1</span> smoking <span class="dv">0</span> <span class="dv">1</span><span class="sc">/</span>ilink cl category<span class="ot">=</span><span class="st">'3'</span>;</span>
<span id="cb16-7"><a></a>estimate <span class="st">"probability of at most II level for ex smoker, high air pollution, job exposure"</span> intercept <span class="dv">1</span> air <span class="dv">1</span> smoking <span class="dv">0</span> <span class="dv">1</span><span class="sc">/</span>ilink cl category<span class="ot">=</span><span class="st">'2'</span>; </span>
<span id="cb16-8"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-4-2">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = Level ~ Air + Exposure + Smoking, data = air_pollution, 
    Hess = TRUE)

Coefficients:
               Value Std. Error  t value
Airlow       0.03929    0.09384   0.4187
Exposureyes  0.86476    0.09576   9.0302
Smokingex   -1.45268    0.13725 -10.5842
Smokingnon  -1.85271    0.16481 -11.2416

Intercepts:
    Value    Std. Error t value 
1|2   0.2750   0.0880     3.1256
2|3   1.1562   0.0924    12.5133
3|4   2.0804   0.1044    19.9318

Residual Deviance: 4178.511 
AIC: 4192.511 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II tests)

Response: Level
         LR Chisq Df Pr(&gt;Chisq)    
Air         0.175  1     0.6753    
Exposure   81.308  1     &lt;2e-16 ***
Smoking   255.541  2     &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tests for Proportional Odds
polr(formula = Level ~ Air + Exposure + Smoking, data = air_pollution, 
    Hess = TRUE)

             b[polr]    b[&gt;1]    b[&gt;2]    b[&gt;3] Chisquare df Pr(&gt;Chisq)  
Overall                                             10.66  8      0.222  
Airlow       0.03929  0.00592  0.10350  0.02952      1.39  2      0.499  
Exposureyes  0.86476  0.84954  0.85999  0.87715      0.04  2      0.981  
Smokingex   -1.45268 -1.39976 -1.71927 -1.76946      3.61  2      0.165  
Smokingnon  -1.85271 -1.83705 -1.75516 -3.02210      5.53  2      0.063 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>cut = 1|2:
 Air  Exposure Smoking cumprob      SE  df asymp.LCL asymp.UCL
 high no       cur       0.568 0.02160 Inf     0.526     0.611
 low  no       cur       0.559 0.01790 Inf     0.524     0.594
 high yes      cur       0.357 0.02200 Inf     0.313     0.400
 low  yes      cur       0.348 0.02140 Inf     0.306     0.390
 high no       ex        0.849 0.01880 Inf     0.812     0.886
 low  no       ex        0.844 0.01780 Inf     0.809     0.879
 high yes      ex        0.703 0.03090 Inf     0.643     0.764
 low  yes      ex        0.695 0.03060 Inf     0.635     0.755
 high no       non       0.894 0.01610 Inf     0.862     0.925
 low  no       non       0.890 0.01600 Inf     0.858     0.921
 high yes      non       0.780 0.03000 Inf     0.721     0.838
 low  yes      non       0.773 0.03070 Inf     0.713     0.833

cut = 2|3:
 Air  Exposure Smoking cumprob      SE  df asymp.LCL asymp.UCL
 high no       cur       0.761 0.01680 Inf     0.728     0.794
 low  no       cur       0.753 0.01440 Inf     0.725     0.782
 high yes      cur       0.572 0.02350 Inf     0.526     0.618
 low  yes      cur       0.563 0.02310 Inf     0.517     0.608
 high no       ex        0.931 0.00978 Inf     0.912     0.951
 low  no       ex        0.929 0.00939 Inf     0.910     0.947
 high yes      ex        0.851 0.01920 Inf     0.814     0.889
 low  yes      ex        0.846 0.01930 Inf     0.808     0.884
 high no       non       0.953 0.00784 Inf     0.938     0.968
 low  no       non       0.951 0.00783 Inf     0.936     0.967
 high yes      non       0.895 0.01670 Inf     0.862     0.928
 low  yes      non       0.891 0.01720 Inf     0.858     0.925

cut = 3|4:
 Air  Exposure Smoking cumprob      SE  df asymp.LCL asymp.UCL
 high no       cur       0.889 0.01030 Inf     0.869     0.909
 low  no       cur       0.885 0.00923 Inf     0.867     0.903
 high yes      cur       0.771 0.01830 Inf     0.735     0.807
 low  yes      cur       0.764 0.01830 Inf     0.728     0.800
 high no       ex        0.972 0.00450 Inf     0.963     0.980
 low  no       ex        0.971 0.00436 Inf     0.962     0.979
 high yes      ex        0.935 0.00965 Inf     0.916     0.954
 low  yes      ex        0.933 0.00976 Inf     0.914     0.952
 high no       non       0.981 0.00346 Inf     0.974     0.988
 low  no       non       0.980 0.00347 Inf     0.973     0.987
 high yes      non       0.956 0.00782 Inf     0.940     0.971
 low  yes      non       0.954 0.00809 Inf     0.938     0.970

Confidence level used: 0.95 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Level = 1:
 Air  Exposure Smoking   prob      SE  df asymp.LCL asymp.UCL
 high no       cur     0.5683 0.02160 Inf    0.5260    0.6106
 low  no       cur     0.5587 0.01790 Inf    0.5236    0.5937
 high yes      cur     0.3567 0.02200 Inf    0.3135    0.3999
 low  yes      cur     0.3477 0.02140 Inf    0.3057    0.3898
 high no       ex      0.8491 0.01880 Inf    0.8123    0.8860
 low  no       ex      0.8440 0.01780 Inf    0.8091    0.8790
 high yes      ex      0.7033 0.03090 Inf    0.6428    0.7638
 low  yes      ex      0.6950 0.03060 Inf    0.6350    0.7551
 high no       non     0.8936 0.01610 Inf    0.8620    0.9251
 low  no       non     0.8898 0.01600 Inf    0.8585    0.9211
 high yes      non     0.7795 0.03000 Inf    0.7207    0.8383
 low  yes      non     0.7727 0.03070 Inf    0.7125    0.8329

Level = 2:
 Air  Exposure Smoking   prob      SE  df asymp.LCL asymp.UCL
 high no       cur     0.1923 0.01060 Inf    0.1716    0.2130
 low  no       cur     0.1948 0.01020 Inf    0.1749    0.2147
 high yes      cur     0.2157 0.01070 Inf    0.1947    0.2366
 low  yes      cur     0.2150 0.01070 Inf    0.1940    0.2360
 high no       ex      0.0823 0.00987 Inf    0.0630    0.1017
 low  no       ex      0.0849 0.00940 Inf    0.0664    0.1033
 high yes      ex      0.1479 0.01370 Inf    0.1210    0.1749
 low  yes      ex      0.1512 0.01360 Inf    0.1245    0.1778
 high no       non     0.0594 0.00875 Inf    0.0423    0.0766
 low  no       non     0.0614 0.00868 Inf    0.0444    0.0784
 high yes      non     0.1156 0.01450 Inf    0.0872    0.1439
 low  yes      non     0.1187 0.01470 Inf    0.0899    0.1475

Level = 3:
 Air  Exposure Smoking   prob      SE  df asymp.LCL asymp.UCL
 high no       cur     0.1283 0.00992 Inf    0.1089    0.1478
 low  no       cur     0.1316 0.00919 Inf    0.1136    0.1496
 high yes      cur     0.1989 0.01280 Inf    0.1738    0.2240
 low  yes      cur     0.2016 0.01280 Inf    0.1764    0.2267
 high no       ex      0.0402 0.00579 Inf    0.0288    0.0515
 low  no       ex      0.0416 0.00559 Inf    0.0307    0.0526
 high yes      ex      0.0839 0.01070 Inf    0.0629    0.1050
 low  yes      ex      0.0865 0.01080 Inf    0.0654    0.1077
 high no       non     0.0278 0.00468 Inf    0.0186    0.0370
 low  no       non     0.0289 0.00468 Inf    0.0197    0.0380
 high yes      non     0.0604 0.00957 Inf    0.0417    0.0792
 low  yes      non     0.0625 0.00985 Inf    0.0432    0.0818

Level = 4:
 Air  Exposure Smoking   prob      SE  df asymp.LCL asymp.UCL
 high no       cur     0.1110 0.01030 Inf    0.0908    0.1312
 low  no       cur     0.1150 0.00923 Inf    0.0969    0.1330
 high yes      cur     0.2287 0.01830 Inf    0.1928    0.2646
 low  yes      cur     0.2357 0.01830 Inf    0.1998    0.2716
 high no       ex      0.0284 0.00450 Inf    0.0196    0.0372
 low  no       ex      0.0295 0.00436 Inf    0.0209    0.0380
 high yes      ex      0.0649 0.00965 Inf    0.0459    0.0838
 low  yes      ex      0.0673 0.00976 Inf    0.0482    0.0864
 high no       non     0.0192 0.00346 Inf    0.0124    0.0260
 low  no       non     0.0200 0.00347 Inf    0.0132    0.0268
 high yes      non     0.0444 0.00782 Inf    0.0291    0.0598
 low  yes      non     0.0461 0.00809 Inf    0.0303    0.0620

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>To calculate the odds ratio, we can use <code>contrast()</code> but we have to manually exponentiate the confidence limits.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    contrast  estimate         SE  df  asymp.LCL asymp.UCL   z.ratio   p.value
1 low - high 0.0392934 0.09384313 Inf -0.1446358 0.2232226 0.4187136 0.6754255
        OR    OR.LCL   OR.UCL
1 1.040076 0.8653374 1.250099</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  contrast  estimate         SE  df asymp.LCL asymp.UCL  z.ratio      p.value
1 yes - no 0.8647616 0.09576341 Inf 0.6770688  1.052454 9.030189 1.713763e-19
       OR OR.LCL   OR.UCL
1 2.37444 1.9681 2.864674</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   contrast  estimate        SE  df   asymp.LCL asymp.UCL   z.ratio
1  cur - ex 1.4526828 0.1372496 Inf  1.13101079 1.7743549 10.584238
2 cur - non 1.8527107 0.1648078 Inf  1.46645064 2.2389708 11.241647
3  ex - non 0.4000279 0.2007087 Inf -0.07037313 0.8704288  1.993077
       p.value       OR   OR.LCL   OR.UCL
1 2.786660e-14 4.274567 3.098787 5.896476
2 5.329071e-15 6.377082 4.333826 9.383668
3 1.138789e-01 1.491866 0.932046 2.387935</code></pre>
</div>
</div>
</div>
<div id="tabset-4-3">
<p>There is no evidence of an air pollution effect (<span class="math inline">\(\chi^2 = 0.18, p=0.68\)</span>). There is evidence of a strong association between exposure (<span class="math inline">\(\chi^2 = 82.1, p=&lt;0.001\)</span>) and smoking history (<span class="math inline">\(\chi^2 = 209.9, p&lt;0.001\)</span>).</p>
<p>The odds of being assigned to Response Level III and lower for current smokers is 0.23 times the odds for ex-smokers. The odds of being assigned to Response Level 4 for current smokers is 4.27 times the odds for ex-smokers.</p>
<p>The probability of receiving a response level III and below for an ex smoker, high air pollution, and with job exposure is 0.9351. The probability of receiving a response level II and below for an ex smoker, high air pollution, and with job exposure is 0.8512. Hence, the estimated probability of receiving a response level III is 0.0839 .</p>
</div>
</div>
</div>
</section>
<section id="partial-proportional-odds-model" class="slide level2">
<h2>Partial Proportional Odds Model</h2>
<p>Sometimes, the <span class="math inline">\(\beta_k=\beta\)</span> assumption does not hold for all explanatory variables, especially if some levels disproportionately affect the odds of success.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>This assumption can be tested using the score test for the proportional odds assumption provided by the <code>LOGISTIC</code> procedure.</p>
</div>
</div>
</div>
<p>To address this, we specify unequal slopes for the explanatory variables that violate the proportional odds assumption.</p>
<p><span class="math display">\[
logit(\theta_{hik}) = \alpha_k + x'_{hi}\beta_k + x'_{h'i'} \gamma
\]</span></p>
<p>where <span class="math inline">\(x'_{hi}\)</span> includes the explanatory variables with unequal slopes <span class="math inline">\(\beta_k\)</span> and <span class="math inline">\(x'_{h'i'}\)</span> includes the explanatory variables with equal slopes <span class="math inline">\(\gamma\)</span>. This model is called the <strong>partial proportional odds model</strong>.</p>
</section>
<section id="partial-proportional-odds-model-in-sas" class="slide level2">
<h2>Partial Proportional Odds Model in SAS</h2>
<ul>
<li>If the score test for the proportional odds assumption is significant at the 0.10 level, we might need to use a partial proportional odds model.</li>
<li>We can specify the model to have unequal slopes using the <code>UNEQUALSLOPES</code> option in the MODEL statement. <code>UNEQUALSLOPES=X</code> specifies that only the explanatory variable X has unequal slopes</li>
<li>Testing for unequal slopes can be done using the <code>TEST</code> statement
<ul>
<li><code>LABEL</code>: TEST statements effectively labels the test.</li>
<li>If the test yields a significant result, there is sufficient evidence for unequal slopes for that explanatory variable.</li>
<li>If the test is not significant, we can assume the proportional odds model holds.</li>
</ul></li>
</ul>
</section>
<section id="partial-proportional-odds-model-in-r" class="slide level2">
<h2>Partial Proportional Odds Model in <code>R</code></h2>
<p>If the score test for the proportional odds assumption led to the rejection of the null hypothesis at the 0.10 level, we might need to use a partial proportional odds model.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The <code>clm()</code> package in the <code>ordinal</code> package in <code>R</code> can be used to perform partial proportional odds model. Suppose we have two predictors, <code>x1</code> and <code>x2</code>, one of which did not satisfy the proportional odds model.</p>
<p>It can also be used to estimate proportional odds models.</p>
</div>
</div>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p>The table contains data from a study by a bicycling clothing manufacturer who wanted to assess their test glove. It was designed to combat the hand problems experienced by cyclists dealing with carpal tunnel syndrome. Cyclists wore either the company’s standard gel glove or the new test glove for a week’s worth of their standard rides. Then they reported whether they experienced major, moderate, or no relief from their usual symptoms (numbness and nerve pain) on the bike.</p>
<div class="panel-tabset">
<ul id="tabset-5" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-5-1">Questions</a></li><li><a href="#tabset-5-2">Data</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1">
<ul>
<li>Assume an unequal slopes, main effect model and test for the equality of slopes for glove and gender.</li>
<li>Perform logistic regression and interpret the results.</li>
</ul>
</div>
<div id="tabset-5-2">
<p><img data-src="img/cycling_C9.png" style="width:200.0%"></p>
</div>
</div>
</div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<p>The table contains data from a study by a bicycling clothing manufacturer who wanted to assess their test glove. It was designed to combat the hand problems experienced by cyclists dealing with carpal tunnel syndrome. Cyclists wore either the company’s standard gel glove or the new test glove for a week’s worth of their standard rides. Then they reported whether they experienced major, moderate, or no relief from their usual symptoms (numbness and nerve pain) on the bike.</p>
<div class="panel-tabset">
<ul id="tabset-6" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-6-1">SAS Code</a></li><li><a href="#tabset-6-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-27"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-27-1"><a href="#annotated-cell-27-1"></a>proc logistic order<span class="ot">=</span>data data<span class="ot">=</span>wrist;</span>
<span id="annotated-cell-27-2"><a href="#annotated-cell-27-2"></a>freq count;</span>
<span id="annotated-cell-27-3"><a href="#annotated-cell-27-3"></a>class glove gender <span class="sc">/</span> param<span class="ot">=</span>reference order<span class="ot">=</span>data;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-27-4" class="code-annotation-target"><a href="#annotated-cell-27-4"></a>model relief<span class="ot">=</span> glove gender <span class="sc">/</span> scale<span class="ot">=</span>none aggregate unequalslopes;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-27-5" class="code-annotation-target"><a href="#annotated-cell-27-5"></a>pogender<span class="sc">:</span> test genderfemale_major<span class="ot">=</span>genderfemale_moderate;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-27-6" class="code-annotation-target"><a href="#annotated-cell-27-6"></a>poglove<span class="sc">:</span> test glovetest_major<span class="ot">=</span>glovetest_moderate;</span>
<span id="annotated-cell-27-7"><a href="#annotated-cell-27-7"></a>run;</span>
<span id="annotated-cell-27-8"><a href="#annotated-cell-27-8"></a></span>
<span id="annotated-cell-27-9"><a href="#annotated-cell-27-9"></a>proc logistic order<span class="ot">=</span>data data<span class="ot">=</span>wrist;</span>
<span id="annotated-cell-27-10"><a href="#annotated-cell-27-10"></a>freq count;</span>
<span id="annotated-cell-27-11"><a href="#annotated-cell-27-11"></a>class glove gender <span class="sc">/</span> param<span class="ot">=</span>reference order<span class="ot">=</span>data;</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-27-12" class="code-annotation-target"><a href="#annotated-cell-27-12"></a>model relief<span class="ot">=</span> glove gender <span class="sc">/</span> scale<span class="ot">=</span>none aggregate unequalslopes<span class="ot">=</span>glove;</span>
<span id="annotated-cell-27-13"><a href="#annotated-cell-27-13"></a>run;</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-27" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="4" data-code-annotation="1"><code>unequal slopes</code> tells SAS to provide unequal slopes for each explanatory level at all response levels.</span>
</dd>
<dt data-target-cell="annotated-cell-27" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="5" data-code-annotation="2"><code>pogender</code> is the label for testing whether the slopes should be the same for different response levels for the gender explanatory variable</span>
</dd>
<dt data-target-cell="annotated-cell-27" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="6" data-code-annotation="3"><code>poglove</code> is the label for testing whether the slopes should be the same for different response levels for the glove explanatory variable</span>
</dd>
<dt data-target-cell="annotated-cell-27" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="12" data-code-annotation="4">Only assumes unequal slopes for glove, but proportional odds assumption holds for gender.</span>
</dd>
</dl>
</div>
<div id="tabset-6-2">
<p>Using a partial proportional odds model, there is a significant effect of the type of glove and gender. the odds of experiencing major relief for females is 2.27 (95% CI: 1.10, 4.66) times that of males. The odds of major relief when using the test glove is 1.4 (0.60, 3.21) times that of gel. Additionally, the odds of moderate relief when using the test glove is 2.91 (1.33, 6.36) times that of gel.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="slide level2">
<h2>Exercise</h2>
<p>Consider the arthritis example discussed earlier. Test the hypothesis of equal slopes for both sex and treatment.</p>
</section>
<section id="exercise-3" class="slide level2">
<h2>Exercise</h2>
<p>Consider the arthritis example discussed earlier. Test the hypothesis of equal slopes for both sex and treatment.</p>
<div class="panel-tabset">
<ul id="tabset-7" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-7-1">SAS Code</a></li><li><a href="#tabset-7-2">R Code</a></li><li><a href="#tabset-7-3">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>proc logistic data<span class="ot">=</span>arthritis order<span class="ot">=</span>data plots<span class="ot">=</span><span class="fu">effect</span>(polybar <span class="at">x=</span>treatment<span class="sc">*</span>sex);; </span>
<span id="cb25-2"><a></a>freq count;</span>
<span id="cb25-3"><a></a>class treatment sex <span class="sc">/</span> param<span class="ot">=</span>reference;</span>
<span id="cb25-4"><a></a>model improve <span class="ot">=</span> sex treatment <span class="sc">/</span> unequalslopes scale<span class="ot">=</span>none aggregate;</span>
<span id="cb25-5"><a></a>equal_sex<span class="sc">:</span> test sexfemale_marked<span class="ot">=</span>sexfemale_some;</span>
<span id="cb25-6"><a></a>equal_treatment<span class="sc">:</span> test treatmentactive_marked<span class="ot">=</span>treatmentactive_some;</span>
<span id="cb25-7"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-7-2">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
     formula:          nominal:         link: threshold:
mod3 Improvement ~ Sex ~Treatment       logit flexible  
mod1 Improvement ~ 1   ~Sex + Treatment logit flexible  

     no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)
mod3      5 159.87 -74.936                      
mod1      6 160.56 -74.280  1.3116  1     0.2521</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
     formula:                nominal:         link: threshold:
mod4 Improvement ~ Treatment ~Sex             logit flexible  
mod1 Improvement ~ 1         ~Sex + Treatment logit flexible  

     no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)
mod4      5 158.59 -74.297                      
mod1      6 160.56 -74.280  0.0331  1     0.8556</code></pre>
</div>
</div>
</div>
<div id="tabset-7-3">
<p>We suppose the slopes are unequal, then test whether there is evidence against the null hypothesis of equal slopes using <code>test</code>.</p>
<p>There is insufficient evidence to claim that the <span class="math inline">\(\beta\)</span> for sex (<span class="math inline">\(\chi^2 = 1.35, p=0.25\)</span>) and treatment (<span class="math inline">\(\chi^2 = 0.03, p=0.86\)</span>) are different across the different outcome levels.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="nominal-response-variables" class="title-slide slide level1 center">
<h1>Nominal Response Variables</h1>

</section>
<section id="generalized-logits-model" class="slide level2">
<h2>Generalized Logits Model</h2>
<p>When the response variables are nominal, the concept of cumulative probabilities is less applicable. The <strong>generalized logits model</strong> is used for nominal polytomous response variables.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Generalized Logit Model</strong></p>
</div>
<div class="callout-content">
<p>The logit function is the logarithm of the ratio of the probability of the level of interest, <span class="math inline">\(\pi_j\)</span> and the <em>reference</em> category <span class="math inline">\(\pi_r\)</span>.</p>
<p><span class="math display">\[
logit \theta_j = \log \left(\frac{\pi_j}{\pi_r}\right) = \alpha_j + \sum_g \beta_{jg} x_g
\]</span> where <span class="math inline">\(g\)</span> comprises of ALL explanatory variables</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Reference level</strong></p>
</div>
<div class="callout-content">
<p>For the reference level, <span class="math inline">\(\alpha_r = 0, \beta_{rg}=0\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="generalized-logits-model-1" class="slide level2">
<h2>Generalized Logits Model</h2>
<p>The resulting expression for <span class="math inline">\(\pi_j\)</span> can be written as:</p>
<p><span class="math display">\[
\pi_j = \frac{\exp[\alpha_j + \sum_g \beta_{jg}x_g]}{\sum_{k=1}^r \exp[\alpha_k + \sum_g \beta_{kg}x_g]}
\]</span></p>
<p>with the constraint <span class="math inline">\(\alpha_r=0, \beta_{rg} = 0\)</span>.</p>
</section>
<section id="generalized-logits-model-sas" class="slide level2">
<h2>Generalized Logits Model: SAS</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Implementing generalized logit models in SAS</strong></p>
</div>
<div class="callout-content">
<p>The <code>LOGISTIC</code> procedure will model the logit models for all levels simultaneously. If there are <span class="math inline">\(r\)</span> levels of the response variable, there will be <span class="math inline">\((r-1)\)</span> degrees of freedom for a single logit model.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Link function</strong></p>
</div>
<div class="callout-content">
<p>SAS does not know whether your response variable is ordinal or nominal. The generalized logits model can be specified using <code>link=glogit</code> in the <code>model</code> statement.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Syntax</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Unless specified, the last variable level based on the specified order in the <code>class</code> statement is set as the reference level.</li>
<li>Syntax is the same as the PO model, but the assumptions are different.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<p>Schoolchildren in experimental learning settings were surveyed to determine which learning style they preferred. Investigators were interested in whether response was associated with school and their program, which was either a standard school day or also included after-hours care.</p>
<div class="panel-tabset">
<ul id="tabset-8" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-8-1">Question</a></li><li><a href="#tabset-8-2">SAS Data Set</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1">
<p>Use logistic regression to test for program and school effects and calculate the relevant odds ratios.</p>
</div>
<div id="tabset-8-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>data school;</span>
<span id="cb28-2"><a></a>input school program <span class="sc">$</span> style <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb28-3"><a></a>datalines;</span>
<span id="cb28-4"><a></a><span class="dv">1</span> regular self <span class="dv">10</span> <span class="dv">1</span> regular team <span class="dv">17</span> <span class="dv">1</span> regular class <span class="dv">26</span></span>
<span id="cb28-5"><a></a><span class="dv">1</span> after self <span class="dv">5</span> <span class="dv">1</span> after team <span class="dv">12</span> <span class="dv">1</span> after class <span class="dv">50</span></span>
<span id="cb28-6"><a></a><span class="dv">2</span> regular self <span class="dv">21</span> <span class="dv">2</span> regular team <span class="dv">17</span> <span class="dv">2</span> regular class <span class="dv">26</span></span>
<span id="cb28-7"><a></a><span class="dv">2</span> after self <span class="dv">16</span> <span class="dv">2</span> after team <span class="dv">12</span> <span class="dv">2</span> after class <span class="dv">36</span></span>
<span id="cb28-8"><a></a><span class="dv">3</span> regular self <span class="dv">15</span> <span class="dv">3</span> regular team <span class="dv">15</span> <span class="dv">3</span> regular class <span class="dv">16</span></span>
<span id="cb28-9"><a></a><span class="dv">3</span> after self <span class="dv">12</span> <span class="dv">3</span> after team <span class="dv">12</span> <span class="dv">3</span> after class <span class="dv">20</span></span>
<span id="cb28-10"><a></a>;</span>
<span id="cb28-11"><a></a></span>
<span id="cb28-12"><a></a>proc freq data<span class="ot">=</span>school order<span class="ot">=</span>data;</span>
<span id="cb28-13"><a></a>weight count;</span>
<span id="cb28-14"><a></a>tables school<span class="sc">*</span>program<span class="sc">*</span>style<span class="sc">/</span> nocol norow nopct;</span>
<span id="cb28-15"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<p>Schoolchildren in experimental learning settings were surveyed to determine which learning style they preferred. Investigators were interested in whether response was associated with school and their program, which was either a standard school day or also included after-hours care. Use logistic regression to test for program and school effects and calculate the relevant odds ratios.</p>
<div class="panel-tabset">
<ul id="tabset-9" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-9-1">SAS Code</a></li><li><a href="#tabset-9-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>proc logistic data<span class="ot">=</span>school order<span class="ot">=</span>data;</span>
<span id="cb29-2"><a></a>freq count;</span>
<span id="cb29-3"><a></a>class <span class="fu">school</span> (<span class="at">ref=</span>first) <span class="fu">program</span> (<span class="at">ref=</span>last) <span class="sc">/</span> param<span class="ot">=</span>ref;</span>
<span id="cb29-4"><a></a>model style<span class="ot">=</span> program school school<span class="sc">*</span>program <span class="sc">/</span> link<span class="ot">=</span>glogit selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">2</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb29-5"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-9-2">
<p>There is sufficient evidence of a program (<span class="math inline">\(\chi^2 = 10.9, p=0.004\)</span>) and school (<span class="math inline">\(\chi^2=14.8, p=0.005\)</span>).</p>
<p>The odds of preferring self-directed learning for those assigned to after-hours care is 0.47 (0.27-0.82) times that of those who assigned to regular class hours. The odds of students from school 2 preferring self-directed learning is 2.95 (1.48-5.91) times that of students from school 1. Similarly, the odds of students from school 3 preferring self-directed learning is 3.72 (1.76-7.90) times that of students from school 1.</p>
<p>The odds of preferring team-based learning for those assigned to after-hours care is 0.48 (0.27-0.82) times that of those who assigned to regular class hours. The odds of students from school 2 preferring self-directed learning is 1.20 (0.64-2.23) times that of students from school 1. Similarly, the odds of students from school 3 preferring self-directed learning is 1.93 (0.99-3.75) times that of students from school 1.</p>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="slide level2">
<h2>Exercise</h2>
<p>The data set “firecracker” shows data of injuries due to firecrackers from three community health centers in rural Philippines. The age groups were coded as A: &lt;25 years of age, B: ≥25 years of age. Use a generalized logit main effect model to determine whether there is a significant effect of age and clinic in the occurrence of face and finger injury compared to other parts of the body.</p>
<div class="panel-tabset">
<ul id="tabset-10" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-10-1">Question</a></li><li><a href="#tabset-10-2">Data</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1">
<p>Use the estimate statement to test and estimate the odds ratio between clinics 1 and 2 for fingers vs.&nbsp;other injury and face vs.&nbsp;other injury.</p>
</div>
<div id="tabset-10-2">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a>data firecracker;</span>
<span id="cb30-2"><a></a>input clinic <span class="sc">$</span> agegroup <span class="sc">$</span> injury <span class="sc">$</span> count;</span>
<span id="cb30-3"><a></a>datalines;</span>
<span id="cb30-4"><a></a><span class="dv">1</span> A Fingers <span class="dv">25</span></span>
<span id="cb30-5"><a></a><span class="dv">1</span> A Face <span class="dv">18</span></span>
<span id="cb30-6"><a></a><span class="dv">1</span> A Other <span class="dv">5</span></span>
<span id="cb30-7"><a></a><span class="dv">1</span> B Fingers <span class="dv">13</span></span>
<span id="cb30-8"><a></a><span class="dv">1</span> B Face <span class="dv">5</span></span>
<span id="cb30-9"><a></a><span class="dv">1</span> B Other <span class="dv">3</span></span>
<span id="cb30-10"><a></a><span class="dv">2</span> A Fingers <span class="dv">42</span></span>
<span id="cb30-11"><a></a><span class="dv">2</span> A Face <span class="dv">7</span></span>
<span id="cb30-12"><a></a><span class="dv">2</span> A Other <span class="dv">12</span></span>
<span id="cb30-13"><a></a><span class="dv">2</span> B Fingers <span class="dv">23</span></span>
<span id="cb30-14"><a></a><span class="dv">2</span> B Face <span class="dv">5</span></span>
<span id="cb30-15"><a></a><span class="dv">2</span> B Other <span class="dv">5</span></span>
<span id="cb30-16"><a></a><span class="dv">3</span> A Fingers <span class="dv">10</span></span>
<span id="cb30-17"><a></a><span class="dv">3</span> A Face <span class="dv">4</span></span>
<span id="cb30-18"><a></a><span class="dv">3</span> A Other <span class="dv">4</span></span>
<span id="cb30-19"><a></a><span class="dv">3</span> B Fingers <span class="dv">9</span></span>
<span id="cb30-20"><a></a><span class="dv">3</span> B Face <span class="dv">7</span></span>
<span id="cb30-21"><a></a><span class="dv">3</span> B Other <span class="dv">5</span></span>
<span id="cb30-22"><a></a>;</span>
<span id="cb30-23"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="exercise-5" class="slide level2">
<h2>Exercise</h2>
<p>The data set “firecracker” shows data of injuries due to firecrackers from three community health centers in rural Philippines. The age groups were coded as A: &lt;25 years of age, B: ≥25 years of age. Use a generalized logit main effect model to determine whether there is a significant effect of age and clinic in the occurrence of face and finger injury compared to other parts of the body.</p>
<div class="panel-tabset">
<ul id="tabset-11" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-11-1">SAS Code</a></li><li><a href="#tabset-11-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>proc logistic data<span class="ot">=</span>firecracker order<span class="ot">=</span>data;</span>
<span id="cb31-2"><a></a>freq count;</span>
<span id="cb31-3"><a></a>class clinic agegroup;</span>
<span id="cb31-4"><a></a>model injury<span class="ot">=</span> clinic agegroup clinic<span class="sc">*</span>agegroup<span class="sc">/</span>link<span class="ot">=</span>glogit selection<span class="ot">=</span>forward include<span class="ot">=</span><span class="dv">2</span> scale<span class="ot">=</span>none aggregate;</span>
<span id="cb31-5"><a></a>estimate <span class="st">"clinic 1 vs clinic 2 - face"</span> clinic <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span> exp cl category<span class="ot">=</span><span class="st">"Face"</span>;</span>
<span id="cb31-6"><a></a>estimate <span class="st">"clinic 1 vs clinic 2 - fingers"</span> clinic <span class="dv">1</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span> exp cl category<span class="ot">=</span><span class="st">"Fingers"</span>;</span>
<span id="cb31-7"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-11-2">
<p>There is a significant effect of clinic (<span class="math inline">\(\chi^2 = 11.9, p=0.02\)</span>), but no evidence of an age effect (<span class="math inline">\(\chi^2 = 0.02, p=0.99\)</span>).</p>
<p>The odds of receiving patients with face injuries in clinic 1 is 4.08 (1.37-12.2) times that of clinic 2. Meanwhile, the odds of receiving patients with finger injuries in clinic 1 is 1.25 (0.49-3.16) times that of clinic 2.</p>
</div>
</div>
</div>
</section>
<section id="exact-generalized-logits-test" class="slide level2">
<h2>Exact Generalized Logits Test</h2>
<ul>
<li>Exact methods are more appropriate for tables with small or zero counts.</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Exact Method Warning</strong></p>
</div>
<div class="callout-content">
<p>Generalized logits tests have more parameters and exact methods are typically more computationally expensive. When using exact methods, try to keep the model small for relatively small data sets.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Exact Method in SAS</strong></p>
</div>
<div class="callout-content">
<p>The <code>exact</code> statement can perform joint tests as well as calculate exact confidence intervals for odds ratios. Use the “Exact” p-value column in the “Probability” row in the exact conditional tests.</p>
</div>
</div>
</div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>The following data come from a study in which a physical therapy practice experimented with different treatment modalities in a strengthening program. The therapists rotated patients through three programs for maintenance after basic strength had been attained. The strengthening programs included free weights, resistance bands, and weight machines. The therapists are interested in whether gender and age affect choice of strengthening programs.</p>
<h3 id="data-set-1">Data Set</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a>data pt;</span>
<span id="cb32-2"><a></a>format therapy <span class="sc">$</span><span class="fl">11.</span>;</span>
<span id="cb32-3"><a></a>input gender <span class="sc">$</span> age <span class="sc">$</span> therapy <span class="sc">$</span> count <span class="sc">@</span><span class="er">@</span>;</span>
<span id="cb32-4"><a></a>datalines;</span>
<span id="cb32-5"><a></a>males adult machines <span class="dv">2</span> males senior machines <span class="dv">10</span></span>
<span id="cb32-6"><a></a>males adult freeweights <span class="dv">13</span> males senior freeweights <span class="dv">9</span></span>
<span id="cb32-7"><a></a>males adult bands <span class="dv">3</span> males senior bands <span class="dv">3</span></span>
<span id="cb32-8"><a></a>females adult machines <span class="dv">3</span> females senior machines <span class="dv">8</span></span>
<span id="cb32-9"><a></a>females adult freeweights <span class="dv">9</span> females senior freeweights <span class="dv">0</span></span>
<span id="cb32-10"><a></a>females adult bands <span class="dv">1</span> females senior bands <span class="dv">1</span></span>
<span id="cb32-11"><a></a>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>The following data come from a study in which a physical therapy practice experimented with different treatment modalities in a strengthening program. The therapists rotated patients through three programs for maintenance after basic strength had been attained. The strengthening programs included free weights, resistance bands, and weight machines. The therapists are interested in whether gender and age affect choice of strengthening programs.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Small cell counts means we need to use exact methods.</p>
</div>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-12" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-12-1">SAS Code</a></li><li><a href="#tabset-12-2">Answer</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>proc logistic data<span class="ot">=</span>pt;</span>
<span id="cb33-2"><a></a>title <span class="st">"asymptotic"</span>;</span>
<span id="cb33-3"><a></a>freq count;</span>
<span id="cb33-4"><a></a>class <span class="fu">gender</span>(<span class="at">ref=</span><span class="st">'females'</span>) <span class="fu">age</span>(<span class="at">ref=</span><span class="st">'senior'</span>) <span class="sc">/</span> param<span class="ot">=</span>ref;</span>
<span id="cb33-5"><a></a>model <span class="fu">therapy</span>(<span class="at">ref=</span><span class="st">'machines'</span>) <span class="ot">=</span> gender age <span class="sc">/</span> link<span class="ot">=</span>glogit scale<span class="ot">=</span>none aggregate;</span>
<span id="cb33-6"><a></a>run;</span>
<span id="cb33-7"><a></a></span>
<span id="cb33-8"><a></a>proc logistic data<span class="ot">=</span>pt;</span>
<span id="cb33-9"><a></a>title <span class="st">"exact"</span>;</span>
<span id="cb33-10"><a></a>freq count;</span>
<span id="cb33-11"><a></a>class <span class="fu">gender</span>(<span class="at">ref=</span><span class="st">'females'</span>) <span class="fu">age</span>(<span class="at">ref=</span><span class="st">'senior'</span>) <span class="sc">/</span> param<span class="ot">=</span>ref;</span>
<span id="cb33-12"><a></a>model <span class="fu">therapy</span>(<span class="at">ref=</span><span class="st">'machines'</span>) <span class="ot">=</span> gender age <span class="sc">/</span> link<span class="ot">=</span>glogit scale<span class="ot">=</span>none aggregate;</span>
<span id="cb33-13"><a></a>exact gender age<span class="sc">/</span>joint estimate<span class="ot">=</span>both;</span>
<span id="cb33-14"><a></a>run;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="tabset-12-2">
<p>There is a marginal effect of gender ($ p=0.099<span class="math inline">\(), but there is a significant effect of age (\)</span>^2 = 12.2, p=0.003$).</p>
<p>The odds of males preferring bands is 4.1 (0.49-59.55) times than that of females. Additionally, the odds of males preferring freeweights is 4.49 (0.93-30.2) times than that of females.</p>
<p>The odds of an adult preferring bands is 5.08 (0.60-53.2) times that of seniors. However, the odds of an adult preferring freeweights is 12.47 (2.7-84.0) times that of seniors.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Chapter 9- <a href="https://madfudolig.quarto.pub/eab770slides/">Back to home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            // Attach click handler to the DT
            const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
            for (const annoteDlNode of annoteDls) {
              annoteDlNode.addEventListener('click', (event) => {
                const clickedEl = event.target;
                if (clickedEl !== selectedAnnoteEl) {
                  unselectCodeLines();
                  const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                  if (activeEl) {
                    activeEl.classList.remove('code-annotation-active');
                  }
                  selectCodeLines(clickedEl);
                  clickedEl.classList.add('code-annotation-active');
                } else {
                  // Unselect the line
                  unselectCodeLines();
                  clickedEl.classList.remove('code-annotation-active');
                }
              });
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>