{
  "hash": "18b368599db8d191d8d0d6e5bda3002e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 5\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 5- [Back to home](https://miguelfudolig.github.io/EAB770-Slides-Website/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n    echo: true\n  pdf: \n    number-sections: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n# $s \\times r$ tables\n\n## Outline\n\n-   Association\n    -   Test for General Association\n    -   Mean Score Test\n    -   Correlation Test\n    -   Exact Tests\n-   Measures of Association\n    -   Ordinal\n    -   Nominal\n-   Observer Agreement (inter-rater reliability)\n-   Test for Ordered Differences\n\n# What if there are more than two groups outcomes?\n\n## Multiple Categorical Outcomes\n\nCommon examples include Likert Scale (Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree) responses and parts of a whole (None, Some, All).\n\n::: callout-note\nWe would need more than two columns in our contingency table to account for these other outcomes. Variables can be forced to be “binary”, but some important information can be lost.\n:::\n\n## Multiple Groups\n\nIt is also common to compare responses from multiple groups such as Race, Income Status, and Exposure levels. Dichotomizing these variables to fit into a 2x2 will also result in loss of information.\n\n# Associations in $s \\times r$ tables\n\n## $s \\times r$ tables\n\nWe now evolve the contingency table from a $2 \\times 2 \\to  s  \\times r$, where $s$ is the number of rows and $r$ is the number of columns. Both $s$ and $r$ are expected to be at least 2.\n\n![](img/sxr_C5.png)\n\n\n## General Association Statistic\n\nWhen the groups and the response variable categories can be nominally scaled, we can only test for general association.\n\n::: callout-note\n### Statistical Hypotheses\n\n-   $H_0$: there is no general association between the groups and response variables.\n-   $H_A$: there is a general association between the two variables\n:::\n\n## General Association Statistic\n\nThe randomization statistic based on Mantel-Haenszel statistics can be calculated from the Pearson chi-square statistic, $Q_P$.\n\n$$\nQ = \\left(\\frac{n-1}{n}\\right) Q_P\n$$ \n\nwhere,\n\n$$\nQ_P = \\sum_{i=1}^s\\sum_{j=1}^r \\frac{(n_{ij}-m_{ij})^2}{m_{ij}}\n$$\n\n::: callout-important\nWhen $n$ is large, $Q \\approx Q_P$. Like the Pearson chi-square, $Q$ follows a chi-square distribution with $(s-1)(r-1)$ degrees of freedom.\n:::\n\n## Mosaic Plot\n\n A mosaic plot visualizes the proportion in each cell of the contingency table.\n \n::: callout-note\nThe horizontal space is divided by sizes corresponding to the relative count of x-axis variable levels, while the vertical space is divided up according to relative sizes of the y-axis variable levels.\n:::\n\n## Mosaic Plot in `R`\n\nThe `mosaic()` function in the `vcd` package creates a mosaic plot for data frames/contingency tables. Shown below is the mosaic plot for the `UCBAdmissions` data set, which shows the aggregate data on applicants to graduate school at UC Berkeley in 1973.\n\n\n::: panel-tabset\n\n### Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcd)\nmosaic(~Admit +Dept,\n       highlighting=\"Admit\",\n       highlighting_fill=c(\"blue\",\"red\"),\n       data=UCBAdmissions)\n```\n\n::: {.cell-output-display}\n![](Chapter5_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Notes\n\n::: callout-tip\nThe `highlighting` option provides `mosaic` information about which variables need to be shaded. The `highlighting_fill` provides the colors you want to use the highlight these variables.\n:::\n\n\n:::\n\n## General Association: SAS\n\n-   In SAS, the Pearson chi-square statistic $Q_P$ is the value referred to as ‘Chi-square”\n-   Note that $Q$ is **NOT** the Mantel-Haenszel statistic in the `chisq` output in SAS.\n    -   $Q$ is the “General Association” cell in the `cmh` output.\n-   We can use the `plots` option in the `tables` statement to create a mosaic plot.\n\n``` r\nproc freq;\nweight count;\ntables a*b/cmh plots=mosaicplot; # <1>\nrun;\n```\n\n1.  `cmh` calculates the general association Cochran-Mantel-Haenszel statistic. `plots=mosaicplot` tells SAS to create a mosaic plot with $a$ and $b$.\n\n## General Association: `R`\n\nThe `CMHtest()` function provides the general association Cochram-Mantel-Haenszel statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(contingencytable)\n```\n:::\n\n\n\n## Example\n\n\nThe table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.\n\n::: panel-tabset\n\n### Questions\n\n-   What is the Pearson chi-square value?\n-   What is the randomization statistic?\n-   Is there sufficient evidence of an association between political party and neighborhood?\n-   Create a mosaic plot for this problem.\n\n\n![](img/party_C5.png)\n\n\n\n### `SAS` \n\n``` r\ndata neighbor;\nlength party $ 11 neighborhood $ 10;\ninput party $ neighborhood $ count @@;\ndatalines;\ndemocrat longview 360 democrat bayside 221\ndemocrat sheffeld 140 democrat highland 160\nrepublican longview 316 republican bayside 208\nrepublican sheffeld 97 republican highland 106\nindependent longview 160 independent bayside 200\nindependent sheffeld 311 independent highland 291\n;\n\nproc freq data=neighbor;\nweight count;\ntables party*neighborhood /\nplots=mosaicplot chisq cmh nocol nopct; #<1>\nrun;\n```\n\n1.  Included both `chisq` and `cmh` to show discrepancy.\n\n### `R` Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Party=c(\"Democrat\",\"Independent\",\"Republican\"),\n                   Neighborhood = c(\"Bayside\",\"Highland\",\"Longview\",\"Sheffield\"))\n\ndat$count <- c(221,200,208,160,291,106,360,160,316,140,311,97)\n```\n:::\n\n\n### `R` Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(count~Party+Neighborhood,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Neighborhood\nParty         Bayside Highland Longview Sheffield\n  Democrat        221      160      360       140\n  Independent     200      291      160       311\n  Republican      208      106      316        97\n```\n\n\n:::\n\n```{.r .cell-code}\nmosaic(data=dat_cc,\n       ~Party+Neighborhood,\n       highlighting=\"Party\")\n```\n\n::: {.cell-output-display}\n![](Chapter5_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\nPearson chi-square:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  dat_cc\nX-squared = 273.92, df = 6, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\nRandomization Statistic (use general association):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Party by Neighborhood \n\n                 AltHypothesis     Chisq Df       Prob\ncor        Nonzero correlation   0.81238  1 3.6742e-01\nrmeans  Row mean scores differ  13.89377  2 9.6163e-04\ncmeans  Col mean scores differ   3.15865  3 3.6781e-01\ngeneral    General association 273.81223  6 3.3158e-56\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n$Q_P$ = 273.92, $Q$ = 273.81. The corresponding p-value $p<0.001$ suggests there is an association between party affiliation and neighborhood.\n\n\n::: callout-note\n\nIn SAS, note that the Mantel-Haenszel statistic reported in the `chisq` output corresponds to the correlation statistic which doesn't make sense in this case (discussed later).\n\n:::\n\n:::\n\n## Exercise\n\nSecondary school teachers were randomly sampled from four school districts in Nevada and asked what marker color they used in grading students’ work.\n\n-   What is the Pearson chi-square statistic?\n-   What is the randomization statistic?\n-   Generate a mosaic plot for this example. Can you see a trend between the colors and/or the counties?\n-   At a significance level of 0.05, do we have sufficient evidence of a general association between the two variables?\n\n\n::: panel-tabset\n\n### Data\n\n``` r\ndata color;\ninput county $ color $ count @@;\ndatalines;\ncl blu 22 cl red 57 cl green 12 cl blk 15\nca blu 12 ca red 30 ca green 6 ca blk 15\ndo blu 17 do red 34 do green 17 do blk 10\nwa blu 5 wa red 56 wa green 7 wa blk 9\n;\nrun;\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(county=c(\"clark\",\"carson\",\"douglas\",\"washoe\"),\n                   color = c(\"blue\",\"red\",\"green\",\"black\")) \ndat$count <- c(22,12,17,5,57,30,34,56,12,6,17,7,15,15,10,9)\n\ndat_cc <- xtabs(count~county+color,data=dat)\n```\n:::\n\n\n### SAS Code\n\n``` r\n\ndata color;\ninput county $ color $ count @@;\ndatalines;\ncl blu 22 cl red 57 cl green 12 cl blk 15\nca blu 12 ca red 30 ca green 6 ca blk 15\ndo blu 17 do red 34 do green 17 do blk 10\nwa blu 5 wa red 56 wa green 7 wa blk 9\n;\nrun;\n\nproc freq data=color;\nweight count;\ntables county*color/\nplots=mosaicplot chisq cmh nocol nopct measures cl;\nrun;\n```\n\n### Answer\n\n$Q_P$= 24.36, $Q$ = 24.28, p = 0.004, which means there is strong evidence of an association between school district and marker color used for grading.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(county=c(\"clark\",\"carson\",\"douglas\",\"washoe\"),\n                   color = c(\"blue\",\"red\",\"green\",\"black\")) \ndat$count <- c(22,12,17,5,57,30,34,56,12,6,17,7,15,15,10,9)\n\ndat_cc <- xtabs(count~county+color,data=dat)\n\nmosaic(data=dat_cc,\n       ~color + county,\n       highlighting=\"color\",\n       highlighting_fill=c(\"blue\",\"red\",\"green\",\"black\"))\n```\n\n::: {.cell-output-display}\n![](Chapter5_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n## Associations Involving Ordinal Variables\n\nSuppose the column variable is ordinal such that $A_j$ is the $j^{th}$ outcome level. Since $A_J$ is ordinal, then $A_1 < A_2 < A_3 <... A_r$.\n\nTo account for ordinality, we assign a set of scores $\\mathbf{a}$ reflecting the relationship between response levels.\n\n$$\n\\mathbf{a} = \\{a_1, a_2, a_3,... a_r\\} : a_1 < a_2 < ...< a_r\n$$\n\n::: callout-note\nThe relationship can be $\\leq$ instead of $<$ as long as at least one pair is a strict inequality.\n:::\n\n## Row Mean Scores\n\nConsider the following contingency table:\n\n![](img/2xr_C4.png)\n\nWe can define a group mean for $X_1$, denoted by $\\bar{f}_1$.\n\n$$\n\\bar{f}_1 = \\sum_{j=1}^r \\frac{a_j n_{1j}}{n_{1+}}\n$$\n\n::: callout-note\nThe scores $\\bar{f}_j$ are referred to as **row mean scores**. The random variable $\\bar{f}_j$ approximately has a normal distribution when the central limit theorem is imposed. This occurs when the row sums are high.\n\nThe term $a_j$ are the assigned scores for the columns. These can be regular integral scores (0,1,2,3,...) or based on rank. Rank-based scores yield midranks for tied values and are standardized for tied values.\n:::\n\n## Mean Score Tests: Null Hypothesis\n\nThe null hypothesis for tests involving the row mean scores is $H_0$: There is no association between the row (X) and column (A) variables. \nUnder the null hypothesis, the expected value of the row mean scores, $\\mu_a$, can be calculated as:\n\n$$\n\\mu_a =  \\sum_{j=1}^r \\frac{a_j n_{+j}}{n}\n$$\n\nThe corresponding alternative hypothesis is $H_a:$ There is a location shift across the groups.\n## Mean Score Tests: Test Statistic\n\nThe test statistic is the mean score statistic $Q_S$ for an $s \\times r$ table is given by:\n\n$$\nQ_S = \\frac{(n-1)\\sum_{i=1}^sn_{i+}(f_i-\\mu_a)^2}{nv_a}\n$$\n\nwhere $v_a = \\sum_{j=1}^r(a_j-\\mu_a)^2(n_{+j}/n)$ is the variance of the row mean scores. This is consistent with an ANOVA approach in comparing means across each group.\n\n## Mean Score Tests: Sample Considerations\n\n::: callout-note\nThe $Q_S$ sample size condition is less stringent: \n\n- The row totals should be greater than 20.\n- Choose one or more cutpoints $j = (2,3,...(r-1))$, add the first through $j^{th}$ columns together and add the $(j+1)^{th}$ through $r^{th}$ columns together. If both of these sums are 5 or greater for at least one cutpoint in each row, then the sample size is adequate.\n:::\n\nIf the sample size conditions are reached, $Q_S$ approximately follows a chi-square distribution with $(s-1)$ degrees of freedom, where $s$ is the number of rows.\n\n::: callout-note\nThe mean score test uses less degrees of freedom compared to the general association test and the Pearson chi-square test.\n:::\n\n## Mean Score Tests: `SAs`\n\nIncluded in the `cmh` table as \"Row Mean Scores Differ\". \n\n::: callout-note\nUse `scores=ridit` to use standardized rank scores or `scores=modridit` to use the expected valurs of the order statistics of the uniform distribution on (0,1).\n:::\n\n## Mean Score Tests: `R`\n\nThe `CMHtest()` default output includes the `Row mean scores differ` row in the analysis. Ensure that the ordinal variable is assigned as the column variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(contingencytable,\n        cscores=\"midrank\")\n```\n:::\n\n\n\n::: callout-note\nThe Col mean scores differ functions similarly with the ordinal variable assigned as the rows.\n\nThe `cscores` argument lets `R` know what $a_j$ to use for the columns. `CMHtest` will use integers as scores, which assumes the ordinal variable is equally spaced. To use rank-based scores, we can specify `cscores=\"midrank\"`. \n:::\n\n## Example\n\nThe data shown comes from a study on headache pain relief. A new treatment was compared with the standard treatment and a placebo. Researchers measured the number of hours of substantial relief from headache pain\n\n::: panel-tabset\n### Question + Data\n\n-   Is the chi-square approximation valid for this case?\n-   What kind of scoring method is most appropriate for this data set?\n-   Make the appropriate conclusion based on the result of the mean score tests using a significance level $\\alpha=0.05$.\n\n![](img/pain_C5.png)\n\n### SAS Code\n\n``` r\ndata pain;\ninput treatment $ hours count @@;\ndatalines;\nplacebo 0 6 placebo 1 9 placebo 2 6 placebo 3 3 placebo 4 1\nstandard 0 1 standard 1 4 standard 2 6 standard 3 6 standard 4 8\ntest 0 2 test 1 5 test 2 6 test 3 8 test 4 6\n;\n\nproc freq data=pain order=data;\nweight count;\ntables treatment*hours/ cmh nocol nopct;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Treatment = c(\"Placebo\",\"Standard\",\"Test\"),\n                   Hours = 0:4)\n\ndat$Count <- c(6,1,2,9,4,5,6,6,6,3,6,8,1,8,6)\n\ndat_cc <- xtabs(Count~Treatment+Hours,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Hours\nTreatment  0 1 2 3 4\n  Placebo  6 9 6 3 1\n  Standard 1 4 6 6 8\n  Test     2 5 6 8 6\n```\n\n\n:::\n:::\n\nNow we can perform the mean score test. The integer scoring method is most appropriate because of the equal distance between the ordinal column variable values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treatment by Hours \n\n                 AltHypothesis   Chisq Df      Prob\ncor        Nonzero correlation  8.0668  1 0.0045084\nrmeans  Row mean scores differ 13.7346  2 0.0010413\ncmeans  Col mean scores differ  8.4151  4 0.0775017\ngeneral    General association 14.4030  8 0.0718470\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n-   Use column 3 (Hours = 2) as cutoff. The use of the chi-square approximation is justified!\n\n-   The integer scoring method is most appropriate.\n\n-   $Q_S$ = 13.7, df=2, p=0.001. At $\\alpha=0.05$, there is sufficient evidence to conclude that at least one treatment group is different compared to the others.\n\n::: callout-warning\nIf we used the general association test, we would end up with p=0.07 and failing to reject the null hypothesis instead.\n:::\n\n\n:::\n\n## Exercise\n\nThe table shows data from a study that investigates intent to breastfeed of women who are interested in having children. The women who participated in the study were asked if they intended to breastfeed your child up to 6 months after birth. The researchers want to know if there is an effect of the order of pregnancy on their intent to breastfeed.\n\n\n::: panel-tabset\n\n### SAS Data\n\n``` r\ndata preg;\ninput pregnancy $  outcome $ score  count @@ ;\ndatalines;\nnpnc sd 1 8 npnc d 2 22 npnc n 3 24 npnc a 4 27 npnc sa 5 15\nnpc sd 1 15 npc d 2 23 npc n 3 15 npc a 4 19 npc sa 5 9\nfp sd 1 18 fp d 2 8 fp n 3 22 fp a 4 23 fp sa 5 11\npwc sd 1 35 pwc d 2 13 pwc n 3 10 pwc a 4 9 pwc sa 5 6\n; \n```\n::: {.callout-note title=\"Variables\"}\n- npnc: not pregnant, no children \n- npc: not pregnant with children\n- fp: first pregnancy\n- pwc: pregnant with children\n- sd: strongly disagree\n- d: disagree\n- n: neutral\n- a: agree\n- sa: strongly agree\n:::\n\n\n### SAS Code\n\n``` r\nproc freq data=preg order=data;\nweight count;\ntables pregnancy*outcome / cmh nocol nopct;\nrun;\n\nproc means data=preg order=data; # <1>\nfreq count;\nclass pregnancy;\nvar score;\nrun;\n```\n\n1.  The `means` procedure is shown to display the mean scores and how they indeed differ for each pregnancy order.\n\n### R Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Pregnancy = c(\"NPNC\",\"NPC\",\"FP\",\"PWC\"),\n                   Outcome =c(\"S Disagree\",\"Disagree\",\"Neutral\",\"Agree\",\"S Agree\"))\n\ndat$Count <- c(8,15,18,35,22,23,8,13,24,15,22,10,27,19,23,9,15,9,11,6)\n\ndat_cc <- xtabs(Count~Pregnancy+Outcome,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nPregnancy S Disagree Disagree Neutral Agree S Agree\n     NPNC          8       22      24    27      15\n     NPC          15       23      15    19       9\n     FP           18        8      22    23      11\n     PWC          35       13      10     9       6\n```\n\n\n:::\n:::\n\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Pregnancy by Outcome \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 18.634  1 1.5837e-05\nrmeans  Row mean scores differ 27.200  3 5.3462e-06\ncmeans  Col mean scores differ 33.731  4 8.4615e-07\ngeneral    General association 48.794 12 2.2725e-06\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n$Q_S= 27.2$, df=3, p=5.35e-6. There is sufficient evidence of an effect of pregnancy order on intent to breastfeed.\n:::\n\n## Ordinal Row and Column Variables\n\nWhen the row variable is also ordinal, we can assign row scores $c_j$ such that\n\n$$\n\\mathbf{c} = \\{c_1, c_2, c_3,... c_s\\} : c_1 < c_2 < ...< c_s\n$$\n\n:::callout-note\nBecause both variables are ordinal, we can test for correlation between the two variables.\n:::\n\n\nThen for each cell, the expected frequency, $\\bar{f}$ can be written as:\n\n$$\n\\bar{f} = \\sum_{i=1}^s\\sum_{j=1}^r \\frac{c_ia_jn_{ij}}{n}\n$$\n\n\n## Correlation Tests\n\nThe null hypothesis for the association tests remains to be $H_0$: There is no association between the two variables. To test this hypothesis, we can use a randomization statistic $Q_{CS}$ that accounts for the ordinality of both variables.\n\n$$\nQ_{CS} = \\frac{(\\bar{f}-\\mu_c\\mu_a)^2}{v_cv_a/(n-1)} = (n-1)r_{ac}^2\n$$\n::: callout-note\n\n- $\\mu_c$ is the expected value of the row scores\n- $\\mu_a$ is the expected value of the column scores.\n- $v_c$ is the variance of the row scores\n- $v_a$ is variance of the column scores\n\n$r_{ac}$ is the Pearson correlation coefficient, which measures the correlation between the ordinal variables.\n:::\n\n## Correlation Tests\n\n$Q_{CS}$ follows a chi-square distribution with 1 degree of freedom, regardless of the size of the table, when the sample size is at least 20.\n\n\n## Correlation Tests: `SAS`\n\n$Q_{CS}$ is the Mantel-Haenszel chi-square statistic displayed by the `chisq` and `cmh` output.\n\n## Correlation Tests: `R`\n\n$Q_{CS}$ is part of the `CMHtest()` output. \n\n::: callout-note\nThe default scores for the row and column scores are integer scores. Specify `rscores`/`cscores` as `midrank` to use rank-based scores.\n:::\n\n## Example \n\nA water treatment company is studying water additives and investigating how they affect clothes washing. The treatments studied were no treatment (plain water), the standard treatment, and a double dose of the standard treatment, called super. Washability was measured as low, medium, and high. The company claims that the dose of water treatment affects the washability of water. Do we have sufficient evidence to support this claim?\n\n![](img/wash_C5.png)\n\n## Example\n\nA water treatment company is studying water additives and investigating how they affect clothes washing. The treatments studied were no treatment (plain water), the standard treatment, and a double dose of the standard treatment, called super. Washability was measured as low, medium, and high. The company claims that the dose of water treatment affects the washability of water. Do we have sufficient evidence to support this claim?\n\n::: panel-tabset\n### SAS Code\n\n``` r\ndata wash;\ninput treatment $ washability $ count @@;\ndatalines;\nwater low 27 water medium 14 water high 5\nstandard low 10 standard medium 17 standard high 26\nsuper low 5 super medium 12 super high 50\n;\n\nproc freq order=data data=wash;\nweight count;\ntables treatment*washability / chisq cmh;\ntables treatment*washability / scores=modridit cmh\nnoprint nocol nopct;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Treatment=c(\"Water\",\"Standard\",\"Super\"),\n                   Washability=c(\"Low\",\"Medium\",\"High\"))\n\ndat$Count <- c(27,10,5,14,17,12,5,26,50)\n\ndat_cc <- xtabs(Count~Treatment+Washability,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Washability\nTreatment  Low Medium High\n  Water     27     14    5\n  Standard  10     17   26\n  Super      5     12   50\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treatment by Washability \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 50.602  1 1.1315e-12\nrmeans  Row mean scores differ 52.779  2 3.4616e-12\ncmeans  Col mean scores differ 50.782  2 9.3945e-12\ngeneral    General association 54.756  4 3.6548e-11\n```\n\n\n:::\n\n```{.r .cell-code}\nCMHtest(dat_cc,\n        rscores=\"midrank\",\n        cscores=\"midrank\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treatment by Washability \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 49.541  1 1.9427e-12\nrmeans  Row mean scores differ 52.515  2 3.9496e-12\ncmeans  Col mean scores differ 49.572  2 1.7205e-11\ngeneral    General association 54.756  4 3.6548e-11\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n$Q_{CS}=50.6$, p\\<0.0001. There is sufficient evidence to claim that the dose of water treatment is associated with the washability of the water.\n\nIf modridit scores are used, $Q_{CS}=49.5$.\n:::\n\n## Exercise\n\nA random sample of 400 college students are classified according to class status and drinking habits. Test the null hypothesis that class status and drinking habits are not correlated to each other.\n\n::: panel-tabset\n\n### Data\n\n::: {.callout-note title=\"Variables\"}\nnon: nondrinkers; mod: moderate; hea: heavy; fres: freshman; soph: sophomore; jun: junior; sen:senior\n:::\n\n```{.r}\ndata drink; \ninput habit $ status $ count @@;\ndatalines;\nnon fres 55 non soph 34 non jun 27 non sen 17\nmod fres 32 mod soph 29 mod jun 36 mod sen 39\nhea fres 29 hea soph 41 hea jun 33 hea sen 28\n;\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(habit = c(\"Nondrinkers\",\"Moderate\",\"Heavy\"),\n                   Status = c(\"Freshmen\",\"Sophomore\",\"Junior\",\"Senior\"))\n\ndat$Count <- c(55,32,29,34,29,41,27,36,33,17,39,28)\n```\n:::\n\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(Count~habit+Status,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Status\nhabit         Freshmen Sophomore Junior Senior\n  Nondrinkers       55        34     27     17\n  Moderate          32        29     36     39\n  Heavy             29        41     33     28\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(dat_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for habit by Status \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation  9.182  1 0.00244408\nrmeans  Row mean scores differ 18.147  2 0.00011468\ncmeans  Col mean scores differ 12.249  3 0.00657745\ngeneral    General association 22.325  6 0.00105692\n```\n\n\n:::\n:::\n\n\n\n### SAS Code\n\n```{.r}\ndata drink;\ninput habit $ status $ count @@;\ndatalines;\nnon f 55 non soph 34 non j 27 non sen 17\nmod f 32 mod soph 29 mod j 36 mod sen 39\nhea f 29 hea soph 41 hea j 33 hea sen 28\n;\n\nproc freq data=drink order=data;\nweight count;\ntables habit*status/cmh chisq;\nrun;\n```\n\n### Answer\n\nTable Scores: $Q_{CS}$ = 9.18, p=0.0024. At $\\alpha=0.05$, here is sufficient evidence to support the claim that class status and drinking habits are correlated to each other.\n:::\n\n## Exact Tests\n\n-   Recall: Fisher’s Exact Test\n    -   sxr: Generalized to a multivariate hypergeometric distribution\n-   For general association, we can get exact p-values for the Pearson chi-square, and likelihood ratio chi-square.\n-   Unlike Fisher’s Exact Test for 2x2 tables, there are no one-sided alternative hypothesis.\n-   Exact p-value for randomization statistic 𝑄 is the same as the Pearson chi-square p-value.\n\n## Exact Tests\n\n-   Recall: Exact testing of sx2 tables\n    -   The correlation statistic is suitable when sample size requirements are not met, but we can't use the chi-square distribution. \n    -   Exact p-value is the sum of p-values associated with contingency tables where the test statistic is larger than the observed table.\n\n## Exact Tests: SAS\n\n-   The `exact` statement can be used to calculate exact p-values and perform exact tests.\n    -   `Fisher` – Fisher’s exact test\n    -   `PCHI` – Pearson chi-square statistic\n    -   `LRCHI` – likelihood ratio chi-square statistic\n    -   `MHCHI` - Mantel-Haenszel statistic (Correlation tests)\n\n## Exact Tests: SAS\n\n::: callout-warning\nExact tests are computationally intensive. More cells lead to more calculations, which makes exact computation not feasible.\n\n-   You can set the `MAXTIME` option in the exact statement to tell SAS to stop computations beyond a certain number of seconds.\n:::\n\n## Example \n\nA marketing research firm organized a focus group to consider issues of new car marketing. Members of the group included people who had purchased a car from a local dealer in the last month. Researchers were interested in whether there was an association between the type of car bought and how group members found out about the car in the media. Cars were classified as sedans, sporty, and utility. The types of media included television, magazines, newspapers, and radio.\n\n![](img/car_C5.png)\n\n## Example \n\nA marketing research firm organized a focus group to consider issues of new car marketing. Members of the group included people who had purchased a car from a local dealer in the last month. Researchers were interested in whether there was an association between the type of car bought and how group members found out about the car in the media. Cars were classified as sedans, sporty, and utility. The types of media included television, magazines, newspapers, and radio.\n\n::: panel-tabset\n### SAS Code\n\n``` r\ndata market;\nlength AdSource $ 9. ;\ninput car $ AdSource $ count @@;\ndatalines;\nsporty paper 3 sporty radio 4 sporty tv 0 sporty magazine 3\nsedan paper 0 sedan radio 2 sedan tv 4 sedan magazine 0\nutility paper 2 utility radio 2 utility tv 5 utility magazine 5\n;\nproc freq;\nweight count;\ntable car*AdSource / norow nocol nopct;\nexact fisher pchi lrchi;\nrun;\n```\n\n### Answer\n\nWe need to use Fisher's exact test because of the small sample size. The p-value was calculated to be 0.04, which is sufficient evidence to conclude that there is an association between car type and media.\n:::\n\n## Exercise\n\nA university professor wanted to test the general association between the most used social media app and the type of high school attended by freshmen. The professor asked 23 students in his class about their social media habits and respective high schools.\n\n|                       | Tiktok | Instagram | Snapchat | Other |\n|-----------------------|--------|-----------|----------|-------|\n| Priv., in-state     | 3      | 2         | 3        | 0     |\n| Pub., in-state      | 3      | 1         | 0        | 0     |\n| Priv., out-of-state | 4      | 1         | 0        | 1     |\n| Pub., out-of-state  | 1      | 0         | 0        | 1     |\n\n## Exercise\n\nA university professor wanted to test the general association between the most used social media app and the type of high school attended by freshmen. The professor asked 23 students in his class about their social media habits and respective high schools.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\ndata sm;\ninput school $ social $ count @@;\ndatalines;\nPr_IS t 3 Pr_IS i 2 Pr_IS s 3 Pr_IS o 0\nPu_IS t 3 Pu_IS i 1 Pu_IS s 3 Pu_IS o 0\nPr_OS t 4 Pr_OS i 1 Pr_OS s 0 Pr_OS o 1\nPu_OS t 1 Pu_OS i 0 Pu_OS s 0 Pu_OS o 1\n;\n\nproc freq data=sm order=data;\nweight count;\ntables school*social;\nexact fisher pchi lrchi;\nrun;\n```\n\n### Answer\n\nThe Fisher's exact test yielded p=0.45, which means there is insufficient evidence to claim that social media habits are associated with the type of high school attended by the students.\n\n:::\n\n# Measures of Association\n\n## Measures of Association\n\n- We only have information on whether the row and column variables are associated, but not by how much.\n- Depends on the scale of the measurements\n  - Ordinal vs. Nominal\n  - Are levels equally spaced?\n  \n\n## Ordinal variables\n\nWhen both row and column variables are ordinal, we can use correlation coefficients.\n\n:::callout-note\nWhen scores are equally spaced, the **Pearson** correlation coefficient is appropriate. For data without an obvious scale, the **Spearman** correlation coefficient is more appropriate.\n:::\n\n\n## Ordinal Variables\n\n- Association can also be measured by classifying all possible pairs of subjects as concordant or discordant pairs.\n  - Concordant: Subject ranks higher on the row variable also ranks higher on the column variable\n  - Discordant: Subject that ranks higher on the row variable also ranks lower on the column variable\n  - Depends on relative ordering of the levels of variables\n\n\n:::callout-note\nMeasures of association that use these pairs are Gamma $\\gamma$, Kendall's $\\tau_B$, Stuart's $\\tau_C$, Somers' Delta.\n\n- All measures range from -1 to 1, inclusive.\n:::\n\n\n## Measures of Association\n\nThese measures differ in adjusting for ties and sample size.\n\n- Somers’ D depends on the location of the explanatory variable.\n- Stuart’s $\\tau_C$ includes an adjustment for table size  to a correction for ties. Recommended when two ordinal variables under consideration have different numbers of values.\n- Kendall’s $\\tau_B$ is preferred when the contingency table is square ($m\\times m$)\n- Gamma does not account for ties, so it is only recommended if there are no ties.\n\n## Measures of Association\n\nWhen the sample size is large enough, 95% confidence intervals can be calculated for these measures using a normal approximation.\n\n$$\nmeasure \\pm 1.96*ASE\n$$\n\nwhere ASE is the asymptotic standard error reported in the `measures` output from the `freq` procedure.\n  - The confidence interval can be calculated using the `cl` option in the `freq` procedure.\n  \n## Exercise\n\nConsider the water treatment example. Calculate the following measures of association with the corresponding 95% CI.\n\n- Pearson correlation\n- Spearman Correlation\n- Gamma\n- Kendall’s $\\tau_b$\n- Stuart’s $\\tau_c$\n- Somers’ Delta \n\n\n![](img/wash_C5.png)\n\n## Exercise\n\nConsider the water treatment example. Calculate the following measures of association with the corresponding 95% CI.\n\n:::{.panel-tabset}\n### SAS Code\n```{.r}\ndata wash;\ninput treatment $ washability $ count @@;\ndatalines;\nwater low 27 water medium 14 water high 5\nstandard low 10 standard medium 17 standard high 26\nsuper low 5 super medium 12 super high 50\n;\nproc freq order=data data=wash;\nweight count;\ntables treatment*washability /  measures cl;\nrun;\n```\n\n\n\n### Answer\n\n- Pearson Correlation: 0.55 (0.44,0.67)\n- Spearman Correlation: 0.55 (0.43, 0.66)\n- Gamma: 0.6974 (0.57-0.82)\n- $\\tau_b$: 0.50 (0.39,0.61)\n- $\\tau_C$: 0.48 (0.37,0.59)\n- Somers' D C|R: 0.49 (0.38,0.59)\n\n:::\n\n## Exercise \n\nA random sample of 400 college students are classified according to class status and drinking habits. Calculate the following measures of association and the 95% CI.\n\n- Pearson correlation\n- Spearman Correlation\n- Gamma\n- Kendall’s $\\tau_b$\n- Stuart’s $\\tau_c$\n- Somers’ Delta \n\n```{.r}\ndata drink; # <1>\ninput habit $ status $ count @@;\ndatalines;\nnon fres 55 non soph 34 non jun 27 non sen 17\nmod fres 32 mod soph 29 mod jun 36 mod sen 39\nhea fres 29 hea soph 41 hea jun 33 hea sen 28\n;\n```\n1.  non: nondrinkers; mod: moderate; hea: heavy; fres: freshman; soph: sophomore; jun: junior; sen:senior\n\n## Exercise \n\nA random sample of 400 college students are classified according to class status and drinking habits. Calculate the following measures of association and the 95% CI.\n\n\n:::{.panel-tabset}\n### SAS Code\n```{.r}\ndata drink;\ninput habit $ status $ count @@;\ndatalines;\nnon f 55 non soph 34 non j 27 non sen 17\nmod f 32 mod soph 29 mod j 36 mod sen 39\nhea f 29 hea soph 41 hea j 33 hea sen 28\n;\n\nproc freq data=drink order=data;\nweight count;\ntables habit*status/measures cl;\nrun;\n```\n\n\n\n### Answer\n\n- Pearson Correlation: 0.15 (0.06,0.25)\n- Spearman Correlation: 0.16 (0.06, 0.25)\n- Gamma: 0.18 (0.07,0.30)\n- $\\tau_b$: 0.13 (0.05,0.21)\n- $\\tau_C$: 0.14 (0.05,0.22)\n- Somers' D C|R: 0.14 (0.05,0.22)\n\n:::\n\n## Nominal Variables \n\nIt is slightly tricky to define association between two nominal variables. There are two measures of association that could measure the strength of association between nominal variables.\n\n- Lambda $\\lambda$\n- Uncertainty coefficients\n\nBoth of these measures are included in the `measures` output.\n\n:::callout-warning\nNote that SAS will calculate all measures despite the nature of the variables. It is your job as an analyst to only report the relevant measures.\n\nDo not use ordinal measures for nominal variables. Do not use nominal measures for ordinal variables\n:::\n\n## Lambda $\\lambda$\n\nLambda measures the probable improvement in predicting the column variable given knowledge of the row variable.\n\n- Asymmetric: Can be C|R or R|C depending on where the explanatory variable is located\n- Symmetric: weighted average of the two asymmetric $\\lambda$ values.\n\n## Uncertainty coefficient\n\nThe uncertainty coefficient, similar to $R^2$, measures the proportion of uncertainty in column variable as explained by the row variable.\n\n- Asymmetric: Can be C|R or R|C depending on where the explanatory variable is located\n- Symmetric: weighted average of the two asymmetric uncertainty coefficients.\n\n\n## Exercise\n\n::::: columns\n::: {.column style=\"width:40%; font-size: 75%\"}\nThe table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.\n\n-   What are the appropriate measures of association to report?\n- Provide the estimate and the 95% CI of these measures.\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/party_C5.png)\n:::\n:::::\n\n## Exercise \nThe table contains data from a study concerning the distribution of party affiliation in a city suburb. The interest was whether there was an association between registered political party and neighborhood.\n\n-   What are the appropriate measures of association to report?\n- Provide the estimate and the 95% CI of these measures.\n\n::: panel-tabset\n### SAS Code\n\n```{.r}\ndata neighbor;\nlength party $ 11 neighborhood $ 10;\ninput party $ neighborhood $ count @@;\ndatalines;\ndemocrat longview 360 democrat bayside 221\ndemocrat sheffeld 140 democrat highland 160\nrepublican longview 316 republican bayside 208\nrepublican sheffeld 97 republican highland 106\nindependent longview 160 independent bayside 200\nindependent sheffeld 311 independent highland 291\n;\n\nproc freq data=neighbor;\nweight count;\ntables party*neighborhood /\nmeasures cl;\nrun;\n```\n\n\n\n### Answer\n\nYou can choose to report the asymmetric $\\lambda$, symmetric $\\lambda$, asymmetric uncertainty coefficient, or the symmetric uncertainty coefficient. \n\nThe asymmetric uncertainty coefficient R|C is estimated to be 0.05 (95% CI: 0.04,0.06). The estimated proportion of uncertainty in party affiliation explained by the neighborhood is estimated to be 0.05.\n:::\n\n# Observer Agreement\n\n## Observer Agreement\n\nErrors are inevitable in making measurements!\n\n  - Biggest error: Observer error\n\n:::callout-note\nHow do we account for observer error, especially for multiple observer measurements?\n:::\n\n## Observer Agreement: $\\kappa$\n\nThe kappa statistic $\\kappa$ measures the extent of agreement between two observers.\n\n- $\\kappa$=0: any agreement is made by chance\n- $\\kappa$=1: perfect agreement\n- $\\kappa \\geq$ 0.8: excellent agreement\n- $\\kappa \\geq$ 0.4: moderate agreement\n\n::: callout-note\nThis is similar to the intraclass correlation coefficient in ANOVA models.\n:::\n  \n## Observer Agreement: $\\kappa$\n\n$\\kappa$ is calculated from the following equation:\n\n$$\n\\kappa = (\\Pi_O - \\Pi_E)/(1-\\Pi_E)\n$$\nwhere $\\Pi_O$ is the probability that observers agreed based on the data, $\\Pi_E$ is the expected probability of agreement if the two observer ratings are assumed to be independent.\n\n## Observer Agreement\n\n- When there is order in the categories, we might need to account how different the disagreements are.\n- We can use weighted $\\kappa$ measurements such as:\n  - Cicchetti-Allison weights puts more weight on cells closest to the diagonal.\n  - Fleiss-Cohen kappa weights use a squared distance between categories, which penalizes highly discordant pairs.\n\n\n## Bowker's Test\n\n- Tests whether the contingency table is symmetric about the diagonals.\n  - Works for square tables \n  - Same as McNemar’s test when the table is $2\\times 2$\n\n\n## Observer Agreement: SAS\n\n- The `AGREE` option in the tables statement generates the kappa statistics and Bowker’s symmetry test.\n  - `AGREE (WT=FC)` specifies to use the *Fleiss-Cohen* criterion for the Weighted Kappa statistic.\n- The agreement plot is also shown.\n  - Comparison of shaded portions of the rectangles to the entire area of the rectangle provides information about the agreement between the two raters.\n- Exact testing can also be done by specifying `KAPPA` in the `EXACT` statement.\n  - Small cell counts with multiple 0 cell counts.\n\n## Example \n\n- The data comes from a study concerning the diagnostic classification of multiple sclerosis patients. Patients from Winnipeg and New Orleans were classified into one of four diagnostic classes by both a Winnipeg neurologist and a New Orleans neurologist.\n  - Calculate the estimate and 95% confidence interval for the simple and weighted Kappa statistic.\n  - What can you say about the agreement between the New Orleans and Winnipeg neurologists?\n\n![](img/neuro_C5.png)\n\n### SAS Code\n\n```{.r}\ndata classify;\ninput no_rater w_rater count @@;\ndatalines;\n1 1 38 1 2 5 1 3 0 1 4 1\n2 1 33 2 2 11 2 3 3 2 4 0\n3 1 10 3 2 14 3 3 5 3 4 6\n4 1 3 4 2 7 4 3 3 4 4 10\n;\n```\n\n\n## Example \n\n- The data comes from a study concerning the diagnostic classification of multiple sclerosis patients. Patients from Winnipeg and New Orleans were classified into one of four diagnostic classes by both a Winnipeg neurologist and a New Orleans neurologist.\n  - Calculate the estimate and 95% confidence interval for the simple and weighted Kappa statistic.\n  - What can you say about the agreement between the New Orleans and Winnipeg neurologists?\n  \n::: {.panel-tabset}\n### SAS Code\n```{.r}\ndata classify;\ninput no_rater w_rater count @@;\ndatalines;\n1 1 38 1 2 5 1 3 0 1 4 1\n2 1 33 2 2 11 2 3 3 2 4 0\n3 1 10 3 2 14 3 3 5 3 4 6\n4 1 3 4 2 7 4 3 3 4 4 10\n;\n\n\nproc freq;\nweight count;\ntables no_rater*w_rater / agree norow nocol nopct;\nrun;\n\n```\n\n### Answer\n\nSimple $\\kappa$: 0.21 (0.11,0.31)\nWeighted $\\kappa$: 0.38 (0.28,0.48)\n\nSince the weighted $\\kappa$ is higher than the simple $\\kappa$, we can infer that there were more disagreements closer to the diagonal. There is a slight to moderate agreement between the two neurologists.\n:::\n\n## Exercise \nTwo radiologists rated 85 patients with respect to liver lesions. The ratings were designated on an ordinal scale as:\n\n0 ='Normal'; 1 ='Benign’ ; 2 ='Suspected'; 3 ='Cancer’\n\n- Calculate the simple and weighted kappa statistics and the corresponding 95% confidence intervals.\n- Compare the asymptotic and exact p-values in testing whether there is an agreement between the two radiologists.\n\n```{.r}\n\ndata radiology;\ninput rater1 rater2 count;\ncards;\n0 0 21\n0 1 12\n0 2  0\n0 3  0\n1 0  4\n1 1 17\n1 2  1\n1 3  0\n2 0  3\n2 1  9\n2 2 15\n2 3  2\n3 0  0\n3 1  0\n3 2  0\n3 3  1\n;\nrun;\n\n```\n\n## Exercise \nTwo radiologists rated 85 patients with respect to liver lesions. The ratings were designated on an ordinal scale as:\n\n0 ='Normal'; 1 ='Benign’ ; 2 ='Suspected'; 3 ='Cancer’\n\n- Calculate the simple and weighted kappa statistics and the corresponding 95% confidence intervals.\n- Compare the asymptotic and exact p-values in testing whether there is an agreement between the two radiologists.\n\n\n::: {.panel-tabset}\n### SAS Code\n```{.r}\ndata radiology;\ninput rater1 rater2 count;\ncards;\n0 0 21\n0 1 12\n0 2  0\n0 3  0\n1 0  4\n1 1 17\n1 2  1\n1 3  0\n2 0  3\n2 1  9\n2 2 15\n2 3  2\n3 0  0\n3 1  0\n3 2  0\n3 3  1\n;\nrun;\n\nproc freq data=radiology;\ntables rater1*rater2/norow nocol nopct agree;\nweight count;\ntest kappa;\nexact kappa;\nrun;\n```\n\n### Answer\n\nSimple $\\kappa$: 0.47 (0.33,0.62)\nWeighted $\\kappa$: 0.57 (0.44,0.70)\n\nThe exact p-value is p<0.001, which shows there is sufficient evidence of an agreement between the radiologists. Based on the simple and weighted kappa values, there is moderate agreement between the two radiologists.\n:::\n\n# Ordered Differences\n\n## Test for Ordered Differences\n\n- What if the columns are ordinal but the rows are nominal?\n  - Recall: rows could pertain to different groups.\n  - Recall: Mean score tests account for location shifts in the mean response\n- What if we want to know if the mean scores are monotonously increasing or decreasing across levels of the row variable?\n  - Example: Showing increasing prevalence of disease in specific environments.\n\n## Test for Ordered Differences \n\nThe Jonckheere-Terpstra test is a nonparametric test that is based on sums of Mann-Whitney test statistics\n\n  - Rank-based test\n\nThis test detects whether there are differences in the trend of group effects.\n\n  - Are the scores strictly increasing or decreasing?\n\n:::callout-note\nThe null hypothesis $H_0$ assumes that the distribution of ordered responses is the same for all groups. For one-sided tests, this tests detect whether $d_1 \\leq d_2 \\leq... d_s$ where $d_i$ corresponds to the $i^{th}$ group effect.\n:::\n\n:::callout-note\nThe Jonckheere-Terpstra test can be performed by adding the `JT` option to the `tables` statement. An exact implementation of the Jonckheere-Terpstra test can also be performed by adding the `JT` option to the `exact` statement.\n::: \n\n## Example \n\nInvestigators conducted a randomized clinical trial in four hospitals, where patients were assigned to one of four surgical procedures for the treatment of severe duodenal ulcers. The treatments include:\n\n- v + d: vagotomy and drainage\n- v + a: vagotomy and antrectomy (removal of 25% of gastric tissue)\n- v + h: vagatomy and hemigastrectomy (removal of 50% of gastric tissue)\n- gre: gastric resection (removal of 75% of gastric tissue)\n\nThe response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is increasing as the amount of gastric tissue removed increased. Ignore hospital effects.\n\n### SAS Code\n```{.r}\ndata operate;\ninput hospital trt $ severity $ wt @@;\ndatalines;\n1 v+d none 23 1 v+d slight 7 1 v+d moderate 2\n1 v+a none 23 1 v+a slight 10 1 v+a moderate 5\n1 v+h none 20 1 v+h slight 13 1 v+h moderate 5\n1 gre none 24 1 gre slight 10 1 gre moderate 6\n2 v+d none 18 2 v+d slight 6 2 v+d moderate 1\n2 v+a none 18 2 v+a slight 6 2 v+a moderate 2\n2 v+h none 13 2 v+h slight 13 2 v+h moderate 2\n2 gre none 9 2 gre slight 15 2 gre moderate 2\n3 v+d none 8 3 v+d slight 6 3 v+d moderate 3\n3 v+a none 12 3 v+a slight 4 3 v+a moderate 4\n3 v+h none 11 3 v+h slight 6 3 v+h moderate 2\n3 gre none 7 3 gre slight 7 3 gre moderate 4\n4 v+d none 12 4 v+d slight 9 4 v+d moderate 1\n4 v+a none 15 4 v+a slight 3 4 v+a moderate 2\n4 v+h none 14 4 v+h slight 8 4 v+h moderate 3\n4 gre none 13 4 gre slight 6 4 gre moderate 4\n;\n```\n\n\n\n\n## Example \n\nInvestigators conducted a randomized clinical trial in four hospitals, where patients were assigned to one of four surgical procedures for the treatment of severe duodenal ulcers. The treatments include:\n\n- v + d: vagotomy and drainage\n- v + a: vagotomy and antrectomy (removal of 25% of gastric tissue)\n- v + h: vagatomy and hemigastrectomy (removal of 50% of gastric tissue)\n- gre: gastric resection (removal of 75% of gastric tissue)\n\nThe response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is different across all treatments, ignoring the hospital effects.\n\n:::{.panel-tabset}\n\n### SAS Code\n\n```{.r}\ndata operate;\ninput hospital trt $ severity $ wt @@;\ndatalines;\n1 v+d none 23 1 v+d slight 7 1 v+d moderate 2\n1 v+a none 23 1 v+a slight 10 1 v+a moderate 5\n1 v+h none 20 1 v+h slight 13 1 v+h moderate 5\n1 gre none 24 1 gre slight 10 1 gre moderate 6\n2 v+d none 18 2 v+d slight 6 2 v+d moderate 1\n2 v+a none 18 2 v+a slight 6 2 v+a moderate 2\n2 v+h none 13 2 v+h slight 13 2 v+h moderate 2\n2 gre none 9 2 gre slight 15 2 gre moderate 2\n3 v+d none 8 3 v+d slight 6 3 v+d moderate 3\n3 v+a none 12 3 v+a slight 4 3 v+a moderate 4\n3 v+h none 11 3 v+h slight 6 3 v+h moderate 2\n3 gre none 7 3 gre slight 7 3 gre moderate 4\n4 v+d none 12 4 v+d slight 9 4 v+d moderate 1\n4 v+a none 15 4 v+a slight 3 4 v+a moderate 2\n4 v+h none 14 4 v+h slight 8 4 v+h moderate 3\n4 gre none 13 4 gre slight 6 4 gre moderate 4\n;\n\nproc freq data=operate order=data;\nweight wt;\ntables trt*severity /  jt;\nrun;\n```\n\n### Answer\n\nThe JT statistic was estimated to be 35,697, corresponding to a one-sided p-value $p=0.005$, which is sufficient evidence to claim that the severity of the duodenal ulcer increases with the amount of gastric tissue removed.\n:::\n\n\n",
    "supporting": [
      "Chapter5_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}