{
  "hash": "bbf30681354fd6ad864f5a7bbb9f3d12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 2\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 2- [Back to home](https://madfudolig.quarto.pub/eab770slides/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    code-annotations: true\n    chalkboard: true\n    echo: true\n  pdf: \n    number-sections: true\n---\n\n# Chapter 2: $2\\times2$ tables\n\n\n::: {.cell}\n\n:::\n\n\n## Outline {.smaller}\n\n- Contingency Tables\n- Chi-Square Statistics\n- Exact Tests\n- Difference in Proportions\n- Odds Ratio and Relative Risk\n- Sensitivity and Specificity\n- McNemar’s Test\n- Incidence Densities\n- Power Analysis\n\n# Contingency Tables\n\n## 2x2 Contingency Tables\n\n::::: columns\n::: {.column style=\"width:40%; font-size: 75%\"}\n- Summarizes categorical data\n  - Response variable has two levels\n  - Exploratory variable has two levels\n- Example:\n  - Treatment/Placebo in RCT\n  - Case/Control in a retrospective study\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/ContingencyTable.png)\n:::\n:::::\n\n## Contingency Tables\n\nWe wish to determine whether there is an association between the row and column variables using the frequencies observed in each category.\n\n::: callout-note\nIs the risk variable associated with the prevalence rate?\n:::\n\nRecall: Intro to Statistics\n\n- Chi-square tests of homogeneity $H_0$: The two populations (rows) have the same distribution of the column variable\n- Chi-square tests of independence $H_0$: The row and column variables are independent of each other.\n\n## Contingency Tables: Convention\n\nThe indices of contingency tables denote the row and column of each number. For a total sample size of $n$,\n\n::::: columns\n::: {.column style=\"width:40%; font-size: 85%\"}\n- $n_{xy}$ denotes the number at row $x$ and column $y$, also referred to as a joint frequency.\n- Seeing a (+) sign indicates that it is a marginal sum, also referred to as marginal frequencies.\n  - $n_{x+}$ denotes the sum of all columns in row $x$.\n  - $n_{+y}$ denotes the sum of all rows in column $y$.\n- The placement of the + sign denotes the margin in which it was summed.\n:::\n\n::: {.column style=\"width:60%\"}\n![](img/ContingencyTable2.png){fig-align=\"center\"}\n:::\n:::::\n\n## `SAS` Example: Contingency Table\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 125%\"}\n```         \ndata respire;\nlength treat $7. outcome $1. ;\ninput treat $ outcome $ count;\ndatalines;\nplacebo f 16\nplacebo u 48\ntest f 40\ntest u 20\n;\nrun;\n\nproc freq data=respire order=data;\nweight count;\ntables treat*outcome;\nrun;\n```\n:::\n\n::: {.column style=\"width:50%; font-size: 75%\"}\n- `proc freq` calls the `FREQ` procedure in `SAS`.\n  - Not defining `data=respire` means `SAS` will automatically use the most recently run data set.\n- `order=data` means we are creating the rows and columns based on how the data was inputted, not alphabetical order.\n- `weight` tells `SAS` the number of counts for each count\n- `tables` creates the contingency table with row, column, and total percentages.\n- `run;` tells `SAS` to run the code. **This is important!**\n:::\n:::::\n\n## Contingency Tables in `SAS`- Long Format\n\nWhen the data is not aggregated, the `FREQ` procedure can still be used to create contingency tables. We can use the import data procedure in SAS ODA to create `work.spore` from `Spore.csv` uploaded on Canvas.\n\n```\nproc freq order=data data=severe;\nweight count;\ntables treat*outcome / chisq nocol;\nexact or;\nrun;\n```\n\n\n## Contingency Tables in `R`\n\nTo create your own contingency table, you can use the `data.frame()` and `xtabs()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_data <- data.frame(Row = c(\"A\",\"A\",\"B\",\"B\"),\n                         Column = c(\"X\",\"Y\",\"X\",\"Y\"),\n                         Count = c(2,4,6,8))\ncount_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Row Column Count\n1   A      X     2\n2   A      Y     4\n3   B      X     6\n4   B      Y     8\n```\n\n\n:::\n\n```{.r .cell-code}\nxtabs(Count~Row+Column,data=count_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Column\nRow X Y\n  A 2 4\n  B 6 8\n```\n\n\n:::\n:::\n\n\nYou can also use the `expand.grid()` function to create combinations of variable levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_data <- expand.grid(Row = factor(c(\"A\",\"B\"), levels=c(\"A\",\"B\")),\n                         Column = factor(c(\"X\",\"Y\"), levels=c(\"X\",\"Y\")))\n\ncount_data$Count = c(2,4,6,8)\n\ncount_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Row Column Count\n1   A      X     2\n2   B      X     4\n3   A      Y     6\n4   B      Y     8\n```\n\n\n:::\n\n```{.r .cell-code}\nxtabs(Count~Row+Column,data=count_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Column\nRow X Y\n  A 2 6\n  B 4 8\n```\n\n\n:::\n:::\n\n\n::: callout-note\n`ordered` can also be used to account for ordering in the row and column variables.\n:::\n\n## Contingency Tables in `R`- Long Format\n\nWhen the data is not aggregated, the `xtabs` function can still be used to create contingency tables. First, we import `Spore.csv` from Canvas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspore <- read.csv(\"Spore.csv\",stringsAsFactors = TRUE)\nspore\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ID Treatment         Period Spore\n1   1      Test  Pre-Treatment  Full\n2   1      Test  Mid-Treatment  Some\n3   1      Test Post-Treatment  Some\n4   2      Test  Pre-Treatment  Full\n5   2      Test  Mid-Treatment  None\n6   2      Test Post-Treatment  None\n7   3      Test  Pre-Treatment  Full\n8   3      Test  Mid-Treatment  Some\n9   3      Test Post-Treatment  Some\n10  4      Test  Pre-Treatment  Full\n11  4      Test  Mid-Treatment  Some\n12  4      Test Post-Treatment      \n13  5      Test  Pre-Treatment  Full\n14  5      Test  Mid-Treatment  None\n15  5      Test Post-Treatment  None\n16  1   Placebo  Pre-Treatment  Full\n17  1   Placebo  Mid-Treatment  Full\n18  1   Placebo Post-Treatment  Full\n19  2   Placebo  Pre-Treatment  Full\n20  2   Placebo  Mid-Treatment  Some\n21  2   Placebo Post-Treatment  Some\n22  3   Placebo  Pre-Treatment  Full\n23  3   Placebo  Mid-Treatment  Some\n24  3   Placebo Post-Treatment  Some\n25  4   Placebo  Pre-Treatment  Full\n26  4   Placebo  Mid-Treatment  Some\n27  4   Placebo Post-Treatment  Some\n28  5   Placebo  Pre-Treatment  Some\n29  5   Placebo  Mid-Treatment      \n30  5   Placebo Post-Treatment      \n31  6      Test  Pre-Treatment  Full\n32  6      Test  Mid-Treatment  Some\n33  6      Test Post-Treatment  Some\n34  7      Test  Pre-Treatment  Full\n35  7      Test  Mid-Treatment  None\n36  7      Test Post-Treatment  None\n37  8      Test  Pre-Treatment  Full\n38  8      Test  Mid-Treatment  Some\n39  8      Test Post-Treatment  Some\n40  9      Test  Pre-Treatment  Full\n41  9      Test  Mid-Treatment  Some\n42  9      Test Post-Treatment  None\n43 10      Test  Pre-Treatment  Full\n44 10      Test  Mid-Treatment  Some\n45 10      Test Post-Treatment  Some\n46  6   Placebo  Pre-Treatment  Full\n47  6   Placebo  Mid-Treatment  Full\n48  6   Placebo Post-Treatment  Full\n49  7   Placebo  Pre-Treatment  Full\n50  7   Placebo  Mid-Treatment  Full\n51  7   Placebo Post-Treatment  Full\n52  8   Placebo  Pre-Treatment  Full\n53  8   Placebo  Mid-Treatment  Full\n54  8   Placebo Post-Treatment  Full\n55  9   Placebo  Pre-Treatment  Full\n56  9   Placebo  Mid-Treatment  Some\n57  9   Placebo Post-Treatment  Some\n58 10   Placebo  Pre-Treatment  Full\n59 10   Placebo  Mid-Treatment  Some\n60 10   Placebo Post-Treatment  Some\n61 11      Test  Pre-Treatment  Full\n62 11      Test  Mid-Treatment  Some\n63 11      Test Post-Treatment  None\n64 12      Test  Pre-Treatment  Full\n65 12      Test  Mid-Treatment  Some\n66 12      Test Post-Treatment  None\n67 13      Test  Pre-Treatment  Full\n68 13      Test  Mid-Treatment  Some\n69 13      Test Post-Treatment  Some\n70 14      Test  Pre-Treatment  Full\n71 14      Test  Mid-Treatment  None\n72 14      Test Post-Treatment  None\n73 15      Test  Pre-Treatment  Full\n74 15      Test  Mid-Treatment  None\n75 15      Test Post-Treatment  None\n76 11   Placebo  Pre-Treatment  Full\n77 11   Placebo  Mid-Treatment  Some\n78 11   Placebo Post-Treatment  Some\n79 12   Placebo  Pre-Treatment  Full\n80 12   Placebo  Mid-Treatment  Some\n81 12   Placebo Post-Treatment  Some\n82 13   Placebo  Pre-Treatment  Full\n83 13   Placebo  Mid-Treatment  Some\n84 13   Placebo Post-Treatment  Some\n85 14   Placebo  Pre-Treatment  Full\n86 14   Placebo  Mid-Treatment  Full\n87 14   Placebo Post-Treatment  Full\n88 15   Placebo  Pre-Treatment  Full\n89 15   Placebo  Mid-Treatment  Full\n90 15   Placebo Post-Treatment  Full\n```\n\n\n:::\n\n```{.r .cell-code}\nxtabs(~Treatment+Spore,data=spore)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Spore\nTreatment    Full None Some\n  Placebo  2   26    0   17\n  Test     1   15   13   16\n```\n\n\n:::\n:::\n\n\n\n## Exercise\n\nSuppose a survey asking sophomores and senior students whether they agree with the statement “I enjoyed my in-person classes this semester.” yielded the following results.\n\nEnter the data in `SAS` using the data step and generate the contingency tables. Name the data set `enjoy`.\n\n|           | Strongly Agree | Agree | Neutral | Disagree | Strongly Disagree |\n|:---------:|:--------------:|:-----:|:-------:|:--------:|:-----------------:|\n| Sophomore |       24       |  43   |   12    |    25    |        12         |\n|  Seniors  |       19       |  37   |   24    |    32    |        21         |\n\n::: panel-tabset\n### `R` Code\n\nOR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenjoy <- expand.grid(year=factor(c(\"Sophomore\",\"Seniors\"), levels = c(\"Sophomore\",\"Seniors\")),\n                     response = factor(c(\"SA\",\"A\",\"N\",\"D\",\"SD\"),levels = c(\"SA\",\"A\",\"N\",\"D\",\"SD\")))\nenjoy$Count <- c(24,19,43,37,12,24,25,32,12,21)\nxtabs(Count~year+response,data=enjoy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           response\nyear        SA  A  N  D SD\n  Sophomore 24 43 12 25 12\n  Seniors   19 37 24 32 21\n```\n\n\n:::\n:::\n\n\n### `SAS` Code\n\nThere are many ways to code the `data` step. Here's one way to do it!\n\n```         \ndata enjoy;\nlength year $9. response $2.;\ninput year $ response $ count @@;\ndatalines;\nsophomore SA 24 sophomore A 43\nsophomore N 12\nsophomore D 25 sophomore SD 12\nsenior SA 19 senior A 37\nsenior N 24\nsenior D 32 senior SD 21\n;\n\nproc freq order=data data=enjoy;\nweight count;\ntables year*response;\nrun;\n```\n:::\n\n## Independence\n\nIf the two categorical variables are independent of each other, they are not associated.\n\n::: callout-note\nIndependence also means that the joint probability $p_{ij}$ can be determined solely on the basis of the marginal probabilities. These can be estimated using sample data.\n:::\n\n# Chi-square Statistics\n\n## Chi-square Statistics\n\nThe null hypothesis of no association (independence or homogeneity) between row and column variables imply that the totals are fixed. The probabilities of realization of each cell is determined by the hypergeometric distribution.\n\n## Chi-square distribution\n\n::::: columns\n::: {.column style=\"width:60%; font-size: 85%\"}\n- The chi-square distribution, $\\chi_k^2$, is defined by the number of degrees of freedom 𝑘, where 𝑘≥1.\n- Properties include:\n  - The value of $\\chi^2$ can only assume non-negative values.\n  - The $\\chi^2$ distribution is asymmetric.\n  - The sum of two or more independent chi-square variables also follows a chi-square distribution.\n  - Mean: $k$, Variance: $2k$\n:::\n\n::: {.column style=\"width:40%\"}\n![](img/Chi-square.png)\n:::\n:::::\n\n## Pearson Chi-square Statistic\n\nThe Pearson Chi-square statistic can be written in terms of the joint frequency `n_ij` and the expected frequency `m_ij`.\n\n$$Q_P = \\sum_{i=1}^2\\sum_{j=1}^2 \\frac{(n_{ij}-m_{ij})^2}{m_{ij}}$$\n\n::: callout-note\n$m_{ij}$ is the expected value of the number of observations in row $i$ and column $j$, $n_{ij}$. The expected frequency $m_{ij}$ can be calculated based on the null hypothesis assumption.\n\n- Independence: $p_{ij}=p_{i+}p_{+j} \\to m_{ij} = \\frac{n_{i+}n_{+j}}{n}$\n- Homogeneity: $p_{i+}=n_{i+}/n; p_{+j}=n_{+j}/n\\to m_{ij} = \\frac{n_{i+}n_{+j}}{n}$\n:::\n\n## Mantel-Haenszel Chi-square statistic {.smaller}\n\nAnother form of the Chi-square statistic is the Mantel-Haenszel chi-square statistic, $Q$. For $2\\times 2$ contingency tables,\n\n$$Q =  \\frac{(n_{11}-m_{11})^2}{v_{11}}$$\n\n$$m_{11} = n_{1+}n_{+1}/n; v_{11} = \\frac{n_{1+}n_{2+}n_{+1}n_{+2}}{n^2(n-1)}$$\n\n::: callout-note\n$Q$, also known as the randomization chi-square, is based on the condition that all marginal totals are fixed and the probability distribution of random allocation of units to groups is given by the hypergeometric distribution. $m_{11}$ and $v_{11}$ are the mean and variance of the hypergeometric distribution based on the $2 \\times 2$ table, respectively.\n:::\n\n## Pearson Chi-square vs. Mantel-Haenszel Chi-square\n\nThe relationship can also be approximated by the following relation:\n\n$$Q_P = \\frac{n}{n-1}Q$$\n\nFor large $n$, both the MH chi-square and the Pearson chi-square approach a chi-square distribution with $1$ degree of freedom ($\\chi^2_1$).\n\n::: callout-warning\nRule of thumb for $Q_P$: The expected value for each cell should be at least 5, i.e. $m_{ij} \\geq 5$ for all $i,j$\n:::\n\n::: callout-tip\nBecause the MH chi-square statistic comes from a hypergeometric distribution, the MH chi-square statistic can be used for small samples using exact calculations of p-values from the hypergeometric distribution. This is not possible with the Pearson chi-square.\n\nThe MH chi-square statistic can also be extended for use in the presence of covariates/stratifying variables.\n:::\n\n## Hypothesis testing\n\nThe null hypothesis of no association states that there is no association between row and column variables. - Assuming this is true and assumptions are satisfied, $Q$ and $Q_P$ follow a $\\chi^2_1$ distribution for $2\\times2$ tables.\n\n::: callout-note\nThe p-values are given by $P(\\chi^2 > Q_P)$ and $P(\\chi^2 > Q)$ for Pearson and MH Chi-squares, respectively.\n:::\n\n## Hypothesis Testing: SAS\n\n![](img/Freq_vcd.png)\n\n## `SAS`: FREQ procedure\n\n- The `weight` statement tells SAS if there is an aggregated count variable present in the data set.\n- The `tables` statement tells SAS to create a contingency table using the stated variables.\n  - Under tables, you can include the `cmh` or the `chisq` option to calculate the randomization and Pearson chi-square values.\n\nShown below is a sample `SAS` code.\n\n```         \nproc freq;\nweight count;\ntables a*b/ cmh chisq;\nrun;\n```\n\n## `R`: `vcdExtra`\n\nIn `R`, the `vcdExtra` package is required to perform the Mantel-Haenszel chi-square tests. The function `CMHtest()` provides the value of the Mantel-Haenszel statistic, while `chisq.test()` provides the Pearson chi-square statistic.\n\n## Example\n\nThe table shows the information from a randomized clinical trial that compared an experimental treatment to a placebo treatment for a respiratory disorder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ndat <- expand.grid(Treatment=factor(c(\"Placebo\",\"Test\"),levels=c(\"Placebo\",\"Test\")),\n                  Outcome = factor(c(\"Favorable\",\"Unfavorable\"),levels=c(\"Favorable\",\"Unfavorable\")))\n\ndat$count = c(16,40,48,20)\n\nxtabs(count ~ .,data=dat) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Placebo        16          48\n  Test           40          20\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Questions\n\n- What is the Pearson chi-square value?\n- What is the Mantel-Haenszel chi-square value?\n- Is there strong evidence of an association between treatment and outcome?\n\n### SAS Code\n\n``` {.r code-line-numbers=\"3,11,13\"}\nSAScode <- \"\ndata respire;\ninput treat $ outcome $ count; \ndatalines;\ntest f 40\ntest u 20\nplacebo f 16\nplacebo u 48\n;\n\nproc freq data=respire order=data; \nweight count;\ntables treat*outcome/chisq; \nrun;\n\"\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndat <- expand.grid(Treatment=c(\"Placebo\",\"Test\"),\n                  Outcome = c(\"Favorable\",\"Unfavorable\")) |> \nmutate(count = c(16,40,48,20))\n\nxtabs(count ~ .,data=dat) -> dat_cc\n```\n:::\n\n\nPearson Chi-square (without continuity adjustment)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n#install.packages(\"tidyverse\")\nlibrary(tidyverse)\ndat <- expand.grid(Treatment=c(\"Placebo\",\"Test\"),\n                  Outcome = c(\"Favorable\",\"Unfavorable\")) |> \nmutate(count = c(16,40,48,20))\n\nxtabs(count ~ .,data=dat) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Placebo        16          48\n  Test           40          20\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nchisq.test(dat_cc,correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  dat_cc\nX-squared = 21.709, df = 1, p-value = 3.174e-06\n```\n\n\n:::\n:::\n\n\nRandomization Chi-square\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"vcdExtra\")\nlibrary(vcdExtra)\nCMH_CC <-CMHtest(dat_cc) \nCMH_CC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treatment by Outcome \n\n                 AltHypothesis  Chisq Df       Prob\ncor        Nonzero correlation 21.534  1 3.4768e-06\nrmeans  Row mean scores differ 21.534  1 3.4768e-06\ncmeans  Col mean scores differ 21.534  1 3.4768e-06\ngeneral    General association 21.534  1 3.4768e-06\n```\n\n\n:::\n:::\n\n\n### Answers\n\n- What is the Pearson chi-square value? **21.7**\n\n- What is the Mantel-Haenszel chi-square value? **21.53**\n\n- Is there strong evidence of an association between treatment and outcome?\n\n  - *p \\< 0.0001*; There is strong evidence of an association between the test treatment and the outcome.\n:::\n\n## Exercise\n\nSuppose we wish to determine if the frequency of falls is related to wheelchair use for Polio survivors. The data is shown in the table.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Wheelchair\nFall         Yes  No\n  Fallers     62 121\n  Nonfallers  18  32\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Questions\n\n- Write the code to enter the data and analyze using the FREQ procedure.\n- What is the Pearson chi-square value?\n- What is the Mantel-Haenszel chi-square value?\n- Using a significance level of 0.05, do we have sufficient evidence to warrant the conclusion that wheelchair use and falling are associated?\n\n### `SAS` code\n\n``` {.r code-line-numbers=\"2,10,12\"}\ndata wheelchair;\ninput fall $ wheelchair $ count;\ndatalines;\nf yes 62\nn yes 18\nf no 121\nn no 32\n;\n\nproc freq data=wheelchair order=data;\nweight count;\ntables fall*wheelchair/chisq;\nrun;\n```\n\n### `R`\n\nPearson Chi-square (without continuity adjustment)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"tidyverse\")\n\nchisq.test(dat_cc, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  dat_cc\nX-squared = 0.078299, df = 1, p-value = 0.7796\n```\n\n\n:::\n:::\n\n\nRandomization Chi-square\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"vcdExtra\")\nCMH_CC <-CMHtest(dat_cc) \nCMH_CC$table \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Chisq Df     Prob\ncor     0.07796307  1 0.780077\nrmeans  0.07796307  1 0.780077\ncmeans  0.07796307  1 0.780077\ngeneral 0.07796307  1 0.780077\n```\n\n\n:::\n:::\n\n:::\n\n# Exact Methods\n\n## Fisher's Exact Test\n\nThe chi-square distribution assumption for $Q$ and $Q_P$ includes a large sample assumption.\n\n::: callout-warning\nWhat if $m_{ij} < 5$?\n:::\n\nThe **Fisher's Exact Test** can be used to analyze these contingency tables.\n\n## Fisher's Exact Test\n\nFisher's Exact Test is based on the hypergeometric distribution. The test calculates an *exact* p-value, unlike the chi-square test which only uses an approximation.\n\n::: callout-note\nThe test is easy to calculate for $2 \\times 2$ and total sample sizes below 50, but computationally expensive as the number increases.\n:::\n\nThe p-value can be calculated using the hypergeometric distribution with the following parameters: $Hyper(N=n,m=n_{+1},k=n_{1+})$\n\n## Fisher's Exact Test: Hypotheses\n\nNull hypothesis $H_0$: there is no association between the row and column variables\n\n- One sided $H_a$: There is a positive/negative association between the row and column variables. OR One combination of the row and column variable levels is more favored compared to the others.\n\n- Two-sided $H_a$: there is an association between the row and column variables.\n\n::: callout-note\nTo solve the exact p-value using the hypergeometric distribution, only add probabilities of outcomes that have lower probabilities than the observed value in the direction of the alternative hypotheses.\n:::\n\n## Fisher's Exact Test: SAS\n\nIncluding the `exact` or the `chisq` option under the `tables` statement will yield the results of the exact test.\n\n```         \nproc freq;\nweight count;\ntables a*b/ exact chisq;\nrun;\n```\n\n## Fisher's Exact Test: R\n\nThe `fisher.test()` can perform Fisher's exact test in `R` using a contingency table as input.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(contingency_table,alternative=\"two.sided\")\n```\n:::\n\n\n## Example\n\nThe table shown shows data from a study on treatments for healing severe infections. Calculate the exact p-value of this contingency table using the Fisher’s Exact Test.\n\n- Under the alternative hypothesis: The test treatment is positively associated with the outcome.\n- Under the alternative hypothesis: The test treatment is associated with the outcome.\n- At a significance level of 0.10, do you have enough evidence to conclude that the treatment is associated with the outcome?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Test            5           1\n  Control         1           3\n```\n\n\n:::\n:::\n\n\n## Example\n\n:::: panel-tabset\n### SAS Code\n\n``` r\ndata severe;\ninput treat $ outcome $ count;\ndatalines;\nTest f 5\nTest u 1\nControl f 1\nControl u 3\n;\nproc freq order=data data=severe;\nweight count;\ntables treat*outcome / chisq nocol;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Treatment=factor(c(\"Test\",\"Control\"),levels=c(\"Test\",\"Control\")),\n                  Outcome = factor(c(\"Favorable\",\"Unfavorable\"),levels=c(\"Favorable\",\"Unfavorable\"))) \ndat$count <- c(5,1,1,3)\n\ndat_cc <- xtabs(count ~ .,data=dat) \ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Test            5           1\n  Control         1           3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(dat_cc, alternative = \"greater\") # one-sided\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dat_cc\np-value = 0.119\nalternative hypothesis: true odds ratio is greater than 1\n95 percent confidence interval:\n 0.5819    Inf\nsample estimates:\nodds ratio \n  10.29391 \n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(dat_cc,alternative= \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dat_cc\np-value = 0.1905\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   0.40161 930.24692\nsample estimates:\nodds ratio \n  10.29391 \n```\n\n\n:::\n:::\n\n\n### Manual p-values: 1-sided\n\n- One-sided hypothesis (+) corresponds to the the probabilities $P(X>=5)$ which are equal to or less than $P(X=5)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 5+1+1+3\nm <- 6\nk <- 6\n\ndhyper(x=5,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1142857\n```\n\n\n:::\n:::\n\n\nFor X \\> 5, the only possible value of X is 6.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=6,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004761905\n```\n\n\n:::\n:::\n\n\nThe p-value is then the sum of these two probabilities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=5,m=m,n=N-m,k=k) + dhyper(x=6,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1190476\n```\n\n\n:::\n:::\n\n\n### Manual p-values: 2-sided\n\n- Two-sided hypothesis need to include values $P(X<5)$ that have probabilities lower than $P(X=5)$. These probabilities will be added to the one-sided p-value to get the two-sided p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=4,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4285714\n```\n\n\n:::\n\n```{.r .cell-code}\ndhyper(x=3,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3809524\n```\n\n\n:::\n\n```{.r .cell-code}\ndhyper(x=2,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07142857\n```\n\n\n:::\n\n```{.r .cell-code}\ndhyper(x=1,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\ndhyper(x=0,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n$P(X=0)$, $P(X=1)$, and $P(X=2)$ have lower probabilities compared to $P(X=5)$. Hence, we add these probabilities to the one-sided p-value to get the two-sided p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=5,m=m,n=N-m,k=k) + dhyper(x=6,m=m,n=N-m,k=k) + dhyper(x=2,m=m,n=N-m,k=k) + dhyper(x=1,m=m,n=N-m,k=k) + dhyper(x=0,m=m,n=N-m,k=k) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1904762\n```\n\n\n:::\n:::\n\n\n### Answers\n\n- Under the alternative hypothesis: The test treatment is positively associated with the outcome. p=0.119\n- Under the alternative hypothesis: The test treatment is associated with the outcome. p= 0.1905\n- At a significance level of 0.10, do you have enough evidence to conclude that the treatment is associated with the outcome? **At** $\\alpha = 0.10$, **we do not have sufficient evidence to conclude that treatment is associated with the outcomes in healing severe infections.**\n\n::: callout-note\nIn SAS, be careful when selecting which one-sided alternative hypothesis to interpret from the results!\n:::\n::::\n\n## Exercise\n\nFisher’s experiment: A number of individuals gathered together for afternoon tea. A lady in the group said that she could differentiate between whether the milk or the tea was poured first into a cup. Fisher suggested to pour tea first into four cups and to pour milk first into four cups. The lady was blinded to which cups had milk or tea poured first, but she knew there were four of each. The contingency table is shown below. At $\\alpha=0.05$, do we have sufficient evidence to conclude that the lady can differentiate tea based on how they were poured?\n\n:::: panel-tabset\n### Contingency Table\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n      Guess\nActual Milk Tea\n  Milk    3   1\n  Tea     1   3\n```\n\n\n:::\n:::\n\n\n### SAS Code\n\n``` r\ndata tea;\ninput actual$ guess $ count;\ndatalines;\nmilk milk 3\nmilk tea 1\ntea milk 1\ntea tea 3\n;\n\nproc freq data=tea order=data;\nweight count;\ntables actual*guess/chisq;\nrun;\n```\n\nDirection is specified, hence we need to use the \"\\>\" one-sided p-value.\n\n### R `fisher.exact()`\n\nDirection is specified, hence we need to use the \"\\>\" one-sided p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Actual=factor(c(\"Milk\",\"Tea\"),levels=c(\"Milk\",\"Tea\")),\n                  Guess = factor(c(\"Milk\",\"Tea\"),levels=c(\"Milk\",\"Tea\")))\n\ndat$count <- c(3,1,1,3)\n\ndat_cc <- xtabs(count ~ .,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Guess\nActual Milk Tea\n  Milk    3   1\n  Tea     1   3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(dat_cc, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  dat_cc\np-value = 0.2429\nalternative hypothesis: true odds ratio is greater than 1\n95 percent confidence interval:\n 0.3135693       Inf\nsample estimates:\nodds ratio \n  6.408309 \n```\n\n\n:::\n:::\n\n\n### Hypergeometric: `R`\n\nDirection is specified, hence we need to use the \"\\>\" one-sided p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 8\nm <- 4\nk <- 4\n\ndhyper(x=3,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2285714\n```\n\n\n:::\n:::\n\n\nThe only other possible value of $X$ is $X=4$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=4,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01428571\n```\n\n\n:::\n:::\n\n\nTo get the one-sided p-value, we need to add these two probabilities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x=3,m=m,n=N-m,k=k) + dhyper(x=4,m=m,n=N-m,k=k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2428571\n```\n\n\n:::\n:::\n\n\n::: callout-note\nNote that we needed to add $P(X=4)$ because its value is less than that of $P(X=3)$.\n:::\n\n### Answer\n\nThe resulting p-value is 0.2429. At significance level $\\alpha=0.05$, we fail to reject the null hypothesis. We have no sufficient evidence to conclude that the lady can differentiate tea based on how they were poured.\n::::\n\n# Difference in Proportions\n\n## Difference in Proportions\n\nWe are often interested in comparing two independent populations. For binary responses, we can compare proportions of success.\n\n::: callout-note\nRecall from Intro to Stats course: we can estimate the confidence intervals and standardized statistics for the difference of two proportions.\n:::\n\n## Difference in Proportions: Estimation\n\nEstimating the difference of the two proportions involves calculating the confidence intervals. There are different methods to calculate the confidence interval for the difference in proportion.\n\n![](img/DiffProp1.png){fig-align=\"center\"} \n\n\n::: callout-note \n\nIndependence of the two populations (Groups 1 and 2) mean that we have two independent binomial distributions. \n\n:::\n\n## Confidence Intervals: Wald\n\nThe commonly used confidence interval in estimating difference in proportions is the **Wald** confidence interval.\n\n$$p_1-p_2 \\pm z_{1-\\alpha/2}\\sqrt{\\frac{p_1(1-p_1)}{n_{1+}} + \\frac{p_2(1-p_2)}{n_{2+}}}$$\n\n::: callout-warning\nThis CI fails when $p_1$ or $p_2$ are close to the extreme values (0 and 1). this CI does not account for the discreteness of the data.\n:::\n\n## Confidence Intervals: Corrected Wald\n\nWe introduce a correction term to the Wald confidence interval to account for the continuity of the data.\n\n$$p_1-p_2 \\pm z_{1-\\alpha/2}\\sqrt{\\frac{p_1(1-p_1)}{n_{1+}} + \\frac{p_2(1-p_2)}{n_{2+}}} +1/2 (1/n_{1+} +1/n_{2+} )$$\n\n::: callout-warning\nThis CI still fails when $p_1$ or $p_2$ are close to the extreme values (0 and 1).\n:::\n\n## Confidence Intervals: Agresti-Caffo\n\nWe introduce a correction term to the Wald confidence interval to account for the extreme values.\n\n$$p_1-p_2 \\pm z_{1-\\alpha/2}\\sqrt{\\frac{\\tilde{p}_1(1-\\tilde{p}_1)}{n_{1+}+2} + \\frac{\\tilde{p}_2(1-\\tilde{p}_2)}{n_{2+}+2}}  $$\nwhere\n\n$$\\tilde{p}_1 = (n_{11}+1)/(n_{1+}+2) ; \\tilde{p}_2 = (n_{21}+1)/(n_{2+}+2)$$\n\n::: callout-note\nThis correction keeps the coverage of the confidence interval at 95% for all possible values of $p_1$ and $p_2$.\n:::\n\n## Other Confidence Intervals\n\n| Confidence Intervals | SAS code | R code | Adjustment Type |\n|-------------------|-----------|---------|----------------------------------|\n| Wald | `wald` | \"wald\" | Default |\n| Corrected Wald | `correct` | \"waldcc\" | Continuity correction |\n| Agresti-Caffo | `ac` | \"ac\" | Improved Coverage |\n| Miettinen-Nurminen | `mn` | \"mn\" | Uses goodness-of-fit to improve coverage |\n| Newcombe | `newcombe` | \"scorecc\" | hybrid interval that does well for small counts |\n| Hauck-Anderson | `ha` | \"ha\" | Accounts for row totals |\n\n## Confidence Intervals: `SAS`\n\n- The FREQ procedure has all mentioned confidence intervals\n  - The options included in the `tables` statement are included in the previous slide.\n  - The `riskdiff` option of the `tables` statement allows us to specify which confidence intervals we need for the difference as well as the estimates for the group proportions.\n  - The `alpha` option can be used to change the confidence level.\n\nSample SAS code:\n\n``` {.r code-line-numbers=\"3\"}\nproc freq;\nweight count;\ntables treat*outcome/riskdiff(correct cl=(mn ac)) alpha=0.05;\nrun;\n```\n\n## Confidence Intervals: `R`\n\nThe `BinomDiffCI()` function in the `DescTools` package in `R` can calculate these confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"DescTools\")\nlibrary(DescTools)\nBinomDiffCI(x1=n11, n1 = row1sum, x2 = n21, n2=row2sum,\n            conf.level=0.95, \n            method = c(\"ac\", \"wald\", \"waldcc\", \"score\", \"scorecc\", \"mn\",\n                       \"mee\", \"blj\", \"ha\", \"hal\", \"jp\") \n            )\n```\n:::\n\n\n\n## Example\n\n\nThe contingency table shows the information from a randomized clinical trial that compared an experimental treatment to a placebo treatment for a respiratory disorder. \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Placebo        16          48\n  Test           40          20\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n\n### Question\n\nCalculate the 95% confidence interval for the difference in proportion of favorable outcomes for both treatment groups.\n\n- Wald\n- Corrected Wald\n- Agresti-Caffo\n- Miettinen-Nurminen\n\n### SAS Code\n\n``` {.r code-line-numbers=\"12\"}\ndata respire;\ninput treat $ outcome $ count; \ndatalines;\ntest f 40\ntest u 20\nplacebo f 16\nplacebo u 48\n;\n\nproc freq data=respire order=data; \nweight count; \ntables treat*outcome/riskdiff(cl=(mn ac)) alpha=0.05; \ntables treat*outcome/riskdiff(correct) alpha=0.05; \nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(Treatment=c(\"Placebo\",\"Test\"),\n                  Outcome = c(\"Favorable\",\"Unfavorable\")) \ndat$count <- c(16,40,48,20)\n\ndat_cc <- xtabs(count ~ .,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Placebo        16          48\n  Test           40          20\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DescTools)\nBinomDiffCI(x1=40,\n            n1 = 40+20,\n            x2=16,\n            n2=16+48,\n            method=c('wald','waldcc','ac','mn'),\n            conf.level = 0.95) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             est    lwr.ci    upr.ci\nwald   0.4166667 0.2570362 0.5762972\nwaldcc 0.4166667 0.2408903 0.5924430\nac     0.4166667 0.2455745 0.5618546\nmn     0.4166667 0.2460145 0.5626554\n```\n\n\n:::\n:::\n\n\n### Answers\n\nThe estimated difference in proportion is 0.4167 with the following 95% confidence intervals:\n- Wald: **0.2570-0.5763**\n- Corrected Wald: **0.2409-0.5924**\n- Agresti-Caffo: **0.2456-0.5416**\n- Miettinen-Nurminen **0.2460-0.5627**\n:::\n\n\n\n\n## Exercise\n\n\nOne of the most famous and largest clinical trials ever performed was in 1954. The data obtained from this RCT is shown in the contingency table.\n\n\n![](img/DiffProp2.png)\n\n\n::: panel-tabset\n\n### Problem\n\nCalculate the *90%* confidence interval for the difference in proportion of polio-free children between the vaccine and placebo group.\n\n- Corrected Wald\n- Miettinen-Nurminen\n- Newcombe\n\n### `SAS` Code\n\n``` {.r code-line-numbers=\"14\"}\ndata vaxx;\nlength treat $7.;\ninput treat $ outcome $ count; \ndatalines;\nvax n 200688\nvax p 57\nplacebo n 201087\nplacebo p 142\n;\n\nproc freq data=vaxx order=data;\nweight count;\ntables treat*outcome/riskdiff(correct cl=(mn newcombe)) \nalpha=0.10;\nrun;\n```\n\n### `R` Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\nBinomDiffCI(x1=142,\n            n1=201087+142,\n            x2=57,\n            n2 = 57+200688,\n            method=c('waldcc','mn','newcombe'),\n            conf.level = 0.9) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                est       lwr.ci       upr.ci\nwaldcc 0.0004217214 0.0003013909 0.0005420518\nmn     0.0004217214 0.0003084844 0.0005405825\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThe estimated difference in proportion is 0.0004.\n\n- Corrected Wald **(0.0003,0.0005)**\n- Miettinen-Nurminen **(0.0003,0.0005)**\n- Newcombe **(0.0003,0.0005)**\n\n:::\n\n# Odds Ratio and Relative Risk\n\n## Odds Ratio (OR)\n\n::: callout-note\n### Odds of success\n\nThe ratio of probability of success and failure of an outcome is referred to as the odds.\n\n$$\nOdds = p/(1-p)\n$$\n:::\n\n::: callout-tip\n### Odds Ratio\nThe ratio of the odds of success for Group 1 and Group 2 is referred to as the odds ratio.\n$$\nOR = \\frac{p_1/(1-p_1)}{p_2/(1-p_2)} = (n_{11}n_{22}/n_{21}n_{12})\n$$\n\nThe odds ratio is commonly used as an effect size for retrospective studies. This statistic is also used in logistic regression techniques, which will be discussed later.\n:::\n\n## Relative Risk (RR)\n\nThe ratio of the risk developing a particular condition for individuals with risk factors present and absent is called the *relative risk*.\n\n$$\nRR = p_1/p_2 = \\frac{(n_{11}/n_{1+})}{(n_{21}/n_{2+})}\n$$\n\nThe relative risk is commonly used as an effect size in prospective studies.\n\n::: callout-note\nFor cross-sectional data, the relative risk is known as the prevalence ratio because the disease and risk factor are assessed at the same time.\n:::\n\n## Odds Ratio & Relative Risk \n\n- When OR, RR \\> 1, Group 1 is **more likely** than Group 2 to record success.\n- When OR, RR\\< 1, Group 1 is **less likely** to record success.\n- When OR, RR= 1, there is **no association** between group and success because the two groups are equally likely to record success.\n\n::: callout-note\nWhen the condition is rare, the OR is approximately equal to the RR.\n:::\n\n## Odds Ratio & Relative Risk: `SAS`\n\n- OR and RR are calculated using the measures option in the TABLES statement in PROC FREQ.\n- For small sample sizes, the exact confidence limits can be calculated for the odds ratios.\n\n``` {.r code-line-numbers=\"3,4\"}\nproc freq;\nweight count;\ntables a*b/measures;\nexact or rr;\nrun;\n```\n\n## Odds Ratio & Relative Risk: `R`\n\nThe odds ratio and relative risk can be calculated using functions from the `epitools` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epitools)\noddsratio(contingency_table,\n          conf.level = 0.95,\n          method=c(\"fisher\",\"wald\")\n)\n\nriskratio(contingency_table,\n          conf.level = 0.95,\n          method=c(\"fisher\",\"wald\")\n)\n```\n:::\n\n\n::: callout-tip\nThe `fisher` method provides exact confidence intervals for relative risk and odds ratio. The `fisher.test()` function provides an exact confidence interval for the odds ratio based on the hypergeometric distribution, but it does not include the relative risk.\n:::\n\n\n## Example\n\nThe contingency table shows data from a study on treatments for severe infections. Calculate the asymptotic and exact confidence limits for the odds ratio of favorable outcomes for test and control groups.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Test           10           2\n  Control         2           4\n```\n\n\n:::\n:::\n\n\n## Example\n\nThe data set `severe_long.csv` includes data  from a study on treatments for severe infections. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read.csv(\"severe_long.csv\")\nhead(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment   Outcome\n1      Test Favorable\n2      Test Favorable\n3      Test Favorable\n4      Test Favorable\n5      Test Favorable\n6      Test Favorable\n```\n\n\n:::\n:::\n\n\n\n::: panel-tabset\n\n### Problem\n\nCalculate the asymptotic and exact confidence limits for the odds ratio of favorable outcomes for test and control groups.\n\n### `SAS` Code\n\n``` r\n\nproc freq order=data data=severe;\nweight count;\ntables treat*outcome / chisq nocol;\nexact or;\nrun;\n```\n\n| Method     | Value and CI         |\n|------------|----------------------|\n| Asymptotic | 10 (1.0256, 97.5005) |\n| Exact      | 10 (0.6896,166.3562) |\n\n**The two methods lead to different conclusions.**\n\n### `R` Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(~Treatment+Outcome,data=dat)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Favorable Unfavorable\n  Control         2           4\n  Test           10           2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(epitools)\n\noddsratio(dat_cc,\n          method=c(\"wald\"),\n          conf.level=0.95,\n          rev=\"rows\" #Reverses the rows\n          )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n         Outcome\nTreatment Favorable Unfavorable Total\n  Test           10           2    12\n  Control         2           4     6\n  Total          12           6    18\n\n$measure\n         odds ratio with 95% C.I.\nTreatment estimate    lower    upper\n  Test           1       NA       NA\n  Control       10 1.025636 97.50049\n\n$p.value\n         two-sided\nTreatment midp.exact fisher.exact chi.square\n  Test            NA           NA         NA\n  Control 0.06119371    0.1070351 0.03389485\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n\n```{.r .cell-code}\noddsratio(dat_cc,\n          method=c(\"fisher\"),\n          conf.level=0.95,\n          rev=\"rows\" #Reverses the rows\n          )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n         Outcome\nTreatment Favorable Unfavorable Total\n  Test           10           2    12\n  Control         2           4     6\n  Total          12           6    18\n\n$measure\n         odds ratio with 95% C.I.\nTreatment estimate     lower    upper\n  Test    1.000000        NA       NA\n  Control 8.457238 0.6896384 166.4345\n\n$p.value\n         two-sided\nTreatment midp.exact fisher.exact chi.square\n  Test            NA           NA         NA\n  Control 0.06119371    0.1070351 0.03389485\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Conditional MLE & exact CI from 'fisher.test'\"\n```\n\n\n:::\n:::\n\n\n::: callout-note\nWe report the **estimate** of the odds ratio from the `\"wald\"` method, but use the `\"fisher\"` confidence interval as the exact confidence interval.\n:::\n\n:::\n## Exercise\n\nTwo groups having the same symptoms of respiratory illness were sampled. One group was treated with an experimental treatment and the other group was treated with a placebo. The participants were asked whether there was an overall treatment in overall respiration.\n\n- Calculate the odds ratio of respiratory improvement between test and placebo groups.\n- What is the relative risk of having respiratory improvement if we consider the treatment as a risk factor?\n- Calculate the asymptotic 95% CI for each answer.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Yes No\n  Test     29 16\n  Placebo  14 31\n```\n\n\n:::\n:::\n\n\n## Exercise\n\nTwo groups having the same symptoms of respiratory illness were sampled. One group was treated with an experimental treatment and the other group was treated with a placebo. The participants were asked whether there was an overall treatment in overall respiration.\n\n- Calculate the odds ratio of respiratory improvement between test and placebo groups.**4.01 (1.67,9.66)**\n- What is the relative risk of having respiratory improvement if we consider the treatment as a risk factor? **2.07 (1.27,3.37)**\n- Calculate the asymptotic 95% CI for each answer.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Outcome\nTreatment Yes No\n  Test     29 16\n  Placebo  14 31\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### SAS Code\n\n``` r\ndata resp;\ninput  Treatment $ Outcome  $ count;\ndatalines;\nTest Yes 29\nPlacebo Yes 14\nTest No 16\nPlacebo No 31\n;\nproc freq data=resp order=data;\nweight count;\ntables treatment*outcome/measures;\nrun;\n```\n\n### R Code\n\nOdds ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epitools)\ndat_cc |> oddsratio(rev=c(\"both\"), method=\"wald\",conf.level=0.95) -> or\nor$measure\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         odds ratio with 95% C.I.\nTreatment estimate    lower    upper\n  Placebo 1.000000       NA       NA\n  Test    4.013393 1.668039 9.656441\n```\n\n\n:::\n:::\n\n\nRelative Risk\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc |> riskratio(rev=c(\"both\"),method=\"wald\")->rr\nrr$measure\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         risk ratio with 95% C.I.\nTreatment estimate    lower    upper\n  Placebo 1.000000       NA       NA\n  Test    2.071429 1.274194 3.367474\n```\n\n\n:::\n:::\n\n:::\n\n# Sensitivity and specificity\n\n## Sensitivity\n\nTrue proportion of positive results that a test elicits when performed on subjects known to have the disease.\n\n$$Sens=TP/(TP+FN) = n_{11}/n_{1+}$$\nSensitivity is the conditional probability of a positive test given that the subject has the disease ($P(PT|HD)$)\n\n## Specificity\n\nTrue proportion of negative results that a test elicits when performed on subjects known to be disease free.\n\n$$Sens=TN/(TN+FP) = n_{22}/n_{2+}$$\nSpecificity is the conditional probability of a negative test when the subject does not have the disease ($P(NT|ND)$).\n\n## Sensitivity and Specificity: SAS\n\nThe `FREQ` procedure can also calculate sensitivity and specificity.\n\n- `riskdiff` approximates these metrics using the risk estimates.\n  - Sensitivity: Row 1 risk estimate for Column 1\n  - Specificity: Row 2 risk estimate for Column 2\n\n## Example\n\nThe following table shows the results of a study investigating a new screening device for a skin disease. Calculate the sensitivity and specificity of the screening device.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Test\nStatus            Positive Negative\n  Disease Present       52        8\n  Disease Absent        20      100\n```\n\n\n:::\n:::\n\n\n## Example\n\nThe following table shows the results of a study investigating a new screening device for a skin disease. Calculate the sensitivity and specificity of the screening device.\n\n- Sensitivity: 0.87 (0.75,0.94)\n- Specificity: 0.83 (0.75,0.90)\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Test\nStatus            Positive Negative\n  Disease Present       52        8\n  Disease Absent        20      100\n```\n\n\n:::\n:::\n\n\nSAS Code\n\n``` r\ndata screening;\ninput disease $ outcome $ count @@;\ndatalines;\npresent + 52 present - 8\nabsent + 20 absent - 100\n;\nproc freq data=screening order=data;\nweight count;\ntables disease*outcome / riskdiff;\nrun;\n```\n\n## Exercise\n\nA pharmaceutical company developed a screening test that can be used to detect infection of the Lassa (virus). The newly developed test was said to be cheaper than the tests currently available to the public, but its performance was yet to be evaluated. The screening test was applied to 115 diagnosed cases (w/ Lassa virus) and 120 control participants (w/o Lassa virus) of the Lassa fever. The resulting contingency table is shown in the table.\n\n- What is the sensitivity of the test?\n- What is the specificity of the test?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Test\nStatus            Positive Negative\n  Disease Present       97       18\n  Disease Absent        45       75\n```\n\n\n:::\n:::\n\n\n## Exercise\n\nA pharmaceutical company developed a screening test that can be used to detect infection of the Lassa (virus). The newly developed test was said to be cheaper than the tests currently available to the public, but its performance was yet to be evaluated. The screening test was applied to 115 diagnosed cases (w/ Lassa virus) and 120 control participants (w/o Lassa virus) of the Lassa fever. The resulting contingency table is shown in the table.\n\n- What is the sensitivity of the test? **0.8435 (0.76, 0.90)**\n- What is the specificity of the test? **0.6250 (0.53, 0.71)**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Test\nStatus            Positive Negative\n  Disease Present       97       18\n  Disease Absent        45       75\n```\n\n\n:::\n:::\n\n\n### SAS Code\n\n``` r\ndata screening;\ninput disease $ outcome $ count @@;\ndatalines;\npresent + 97 present - 18\nabsent + 45 absent - 75\n;\nproc freq data=screening order=data;\nweight count;\ntables disease*outcome / riskdiff;\nrun;\n```\n\n# McNemar's Test\n\n## McNemar's Test\n\n- When the 2x2 table provides information from matched pairs, the two responses are related to each other. Hence, independence cannot be assumed.\n\n- Null hypothesis: The marginal probabilities of each outcome are the same.\n\n- The test statistic for the McNemar’s test is $Q_M$ given by\n\n$$Q_M = (n_{12}-n_{21})^2/(n_{12}+n_{21})$$\n\n## McNemar's Test: SAS\n\n- The `agree` option in the `tables` statement can be used to perform the McNemar's test.\n- Exact p-values can be calculated using the `exact` statement.\n\n### Sample SAS Code\n\n``` r\nproc freq;\nweight count;\ntables a*b/agree;\nexact mcnem;\nrun;\n```\n\n## Example\n\nThe table displays data collected by political science researchers who polled husbands and wives on whether they approved of one of their U.S. senators. The cell counts represent the number of pairs of husbands and wives who fit the configurations indicated by the row and column levels. Use the McNemar’s test to determine whether there is no difference in husband and wife approvals on the state senator.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       Wife\nHusband Yes No\n    Yes  20  5\n    No   10 10\n```\n\n\n:::\n:::\n\n\n## Example\n\nThe table displays data collected by political science researchers who polled husbands and wives on whether they approved of one of their U.S. senators. The cell counts represent the number of pairs of husbands and wives who fit the configurations indicated by the row and column levels. Use the McNemar’s test to determine whether there is no difference in husband and wife approvals on the state senator.\n\n- Exact p-value = 0.3018, which implies that there is no evidence of a difference between the senator approval ratings of the husbands and wives.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       Wife\nHusband Yes No\n    Yes  20  5\n    No   10 10\n```\n\n\n:::\n:::\n\n\n### SAS Code\n\n``` {.r code-line-numbers=\"12,13\"}\ndata approval;\ninput hus_resp $ wif_resp $ count;\ndatalines;\nyes yes 20\nyes no 5\nno yes 10\nno no 10\n;\n\nproc freq order=data;\nweight count;\ntables hus_resp*wif_resp / agree;\nexact mcnem;\nrun;\n```\n\n## Exercise\n\nThe tables show the data from a study that compared the diagnostic accuracy of magnetic resonance imaging (MRI) and ultrasound in patients who had been established as having localized prostate cancer by a gold standard test.\n\n- Use the McNemar’s test to determine whether the two methods have a different probabilities in diagnosing localized prostate cancer. (*Hint: Small cell counts*)\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Ultrasound\nMRI         Localized Advanced\n  Localized         4        6\n  Advanced          3        3\n```\n\n\n:::\n:::\n\n\n## Exercise\n\nThe tables show the data from a study that compared the diagnostic accuracy of magnetic resonance imaging (MRI) and ultrasound in patients who had been established as having localized prostate cancer by a gold standard test.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Ultrasound\nMRI         Localized Advanced\n  Localized         4        6\n  Advanced          3        3\n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n### Answer\n\n- Use the McNemar’s test to determine whether the two methods have a different probabilities in diagnosing localized prostate cancer. (*Hint: Small cell counts*)\n  - Use exact p-value\n  - $p=0.5078$. No evidence of any difference in probabilities in correctly diagnosing localized prostate cancer.\n\n### SAS Code\n\n``` r\ndata imaging;\ninput mri $ ult $ count;\ndatalines;\nloc loc 4\nloc adv 6\nadv loc 3\nadv adv 3\n;\n\nproc freq order=data;\nweight count;\ntables mri*ult / agree;\nexact mcnem;\nrun;\n```\n:::\n\n# Incidence Densities\n\n## Incidence Densities {.smaller}\n\n- Counts of subjects who responded within a duration of exposure to an event.\n- Poisson distribution: counts\n- Examples:\n  - Bacteria colony count\n  - Disease incidence\n  - Accidents\n  - Vaccine failure\n- Common measure of duration of exposure/ time-at-risk: person-time\n\n## Poisson Distribution\n\nRecall that the Poisson distribution is described by the following density function:\n\n$$P(x)= e^{-\\lambda}\\lambda^x/x!$$\n\nwhere $\\lambda$ is the expected number of events at a given unit of time.\n\n- \\lambda is also referred to as incidence density.\n- For $t$ units of time, the expected number of events scales to $\\lambda t$.\n- Main assumption: The time to event is a random variable following an exponential distribution.\n\n## Incidence Density Ratios\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 85%\"}\n- The table shows the number of infections (events) and person years for participants of an RCT.\n  - $n_v$ and $n_p$ are Poisson random variables with respective incidence densities equal to $\\lambda_v$ and $\\lambda_p$\n- If $\\lambda_v$ is the incidence density for the vaccine group, then the expected number of events is $\\lambda_v N_v$.\n- Similarly, the expected number of events in the placebo group is $\\lambda_p N_p$\n- We are interested in testing the null hypothesis $\\lambda_v/\\lambda_p = 1$.\n  - $\\lambda_v/\\lambda_p$ is referred to as the **Incidence Density Ratio (IDR)**\n:::\n\n::: {.column width=\"50%\"}\n![](img/IDR.png)\n:::\n:::::\n\n## Incidence Density Ratios\n\nThe IDR can be estimated using conditional binomial distributions assuming $n_v$ and $n_p$ are independent Poisson processes.\n\n$$P(n_v|n_v+n_p) \\sim Bin\\left(N=n_v + n_p, p = \\frac{\\lambda_vN_v}{\\lambda_vN_v+\\lambda_pN_p}\\right)$$\n\n## Incidence Density Ratios: Confidence Interval\n\nThe binomial proportion can be estimated using the proportion of events in the treatment group:\n\n$$p = \\frac{n_v}{n_v+n_p} = \\frac{IDR(N_v/N_p)}{1+(IDR)(N_v/N_p)}$$\nUsing algebra (Problem Set 1), *it is easy to show that*:\n\n$$IDR = \\frac{p}{1-p}\\left(N_p/N_v\\right)$$\n\n## Incidence Density Ratios: Confidence Interval\n\nYou can calculate the confidence interval estimates for $p$ using the binomial distribution assumption ($p_L,p_U$) and apply the scaling factor to each confidence limit.\n\n$$95\\% CI: \\left(\\frac{p_L}{1-p_L}(N_p/N_v),\\frac{p_U}{1-p_U}(N_p/N_v)\\right)$$\n\n## Incidence Density Ratios: SAS\n\n- The `binomial` option in the `tables` statement produces the estimate and exact confidence limits for the binomial proportion $p$, i.e. $p_L$ and $p_U$.\n- We use the estimate and exact confidence limits of $p$ in calculating the IDR.\n- The `IML` procedure, which is the procedure used to perform mathematical equations, is used to calculate the IDR confidence limits.\n  - Later on, we will use the `GENMOD` procedure to calculate exact confidence intervals for the IDR.\n\n## Example\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 95%\"}\nThe table shows the results of an international study of the effect of a rotavirus vaccine in nearly 70,000 infants on health care events. The events counted were hospitalizations or emergency room visits.\n\n- Estimate the IDR of hospitalization/emergency room visits between the two groups.\n- Calculate the 95% CI.\n:::\n\n::: {.column width=\"50%\"}\n![](img/IDR.png)\n:::\n:::::\n\n## Example\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 95%\"}\nThe table shows the results of an international study of the effect of a rotavirus vaccine in nearly 70,000 infants on health care events. The events counted were hospitalizations or emergency room visits.\n\n- Estimate the IDR of hospitalization/emergency room visits between the two groups. **IDR = 0.05**\n- Calculate the 95% CI. **(0.01, 0.15)**\n:::\n\n::: {.column width=\"50%\"}\n![](img/IDR2.png)\n:::\n:::::\n\n::: panel-tabset\n### SAS Code\n\n``` {.r code-line-numbers=\"12,13,16-27\"}\ndata vaccine2;\ninput Outcome $ Count @@;\ndatalines;\nvaccine 3 placebo 58\n;\n\nods select BinomialCLs; *this statement filters the output.;\n\n\nproc freq order=data data=vaccine2; # <1>\nweight count;\ntables Outcome / binomial (exact); *calculates the exact confidence limits for the binomial proportion;\nods output BinomialCLs=BinomialCLs; *outputs a dataset that includes the binomial CLs.;\nrun;\n\nproc iml ;\nUse BinomialCLs var{LowerCL UpperCL};\nread all into CL;\nprint CL;\nq = { 3, 7500, 58 , 7250 }; *vector of numbers from the table;\nC= q[2]/q[4]; *q[i] represents the ith number in the q vector defined above. C is the person-years ratio Nv/Np;\nP= q[1]/ (q[1] + q[3]); *estimate of the binomial distribution;\nR= P/ ((1-P) *C) ; * IDR estimate;\nCI= CL[1]/((1-CL[1])*C) || CL[2]/((1-CL[2])*C) ; *IDR CL;\nprint r CI;\nquit;\n```\n\n1.  `order=data` is important so as to keep the proportions consistent.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevents <- c(3,58)\nperson_years <- c(7500, 7250)\n\nmult <- person_years[2]/person_years[1] #multiplier\nDescTools::BinomCI(events[1],sum(events),method = \"clopper-pearson\") -> p_est\n\n\n\ndata.frame(IDR = p_est[1]/(1-p_est[1])*mult,\n           IDR_lower = p_est[2]/(1-p_est[2])*mult,\n          IDR_higher = p_est[3]/(1-p_est[3])*mult) |> gt::gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wqrzaiitik\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wqrzaiitik table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wqrzaiitik thead, #wqrzaiitik tbody, #wqrzaiitik tfoot, #wqrzaiitik tr, #wqrzaiitik td, #wqrzaiitik th {\n  border-style: none;\n}\n\n#wqrzaiitik p {\n  margin: 0;\n  padding: 0;\n}\n\n#wqrzaiitik .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wqrzaiitik .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wqrzaiitik .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wqrzaiitik .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wqrzaiitik .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wqrzaiitik .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wqrzaiitik .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wqrzaiitik .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wqrzaiitik .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wqrzaiitik .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wqrzaiitik .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wqrzaiitik .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wqrzaiitik .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wqrzaiitik .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wqrzaiitik .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrzaiitik .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wqrzaiitik .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wqrzaiitik .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wqrzaiitik .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrzaiitik .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wqrzaiitik .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrzaiitik .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wqrzaiitik .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrzaiitik .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrzaiitik .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrzaiitik .gt_left {\n  text-align: left;\n}\n\n#wqrzaiitik .gt_center {\n  text-align: center;\n}\n\n#wqrzaiitik .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wqrzaiitik .gt_font_normal {\n  font-weight: normal;\n}\n\n#wqrzaiitik .gt_font_bold {\n  font-weight: bold;\n}\n\n#wqrzaiitik .gt_font_italic {\n  font-style: italic;\n}\n\n#wqrzaiitik .gt_super {\n  font-size: 65%;\n}\n\n#wqrzaiitik .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wqrzaiitik .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wqrzaiitik .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wqrzaiitik .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wqrzaiitik .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wqrzaiitik .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wqrzaiitik .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wqrzaiitik .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wqrzaiitik div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR\">IDR</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR_lower\">IDR_lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR_higher\">IDR_higher</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"IDR\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"IDR_lower\" class=\"gt_row gt_right\">0.01002014</td>\n<td headers=\"IDR_higher\" class=\"gt_row gt_right\">0.1535468</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n## Exercise\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 85%\"}\nThe table lists the number of accidents for day and night shift workers at a certain factory in Southeast Asia. The company wants you to investigate if there is any evidence of night shift workers having a higher accident density, i.e., higher incidence density of accidents, compared to the day shift.\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       Metric\nShift   Accidents Person-Hours\n  Night        25         1150\n  Day          20         1240\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n## Exercise\n\n::::: columns\n::: {.column style=\"width:50%; font-size: 85%\"}\nThe table lists the number of accidents for day and night shift workers at a certain factory in Southeast Asia. The company wants you to investigate if there is any evidence of night shift workers having a higher accident density, i.e., higher incidence density of accidents, compared to the day shift.\n\n- IDR: 1.37\n- 95% CI: (0.72,2.56)\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       Metric\nShift   Accidents Person-Hours\n  Night        25         1150\n  Day          20         1240\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n::: panel-tabset\n### SAS Code\n\n``` r\ndata accident;\n/*data only has the events. Person-Hours are used later.*/\ninput Outcome $ Count @@;\ndatalines;\nnight 25 day 20 # <1>\n;\n\nods select BinomialCLs; *this statement filters the output.;\n\nproc freq order=data data=accident;\nweight count;\ntables Outcome / binomial (exact) alpha=0.05; *calculates the exact confidence limits for the binomial proportion;\nods output BinomialCLs=BinomialCLs; *outputs a dataset that includes the binomial CLs.;\nrun;\n\nproc iml ;\nUse BinomialCLs var{LowerCL UpperCL};\nread all into CL;\nprint CL;\nq = { 25 1150 20 1240 }; *vector of numbers from the table;\nC= q[2]/q[4]; *q[i] represents the ith number in the q vector defined above. C is the person-years ratio Nv/Np;\nP= q[1]/ (q[1] + q[3]); *estimate of the binomial distribution;\nR= P/ ((1-P) *C) ; * IDR estimate;\nCI= CL[1]/((1-CL[1])*C) || CL[2]/((1-CL[2])*C) ; *IDR CL;\nprint r CI;\nquit;\n```\n\n1.  \"Success\" is an event happening during the night shift.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevents <- c(25,20)\nperson_years <- c(1150,1240)\n\nmult <- person_years[2]/person_years[1] #multiplier\nDescTools::BinomCI(events[1],sum(events),method = \"clopper-pearson\") -> p_est\n\n\n\ndata.frame(IDR = p_est[1]/(1-p_est[1])*mult,\n           IDR_lower = p_est[2]/(1-p_est[2])*mult,\n          IDR_higher = p_est[3]/(1-p_est[3])*mult) |> gt::gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zbvyrzjghl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zbvyrzjghl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zbvyrzjghl thead, #zbvyrzjghl tbody, #zbvyrzjghl tfoot, #zbvyrzjghl tr, #zbvyrzjghl td, #zbvyrzjghl th {\n  border-style: none;\n}\n\n#zbvyrzjghl p {\n  margin: 0;\n  padding: 0;\n}\n\n#zbvyrzjghl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zbvyrzjghl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zbvyrzjghl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zbvyrzjghl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zbvyrzjghl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zbvyrzjghl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zbvyrzjghl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zbvyrzjghl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zbvyrzjghl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zbvyrzjghl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zbvyrzjghl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zbvyrzjghl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zbvyrzjghl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zbvyrzjghl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zbvyrzjghl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbvyrzjghl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zbvyrzjghl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zbvyrzjghl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zbvyrzjghl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbvyrzjghl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zbvyrzjghl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbvyrzjghl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zbvyrzjghl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbvyrzjghl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zbvyrzjghl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zbvyrzjghl .gt_left {\n  text-align: left;\n}\n\n#zbvyrzjghl .gt_center {\n  text-align: center;\n}\n\n#zbvyrzjghl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zbvyrzjghl .gt_font_normal {\n  font-weight: normal;\n}\n\n#zbvyrzjghl .gt_font_bold {\n  font-weight: bold;\n}\n\n#zbvyrzjghl .gt_font_italic {\n  font-style: italic;\n}\n\n#zbvyrzjghl .gt_super {\n  font-size: 65%;\n}\n\n#zbvyrzjghl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zbvyrzjghl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zbvyrzjghl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zbvyrzjghl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zbvyrzjghl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zbvyrzjghl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zbvyrzjghl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zbvyrzjghl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zbvyrzjghl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR\">IDR</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR_lower\">IDR_lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IDR_higher\">IDR_higher</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"IDR\" class=\"gt_row gt_right\">1.347826</td>\n<td headers=\"IDR_lower\" class=\"gt_row gt_right\">0.7187612</td>\n<td headers=\"IDR_higher\" class=\"gt_row gt_right\">2.559057</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n# Power Analysis\n\n## Power Analysis\n\n- Power is defined as the probability of rejecting the null hypothesis when it is false.\n  - Acceptable range: 80% and above.\n- Also known as (a priori) Sample Size Calculations\n  - How many samples do I need to detect a set difference between the treatment and placebo group at a significance level of 0.05?\n\n## Power Analysis: SAS\n\n- The `POWER` procedure enables us to calculate how many samples are needed to detect a set effect size in examining the difference between two proportions from two different populations.\n- Specifically, the TWOSAMPLEFREQ option\n  - RCT: treatment vs. control\n- We need to set an effect size (theory-based), significance level, and power level.\n  - Other options can be found [here](https://documentation.sas.com/doc/en/statug/15.2/statug_power_syntax83.htm)\n\n## Example\n\nSuppose prior literature states that the incidence rate of a chronic disease is 0.40. Suppose we want to perform a prospective study to test the association between the disease incidence and family history, i.e. whether other family members were diagnosed with the chronic disease. We want to detect a proportion difference of 0.10 between groups with power of 80% (0.80) at a significance level of 0.05.\n\n## Example\n\nSuppose prior literature states that the incidence rate of a chronic disease is 0.40. Suppose we want to perform a prospective study to test the association between the disease incidence and family history, i.e. whether other family members were diagnosed with the chronic disease. We want to detect a proportion difference of 0.10 between groups with power of 80% (0.80) at a significance level of 0.05.\n\n- We need 388 units per group (family +, family -). This brings us to 776 total units.\n\n::: panel-tabset\n### SAS Code\n\n``` r\nproc power ;\ntwosamplefreq\n    refproportion=0.4 \n    alpha=0.05\n    power=0.80\n    proportiondiff=0.1\n    npergroup=.;\n\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower.prop.test(p1=0.4,p2=0.5,power=0.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample comparison of proportions power calculation \n\n              n = 387.3385\n             p1 = 0.4\n             p2 = 0.5\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}