{
  "hash": "29983d7e8fc6027697b2272c05cac516",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAB 770 - Chapter 6\"\nauthor: \"Miguel Fudolig\"\nformat:\n  revealjs:\n    theme: clean.scss\n    scrollable: true\n    footer: \"Chapter 6- [Back to home](https://madfudolig.quarto.pub/eab770slides/)\"\n    code-block-bg: true\n    code-block-border-left: \"#31BAE9\"\n    slide-number: true\n    menu: true\n    embed-resources: false\n    self-contained-math: true\n    code-annotations: false\n    chalkboard: true\n    echo: true\n  pdf: \n    number-sections: true\n    toc: true\n---\n\n# Sets of $s \\times r$ tables\n\n## Outline\n\n-   General Mantel-Haenszel Method\n-   Mantel-Haesnzel Applications\n-   Repeated Measures\n\n## General Mantel-Haenszel Method\n\n-   Recall: 2x2, and sxr tables all use Mantel-Haenszel Statistics\n    -   Able to account for ordinality unlike Pearson Chi-Square tests\n    -   Less stringent sample size requirements for ordinal variables\n-   MH statistics in sets of contingency tables removes the confounding influence of the stratification variable.\n\n## General Mantel-Haenszel Method\n\n::: callout-note\n$H_0$: The response variable is distributed at random with respect to the groups defined by the row variables\n:::\n\nDepending on the nature of the row and column variables, the Mantel-Haenszel statistic has different forms:\n\n-   $Q_{GMH}$: General Mantel-Haenszel statistic\n-   $Q_{SMH}$: Mean Score Statistic\n-   $Q_{CSMH}$: Correlation Statistic\n\n## General Mantel-Haenszel Method {.smaller}\n\n| MH Statistic | Alternative Hypothesis     | SAS Output Label        | Degrees of Freedom | Scale Requirements              | Nonparametric Equivalents |\n|--------------|----------------------------|-------------------------|--------------------|---------------------------------|---------------------------|\n| $Q_{GMH}$    | General Association        | General Association     | $(s-1)(r-1)$       | None                            |                           |\n| $Q_{SMH}$    | Mean score location shifts | Row Means Scores Differ | $(s-1)$            | Column Variable Ordinal         | Kruskal-Wallis            |\n| $Q_{CSMH}$   | Linear Association         | Nonzero correlation     | $1$                | Row and Column Variable Ordinal | Spearman Correlation      |\n\n: Extended Mantel-Haenszel Statistics\n\n## Example\n\nInvestigators conducted a randomized clinical trial in four hospitals, where patients were assigned to one of four surgical procedures for the treatment of severe duodenal ulcers. The treatments include:\n\n- v + d: vagotomy and drainage\n- v + a: vagotomy and antrectomy (removal of 25% of gastric tissue)\n- v + h: vagatomy and hemigastrectomy (removal of 50% of gastric tissue)\n- gre: gastric resection (removal of 75% of gastric tissue)\n\nThe response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is different across all treatments, **controlling** for hospital effects.\n\n::: panel-tabset\n\n### SAS Data set\n```{.r}\ndata operate;\ninput hospital trt $ severity $ wt @@;\ndatalines;\n1 v+d none 23 1 v+d slight 7 1 v+d moderate 2\n1 v+a none 23 1 v+a slight 10 1 v+a moderate 5\n1 v+h none 20 1 v+h slight 13 1 v+h moderate 5\n1 gre none 24 1 gre slight 10 1 gre moderate 6\n2 v+d none 18 2 v+d slight 6 2 v+d moderate 1\n2 v+a none 18 2 v+a slight 6 2 v+a moderate 2\n2 v+h none 13 2 v+h slight 13 2 v+h moderate 2\n2 gre none 9 2 gre slight 15 2 gre moderate 2\n3 v+d none 8 3 v+d slight 6 3 v+d moderate 3\n3 v+a none 12 3 v+a slight 4 3 v+a moderate 4\n3 v+h none 11 3 v+h slight 6 3 v+h moderate 2\n3 gre none 7 3 gre slight 7 3 gre moderate 4\n4 v+d none 12 4 v+d slight 9 4 v+d moderate 1\n4 v+a none 15 4 v+a slight 3 4 v+a moderate 2\n4 v+h none 14 4 v+h slight 8 4 v+h moderate 3\n4 gre none 13 4 gre slight 6 4 gre moderate 4\n;\n```\n\n### R Data Set\n\nPlease refer to `operate.csv` for the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\noperate <- read.csv(\"operate.csv\") |> \n  mutate(Treatment=factor(Treatment,levels=c(\"v+d\",\"v+a\",\"v+h\",\"gre\")),\n         Severity=factor(Severity,levels=c(\"none\",\"slight\",\"moderate\")))\n```\n:::\n\n\n:::\n## Example\n\nThe response measured was the severity (none, slight, moderate) of symptoms, which is expected to increase directly with the proportion of gastric tissue removed. Investigators wanted to determine whether the distribution of the severity of duodenal ulcers is different across all treatments, **controlling** for hospital effects. Use rank-based scores.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc freq data=operate order=data;\nweight wt;\ntables hospital*trt*severity / cmh; # <1>\ntables hospital*trt*severity / cmh scores=ridit; # <2>\nrun;\n```\n\n1. Table Scores\n2. Rank-based scores\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(Count~Treatment+Severity,data=operate)\ndat_cc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Severity\nTreatment none slight moderate\n      v+d   61     28        7\n      v+a   68     23       13\n      v+h   58     40       12\n      gre   53     38       16\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(vcdExtra)\n\nCMHtest(dat_cc,\n        rscores=\"midrank\",\n        cscores=\"midrank\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Treatment by Severity \n\n                 AltHypothesis   Chisq Df      Prob\ncor        Nonzero correlation  6.6405  1 0.0099687\nrmeans  Row mean scores differ  7.2468  3 0.0644329\ncmeans  Col mean scores differ  6.6688  2 0.0356356\ngeneral    General association 10.5166  6 0.1045146\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nBoth variables are ordinal, hence we can test for correlation using $Q_{CSMH}$. Using modridit scores, we get $Q_{CSMH}=6.64$, p=0.0100. Hence, we have sufficient evidence that the proportion of gastric tissue removed is associated with symptom severity in patients.\n:::\n\n## Exercise \n\nThe following data were collected in a study of shoulder harness usage in observations for a sample of North Carolina cars. The researchers wanted to test for an association between car size and usage after adjusting for geographical area and location.\n\n::: panel-tabset\n### SAS Code\n\n```{.r}\ndata shoulder;\ninput area $ location $ size $ usage $ count @@;\ndatalines;\ncoast urban large no 174 coast urban large yes 69\ncoast urban medium no 134 coast urban medium yes 56\ncoast urban small no 150 coast urban small yes 54\ncoast rural large no 52 coast rural large yes 14\ncoast rural medium no 31 coast rural medium yes 14\ncoast rural small no 25 coast rural small yes 17\npiedmont urban large no 127 piedmont urban large yes 62\npiedmont urban medium no 94 piedmont urban medium yes 63\npiedmont urban small no 112 piedmont urban small yes 93\npiedmont rural large no 35 piedmont rural large yes 29\npiedmont rural medium no 32 piedmont rural medium yes 30\npiedmont rural small no 46 piedmont rural small yes 34\nmountain urban large no 111 mountain urban large yes 26\nmountain urban medium no 120 mountain urban medium yes 47\nmountain urban small no 145 mountain urban small yes 68\nmountain rural large no 62 mountain rural large yes 31\nmountain rural medium no 44 mountain rural medium yes 32\nmountain rural small no 85 mountain rural small yes 43\n;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nharness <- read.csv(\"harness.csv\")\nglimpse(harness)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 36\nColumns: 5\n$ Area     <chr> \"coast\", \"coast\", \"coast\", \"coast\", \"coast\", \"coast\", \"coast\"…\n$ Location <chr> \"urban\", \"urban\", \"urban\", \"urban\", \"urban\", \"urban\", \"rural\"…\n$ CarSize  <chr> \"large\", \"large\", \"medium\", \"medium\", \"small\", \"small\", \"larg…\n$ Usage    <chr> \"no\", \"yes\", \"no\", \"yes\", \"no\", \"yes\", \"no\", \"yes\", \"no\", \"ye…\n$ Count    <int> 174, 69, 134, 56, 150, 54, 52, 14, 31, 14, 25, 17, 127, 62, 9…\n```\n\n\n:::\n:::\n\n\n\n:::\n## Exercise\n\n\nThe following data were collected in a study of shoulder harness usage in observations for a sample of North Carolina cars. The researchers wanted to test for an association between car size and usage after adjusting for geographical area and location.\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc freq data=shoulder order=data;\nweight count;\ntables area*location*size*usage / cmh scores=ridit;\n;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(Count~CarSize+Usage+Area+Location,data=harness)\nCMHtest(dat_cc,\n        rscores=\"midrank\",\n        cscores=\"midrank\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Area:coast|Location:rural`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:coast|Location:rural \n\n                 AltHypothesis  Chisq Df     Prob\ncor        Nonzero correlation 4.6341  1 0.031343\nrmeans  Row mean scores differ 4.6460  2 0.097980\ncmeans  Col mean scores differ 4.6341  1 0.031343\ngeneral    General association 4.6460  2 0.097980\n\n\n$`Area:mountain|Location:rural`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:mountain|Location:rural \n\n                 AltHypothesis    Chisq Df    Prob\ncor        Nonzero correlation 0.017854  1 0.89370\nrmeans  Row mean scores differ 1.826674  2 0.40118\ncmeans  Col mean scores differ 0.017854  1 0.89370\ngeneral    General association 1.826674  2 0.40118\n\n\n$`Area:piedmont|Location:rural`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:piedmont|Location:rural \n\n                 AltHypothesis   Chisq Df    Prob\ncor        Nonzero correlation 0.15378  1 0.69495\nrmeans  Row mean scores differ 0.48751  2 0.78368\ncmeans  Col mean scores differ 0.15378  1 0.69495\ngeneral    General association 0.48751  2 0.78368\n\n\n$`Area:coast|Location:urban`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:coast|Location:urban \n\n                 AltHypothesis   Chisq Df    Prob\ncor        Nonzero correlation 0.17007  1 0.68005\nrmeans  Row mean scores differ 0.45528  2 0.79641\ncmeans  Col mean scores differ 0.17007  1 0.68005\ngeneral    General association 0.45528  2 0.79641\n\n\n$`Area:mountain|Location:urban`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:mountain|Location:urban \n\n                 AltHypothesis  Chisq Df     Prob\ncor        Nonzero correlation 6.4876  1 0.010863\nrmeans  Row mean scores differ 7.1263  2 0.028349\ncmeans  Col mean scores differ 6.4876  1 0.010863\ngeneral    General association 7.1263  2 0.028349\n\n\n$`Area:piedmont|Location:urban`\nCochran-Mantel-Haenszel Statistics for CarSize by Usage \n\tin stratum Area:piedmont|Location:urban \n\n                 AltHypothesis  Chisq Df     Prob\ncor        Nonzero correlation 6.4411  1 0.011151\nrmeans  Row mean scores differ 6.5068  2 0.038643\ncmeans  Col mean scores differ 6.4411  1 0.011151\ngeneral    General association 6.5068  2 0.038643\n```\n\n\n:::\n:::\n\n\n### Answer\n\nBoth variables are ordinal. We can use the extended correlation statistic $Q_{CSMH}$. Using ridit/rank-based scores, $Q_{CSMH}$ =6.44, p=0.01. There is sufficient evidence to conclude that car size and shoulder harness usage are correlated after controlling for geographical area and location.\n\n:::\n\n# Repeated Measures\n\n## Repeated Measures: Application \n\nRepeated measures are commonly encountered in longitudinal studies (e.g. cohort studies). \n\n::: callout-note\nMantel-Haenszel statistics can be calculated to determine whether there is an association between a repeated measurement factor (usually time) and a response variable adjusting for an effect of subject. Controlling for subject adjusts for the variability between subjects, which focuses the analysis to within-subject.\n:::\n  \n\n## Repeated Measures\n\nConsider an experiment with $n$ subjects.\n  - The treatment is applied to each subject.\n  - The response is measured at $t$ time points. \n  - Cohort studies/ longitudinal RCT\n\n- In general, the repeated measures can come from multiple subjects. Responses can come from:\n  - Same location\n  - Same family/litter\n  - Matched pairs\n\n## Repeated Measures\n\nConsider a repeated measures design with $t$ time points and a response variable with $C$ levels.\n\n![](img/rm_C6.png)\n\n\n::: callout-note\nEach time point will have a measured response value. For a sample size $n$, we will end up with $n$ contingency tables with shape $t \\times C$\n:::\n\n![](img/subjrm_C6.png)\n\n::: callout-note\n$n_{ijk} = 1$ if response $k$ is measured at time $j$. Otherwise, $n_{ijk}=0$\n:::\n\n## Repeated Measures: Hypotheses\n\nMantel-Haenszel statistics can be used to test the hypothesis of no association between time and response under the assumption that marginal totals per subject in response and time is fixed.\n\n::: callout-note\nThe null hypothesis for Mantel-Haenszel tests for repetaed measures is $H_0$: The response variable is distributed at random with respect to the time points.This null hypothesis is referred to as the hypothesis of interchangeability or marginal homogeneity.\n\nAs in previous chapters, $Q_{CSMH}$, $Q_{SMH}$, and $Q_{GMH}$ pertain to different alternatives to no association.\n:::\n\n\n:::callout-warning\nOdds ratio estimates and CI limits assumes independence between contingency table entries, which is broken in repeated measures data. Breslow-Day assumptions are also not satisfied.\n\nThe Breslow-Day statistic as well as the MH and logit estimates of the odds ratio should be taken with a grain of salt. \n:::\n\n## Example\n\nA running shoe company produces a new model of running shoe that includes a harder material for the insert that corrects for overpronation. However, the company is concerned that the material will induce heel tenderness as a result of some loss of cushioning on the strike of each step. It conducted a study on 87 runners who used the new shoe for a month. Researchers asked the participants whether they experienced occasional heel tenderness before and after they used the new shoe. Is there a difference in proportion of people reporting more heel tenderness with the new running shoes compared with the older running shoes?\n\n::: callout-note\n### SAS Data\n\n```{.r}\ndata pump;\ninput subject time $ response $ @@;\ndatalines;\n1 before no 1 after no 2 before no 2 after no\n3 before no 3 after no 4 before no 4 after no\n5 before no 5 after no 6 before no 6 after no\n7 before no 7 after no 8 before no 8 after no\n9 before no 9 after no 10 before no 10 after no\n11 before no 11 after no 12 before no 12 after no\n13 before no 13 after no 14 before no 14 after no\n15 before no 15 after no 16 before no 16 after no\n17 before no 17 after no 18 before no 18 after no\n19 before no 19 after no 20 before no 20 after no\n21 before no 21 after no 22 before no 22 after no\n23 before no 23 after no 24 before no 24 after no\n25 before no 25 after no 26 before no 26 after no\n27 before no 27 after no 28 before no 28 after no\n29 before no 29 after no 30 before no 30 after no\n31 before no 31 after no 32 before no 32 after no\n33 before no 33 after no 34 before no 34 after no\n35 before no 35 after no 36 before no 36 after no\n37 before no 37 after no 38 before no 38 after no\n39 before no 39 after no 40 before no 40 after no\n41 before no 41 after no 42 before no 42 after no\n43 before no 43 after no 44 before no 44 after no\n45 before no 45 after no 46 before no 46 after no\n47 before no 47 after no 48 before no 48 after no\n49 before no 49 after yes 50 before no 50 after yes\n51 before no 51 after yes 52 before no 52 after yes\n53 before no 53 after yes 54 before no 54 after yes\n55 before no 55 after yes 56 before no 56 after yes\n57 before no 57 after yes 58 before no 58 after yes\n59 before no 59 after yes 60 before no 60 after yes\n61 before no 61 after yes 62 before no 62 after yes\n63 before no 63 after yes 64 before yes 64 after no\n65 before yes 65 after no 66 before yes 66 after no\n67 before yes 67 after no 68 before yes 68 after no\n69 before yes 69 after yes 70 before yes 70 after yes\n71 before yes 71 after yes 72 before yes 72 after yes\n73 before yes 73 after yes 74 before yes 74 after yes\n75 before yes 75 after yes 76 before yes 76 after yes\n77 before yes 77 after yes 78 before yes 78 after yes\n79 before yes 79 after yes 80 before yes 80 after yes\n81 before yes 81 after yes 82 before yes 82 after yes\n83 before yes 83 after yes 84 before yes 84 after yes\n85 before yes 85 after yes 86 before yes 86 after yes\n87 before yes 87 after yes\n;\n\n```\n\n### R Data\n\nPlease refer to `pump.csv` on Canvas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\npump <- read.csv(\"pump.csv\") |> \n  mutate(Subject = as.factor(Subject))\nglimpse(pump)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 174\nColumns: 3\n$ Subject  <fct> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10,…\n$ Time     <chr> \"before\", \"after\", \"before\", \"after\", \"before\", \"after\", \"bef…\n$ Response <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"…\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n## Example\n\nIs there a difference in proportion of people reporting more heel tenderness with the new running shoes compared with the older running shoes?\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\n\ndata pump;\ninput subject time $ response $ @@;\ndatalines;\n1 before no 1 after no 2 before no 2 after no\n3 before no 3 after no 4 before no 4 after no\n5 before no 5 after no 6 before no 6 after no\n7 before no 7 after no 8 before no 8 after no\n9 before no 9 after no 10 before no 10 after no\n11 before no 11 after no 12 before no 12 after no\n13 before no 13 after no 14 before no 14 after no\n15 before no 15 after no 16 before no 16 after no\n17 before no 17 after no 18 before no 18 after no\n19 before no 19 after no 20 before no 20 after no\n21 before no 21 after no 22 before no 22 after no\n23 before no 23 after no 24 before no 24 after no\n25 before no 25 after no 26 before no 26 after no\n27 before no 27 after no 28 before no 28 after no\n29 before no 29 after no 30 before no 30 after no\n31 before no 31 after no 32 before no 32 after no\n33 before no 33 after no 34 before no 34 after no\n35 before no 35 after no 36 before no 36 after no\n37 before no 37 after no 38 before no 38 after no\n39 before no 39 after no 40 before no 40 after no\n41 before no 41 after no 42 before no 42 after no\n43 before no 43 after no 44 before no 44 after no\n45 before no 45 after no 46 before no 46 after no\n47 before no 47 after no 48 before no 48 after no\n49 before no 49 after yes 50 before no 50 after yes\n51 before no 51 after yes 52 before no 52 after yes\n53 before no 53 after yes 54 before no 54 after yes\n55 before no 55 after yes 56 before no 56 after yes\n57 before no 57 after yes 58 before no 58 after yes\n59 before no 59 after yes 60 before no 60 after yes\n61 before no 61 after yes 62 before no 62 after yes\n63 before no 63 after yes 64 before yes 64 after no\n65 before yes 65 after no 66 before yes 66 after no\n67 before yes 67 after no 68 before yes 68 after no\n69 before yes 69 after yes 70 before yes 70 after yes\n71 before yes 71 after yes 72 before yes 72 after yes\n73 before yes 73 after yes 74 before yes 74 after yes\n75 before yes 75 after yes 76 before yes 76 after yes\n77 before yes 77 after yes 78 before yes 78 after yes\n79 before yes 79 after yes 80 before yes 80 after yes\n81 before yes 81 after yes 82 before yes 82 after yes\n83 before yes 83 after yes 84 before yes 84 after yes\n85 before yes 85 after yes 86 before yes 86 after yes\n87 before yes 87 after yes\n;\n\nproc freq data=pump order=data; #<1>\ntables subject*time*response/ noprint cmh; *noprint does not print the 87 contingency tables.;\nrun;\n```\n\n1. There's no weight statement because each line is an observational unit.\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc<- xtabs(~Time+Response+Subject,data=pump)\n\nmantelhaen.test(dat_cc,correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMantel-Haenszel chi-squared test without continuity correction\n\ndata:  dat_cc\nMantel-Haenszel X-squared = 5, df = 1, p-value = 0.02535\nalternative hypothesis: true common odds ratio is not equal to 1\n95 percent confidence interval:\n 0.1211491 0.9171436\nsample estimates:\ncommon odds ratio \n        0.3333333 \n```\n\n\n:::\n:::\n\n\n\n### Answer\n\n- We can construct 2x2 tables for each runner and control for each subject. The resulting CMH tables will have the same results because of the shape of the contingency tables.\n- $Q_{CSMH}$=5, p=0.03, which means there is strong evidence that there is a difference in heel tenderness before and after using the new shoe.\n- All extended Mantel-Haenszel statistic will yield the same result because the resulting contingency table for each subject is a 2x2 table.\n\n### McNemar's test\n\n```{.r}\ndata shoes;\ninput before $ after $ count;\ndatalines;\nyes yes 19\nyes no 5\nno yes 15\nno no 48\n;\n\nproc freq data=shoes order=data;\nweight count;\ntables before*after/agree;\nrun;\n\n```\n\nIn `R`, we can create a repeated measures table and apply the McNemar's test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat2 <- pump |> \n  pivot_wider(names_from=Time,values_from=Response) \ndat_cc2 <- xtabs(~before+after,data=dat2)\n\nmcnemar.test(dat_cc2,correct=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMcNemar's Chi-squared test\n\ndata:  dat_cc2\nMcNemar's chi-squared = 5, df = 1, p-value = 0.02535\n```\n\n\n:::\n:::\n\n\n\nThe McNemar's test yields the same result as $Q_{CSMH}$.\n:::\n\n## Exercise\n\nThe DRUG2 dataset shows the data from a study in which 46 patients were each treated with three drugs (A, B, and C). The response to each drug was recorded as favorable (F) or unfavorable (U). Use the appropriate test to determine whether the three drugs have equal probabilities for favorable response.\n\n- Which Mantel-Haenszel statistic is the most appropriate for this example?\n- At a significance level of 0.01, is there sufficient evidence against the hypothesis that the three drugs have equal probabilities?\n\n::: panel-tabset\n\n### SAS Data\n\n```{.r code-line-numbers=\"14-23\"}\ndata drug;\ninput druga $ drugb $ drugc $ count;\ndatalines;\nF F F 6\nF F U 16\nF U F 2\nF U U 4\nU F F 2\nU F U 4\nU U F 6\nU U U 6\n;\nrun;\ndata drug2; set drug;\nkeep patient drug response;\nretain patient 0;\ndo i=1 to count;\npatient=patient+1;\ndrug='A'; response=druga; output;\ndrug='B'; response=drugb; output;\ndrug='C'; response=drugc; output;\nend;\nrun;\n```\n\n### R Data\n\nPlease refer to `drug.csv` uploaded on Canvas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug <- read.csv(\"drug.csv\") |> \n  mutate(Patient=as.factor(Patient),\n         Outcome=factor(Outcome,levels=c(\"U\",\"F\")))\nglimpse(drug)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 138\nColumns: 3\n$ Patient <fct> 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7,…\n$ Drug    <chr> \"A\", \"B\", \"C\", \"A\", \"B\", \"C\", \"A\", \"B\", \"C\", \"A\", \"B\", \"C\", \"A…\n$ Outcome <fct> F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, U,…\n```\n\n\n:::\n:::\n\n\n:::\n\n## Exercise\n\n- Which Mantel-Haenszel statistic is the most appropriate for this example?\n- At a significance level of 0.01, is there sufficient evidence against the hypothesis that the three drugs have equal probabilities?\n\n:::{.panel-tabset}\n### SAS Code\n\n```{.r}\nproc freq data=drug2 order=data;\ntables patient*drug*response/cmh noprint;\nrun;\n```\n\n### R Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_cc <- xtabs(~Drug+Outcome+Patient,data=drug)\n\nCMHtest(dat_cc,overall=T)$ALL\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCochran-Mantel-Haenszel Statistics for Drug by Outcome \n\tOverall tests, controlling for all strata \n\n                 AltHypothesis  Chisq Df     Prob\ncor        Nonzero correlation 6.3529  1 0.011719\nrmeans  Row mean scores differ 8.4706  2 0.014476\ncmeans  Col mean scores differ 6.3529  1 0.011719\ngeneral    General association 8.4706  2 0.014476\n```\n\n\n:::\n:::\n\n\n\n### Answer\n\nThe most appropriate MH statistic to examine is the mean score statistic, specifically the row means.\n\nThe statistic $Q_{SMH}=8.47$ yields a p-value $p=0.0145$. At a significance level of 0.01, there is marginally sufficient evidence that at least one drug has a different probability of a favorable response.\n:::\n\n## Ordinal Response with Missing Data\n\nExperiments using a repeated measures design tend to include plenty of missing data.\n\n\n- Missing data decreases the power of the study.\n  - Including missing data in the analysis still gives a higher power than excluding incomplete cases in the analysis.\n\n- Techniques to deal with missing data include:\n  - Multiple imputation\n  - Omission\n  - Adjusting ANOVA scores\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}